### ISSUE TITLE
Incoming calls: no more sound...

### ISSUE THREAD

**Issue by FlavioMala** [ubports/ubuntu-touch#1899] opened 2021-12-20 16:31 UTC
Bug report

- Device: BQ E5
- Channel: dev

Incoming calls: no more sound... (ringtone) and vibration.
update 811 18 dec 2021 & update 813 20 dec 2021.
(SMS OK;
Ringtones are normally "played" in "audio settings"...)

**Comment by FlavioMala** [comment] 2021-12-21 09:03
Addendum: ...and battery draining very fast!
(in sleep mode: no network, no wifi, etc.; no apparent operation)

**Comment by Danfro** [comment] 2021-12-22 11:05
Confirmed on Xperia X, current devel, two devices.

**Comment by mardy** [comment] 2021-12-22 15:49
Unfortunately my BQ 4.5 SIM slots seem to be broken since several months, so I cannot test this (I even flashed Android on it, and they are not working there either). This could be related to media-hub changes if the issue was only about the ringtones, but it's strange that it affects the vibrations too.

**Comment by Danfro** [comment] 2021-12-22 15:50
Vibrations do still work fine for me. Here on Xperia X only sound is
affected.

**Comment by Sladek90** [comment] 2021-12-22 16:14
I have the same experience since today. After update to version 40 from release candidate channel, I have no ringtones, only vibrations at incoming calls. My phone is Xiaomi Mi A2.

**Comment by pixnat** [comment] 2021-12-22 16:57
I have the same issue since today, after OTA, RC channel on Redmi Note 9S. No ringtone, only vibrations.

**Comment by wilfridd** [comment] 2021-12-22 20:36
Same here with MiA2 on RC 2021-12-18

**Comment by Flohack74** [comment] 2021-12-22 21:05
Ok we merged a potential fix, please switch to devel tomorrow to see if its fixed there.

**Comment by Sladek90** [comment] 2021-12-23 07:50
It looks like solved now. After update to version 764 from development channel it is ringing again.

**Comment by Danfro** [comment] 2021-12-23 08:37
Confirmed on two Xperia X, fixed with todays devel. Thanks a lot.

**Comment by wilfridd** [comment] 2021-12-23 13:29
Confirmed working also on MiA2 with Devel 764. Many thanks!

**Comment by ivoxavier** [comment] 2021-12-23 13:40
Hi, can also confirm on the FP2. It's fixed

**Comment by FlavioMala** [comment] 2021-12-23 17:05
Fixed (ringtone) with devel 816 (for BQ E5) 23/12/2021.

The battery draining was over with devel 814 21/12/2021  (so a different issue).

Vibration:
I'll do tests (maybe the problem is hardware ... )

Thanks!

**Closed** 2021-12-24 14:28 UTC
Labels: critical (rc)

**Comment by coinflow** [comment] 2022-01-12 14:28
Reopening the issue.

Sony Xperia X Performance (F8131 & F8132) x 2
Channel: stable
Version: OTA-21

Both phones do not ring (but vibration works) and the volume cannot be set. Microphone cannot be switched off.
However, alert-sounds (emails) do work, as do keyboard-tones. if activated.

**Comment by ivoxavier** [comment] 2022-01-12 15:00
Hi, on myH9 device (6T) incoming sound calls is working, and I can rise and low volume during call. Although an user has described problems  with volume can't be managed during calls on  6T #1908. I've just confirmed with other friends also with an 6T on Portugal and Spain networks, and everything is working as expected.

**Comment by Danfro** [comment] 2022-01-12 16:03
I have two Xperia X, devel. For both sound on incoming calls IS
WORKING. Turning off mic during call IS WORKING.

Volume not being able to set during a call is a known issue. From what
I know, that is limited somehow by the android driver part. If a fix is
possible at all, that is going to be hard work.

**Comment by coinflow** [comment] 2022-01-12 16:50
> I have two Xperia X, devel. For both sound on incoming calls IS WORKING. Turning off mic during call IS WORKING. Volume not being able to set during a call is a known issue. From what I know, that is limited somehow by the android driver part. If a fix is possible at all, that is going to be hard work.

Do you have Xperia X (https://devices.ubuntu-touch.io/device/suzu/) or Xperia X Performance (https://devices.ubuntu-touch.io/device/dora/)?

**Comment by Danfro** [comment] 2022-01-12 17:30
The first, two suzu. One 5121, one 5122.

--

**Comment by Danfro** [comment] 2022-01-12 18:11
Did you reboot your phone(s)? Someone in main group had sound issues in calls that seemed to be fixed after two reboots. Worth checking...

--

**Comment by coinflow** [comment] 2022-01-14 14:49
The phones (dora) were rebooted several times.

I have found the following:
https://forums.ubports.com/topic/6462/no-ringtone-with-dora-for-incoming-calls-all-other-sounds-work

Maybe that helps in locating, what is going wrong? The first post describes that suzu works, dora not.
