### ISSUE TITLE
Pixel 3a - No Text Messaging.

### ISSUE THREAD

**Issue by Xozk** [ubports/ubuntu-touch#1794] opened 2021-08-06 22:15 UTC
Device: Google Pixel 3a
    Channel: ?
    Build: Ubuntu 16.04 (2021-07-28)

I have a Pixel 3a which I put UT on and really like everything about it except for the fact that I cannot get text messaging to work.

My wife tried on her Pixel 3a for almost a month as well and could not get it to work. She moved over to GraphineOS and it works flawlessly. I still however would like to get UT to work as I have used Ubuntu and Linut Mint for over a decade.

Sometimes I can send a text, but I cannot ever receive texts. Well once one morning I got two texts, but then never after that.

We have tried US Mobile, T Mobile, AT&T, Puretalk, Verizon, and now on RedPocket.

My wife was talking with one of the developers on the Telegram chat, and they did not get it working. I guess we are a unique pair. LOL.

Any help would be appreciate. Thanks!

**Expected Behavior**

To be able to send and receive text messages.

**Steps to reproduce**

Try to send and receive text messages.

**Actual behavior**

Does not receive text messages, and occasionally will send a message.

**Logfiles and additional information**

**Comment by lduboeuf** [comment] 2021-08-07 11:14
nothing found usefull on the forum ? We see lots of issues regarding texting on Pixel3a

**Comment by Xozk** [comment] 2021-08-07 15:27
No, I have been trying every solution with no luck. I think the Ubuntu Touch website should change SMS to show "Not Working". If it had not listed The P3a as working we would have bought different phones.

**Comment by mattbel10** [comment] 2021-08-08 16:29
I own a Pixel 3a using it as daily driver. I can confirm sms works flawlessly for me both sending and receiving. I suspect the culprit may be the carrier since I read in US there are general issues for several carriers with UT, even for internet connection. I'm in Italy by the way.

**Comment by republicofgavin** [comment] 2021-08-08 22:56
@Xozk 
I'm in the same boat as you. I'm in the US and I bought the Pixel3a, because I thought it would be able to do the features it listed on the supported devices page. Only to find out that it wasn't using the cellular data. I'm currently trying to troubleshoot it.
I have gotten internet to work (AT&T) by modifying the APN settings on the device (https://www.att.com/support/article/wireless/KM1062162/) (Android section). You may be able to mimic what I did with a different carrier and have it work.
After applying the APN settings for MMS, I was able to send texts and have them received, but I have not been able to receive them. If you find out how to get that working, please let me know.
BTW I'm using the RC version, instead of stable or dev.

**Comment by lduboeuf** [comment] 2021-08-12 21:26
for MMS issues, nuntium logs might help debug

**Comment by angelomaragna** [comment] 2021-08-16 16:21
If it can help, there is a Logviewer app. I don't know whether there is a helpful log for the messages though. But I would try sending a txt message and then browse logs.

**Comment by angelomaragna** [comment] 2021-08-23 19:17
Yesterday and today I've lost possibility of sendinf text messages (UK). This evening, the signal indicator was empty and was showing the text "denied" (in the pull-down section). Tried turning on and off 2-3 times. Tried turning on and off the network.

In the end, moved sim to an iphone, and then back to the Pixel 3a xl and cellular signal is back on.

I wonder if there is a protocol or an authentication handshake that devices have to do once in a while in order to obtain access to the networks.

My device has worked and has been on for the past 7 days without any problem.

**Comment by fredldotme** [comment] 2021-08-24 09:16
Reopened due to auto-closing, needs further testing with the upcoming devel image.

**Closed** 2021-12-24 15:34 UTC
