### ISSUE TITLE
Double battery consumption since update to OTA-18

### ISSUE THREAD

**Issue by yhervouette** [ubports/ubuntu-touch#1780] opened 2021-07-21 17:04 UTC
### Illustrations

- Device: BQ E4.5
- Channel: RC
- Build: 20210708-27954

### Steps to reproduce

Update to OTA-18

### Expected behavior

Battery can hold one day long on normal use (like it is with previous OTA version)

### Actual behavior

Battery consumption is faster and the battery is discharged is less than one day.

### Logfiles and additional information

Linked to/same as  #1779 ?

**Comment by yhervouette** [comment] 2021-07-26 11:36
Seems less obvious after several shutdowns and restarts.

**Comment by UniversalSuperBox** [comment] 2021-07-28 01:05
Duplicate of https://github.com/ubports/ubuntu-touch/issues/1779

**Closed by UniversalSuperBox** 2021-07-28 01:05 UTC
Labels: bug, device: krillin
