### ISSUE TITLE
Edge:  indicator menu, touch area too restrictive

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-touch#1233] opened 2019-09-23 20:30 UTC
### Illustrations

- Device: Nexus 5
- Channel: Edge
- Build: today 

### Steps to reproduce

The area before the first icon of the indicator menu is not responsive.

### Expected behavior

I would expect to have indicator menu displayed without pointing precisely to the notification icon

### Actual behavior

Indicator not displayed.

**Comment by NeoTheThird** [comment] 2019-09-23 20:31
This was probably introduced by the global menus that will use that space. Don't think there's anything we can do about that.

**Comment by NeoTheThird** [comment] 2019-09-23 20:33
That being said, maybe we can make the area a little bigger. Let's keep this open for discussion :)

**Comment by lduboeuf** [comment] 2019-09-23 20:34
humm ok, certainly an habit on my side. But regarding experience, i use the thumb for acting with the indicator which is not always precise.

**Comment by mauricioduarte01** [comment] 2019-09-25 17:21
maybe for now until the "global menu" starts to be used I think the suggestion from @NeoTheThird is a good one.

**Comment by lduboeuf** [comment] 2019-09-25 19:49
Sorry, i don't get what "global menu" is or will be.
I think we will need a screenshot with names of visual components to understand each other for later, but that's another discussion

**Comment by PhoenixLandPirate** [comment] 2019-10-01 14:48
> maybe for now until the "global menu" starts to be used I think the suggestion from @NeoTheThird is a good one.

I don't think its a good idea to implement that until we have the global menu, because we might need to pull it back, which would land us back in a similar position.

If the global menu turns out not to need that space, then we could make the area a little bigger.

**Comment by dobey** [comment] 2019-10-01 18:38
> Sorry, i don't get what "global menu" is or will be.

It is the menu bar for applications, which appears in the top panel or window titlebar, in Unity. You should be able to see it in action if you use legacy apps that use GTK+3 or Qt.

**Comment by JassMan23** [comment] 2019-11-04 10:20
I am not sure this is a new problem. I have seen it ever since I started using UT. It seems to vary and I assume it an oversensitivity to **x** movement while the menu bar is expanding to include the hidden options and text labels. It seems to be work better with a swift decisive pull action rather than trying to find the point at which it all goes wrong (which is impossible because the vertical point is always different). I have also found that a perfctly clean screen seems to make more of a difference than any changes to finger action. This may be a side effect of the particular screen protection films I am using.

**Comment by hummlbach** [comment] 2020-02-14 07:35
+2 already talked to others... somehow we tend to swipe down from slightly left of the envelop icon and then nothing happens ofc. Maybe we can add a liitle extra space for opening the most left indicator...?

**Comment by cm-t** [comment] 2020-02-14 07:39
Hi.

as mentionned in #1366 , I think the extra space is needed. first because it affect a user's most daily used indicator, second because it call user to focus a lot on that repetitive action and it creats frustration a lot to the user.

Until there is a (new, or an unlnow to me) design reason to reduce the zone to trigger the swipe of indicator in unity **phone** factor, the “extra” zone should simply be as before the new app menu appears: full size


i'm pretty sure the behavior before this update was discussed at canonical to make on purpose an exception to allow all screensize when it is phone, just to make sure the most used indicator will got the love it needs ^^

**Comment by jezek** [comment] 2020-02-21 14:12
Hello. For me this issue very annoying. It takes me about 2-3 tries to pull down notifications now. Though, it's been only 3 days since update, maybe my accuracy will be better. But the possibility to swipe down from every place from the top made things more easier. 

I think, the touch area should dynamically expand to the left, until the last item of the possible menu. If there's no menu, the touch area is the whole notification bar.

Is this dynamic behavior possible? Where should I start (repo & how to), if I want to experiment on this idea?

**Comment by mauricioduarte01** [comment] 2020-03-18 11:54
Much better now! Thank you @UniversalSuperBox

**Comment by UniversalSuperBox** [comment] 2020-03-18 20:10
@mauricioduarte01, I assume you're using the change installed from the PPA? It hasn't been merged yet.

**Closed** 2020-03-26 18:10 UTC
Labels: opinion

**Comment by thilovv** [comment] 2020-03-30 16:05
Works fine now!

**Comment by abkro** [comment] 2020-03-30 17:04
Tested today on my N5 running RC.

When I swipe down from the top of the screen to the left of the leftmost item in the indicator menu nothing happens. Only when I actually swipe over the leftmost icon (notifications) does the indicator menu open. Intuitively one would expect the menu to also open for notifications when one swipes to the left of this icon.

**Comment by cibersheep** [comment] 2020-03-30 17:09
This might refer about the menu area. Some changes are in the way.
For now: it works as expected: pulling from notification indicator works, from the left of it does nothing.

**Comment by UniversalSuperBox** [comment] 2020-03-30 17:52
Pull request https://github.com/ubports/unity8/pull/289 was merged 4 days ago. This change will not reach rc until Wednesday. It can currently be tested in devel.

**Comment by Danfro** [comment] 2020-03-30 18:00
With two phones, one devel, one rc I can feel the difference. Much better in devel. I would call this fixed.

**Comment by Flohack74** [comment] 2020-03-30 18:32
Yes confirmed too, fixed.
