### ISSUE TITLE
Unable to save passwords in Morph Browser

### ISSUE THREAD

**Issue by Lee197722** [ubports/ubuntu-touch#1136] opened 2019-05-10 20:19 UTC
I have been using Ubuntu Touch for about a month now on a Nexus 5 and so far I am very happy. Only a few issues with the camera/video freezing, but this has a workaround to continue using it. Battery life is great if the location services are turned off and brightness is set to half way. I can get through the day with a decent amount of browsing and listening to podcasts. However, I find that I need to re-enter my passwords every time I go to websites I access a lot. Is there a way for the browser to save passwords? It is real pain that I need to re-enter passwords constantly so if this cannot be done at present, it would be great if it could be implemented in the next update. Apart from that, I am really impressed by the OS. 

Cheers

**Comment by advocatux** [comment] 2019-05-11 07:11
Hi, https://github.com/ubports/morph-browser/issues is a better place to file Morph's bugs :)

**Comment by dobey** [comment] 2019-05-26 14:46
Closing as it is a duplicate of morph-browser#181

**Closed by dobey** 2019-05-26 14:46 UTC
