### ISSUE TITLE
Telephone dialer

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubuntu-touch#804] opened 2018-07-30 16:51 UTC
- Device:Mako
- Channel:16.04
- Build:

### Steps to reproduce
Make a call with the horizontal device

### Expected behavior
Horizontal telephone dialer

### Actual behavior
The letters are misaligned with respect to the numbers

**Comment by Flohack74** [comment] 2018-07-30 20:01
Duplicate of https://github.com/ubports/dialer-app/issues/6

**Closed by Flohack74** 2018-07-30 20:01 UTC
