### ISSUE TITLE
Google Nexus 5 - Screen shifts and is half on screen

### ISSUE THREAD

**Issue by styles6957** [ubports/ubuntu-touch#1696] opened 2021-03-26 13:10 UTC
The screen shifts and is half on the screen sometimes when I reboot. I have to reboot the phone 3 or 4 times to correct issue

### Illustrations

- Device:
- Channel:
- Build:

**Comment by Flohack74** [comment] 2021-03-29 10:15
Duplicate of #27 - we closed that already since there is a potential workaround: _Something new : I reflashed a UT Nexus 5 with the last androïd factory image 6.0.1 (M4B30Z dec 2016), then reflashed UT by following. I have since restarted at least 10 times my phone and no sign of this bug! Passed out!_

**Closed by Flohack74** 2021-03-29 10:15 UTC

**Comment by Flohack74** [comment] 2021-03-29 10:16
Keep in mind that Ubuntu Touch does not update firmware during installation, we simply cannot bundle 3rd party components that are copyright protected etc.
