### ISSUE TITLE
Provide zram for devices with 2GB RAM (e.g. `hammerhead`)

### ISSUE THREAD

**Issue by myii** [ubports/ubuntu-touch#1212] opened 2019-08-28 18:19 UTC
- Device: `hammerhead`
- Channel: `devel`
- Build: `2019-08-28`

The discussion took place in the UBports room on Matrix [from this point forward](https://matrix.to/#/!NrkQorBIyLCRuiynHA:matrix.org/$15669459184807JHqnO:ubports.chat) -- just quoting the salient parts here:

> beton
> why Nexus 5 don't have zram enabled, only 32mb disk swap?
> 
> ---
> 
> beton
> BQ M10 also have 2GB RAM and have zram enabled and using it. I think that Nexus 5 need it too, especially as a convergence device.
> 
> ---
> 
> beton
> And why just not enable it on every device by default? It doesn't cost anything, it's much faster than normal swap, and doesn't make additional writes on internal storage like normal swap do.
> 
> ---
> 
> dobey
> well, cpu usage is only there if that area of memory gets hit. but it eats up the RAM, so you end up hitting zram sooner
> 
> ---
> 
> beton
> It costs extra CPU, but even then, it's a lot faster than swapping on flash memory
> 
> ---
> 
> dobey
> why are you swapping at all?
> 
> ---
> 
> beton
> Swap file is enabled by default in Nexus 5, in my opinion its better to enable zram than swapping on flash, this is what i'm trying to say.
> 
> ---
> 
> dobey
> zram is only better if you actually hit swap. for people who don't hit swap, it's not really better. and i'm not arguing against your statement. i'm asking why you are hitting swap on that device
> 
> ---
> 
> beton
> I installed few apps from OpenStore before, now I have opened Settings, FluffyChat, web browser with few pages, so, normal usage and it already hitting swap for me.
> 
> ---
> 
> dobey
> is zram used in android on nexus 5?
> 
> ---
> 
> myii
> Interesting discussion, `htop` shows me: `Swp: 32.0M used: 31.9M`. RAM usage is `1.33G` out of `1.81G`. Can zram even be enabled on an N5?
> 
> ---
> 
> beton
> I have the same, swap is used in normal usage, I don't remember in which file zram initialization is defined.
> 
> ---
> 
> myii
> So restarted my device to apply the latest `devel`. Fresh figures are: `Swp: 32.0M used: 748K`. RAM usage is `1.19G` out of `1.81G`.
> 
> ---
> 
> dobey
> open a bug that zram is not enabled on nexus 5 then

### Steps to reproduce

Swap is being used even after restarting the device.

### Expected behavior

Swap to be avoided as much as possible.

### Actual behavior

It fills the `32.0M` swap with even fairly standard use.  Heavier use causes apps to be terminated.

**Comment by myii** [comment] 2019-08-28 18:26
Further info:

1. No `/dev/zram0` device available.
1. `/sys/block/zram0/disksize` not present.
1. `/etc/init/zram-touch.conf` is already available.
1. `sudo start zram-touch` results in `zram-touch stop/waiting` (obviously, due to numbers 1 and 2).

**Comment by UniversalSuperBox** [comment] 2019-09-01 15:09
## Summary

I suspect the real issue you're looking for a solution for is, "Heavier use causes apps to be terminated." It's unclear exactly what "heavier use" is to me. Are you loading 50 tabs in the browser with a few Libreoffice sessions running in the background? In that case, yeah, some tabs will be suspended or other apps will be killed. Ubuntu Touch is expressly designed to do this. However, it's also designed to make this transparent to the user. I suspect that we've lost that part of the design.

I think this report is providing a concrete solution looking for a problem. Instead, please write a report providing, in reproducible terms, the set of user-facing problems you are experiencing (especially defining "heavy use." A set of apps to run, things to load, etc.). That gives us a better starting point toward making Ubuntu Touch better for you.

For that reason, I'm going to close this issue as 'invalid,' since it provides one possible solution to a not well-defined issue.

## Explanation

Somewhere in the code of Ubuntu Touch it is mentioned, roughly:

> Use a small amount of swap (32M) because the system performs better with very little swap than no swap.

Since I can't find the reference, I assume that this was done because a study proved this was the case: Linux memory management behaved better with 32M swap than it did with no swap. The reason I believe this assumption is, "Canonical is full of really smart engineers."

It's natural for the Linux kernel to decide that some small amount of data is not important enough to keep in memory and swap it away. For example, I'm currently using a laptop with 16GB of RAM. About 150M of data is sitting in swap, with 2.6G of RAM currently in use. To me, there's no logical reason that it can't be 2.75G of RAM. To the kernel developers, maybe I don't know best.

I think that flash longevity concerns are overblown in general. 32M of writable space really isn't going to add that much wear to the flash. I've never heard of a case where a phone failed due to a worn flash chip when running Ubuntu Touch. That's not to say it hasn't happened, but it's a very rare concern.

All that to say, the expected behavior, "swap to be avoided as much as possible," is not an appropriate expectation.

zram in Ubuntu Touch is opportunistic. If the Android image provides zram, the `zram-touch` job uses it. If not, `zram-touch` transitions to `stop/waiting` with no problems and everyone goes on with their day. Canonical enabled `zram` on devices with 1GB of RAM by including that support in Android. It's unclear what would need to be done to make the Android image provide `zram`, but it does not appear to be included in the Nexus 5 kernel.

In summary:

* Hitting swap is not a problem.
  * The kernel does this normally, even on systems with far more RAM.
  * Someone way smarter than me determined that having 32M of swap provides better performance than having zero swap.
  * It is only 32M of writable data. It seems unlikely that this will cause device longevity concerns.
* zram is opportunistic based on the Android image's support. The Nexus 5's Android image does not have support. It is unclear how this would be changed.
* It would be helpful to have a better definition of heavy use, so we can appropriately target a fix for that use case. Depending on your definition, the system may be working as intended (and adding zram won't help with what you expect the system to do)

(Note: with a better definition, "enable zram" may be just enough of a patch over limited RAM to make you happy. It also may not. That's why I prefer to have the abstract bug.)

**Closed by UniversalSuperBox** 2019-09-01 15:09 UTC

**Comment by dobey** [comment] 2019-09-01 16:29
> * The Nexus 5's Android image does not have support. It is unclear how this would be changed.

AFAIK, it should just be a matter of re-building the kernel with support enabled:
```
CONFIG_ZRAM=y
CONFIG_ZRAM_WRITEBACK=y
CONFIG_ZRAM_MEMORY_TRACKING=y
```

On a standard Ubuntu system, zram is available as a module. On Ubuntu Touch devices, it's just always enabled in the kernel.

**Comment by UniversalSuperBox** [comment] 2019-09-01 16:42
The configs aren't in the file, even as `# _ is not set`. I suspect that zram was not backported to that kernel. zram went mainline in 3.14 and was backported as far back as 2.6.

**Comment by myii** [comment] 2019-09-01 17:36
@UniversalSuperBox Thanks for the detailed discussion.  I appreciate the points you raise.  At this moment, I'll just refer back to points about usage:

> It fills the `32.0M` swap with even fairly standard use. Heavier use causes apps to be terminated.

The part I'd like to focus on is that the whole of the swap is used effectively _all of the time_.  Just start using your device normally and you'll find it's full.  I've never achieved truly "heavy" use; what I've found is that the device becomes unstable (closing apps) way before that and I've just learnt to accommodate for that.  No browser tab spam nor Libertine usage on my device.

If I can find some time, maybe I can provide some figures going from a fresh boot, though to max swap and then onto the first instability.  I'll wait for your response before going ahead with this, to ensure it's worthwhile.

**Comment by UniversalSuperBox** [comment] 2019-09-01 17:45
I'm saying, swap is probably innocent in this case. Don't get sidetracked from the real problem, an unstable device.

If you wanted to confirm or deny the assumption that swap is the problem, you could create a larger swap area by placing a larger empty file at `/userdata/swap.IMG` (I think). You could also turn swap off by running `sudo swapoff /userdata.swap.IMG`, or turn down the swappiness value by running `sudo sysctl vm.swappiness [x]`, where [x] is any number lower than 60.

**Comment by dobey** [comment] 2019-09-01 19:10
Perhaps @myii could volunteer to investigate pulling in the backport of zram to the Nexus kernel. :)

**Comment by myii** [comment] 2019-09-01 19:31
@UniversalSuperBox Let me see what I can do over the coming days.

@dobey I'll leave that to the experts!

**Comment by myii** [comment] 2019-09-01 19:52
OK, I've gone for `512M` swap with the default `swappiness` of `60`.  Let's see how that fares.
