### ISSUE TITLE
No working IPv6 support

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#116] opened 2017-06-18 09:26 UTC
While being in a ntwork with available IPv6 support the phone log shows this message every few seconds:
```

Jun 18 11:23:13 ubuntu-phablet NetworkManager[1342]: <error> [1497777793.9960] platform-linux: do-add-ip6-address[21: 2a02:8388:8981:d00:9c9b:9eab:443f:a3aa]: failure 22 (Invalid argument)
Jun 18 11:23:44 ubuntu-phablet NetworkManager[1342]: <error> [1497777824.2948] platform-linux: do-add-ip6-address[21: 2a02:8388:8981:d00:9c9b:9eab:443f:a3aa]: failure 22 (Invalid argument)

```

**Comment by Flohack74** [comment] 2017-06-18 09:37
Adding vegetahd, after setting autoconf to true:

`echo 1 > /proc/sys/net/ipv6/conf/default/autoconf`

```
Jun 18 11:34:21 ubuntu-phablet NetworkManager[1360]: <error> [1497778461.1348] platform-linux: do-add-ip6-address[10: 2a02:8388:8981:d00:8196:cffe:438e:f808]: failure 22 (Invalid argument)
Jun 18 11:34:21 ubuntu-phablet kernel: [46775.779133][mtk_net][ipv6]receive RA with o bit!
Jun 18 11:34:21 ubuntu-phablet kernel: [46775.779159][mtk_net][ipv6]RDNSS, ignore RA with o bit!

```

**Comment by skeever** [comment] 2018-09-18 08:56
I see this same problem on hammerhead

**Comment by mattbel10** [comment] 2018-12-20 19:06
I have the same on the Pro5. Could it be related to the fact that my phone doesn't connect automatically to my home wifi access point after rebooting?

**Comment by Flohack74** [comment] 2018-12-26 10:55
No that has nothing to do with not reconnecting to a network automatically. Its a mixture of kernel features and issues of NetworkManager in upstream.

**Comment by kkeijzer** [comment] 2020-03-03 22:57
I have the same problem on a OnePlus One running 2020-W07 from the `rc` channel.

I get many errors like

```
platform-linux: do-add-ip6-address[21: 2001:dead:beef::6e2]: failure 22 (Invalid argument)
```

Manually adding the address does work however:

```
ip address add 2001:dead:beef::938 dev wlan0
```

After that, the phone has working IPv6 connectivity, but loses it every time the network switches.

Is there any workaround for this problem that is probably in NetworkManager? I would really like IPv6 to just work.

**Comment by Flohack74** [comment] 2020-03-03 23:09
No sorry, no workaround. It needs to be patched somehow, but nobody knows whats wrong. network-manager guys offered help but the dried out... PRs and analysis welcome ofc.

**Comment by kkeijzer** [comment] 2020-03-03 23:17
Do you know if this also happens on PinePhones? My Brave Heart is still locked in China, so I probably won't get it anytime soon.

But if it works normally on a mainline kernel, then something is probably broken in the Android 3.4.0 kernel.

**Comment by kkeijzer** [comment] 2020-03-04 13:51
Maybe not the nicest "fix", but running `sudo dhclient -6` after establishing the connection, will add a DHCPv6 address to the interface nicely. Maybe I can put something in `/etc/NetworkManager/dispatcher.d/` to at least make it work and test for adverse effects.

**Comment by kkeijzer** [comment] 2020-03-04 14:42
Well, this is not very pretty, but it works...

**/etc/NetworkManager/dispatcher.d/99dhclient6** 
```
#!/bin/bash

IF=$1
STATUS=$2

if [ "$IF" == "wlan0" ]
then
    case "$2" in
        up)
         logger -s "Running dhclient to work around IPv6 bug..."
         dhclient -6 "$IF"
        ;;
        down)
         kill $(pgrep -f "dhclient -6 "$IF"")
        ;;
    esac
fi
```

It doesn't do SLAAC and it will request two IPv6 addresses (as NetworkManager's dhclient -6 child will do the same), but it does allow me to access IPv6 internet automatically on every WiFi connection.

The only downside is that this has to be put in the read-only part of the filesystem.

**Comment by kkeijzer** [comment] 2020-03-04 23:30
There are some more topics about this issue, but I can't seem to find anything leading towards a solution. However, many cases do seem to point to a 3.4 Linux kernel and an Ubuntu 16.04 rootfs.

https://forum.odroid.com/viewtopic.php?t=27378
https://forum.odroid.com/viewtopic.php?t=24026
https://gitlab.com/postmarketOS/pmaports/issues/148

Eventually I also found a lot of this in my syslog:

```
The kernel does not support extended IFA_FLAGS needed by NM for IPv6 private addresses. This feature is not available.
```

Which seems to be the exact problem.

I then found this thread: https://mail.gnome.org/archives/networkmanager-list/2016-May/msg00025.html

**Comment by kkeijzer** [comment] 2020-03-05 09:23
I've created a new bug report on NetworkManager's bug tracker: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/373

I'm now looking into if I can reproduce this problem on an old Armbian xenial image with 3.4 kernel on one of my Olimex boards. That would make it easier to test than on a phone.

**Comment by Flohack74** [comment] 2020-03-05 09:49
I dont think the bug will be in recent NM versions. They will tell you to update, and we already tried to do this here for example: https://github.com/ubports/network-manager-packaging/pull/1 - BUt, alas, there are special patches inside to make it work with ofono and network modem. So this PR cannot be merged as it needs further fixing. I am trying to get this upgrade since over one year now...

**Comment by kkeijzer** [comment] 2020-03-05 09:53
@Flohack74 Can you tell me where the source code for the version used in UT is? Maybe they would be willing to help out backporting something.

**Comment by kkeijzer** [comment] 2020-03-05 11:30
I was able to reproduce this bug on a development board with a non-patched and slightly newer NM as well. See https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/373#note_427641

**Comment by Flohack74** [comment] 2020-03-06 07:44
Cool. Meanwhile a dev from NM team contacted me, we might get the upgrade moving again a bit ;)

**Comment by kkeijzer** [comment] 2020-03-06 12:02
Is there something I can do to help with that as well?

By the way, are you certain that this bug is fixed in that newer NetworkManager, or only hopeful?

**Comment by Flohack74** [comment] 2020-03-06 20:01
Hmm one thing you could please do: Write a doc about how to enable debug logs correctly, I habe a nother case here with high CPU usage for NM and I want to tell this guy how to capture logs, but on Ubuntu Touch thats not easy. Second question, no I dont know if its fixed, I just hope so ^^

**Comment by kkeijzer** [comment] 2020-03-08 12:24
Hmm, my guess would be:

```
sudo mount -o remount,rw /

sudo sh -c echo "[logging]
level=TRACE
domains=all" >> /etc/NetworkManager/NetworkManager.conf

sudo mount -o remount,ro /

sudo service network-manager restart
```

And then look in `/var/log/syslog`.

**Comment by Flohack74** [comment] 2020-06-19 15:45
@kkeijzer btw source code is from this packaging repo: https://github.com/ubports/network-manager-packaging which basically grabs https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/stable-phone-overlay/+files/network-manager_1.2.2.orig.tar.xz

**Comment by zubozrout** [comment] 2020-07-23 14:11
I think the support for this has just landed in devel today (or maybe earlier but tbh I did not check thoroughly) and although I've seen some weird issue when I first started my phone after this update as it did not see the sim card but on second boot+ everything seems work flawlessly on my MX4 so far. And I have IPv6 working, thank you :).

**Comment by kkeijzer** [comment] 2020-08-17 14:04
I tested this on my grandpa's bq E4.5 and I can confirm that IPv6 is now working properly on the very old devices.

**Closed** 2020-08-17 18:51 UTC
Labels: bug, team: middleware
