### ISSUE TITLE
OTA-25 galaxy s3 neo + must be turned on 2 times before launch the system

### ISSUE THREAD

**Issue by mosiubuntu** [ubports/ubuntu-touch#2126] opened 2023-04-04 22:28 UTC
When i turn on the device, it shows the galaxy pic then the ubuntu touch animation and then it turns off by itself. So i have to turn it on again and after that it starts.

**Comment by lduboeuf** [comment] 2023-04-05 09:06
confirmed on many devices.

**Comment by lduboeuf** [comment] 2023-04-06 11:29
duplicate of https://github.com/ubports/ubuntu-touch/issues/2124

**Closed as completed by lduboeuf** 2023-04-06 11:29 UTC
Labels: bug
