### ISSUE TITLE
Cant Change default call forwarding settings

### ISSUE THREAD

**Issue by ManyHatsOfLinux** [ubports/ubuntu-touch#577] opened 2018-05-01 22:42 UTC
- Device: Nexus 5
- Channel: Development
- Build: Ubuntu15.04 (r285) armhg (20171221)

### Steps to reproduce
 System Settings > Phone > Call forwarding | [[ change anything you want here. ]]
### Expected behavior
configuration changes persist after leaving the menu
### Actual behavior
they do not. 

Is someone getting my phone calls?

**Comment by ManyHatsOfLinux** [comment] 2018-05-01 23:01
After looking the number up, i think its just the voicemail number att uses.

**Comment by UniversalSuperBox** [comment] 2018-05-02 00:52
So is this still an issue with Ubuntu Touch, or do you think that the forward is from AT&T?

**Comment by ruedigerkupper** [comment] 2018-06-23 09:08
Confirmed on hammerhead OTA-3 vivid.
I  ended up calling the phone codes from the dialer app to change call forwarding. It works, but is not reflected in system settings.

**Comment by NeoTheThird** [comment] 2018-06-27 08:17
Just to be sure, can someone confirm this for xenial?

**Comment by Flohack74** [comment] 2018-06-27 08:47
This is neither release nor device specific, on the OPO I get:
![grafik](https://user-images.githubusercontent.com/16186470/41963282-6922e7cc-79f7-11e8-8f33-be15f09f9e4f.png)

Red text saying that call forwarding cannot be changed "just now" ... Well it seems to be persistent.

**Comment by Flohack74** [comment] 2018-06-27 11:56
Here on N5 and xenial same story, maybe this never worked:
![grafik](https://user-images.githubusercontent.com/16186470/41972333-e0941e60-7a11-11e8-99ec-5fbfa0b9d412.png)

**Comment by WillemHexspoor** [comment] 2018-11-25 21:10
On my Nexus 5, Xenial and OTA-5, call forwarding works the way it should. I can't reproduce.

**Comment by UniversalSuperBox** [comment] 2018-11-26 17:40
I'm also able to change call forwarding settings under OTA-5 and 16.04 `devel`. Closing barring any new confirmations.

**Closed by UniversalSuperBox** 2018-11-26 17:40 UTC
Labels: device: hammerhead, needs confirmation
