### ISSUE TITLE
file access problem for applications

### ISSUE THREAD

**Issue by hoh61** [ubports/ubuntu-touch#618] opened 2018-05-20 18:11 UTC
### Illustrations

- Device: frieza
- Channel: 16.04/devel
- Build: r83

### Steps to reproduce

insert SD-card
Filemanager recognizes the SD card but cannot see the content.

write application that will write and read a file in the home folder

### Expected behavior

files in home folder should be visible (like in the console application or via adb)
SD-Card content should be visible (like in the console application or via adb)
files can be created in the owned hone folder.

### Actual behavior

Everything described above doesn't work.

### Logfiles and additional information

I couldn't find any hints on this behavior in the log files.

**Comment by Flohack74** [comment] 2018-05-20 19:00
Confirmed on FP2

**Comment by UniversalSuperBox** [comment] 2018-05-30 14:03
It is correct that most applications will not be able to access the SD card or home folder. AppArmor confinement restricts apps to their own folders in `.cache` and `.config`. Content should be read from and written to storage using the [Content API](https://api-docs.ubports.com/sdk/apps/qml/Ubuntu.Content/Ubuntu%20Content%20API.html). An application may use the new `document_files` or `document_files_read` policies to gain access to `~/Documents`, but this access is reserved for applications that *really* need that functionality like the Document Viewer.

To access files on your SD card from the File Manager, click the lock in the upper right corner of the File Manager to give it rights to access all files on your device.

I'm not able to see anything but the expected behavior here so I'm closing this issue for now. If you are still experiencing the problem, please leave a comment and we can discuss further.

**Closed by UniversalSuperBox** 2018-05-30 14:03 UTC
Labels: bug

**Comment by UniversalSuperBox** [comment] 2018-05-30 16:08
AppArmor policies denying access to files in the home folder are in place for user protection. Not all apps need access to all of the user's data. Apps which require access to these folders should request it using the appropriate entries in their `apparmor.json` file or by using the Content Hub (this would be the appropriate thing to do with your app). As it is, the system appears to be working as designed. The music app and friends have the appropriate policies in place to access their required files. 

I've noticed that we don't have a full list of policy groups available, so I've filed https://github.com/ubports/docs.ubports.com/issues/113. There is an incomplete list of available policies on [App Development](https://github.com/ubports/docs.ubports.com/issues/113). The complete list can be found in [apparmor-easyprof-ubuntu](https://github.com/ubports/apparmor-easyprof-ubuntu/tree/xenial/data/policygroups/ubuntu), specifically the 16.04 folder for the next release of UT. Note that `document_files`, `music_files`, and the like allow access to their respective folders on the SD card or home folder.

I am not able to reproduce the problem with an SD card hotplug causing an "Internal error". Every time I plug in my Micro SD cards, the phone says "Storage device detected - This device will be scanned for new content" and apps which are able to access the content (such as the music app as mentioned before) work correctly. I'm also able to access the card from my PC via MTP. You may wish to perform a `fsck` or `chdisk` on your card to ensure its consistency.

![screenshot20180530_105235993](https://user-images.githubusercontent.com/21966173/40732006-f0eaa516-63f7-11e8-8aa9-d54369397225.png)

I found that my SD card was listed as empty in the file manager on my FP2, but the contents were displayed when I used the Unlock option.

![screenshot20180530_105350547_scale](https://user-images.githubusercontent.com/21966173/40732352-c9a1a508-63f8-11e8-9cee-5c72e0816696.png)

If you would like to discuss the addition of new policies or changes to content-hub (it is definitely a system which needs improvement so I don't mind you saying so), a post on [the appropriate subforum](https://forums.ubports.com/category/35/app-development) detailing the changes you have in mind would be the best place for it. GitHub issues are not always the best place for discussions at length.

**Comment by hoh61** [comment] 2018-05-30 21:13
just a few thoughts:
For which reason you should deny to grand a full access to a SD card? A tablet is primarily a display device. Why sould we block all display activities from the SD card?

OK, you can grant access by activating the superuser. By this you have full access to all system files too.  Would you like to allow everybody to mess around with your system settings?

**Comment by hoh61** [comment] 2018-05-30 21:51
Sorry, but I have some different approaches in mind. User data, at least the config and cache data as well as maybe some application specific data can only rely on the home folder since this is available constantly, not any removable media. Furthermore they are most commonly stored as hidden files and by this not visible to the normal user.  So where is the problem?

What kind of application is using the SD card as home folder and are storing data without my explicit action? 

And when I use a tablet as work device I strongly demand a free access on SD card and home folder since I want not to be limited by the four default folders!

Finally me, the owner of all the data, will have a free access on my(!) data by the filemanager app as default. That's the  reason for this kind of software.

Since I had this requested behaviour in 15.10 , the original ubuntu touch version on this device, I cannot accept any excuses why it shouldn't remain so.

**Comment by sverzegnassi** [comment] 2018-05-30 23:29
In the dev version of File Manager we got it fixed, and SD card access (or any other USB OTG external drive) is fully unlocked by default. Access to hidden files[1] or hidden folders[2] still requires authentication.

This is a specific design choice. Since those fs entries may contain critical data to make apps function properly, File Manager has been designed to prevent accidental deletion or modification.

The question is rather when work on the 'dev' version will be merged with UBports 'master'.

- There is a custom Clickable manifest in order to get '.deb' dependencies included at the build time
- A blocker was the need for a [custom Docker container](https://hub.docker.com/r/clickable/ubuntu-sdk/tags/) to deal with broken dependencies in 'vivid' repositories. That partially breaks with the regular functionalities included in Clickable.

With 'xenial' everything is expected to work out-of-the-box. I've already got some request to finalize the new build system, and that's what I wish to complete within the week.

I expect to create a new branch within UBports' repository. There was no clear consensus whether to simply merge the new code in 'master'. I'm not going to argue about the best solution, so I'll leave the final decision to whom currently manages all the repos.

P.S. No third party app can access to external media atm. There is no risk for File Manager in unlocking SD card access, since third party apps would still rely on ContentHub service.

[1] They're used for system configuration
[2] e.g. '.cache' '.local' - They contains applications data
