### ISSUE TITLE
It should be possible to add the date of birth for a contact

### ISSUE THREAD

**Issue by Benni777** [ubports/ubuntu-touch#873] opened 2018-09-07 14:03 UTC
Feature request:
It should be possible to add the date of birth (YYYY-MM-DD) of a contact in contacts.

**Comment by hummlbach** [comment] 2018-09-08 01:50
This is already tracked here: https://github.com/ubports/address-book-app/issues/5.

**Comment by Flohack74** [comment] 2018-09-08 11:58
Duplicate of  ubports/address-book-app#5

**Closed by Flohack74** 2018-09-08 11:58 UTC
Labels: duplicate
