### ISSUE TITLE
Nexus5, Ubuntu Touch 16.04, phone conversation recording problem.

### ISSUE THREAD

**Issue by leftside2** [ubports/ubuntu-touch#1020] opened 2019-01-07 11:50 UTC
### Illustrations

- Device: Nexus 5
- Channel:
- Build: 16.04 ubuntu touch

### Steps to reproduce
Receive a phone call and push the record icon.

### Expected behavior
Recording voice conversation between the caller and me and saving to a certain directory.

### Actual behavior
The caller doesn't hear my voice when I enable the recording, but he can hear me again if I un-check the recording icon. Moreover, I can't find where the recorded file is saved.

**Comment by UniversalSuperBox** [comment] 2019-01-07 15:38
Ubuntu Touch does not have a call recording feature. However, one is requested in https://github.com/ubports/ubuntu-touch/issues/788.

Might you be using this icon?

![microphone mute button highlighted](https://user-images.githubusercontent.com/21966173/50776009-71ae0800-125d-11e9-8821-e47709f74c2a.png)

This is the Microphone Mute button, which turns off your microphone so the remote end cannot hear you.

Please let me know if I misunderstand the problem. Otherwise I'll close this issue as a duplicate of the call recording request.

**Comment by dobey** [comment] 2019-01-08 02:43
"Normal feature of the smartphone" ?

I'm sorry, but I don't think I've used any smartphone in the last 10 years where recording a conversation was a standard feature of the phone dialing application. I just checked on my HTC 10 and it certainly doesn't have a record button on the call screen.

**Comment by UniversalSuperBox** [comment] 2019-01-08 02:49
Okay, glad I wasn't just unaware of a mystery feature in Ubuntu Touch! :D

I'll close this issue as it is a duplicate of https://github.com/ubports/ubuntu-touch/issues/788, requesting a call recording feature in the OS.

**Closed by UniversalSuperBox** 2019-01-08 02:49 UTC
