### ISSUE TITLE
Changelog on system updates.

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-touch#1525] opened 2020-08-05 18:08 UTC
An changelog for system or device specific changes or fixes on system updates.

**Comment by UniversalSuperBox** [comment] 2020-08-07 18:11
Hi, @rubencarneiro!

Looks like this is a duplicate of the report https://github.com/ubports/ubuntu-touch/issues/1478. To keep the issue tracker clean, I'll close this report. Please continue any further discussion there.

Thank you!

**Closed by UniversalSuperBox** 2020-08-07 18:11 UTC
