### ISSUE TITLE
Unable to see touchsreen keyboard after disconnecting bluetooth keyboard

### ISSUE THREAD

**Issue by kkarioja** [ubports/ubuntu-touch#795] opened 2018-07-25 14:44 UTC
Bug report

- Device: BQ M10 Frieza and Logitech K830 bluetooth keyboard
. OS: 16.04
- Channel: RC
- Build: 2018-W30

### Steps to reproduce
Switch on and connect BT keyboard to enter desktop mode. Then switch off keyboard and/or manually exit desktop mode.

### Expected behavior
System exits desktop mode and the touchscreen keyboard appears as needed.

### Actual behavior
System does not exit desktop mode when switching off the keyboard. No touchscreen keyboard will be available until reboot. Exiting the desktop mode in addition to switching off the keyboard does not elp. If device is locked and requires passphrase, the only way to unlock is to connect BT keyboard again or rebooting the tablet.

**Comment by Flohack74** [comment] 2018-07-26 18:00
Duplicate of #351

**Closed by Flohack74** 2018-07-26 18:00 UTC
