### ISSUE TITLE
calculator app: 49.8-2.1 = 47.699999999999996

### ISSUE THREAD

**Issue by gurucubano** [ubports/ubuntu-touch#940] opened 2018-10-29 05:40 UTC
- Device: BQ E4.5
- Channel: Stable
- Build: OTA-5

### Steps to reproduce

start calculator app and enter 49.8-2.1

### Expected behavior

result expected: 47.7

### Actual behavior

result: 47.699999999999996

**Comment by Daniel20000522** [comment] 2018-10-29 06:00
The same problem on Nexus 5 (2018-W43)

**Comment by dark-eye** [comment] 2018-10-29 08:01
This a regular floating point binary and decimal system difference the  only  way to solve it  is to round the  number at a given decimal point.
I think that we can just  round any value lower then  10^-9 (but only the displayed value not the  actual computed value  so  further calculation will not  lose possible perception).
maybe  we  should add it a as configurable value  so the user  can control it  and  also  won't  be confuse when the  value is rounded

**Comment by mymike00** [comment] 2018-10-29 09:31
well but the user expects a decimal system result so the app should provide it and also adjust the actual computed value as otherwise the user will do further calculation with a different number from what he is expecting...

**Comment by Flohack74** [comment] 2018-10-29 17:53
But I agree with the OP that it should be at least consistent with Desktop. This is from Ubuntu 16.04:

![grafik](https://user-images.githubusercontent.com/16186470/47669757-e274dc00-dbab-11e8-9b0e-82b92ec279fd.png)

But maybe its different on armhf...?

**Comment by Flohack74** [comment] 2018-10-29 18:48
Its rather QML/JavaScript, and different math libraries have different precisions. Deal with it, floating point arithmetic cannot be "precise" on any computer system.

**Comment by Flohack74** [comment] 2018-10-29 18:50
Actually its using http://mathjs.org/ -> So please file a bug with them, if you think thats not correct.

**Comment by dobey** [comment] 2018-10-29 18:57
I don't think this should be closed as "we don't care, because some languages are broken in some cases." I think we should fix the problem. If the problem is JavaScript can't do the correct thing, then we should almost certainly be switching it to do calculations within the C++ plug-in rather than in JS. Maybe it is not a priority, but I think it's something someone should fix, and it would definitely be a good bug for someone working on UT bugs in a mentorship program, to work on.

**Comment by Flohack74** [comment] 2018-10-29 19:01
Alright.

**Comment by gurucubano** [comment] 2018-10-29 19:17
re/ comparing with 'bc': do you prefer compare with the app on an iPhone? 
This gives 47,7. It's just a bug, and it's riduculous, and should be fixed 
and not closed before being fixed.


-- 
Sent from my Ubuntu phone
http://www.unixarea.de/

**Comment by Flohack74** [comment] 2018-10-29 19:51
I will close this here and move to the right tracker in calculator-app...

**Comment by dark-eye** [comment] 2018-10-29 19:51
this might help : https://github.com/MikeMcl/bignumber.js/

**Comment by AnotherStranger** [comment] 2018-10-29 21:02
Hey there, the bug is indeed caused by math.js.
The calculator app used an older version of math.js
I already filed a pull request for the calculator.

In a nutshell: adding the newest math.js to the calculator fixes the issue.

**Comment by Flohack74** [comment] 2018-10-29 22:34
I would love to move this ticket to calculator-app, but unfortunately the github issue mover is broken.

**Comment by Flohack74** [comment] 2018-10-31 21:32
Fixed in calculator-app 2.3.8

**Closed by Flohack74** 2018-10-31 21:32 UTC

**Comment by gurucubano** [comment] 2018-11-01 11:39
On Wed, 31 Oct 2018 14:32:54 -0700, Florian Leeber wrote:
> Fixed in calculator-app 2.3.8
>

ACK.


-- 
Sent using Dekko from my Ubuntu device
