### ISSUE TITLE
Issues with turning off screen and screen brightness on latest N5 `devel` update (`1583`; `2020-06-25`)

### ISSUE THREAD

**Issue by myii** [ubports/ubuntu-touch#1493] opened 2020-06-25 12:04 UTC
- Device: hammerhead
- Channel: devel
- Build: 1583 (`2020-06-25`)

### Steps to reproduce

https://t.me/ubports_qa_team/35188 (involving @lduboeuf):

> myii, [25.06.20 11:45]
> Having a couple of strange problems with my N5 devel with the latest update (1583 == 2020-06-25).
> 
> 1. The power button won't turn off the screen and go to the screen lock — but it's working to turn on the screen in the first place.
> 2. The screen brightness settings aren't working and the auto-brightness setting is missing.
> 
> Anyone else facing these problems?
> 
> Lionel Duboeuf, [25.06.20 12:42]
> yes for me the same

### Expected behavior

Standard behaviour:

* Screen turning off when power button is pressed.
* Brightness configurable.

### Actual behavior

As mentioned above.

**Comment by UniversalSuperBox** [comment] 2020-06-26 00:14
This is most probably a duplicate of https://github.com/ubports/ubuntu-touch/issues/1446, but on devel. I'll close that one.

**Comment by UniversalSuperBox** [comment] 2020-06-26 00:15
That darn "Close and comment" button gets me every time

**Comment by myii** [comment] 2020-06-26 10:13
Using the workaround suggested by @UniversalSuperBox for the time being.

https://t.me/ubports_devel/7360:

> Well, 
> `echo 'pre-start script\n sleep 4\nend script' > /etc/init/repowerd.override`
> does fix the issue

```upstart
pre-start script
    sleep 4
end script
```

**Comment by FeZoli** [comment] 2020-06-28 15:30
Hi Guys,

I've applied the workaround, then rebooted. 
Unfortunately my N5 is in boot-loop since then.

I could power off only in the boot menu (volDown + power button)

What do you think I can do now?

Thanks,

FeZ

**Comment by myii** [comment] 2020-06-28 15:52
> I've applied the workaround, then rebooted.
> Unfortunately my N5 is in boot-loop since then.

@FeZoli I noticed that the `echo` command didn't quite work for me so I had to edit the file `/etc/init/repowerd.override` to make sure it's content was as shown.  If you're still having trouble, try to get in touch on Telegram.

**Closed** 2020-07-01 14:06 UTC
Labels: bug, critical (devel)

**Comment by myii** [comment] 2020-07-02 13:42
Upgraded to the latest `devel` update and removed the workaround, all appears to be working well.  Thanks for the fix!
