### ISSUE TITLE
Predictive text bug.

### ISSUE THREAD

**Issue by rockybulwinkle** [ubports/ubuntu-touch#545] opened 2018-03-31 01:30 UTC
- Device: OnePlus One
- Channel: 15.04 stable
- Build: r3

### Steps to reproduce
1. Open up the keyboard in the telegram web app (I'm not 100% sure that it's a specific telegram web app bug or if it's truly an ubuntu touch bug. I don't see it in the messaging app.)
2. Type some words, for this example I'll say "hello world"
3. press enter to send the message

### Expected behavior
I don't expect the last word of my last message to appear in predictions. I don't expect the last word of my last message to be entered into the text entry box if I navigate away and back.

### Actual behavior
At this point the bug manifests in three ways:
1. Notice that the last word (in this case, "world") appears in the predictive text
2. If you press space, it fills in the last word of the last message.
3. If you didn't press space, navigate to a different app and back, you will find the text entry box filled with the text.

**Comment by balcy** [comment] 2018-03-31 19:35
should be a duplicate of https://github.com/ubports/keyboard-component/issues/7 / https://github.com/ubports/oxide/issues/1 
can someone test if it is resolved in 16.04 ?

**Comment by balcy** [comment] 2018-03-31 19:37
a possible solution was merged to the 1.19 branch of oxide:
https://github.com/ubports/oxide/pull/2

**Closed** 2018-04-02 16:46 UTC
Labels: duplicate
