### ISSUE TITLE
google account - unable to create

### ISSUE THREAD

**Issue by ksalver** [ubports/ubuntu-touch#1463] opened 2020-06-03 17:47 UTC
on my device (BQ E4.5) i cannot add my google-account since update to OTA-12

### Illustrations

- Device:
- Channel:
- Build:

**Comment by Qiangong2** [comment] 2020-06-08 17:09
Duplicate of #1456

**Comment by lduboeuf** [comment] 2020-06-18 06:53
close as duplicate

**Closed by lduboeuf** 2020-06-18 06:53 UTC
