### ISSUE TITLE
mp4 video playback has color issue

### ISSUE THREAD

**Issue by lgd821** [ubports/ubuntu-touch#848] opened 2018-09-01 16:46 UTC
### Illustrations

- Device: Hammerhead
- Channel: stable
- Build: OTA-4

### Steps to reproduce
Play back any .mp4 video

### Expected behavior
Video is displayed on the screen without any issue

### Actual behavior
The video is play back as expected, but the green colour channel seems to have a different scalling regarding screen size. This lead to a strange looking video

**Comment by NeoTheThird** [comment] 2018-09-01 16:59
Duplicate of #7.

**Closed by NeoTheThird** 2018-09-01 16:59 UTC
