### ISSUE TITLE
Mircacast (wireless display) no longer works in 16.04

### ISSUE THREAD

**Issue by BigET** [ubports/ubuntu-touch#956] opened 2018-11-16 18:28 UTC
- Device: turbo
- Channel: stable
- Build: ota 5

### Steps to reproduce
The wireless display is not working on 16.04 (was working on 15.04)
Have a miracast dongle (Mine is "prestigio miracast dongle") attached to a HDMI monitor and powered.
Activate wifi.
Go into SystemSettings->Brightness & Display
Activate "External Display"
Enter "Wireless display"
Choose the dongle.

### Expected behavior
After some handshaking you should have your display on your Monitor and the telephone screen becomes a track-pad.

### Actual behavior
The handshaking stops right after security step.

**Comment by mardy** [comment] 2018-11-17 11:39
Duplicate of #781.

**Closed by mardy** 2018-11-17 11:39 UTC
