### ISSUE TITLE
Provide Cell Broadcasting support to Ubuntu-touch

### ISSUE THREAD

**Issue by matv1** [ubports/ubuntu-touch#350] opened 2017-12-04 23:38 UTC
Part of the GSM specification is supporting cell-broadcast (sms-bc). This means being able to receive text messages that are 'broadcast' to all phones in the range of any or all cell towers in a network. Ubuntu Touch does not support this currently.

Some practical context: in the Netherlands almost all people subcribe to the so-called NL-Alert broaddcast government service, to notify them of any disaster nearby. It is my understanding that most european countries have a similar implementation.

In Android this is typically configured under 'Mobile Broadcast settings' where one can opt-in to receiving emergency texts.

I am told that Ofono supports this already, and exposes a dbus API for it.
This would mean that Ubuntu touch 'only' needs an interface for this. Either under System-Settings --> ' Cellular' or on the Settings page of the Messaging app. I cannot make up my mind which is better.

Verifying this works can be done in the Netherlands where the government periodically sends out test-messages on pre-defined moments.

**Comment by YougoCodes** [comment] 2017-12-05 07:17
https://github.com/ubports/ubuntu-touch/issues/141 adresses this also. 
@Flohack74 mentioned a doc about the API:
https://github.com/intgr/ofono/blob/master/doc/cell-broadcast-api.txt

**Comment by NeoTheThird** [comment] 2017-12-05 10:29
Duplicate of #141.

**Closed by NeoTheThird** 2017-12-05 10:29 UTC
Labels: feature request
