### ISSUE TITLE
[xenial] Web browser is not respecting the space between the words and numbers are in blue circles

### ISSUE THREAD

**Issue by lapor** [ubports/ubuntu-touch#423] opened 2018-01-09 17:55 UTC
### Description of the feature
Web browser doesn't respect spaces between the words and numbers are in odd blue circles. But not on every web page. One of the affected is github.

### Illustrations

- Device: M10 FHD
- Channel: 16.04/devel 
- Build:?

### Steps to reproduce
Open web browser and go to the github page.

### Expected behavior
There should be spaces between the words and numbers should be in normal font.

### Actual behavior
There are no spaces between the words and numbers are in blue circles.

**Comment by ernesst** [comment] 2018-01-17 04:10
Same issue on hammerhead, r206

**Comment by tomoqv** [comment] 2018-03-16 09:13
Perfect! Just `sudo apt remove gsfonts` and web pages look normal again.

**Comment by NeoTheThird** [comment] 2018-03-16 09:33
@tsimonq2 Do you want to get this in?

**Comment by userj** [comment] 2018-03-25 17:27
@tomoqv `sudo apt remove gsfonts` requires write access I guess?

**Comment by tomoqv** [comment] 2018-03-25 19:28
> `sudo apt remove gsfonts` requires write access I guess?

Correct.

**Comment by padraic7a** [comment] 2018-03-28 07:14
This  looks straightfoward , could this be fixed for the next 16.04 update  please?
It would really increase usability.

**Comment by Flohack74** [comment] 2018-03-28 19:04
We just need to modify the list of installed debs, but I am always failing with understanding the image build process, so it's not me ;)

**Comment by PhoenixLandPirate** [comment] 2018-03-31 16:59
@userj 
to get the fonts to work you just use the command
> sudo mount -o remount, rw /
then 
> sudo apt remove gsfonts

You would have to do this every update however.

**Comment by padraic7a** [comment] 2018-03-31 18:49
You don't want individuals fixing issues on their own devices for the development build though. That interferes with their ability to spot and submit bugs.

**Comment by PhoenixLandPirate** [comment] 2018-04-01 16:52
@padraic7a I dont quite understand what you expect in a development build, Theres been development builds in which the phone doesnt boot, and some where it will but the keyboard doesnt show up.

they're bugs you can fix yourself or report and have them fixed, this is one, it just hasn't been fixed yet.

**Comment by UniversalSuperBox** [comment] 2018-04-30 18:54
The problem actually appears to be the `fonts-emojione` package. Removing that fixes the issue, but I expect more than 50 hate e-mails if we remove the color emoji from Ubuntu Touch.

**Comment by padraic7a** [comment] 2018-04-30 19:57
hmm, just googling shows that there have been similar problems on android: https://github.com/emojione/emojione/issues/222

Is this an updated fork / reimplementation of emojione fonts?
https://github.com/eosrei/twemoji-color-font
The readme does speak about issues with whitespace that sound similar. It talks about Bitstream Vera being used instead of DejaVu as a solution to these spacing issues. 
From this search it looks like UT uses DejaVu. So might switching to Bitstream Vera be a solution / owrth testing?
[I have no idea how to do this or how big a deal it would be]

**Comment by UniversalSuperBox** [comment] 2018-04-30 21:11
No, it looks like the Emoji One font provided characters for some symbols that it really shouldn't (like spaces and numerals), causing this issue. This should be fixed by the PR that GitHub handily linked above.

This has fixed the devices I've tested on, but if you'd like to test yourself before it's merged you can do the following:

```
sudo mount / -o remount,rw
echo "deb http://repo.ubports.com/ xenial_-_emoji-are-fun main" | sudo tee -a /etc/apt/sources.list.d/emoji.list
sudo apt update
sudo apt install fonts-emojione
```

Right after that, you can refresh any browser pages and they should work correctly again.

Waiting for merge to close.

**Comment by padraic7a** [comment] 2018-04-30 21:15
Cool, I'll test it now so.

**Comment by padraic7a** [comment] 2018-04-30 21:27
hmmm, I don't have enough free space in /var/cache/apt/archives.

I don't think I installed anything that way ....

Any I guess I'll wait for the update

**Comment by Flohack74** [comment] 2018-05-01 09:01
Merged, should be in the the nightly devel tomorrow :)

**Comment by UniversalSuperBox** [comment] 2018-05-02 00:50
Closing for QA.

For reference, these are the sites that I was able to confirm the issue and fix with:

* "Adobe fonts" at [Browser Font Test](http://www.zipcon.net/~swhite/docs/computers/browsers/fonttest.html)
* [Wikipedia](https://en.wikipedia.org/wiki/Main_Page)
* [GitHub](https://github.com)

**Closed by UniversalSuperBox** 2018-05-02 00:50 UTC
Labels: bug

**Comment by Arc676** [comment] 2018-05-02 08:41
Just updated to the latest build (16.04, r357, devel channel) on Nexus 5 (hammerhead). Can confirm that the issue is fixed, at least on GitHub with regards to the spacing and number bubbles.

![GitHub view](https://user-images.githubusercontent.com/30745465/39513543-50187342-4e27-11e8-9a08-7d2776f30b8f.png)
