### ISSUE TITLE
System Settings Update feature not including (some? all?) app updates that are available in the OpenStore

### ISSUE THREAD

**Issue by stuarttempleton** [ubports/ubuntu-touch#1484] opened 2020-06-18 14:25 UTC
- Device: PinePhone
- Channel: Developer
- Build: 52

### Steps to reproduce
Navigate to System Settings -> Updates. Existing app updates are not showing up in the list. 
Navigate to OpenStore and view an app with an active update (Podbird for example). The app has an upgrade button.

### Expected behavior
The System Settings->Update feature includes updatable apps with new versions on the openstore.

### Actual behavior
The System Settings->Update feature does *not* include app updates.

**Comment by ubuntu-touch-testing** [comment] 2020-06-19 15:48
Yes, I have had this also.   Occurred in the past few days on Development Channel.  However, I hadn't done the "Reinstall all apps" after some version changes (eg stable to RC to dev), so I am not sure if it maybe related to that?  Have you been always doing "Reinstall all apps" after major updates?

Settings --> Updates --> Update settings --> Reinstall all apps

**Comment by UniversalSuperBox** [comment] 2020-06-25 23:22
Hi @stuarttempleton and @ubuntu-touch-testing,

This occurs when the apps installed on the system do not match any version that has ever been available in the OpenStore. When this occurs, you'll see the OpenStore warning you that there is a "Stable version available" rather than an "Update available" for your apps.

This was caused by us installing apps that weren't released in the OpenStore into the image.

This should be resolved in stable OTA 3 or anything newer, app updates are now baked into the image.

For reference, here is what apps that will never show in system-settings look like, under the "Stable version available" header:

![screenshot20200625_180103017](https://user-images.githubusercontent.com/21966173/85803940-f4ef4200-b70d-11ea-958b-e3a49ba9b541.png)

**Closed by UniversalSuperBox** 2020-06-25 23:22 UTC
