### ISSUE TITLE
Call volume not controlled by volume buttons

### ISSUE THREAD

**Issue by tecywiz121** [ubports/ubuntu-touch#1749] opened 2021-06-15 18:35 UTC
## BUG REPORT

- Device: Pixel 3a (`sargo`)
- Channel: Stable
- Build: OTA-17 // Device Image 20210504-15900 // UBports Image 20210504-3362

### Steps to reproduce

1. Make or receive a phone call.
2. Attempt to adjust volume with side buttons.

### Expected behavior

Call audio should get quieter or louder based on the displayed volume and button pushed.

### Actual behavior

The call audio remains way too loud, though the volume dialog appears and shows the volume changing.

### Additional Information

* Possible duplicate of: #1621 #1402 #992

**Comment by UniversalSuperBox** [comment] 2021-06-16 21:19
I agree that this sounds like a duplicate of all of those issues. However, it seems that each device needs its call audio volume fixed independently of the others... which is annoying. So this issue stands alone.

**Comment by Openanonwriter** [comment] 2021-06-17 01:33
Confirmed Pixel 3a, RC 2021-W24

**Comment by Openanonwriter** [comment] 2021-06-23 17:43
OTA-18 did not fix this issue.

**Comment by Xozk** [comment] 2021-08-06 23:56
Pixel 3a same issue, even after todays update.

**Comment by mattbel10** [comment] 2021-08-14 17:28
I noticed this issue applies to my Pixel 3a as well when in a call and earphones are plugged in: volume modulation isn't working at all and the volume results set too high for my poor ears so I desperately need to lower the volume but I can't.
Device: Pixel 3a
Channel: Devel
Build: 2021-07-31/2

**Comment by rusins** [comment] 2021-09-27 12:48
If I adjust the volume below 50% or so, the actual volume goes straight down to zero. Possibly more related to #992, but device is a pixel3a, so I guess this is the correct issue to report in.

OS build number OTA-19 (2021-09-10)

**Comment by Flohack74** [comment] 2021-09-28 12:09
@fredldotme thats interesting I see similar things on Halium 10´s SHIFT6mq, and I thought you fixed that already? Lets have a call this week.

**Comment by Intrinsically-Sublime** [comment] 2022-01-07 18:44
This is now happening on the oneplus 6T Fajita as of OTA-21. It makes the phone unusable to make calls. We really need a way to revert to the previous release when there is an issue with a release. Waiting months for a working version to make calls is not acceptable. Please if anyone knows how to revert to OTA-20 even if it takes doing things manually please let me know.

**Comment by Flohack74** [comment] 2022-01-12 22:38
@Intrinsically-Sublime there is no wy to roll back out of box since we only have current full image, and forward deltas from older images to the latest ones. Ideally such bugs are caught in the devel phase (1 month normally) or the release candidate phase (1-2 weeks), and this should then be blocked to move to stable.
Obviously there are not enough people helping to test this device properly. We cannot do this for all devices, as you need to own one.
Well if its not acceptable for you I cant help that, but we are not selling a product with a 100% satisfaction guarantee. Such things can happen from time to time, especially in the last year or 2 when the number of devices exploded and we were not able anymore to test all of them ourselves.
The only option then is to delist 80% of the ported devices, since they have quality issues. But I dont think thats a good way forward.

**Comment by Intrinsically-Sublime** [comment] 2022-01-13 01:06
@Flohack74 I understand the difficulty in maintaining lots of devices but I do not understand not keeping one older version in case of issues.

Maybe the channels need to be re-thought. Like Legacy, Stable and Development rather than Stable, RC and Development. That would mean more people testing and being able to revert to a older version before it is too late since the new Stable would be RC and the old Stable would Legacy. This would make a legacy version available for as long as the Stable exists. Right now there is a small window where testing of RC can take place and if you do not follow development you miss it and end up with a device that did work and now doesn't without an option to roll back.

Or maybe just add a Legacy channel and base everything off of it rather than off of stable.

**Comment by rusins** [comment] 2022-01-13 09:47
Not being able to easily roll back, especially with relatively niche software like this, seems like a pretty serious issue. Rethinking channels seems like a radical solution that might not always catch such problems anyway. Just my 2¢

**Comment by Flohack74** [comment] 2022-01-13 12:48
Technically a "previous-stable" channel would be possible, yes. We will discuss it in the team.

**Comment by fredldotme** [comment] 2022-01-13 13:04
With all due respect, the core development team is busy upgrading the base OS to 20.04, that leaves Florian and me maintaining the 16.04 based branch and we already have other things to care about.

This might sound like a rant, but it's not meant to be taken personal. Take it as a bit of understanding of what is going on as it clearly needs to be said once and for all:

For the Pixel 3a (the original device tagged here) it is a known issue and related to proprietary blobs not working right in our environment. I'm aware, I'm working my ass off on the issue, but nobody with the *actual* access to sources helps.
For the other devices, IMHO, it is a "tough luck" situation because either the porters got disinterested or are having other priorities.

Now, wanting to roll back on an otherwise well supported device like the P3a sounds like a band aid.
Wanting to roll back on any suboptimally supported device might make more sense, but then again, we're not the ones having those phones in the first place, but the volunteer porters who don't aim to be part of the team.

**This is Open Source & Free Software, *relying* on volunteers to do something. It's an unpaid job with unwritten duties.
Now, if someone wants to write an OTA selection front end on the device and work out corner cases on the back-end side, please go ahead, talk with us, and let us know how we can help.**

**It probably won't be us "right now" though since that would be really disrespectful against those who already have their hands full.**

And now if you excuse, I would like to steer this bug report back on topic again. Thank you.

**Comment by fredldotme** [comment] 2022-01-27 23:48
Fixed by:

https://github.com/fredldotme/android_device_google_bonito/commit/f7d003f1b9c8e4082f3878955ed23c28b318c706
https://github.com/Halium/hybris-patches/pull/39

**Closed** 2022-01-28 09:11 UTC
Labels: bug, device: sargo

**Comment by cibersheep** [comment] 2022-02-15 01:12
Call volume works on Pixel 3a dev channel :)
