### ISSUE TITLE
No network on 16.04, calls freezes , unable make or receive immediately another call.

### ISSUE THREAD

**Issue by Stefano0101** [ubports/ubuntu-touch#860] opened 2018-09-04 18:20 UTC
### Illustrations

![screenshot20180903_090502921](https://user-images.githubusercontent.com/29058699/45049278-0cab9100-b076-11e8-89e0-31a067d1a882.png)

- Device: Meizu Pro 5
- Channel: 16.04/stable & rc
- Build:  OTA-4 & 2018 -W35

### Steps to reproduce
Initiate a call, finish the call and the screen immediately shows "NO NETWORK"  message. No call are possible to make or receive at this time even when network indicator shows network as connected. This situation can last couple of seconds, up to some seriously long time...we're talking minutes here. Switching on and off the Flight mode or a reboot help to solve this issue temporarily, until the next call.

### Expected behavior
Make or receive a call and upon hang up, there should be no problem to make or receive another call.

### Actual behavior
Initiate a call, finish the call and the screen immediately shows "NO NETWORK"  message. No call are possible to make or receive at this time. This situation can last couple of seconds, up to some seriously long time...we're talking minutes here. Switching on and off the Flight mode or a reboot help to solve this issue temporarily, until the next call. This did not happened on 15.04. Only introduced by 16.04/stable/rc

There is an additional issue. While in call, sometimes the menu freezes and it's impossible to close the call. Again, switching Flight mode on and off, helps close the call. This particular issue was fixed previously in 15.04 and it seam it found the way back to 16.04

**Comment by Stefano0101** [comment] 2018-09-04 18:39
also, the mobile network manager can't remember preferences set on dual sim phones. If selected one particular network for phone calls and texts, upon hang up, the preferred network for call is not selected. It seams to default to SIM1, for whatever reason. This is inconvenient, just in case if I need to make another call to the same No., if it chooses the other SIM, this could be costly call.

**Comment by dark-eye** [comment] 2018-09-04 19:32
same issue on my pro 5

**Comment by mihaelmilea** [comment] 2018-09-04 19:39
Same here on my Pro 5 just that rarely it's about 10 seconds, usually more like about two or three seconds.

**Comment by thebosbird** [comment] 2018-09-06 08:06
> @Stefano0101 ... This situation can last couple of seconds, up to some seriously long time ...

The first time, it only takes a few seconds, but repeating making a call and ending the call (make a call by selecting a phonenumber and hit the green phone button, than when it rings hit the red phone button) the time you'll see the 'NO NETWORK' message increases until it won't disappear and you'll have to reboot or try Flight mode on and off. 

Besides that you can't make a call or receive a call during the 'NO NETWORK' message, but your cellular data keeps working. So you'll still have your internet connection (I checked but Wifi was selected to off)

**Comment by Stefano0101** [comment] 2018-09-08 10:54
seems that 16.04 stable is little bit better then the rc... so I'm staying on Stable for the time being.

**Comment by yugioh2017** [comment] 2018-10-27 16:53
same here, BQ E4.5 16.04

**Comment by mgresko8** [comment] 2018-10-28 19:11
I confirm both issues on 16.04. But it is not true the second one was fixed in 15.04. I was suffering it also in latest 15.04.

**Comment by mgresko8** [comment] 2018-10-28 19:12
And moreover huge phone application flickering apperad after upgrade to 16.04. I think it could be related.

**Comment by yugioh2017** [comment] 2018-10-29 00:07
Also, I'm getting phone calls but it's not ringing when the "No Network" appears!!!!

**Comment by yugioh2017** [comment] 2018-10-29 10:37
This issue caused some problems to me since people are calling and I'm not answering, downgrading to 15.04 till a fix is released.

**Comment by yugioh2017** [comment] 2018-11-27 19:33
PLEASE FIX IT ASAP.

**Comment by mihaelmilea** [comment] 2018-11-27 20:59
I'm on current rc, Pro 5 and still have the issue...

**Comment by yugioh2017** [comment] 2018-11-27 22:38
I'm on development and installing all the updates everyday but the issue to stay, I've also tried to downgrade to 15.04 and failed :(

**Comment by hummlbach** [comment] 2018-11-28 18:37
Now i've seen that too. Doesn't happen always here and the no network does not show immediately but when trying to make the next call shortly after the previous. Switching mobile data off and on (after each call) seems to resolve it in my case. I didn't have that on 15.04 for sure. I  have also updated the radio firmware at the same time...

**Comment by mgresko8** [comment] 2018-12-12 18:09
Quite critical bug. Is somebody working on it?

**Comment by yugioh2017** [comment] 2018-12-12 18:10
Any update on this?

**Comment by Stefano0101** [comment] 2018-12-12 19:44
OTA-6 and the issue persist. Same as on previous 16.04 OTA-5. Sometimes nothing else (flight mode on/off, data off/on ) only a reboot helps. It's rather a annoying when you trying to call someone, first call is not picked up and then can't make a second call as this is happening. Or the other party tries to call you and it goes straight to voice mail.

**Comment by yugioh2017** [comment] 2018-12-13 11:44
I'm pretty sure the ubports developers are using Android or iOS as their main phones and don't care if Ubuntu touch users doesn't make or receive calls.

**Comment by Stefano0101** [comment] 2018-12-13 12:56
yugioh2017 you don't need to be mean, they trying their best, in they free time, don't get paid for it (only a few of them). After all, if you don't like UT, nobody force you to use it. How about help them instead of such a statement?

**Comment by mihaelmilea** [comment] 2018-12-13 14:20
yugioh2017, I am not a developer but an user. I fell your pain but I strongly disagree with the use of expressions like "really disappointing" or the idea that someone could pay and have things done. Please understand that I don't see myself as someone able to teach people lessons but rather I am learning what an opensource comunity means and that actually all that is part of the UT project, including the rithm at which bugs are solved.

**Comment by UniversalSuperBox** [comment] 2018-12-13 14:21
A huge majority of the Ubuntu Touch developers are, as noted in this thread, volunteers who do this out of their own passion for the platform. We are supporting a platform we didn't create on hardware devices that we don't have the source code to modify. I personally don't have this device and it's very difficult (read: expensive) to get one into the US.

@yugioh2017, I understand that you're upset but yelling at people is not acceptable or helpful. 

Something useful to add to this report would be the contents of `/var/log/syslog` **directly after** the issue occurs. That would give us insight into exactly what has happened when "No network" appears. As it is, looking through the logs in this thread is difficult since I'm not able to find the log statements which are relevant to what we're trying to solve.

**Comment by Stefano0101** [comment] 2018-12-13 14:23
> Stefano0101 I'm Ubuntu lover and that's why I'm talking like this, I don't need any features I'm ok with it but they called it a phone for a reason, so you can make and receive calls, I don't want to be forced to move to another OS because I can't make or receive calls it's really disappointing.
> I'm ready to help them and even pay to them so they can fix this annoying bug, I hope you understand me.

I understand you perfectly. The other day I was at breaking point, wanted to smash the phone on the wall or floor. Couldn't make or receive a call, when needed, so stressful. Yeah, phone should be able to make a call when needed and you are totally right about that. Just comments like the one you made won't help. But maybe you wanted just stir the water so UBports guys notice this bug?!? Anyway, hoping the fix is on the way.

**Comment by yugioh2017** [comment] 2018-12-13 14:42
Only who is using UT as a daily and main phone would know why I'm talking like this, I'm really sorry if I hurt you by my words, but also I hope you understand the problem here it been a month without taking any attention although it is really critical issue, I have faith in Ubuntu and UT and in UBPorts guys, I hope you guys help us here. 
syslog: https://pastebin.com/jEkwv1Zj

**Comment by yugioh2017** [comment] 2018-12-13 15:31
> Just happened today on Nexus 5 16.04 OTA6 stable along with another bug referenced here:
> #195
> Didn't need to reboot, it disapeared after a while.

Yes, that happens sometimes on my phone E4.5, but this bug is different, we can't make or receive calls after one or two calls made.

**Comment by Stefano0101** [comment] 2018-12-13 15:34
> > Just happened today on Nexus 5 16.04 OTA6 stable along with another bug referenced here:
> > #195
> > Didn't need to reboot, it disapeared after a while.
> 
> Yes, that happens sometimes on my phone E4.5, but this bug is different, we can't make or receive calls after one or two calls made.

But it might be connected to that one. This issue was here before #195, on 15.04 and was fixed, how this get back to 16.04??? Yeah, it's happening on Pro5 on 16.04/ OTA-6 as well.

**Comment by yugioh2017** [comment] 2018-12-13 15:37
Yes, It could be. And I was forced to reboot to hang. 
Anyway I have attached my syslog, I hope the UBports guys can find the solution.

**Comment by UniversalSuperBox** [comment] 2018-12-13 15:39
Yes @yugioh2017 I understand the problem clearly ("only people who use UT understand" is not true), but unless people are willing to get involved to triage these issue reports and bring them to people's attention this will not improve. The "us versus them" mentality is not true. *We* are the UBports community, "The UBports guys" includes you.

**Comment by yugioh2017** [comment] 2018-12-13 15:43
> Yes @yugioh2017 I understand the problem clearly ("only people who use UT understand" is not true), but unless people are willing to get involved to triage these issue reports and bring them to people's attention this will not improve. The "us versus them" mentality is not true. _We_ are the UBports community, "The UBports guys" includes you.

Yes, and I've been always ready to help improving Ubuntu and UT since I reported a bug happened  before and it got fixed, but this one is not taking any attention that what made me upset. 
We are all ready to help, but this one deserves some attention and we can all collaborate to fix it, all what we needed is some attention.

**Comment by yugioh2017** [comment] 2018-12-13 15:55
I'm not an expert, but I think there's a problem here: 
Dec 13 16:34:58 ubuntu-phablet repowerd[968]: UPowerPowerSource: change_device(/org/freedesktop/UPower/devices/battery_battery), is_present=1, state=1, percentage=84.00, temperature=24.00
Dec 13 16:34:58 ubuntu-phablet kernel: [ 1129.058045]init: sys_prop: permission denied uid:32011  name:af.modem_1.status
Dec 13 16:34:58 ubuntu-phablet kernel: [ 1129.094958]init: sys_prop: permission denied uid:32011  name:af.modem_1.status

**Comment by mgresko8** [comment] 2018-12-13 18:16
I think these two bugs are not related, since I suffer the Cannot
Hangup since moving from Ubuntu Touch to UBPorts and suffer the No
Network bug after upgrade from OTA-3 to OTA-5.

I think UBPorts is lacking real bugreporting system. There is no way
to mark the bug as critical to get it higher priority. I think both
these bugs are very important to fix in a short time and I am not sure
whether some developer read about it already. is somebody working on
it? I think developers should work primarily on basic phone functions.
I really do not care about replacing browser. I see no real advantage
comapring the first one. I am also not able to set proxy (per wifi
connection) as before and so on.

2018-12-13 16:55 GMT+01:00, Charles Stevens <notifications@github.com>:

**Comment by lduboeuf** [comment] 2018-12-13 19:23
I agree that basic phone features issues should be marked as a high priority. But i understand also that most developers here are volunteers and those bugs are not easy to spot and not reproductible on every devices.

**Comment by lduboeuf** [comment] 2018-12-13 21:23
so it happens just now while trying to call voicemail:
logs for `application-legacy-dialer-alog` : 
```
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
void installIconPath()
qml: Has mouse: false
library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found
USSDManager: Failed to connect signals
USSDManager: Failed to connect signals
QObject::connect: No such signal QtContacts::QContactManager::contactsChanged(QList<QContactId>)
The phone number is not a valid number: "dummy"
The phone number is not a valid number: "dummy"
qml: Starting a call to 666
qml: 'caller' is DEPRECATED. It has no effect.
USSDManager: Failed to connect signals
USSDManager: Failed to connect signals
```
syslog,nothing special, some:
```
Dec 13 21:01:11 ubuntu-phablet ofonod[1798]: rild_cb: DIAL request fails after the call appeared in the call list.
```

**Comment by lduboeuf** [comment] 2018-12-13 22:45
> I think UBPorts is lacking real bugreporting system. There is no way to mark the bug as critical to get it higher priority

https://forums.ubports.com/topic/2115/issue-priorities-basic-phones-features-should-be-first

**Comment by mariogrip** [comment] 2018-12-14 00:09
This is one of the main reasons why we are moving to gitlab, we are aware that the bug system is not great and we do have a problem here. But gitlab has a much more promising bug reporting system allowing us to better utilize the bug system.

Also please understand, we are a small team with a huge task, we have many moving parts and moving to a newer version of mir and unity8 at the same time is not helping, we are doing our best to make an an awesome operative system. but we are in a really busy period after taking over from canonical, we updated to xenial, we are updating mir and updating unity8 all these are huge since canonical left it far behind the latest releases, this forces us to make major changes. We are also building Halium and following the evolving of android and newer devices to be able to follow the mobile marked. At halium we are also trying to move our sensor, gps, media and camera system over to an active maintained system instead of maintaining our own. And we are also looking at merging our patched in celluar and pulse with an active maintained one. Once we move things to active maintained systems where we can work together to get to the same goal, we will then get more time to focuses on core functions.

About replacing the browser, this is an huge part for us, we are not able to maintain our own fork of chromium (oxide) that why we are forced to move the browser, this move will in fact give more time to focused on the core functions on the phone.

There is also a low amount of pro 5 out there with Ubuntu Touch, this results in out low amount of pro 5's in the qa team. This has resulted in this bug slipped the radar. Please if anyone here wants to help out our qa team let me know. 

And i'm deeply sorry that this happened, this should have been fixed before. I'll do my best to get it fixed asap!

**Comment by yugioh2017** [comment] 2018-12-14 00:44
> This is one of the main reasons why we are moving to gitlab, we are aware that the bug system is not great and we do have a problem here. But gitlab has a much more promising bug reporting system allowing us to better utilize the bug system.
> 
> Also please understand, we are a small team with a huge task, we have many moving parts and moving to a newer version of mir and unity8 at the same time is not helping, we are doing our best to make an an awesome operative system. but we are in a really busy period after taking over from canonical, we updated to xenial, we are updating mir and updating unity8 all these are huge since canonical left it far behind the latest releases, this forces us to make major changes. We are also building Halium and following the evolving of android and newer devices to be able to follow the mobile marked. At halium we are also trying to move our sensor, gps, media and camera system over to an active maintained system instead of maintaining our own. And we are also looking at merging our patched in celluar and pulse with an active maintained one. Once we move things to active maintained systems where we can work together to get to the same goal, we will then get more time to focuses on core functions.
> 
> About replacing the browser, this is an huge part for us, we are not able to maintain our own fork of chromium (oxide) that why we are forced to move the browser, this move will in fact give more time to focused on the core functions on the phone.
> 
> There is also a low amount of pro 5 out there with Ubuntu Touch, this results in out low amount of pro 5's in the qa team. This has resulted in this bug slipped the radar. Please if anyone here wants to help out our qa team let me know.
> 
> And i'm deeply sorry that this happened, this should have been fixed before. I'll do my best to get it fixed asap!

Thank you for your time and we really appreciate your huge work on UT. 
I'm ready to help, let me know how.

**Comment by lduboeuf** [comment] 2018-12-14 07:49
@mariogrip  i faced this issue on N5 also :)

> There is also a low amount of pro 5 out there with Ubuntu Touch, this results in out low amount of pro 5's in the qa team. This has resulted in this bug slipped the radar. Please if anyone here wants to help out our qa team let me know.

I faced this issue on N5 OTA6 devel too :) see https://github.com/ubports/ubuntu-touch/issues/860#issuecomment-447009370

**Comment by mgresko8** [comment] 2018-12-14 09:39
Hello Marius,

thanks for your effort. Sorry if you felt offence from my side. I am
very happy there is such great operating system. But I feel quite
frustrated because since I bought UT phone there are continuous basic
function malfunctionings. After some bugs were fixed there are always
replaced but another bugs. And this is for years. I undestand there
are many things to work on. Also the work on mir and unity
replacement. But the basic phone functions should be always the first
thing to consider. There should be no such issues like unability to
place call, unablility to hangup call, invisible keyboard (this is
fixed already) and so in the stable channel.

I can stand with other issues. Like wrong battery level reporting
(also frustrating when it is hard to predict how long the phone will
stay alive, but less then previous issues), unability to browse using
proxy and such (browsing is really a secondary function of the phone).

Thanks once more for your effort. If we can help with debugging the
issues, please could you give us instructions? I found no relevant
logs when issue occurs. Which logfile to concentrate on?

Marek


2018-12-14 9:23 GMT+01:00, Stefano0101 <notifications@github.com>:

**Comment by Stefano0101** [comment] 2018-12-16 20:10
syslog attached, right after No network message, after 3 calls, then no network for a long time. 
[syslog.zip](https://github.com/ubports/ubuntu-touch/files/2683921/syslog.zip)

**Comment by yugioh2017** [comment] 2018-12-24 23:15
I thought they would give us a christmas gift by fixing this bug, but it seems we have to wait months before they start working on it :(

**Comment by advocatux** [comment] 2018-12-25 12:12
@yugioh2017 friendly reminder: there is no "they", this volunteer based project is all about "we" ;)

That means too that if you want a specific issue fixed, you need to do it yourself, find a developer, or wait until it gets its turn in the (huge) pending queue :)

**Comment by yugioh2017** [comment] 2018-12-25 19:41
"they" broke the phone not "we" or "us", it was working perfectly till "they" got involved. I'm no longer waiting the fix. 
There's no hope in developing UT since there's not intention in making even the basic phone functions works, for sure I didn't mention the "internet browser" that hangs on most of websites or not able to hang a call, etc....

**Comment by yugioh2017** [comment] 2018-12-25 19:44
> @yugioh2017 friendly reminder: there is no "they", this volunteer based project is all about "we" ;)
> 
> That means too that if you want a specific issue fixed, you need to do it yourself, find a developer, or wait until it gets its turn in the (huge) pending queue :)

Then, the UBPorts slogan should be: We broke UT functions and you should find a developer to fix them.

**Comment by mariogrip** [comment] 2018-12-25 19:50
No useful input here, locked.

As I said before, this bug will be fixed, i will even try right now even although its xmas. we try our best to fix as many bugs as we can, but we don't have apple money and developers. But the fact is that there is a lot of bugs, and the pro5 has little userbase so its not always it will get the highest priority. 

I know this is a bad bug, we will get it fixed and i'm sorry it took so long. but this input does not help the matter :)

**Comment by mariogrip** [comment] 2018-12-25 23:50
Ok, so got this fixed: https://github.com/ubports/telepathy-ofono/pull/2

Please test, use `sudo ubports-qa install xenial_-_fix-end-call` install

**Comment by mariogrip** [comment] 2018-12-25 23:50
There we go, a fix for it. Merry Christmas everyone!

**Closed by mariogrip** 2018-12-25 23:50 UTC
Labels: bug, device: turbo

**Comment by yugioh2017** [comment] 2018-12-26 00:07
Finally!!! Thank you!!!! Merry Christmas everyone (including: Ubports team :P) ! Long live UT!

**Comment by mihaelmilea** [comment] 2018-12-26 08:13
Beautiful! Wonderful! Fixed! Thank you! Merry Christmas!

**Comment by Stefano0101** [comment] 2018-12-26 13:06
Thank you Marius, it seems to be fixed, no trouble with it now. If I observe anything else, I'll let you know. Merry Christmas!

**Comment by thebosbird** [comment] 2018-12-27 20:13
Thanks Marius! Tested it in Dev mode (BQ E4.5) and the problem is gone!

**Comment by advocatux** [comment] 2019-01-01 19:57
Device: Nexus 5 (hammerhead)
Channel: RC
Version: `2018-W01` (_really_ `2019-W01`)

It seems this issue is fixed but I'll keep an eye on it because it was so random when it happened that I can't be 100% sure for now

**Comment by erik-kueng** [comment] 2019-01-02 18:54
Fairphone 2
rc
2018-W01

Fix works. I could not reproduce this issue.
