### ISSUE TITLE
Issues found when using PinePhone

### ISSUE THREAD

**Issue by RossComputerGuy** [ubports/ubuntu-touch#1363] opened 2020-02-07 19:08 UTC
- Device: PinePhone Braveheart
- Channel: unknown
- Build: 02/06/20's latest build

1. Camera doesn't work, I've checked the privacy switches and I believe its just an app bug
2. WiFi networks not found after connecting to one, this happened at school and we've got multiple networks with the same name. I believe the phone found the networks, connected, then had an issue with the ones that have the same name.
3. User unit not found, this isn't too bad of an issue but systemd reports that the user@[uid].service is not found when shutting down.
4. Unity sometimes crashes. This bug is a gamble, meaning sometimes it happens and sometimes it doesn't but at least Unity comes back up in 30 seconds.
5. Boot splash logo isn't rendering right
6. Changing timezone doesn't work, the OS is stuck at UTC+0
7. Terminal settings don't work at all. The settings for terminal don't respond at all, I somehow got the font changed to EmojiOne for several hours and by pushing randomly on the touchscreen I was able to change it to something else.
8. Batter isn't immediately recognized as charging. It takes about 5 minutes till the indicator changes to the charging symbol.
9. Screen becomes unresponsive. I've had this issue only once which was last night, I was watching YouTube and the screen quit updating, tapping would cause a flash. Rebooting solved the issue.
10. Music player doesn't play MP3's.

**Comment by Xohwie1i** [comment] 2020-02-07 20:50
I can confirm that I'm having the same issues. Also, I found a temporary "fix" for the terminal settings problem: after entering the settings menu, do a long right to left swipe, click on the settings again, and you should be able to make some changes....repeat every time it gets stuck.

**Comment by RossComputerGuy** [comment] 2020-02-07 21:00
That's good that there's a "fix".

**Comment by Flohack74** [comment] 2020-02-07 22:46
Our Pinephone hub is here: https://gitlab.com/ubports/community-ports/pinephone - Please file whatever you think is worth as _single issues_ (otherwise how can we deal with it one by one?) and please _do not create duplicates_ - as always. Closing here...

**Comment by Flohack74** [comment] 2020-02-07 22:47
Regardin item 3: Thats not a bug, you can ignore it.

**Closed by Flohack74** 2020-02-07 22:46 UTC
