### ISSUE TITLE
Unlock swipe mode is too easy to unlock

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1197] opened 2019-08-19 10:56 UTC
### Description of the feature
Unlock swipe mode (without password) looks too easy to unlock.
Each time I unlocked my phone (I fished from my pocket/bag) I noticed that a lot of apps had been opened and settings changed (e.g.: language...)!
Could be quite "dangerous".
Maybe that an implementation of scheme mode would be nice?

- Device: mako, LG Nexus 4
- Channel: Stable
- Build: OTA-9

### Expected behavior
A phone not so easy to unlock even with the swipe-mode.

### Actual behavior
Went back to the password mode...

**Comment by UniversalSuperBox** [comment] 2019-08-20 19:16
Please let me know if I have this right. You've:

1. Enabled Swipe unlock mode
1. Placed the phone in your bag unattended

And the device woke up, was unlocked, and many settings were changed.

Do you have especially capacitive things in your bag, or did someone take your phone?

**Comment by Thieb67k** [comment] 2019-08-21 06:49
Hello,
Yes, at least, that is what happened to me.
And I am sure that no one took my phone.
Concerning capacitive things, obviously something behaved like that, but what and how, no idea... keys, wallet..?

Plus (do not know if I have to open an issue for that), when I went back to the 4-numeral code, I choose my code and each selected number appeared and dissapeared immediately from the text-area, making unable the password creation.
I had to quit the menu and went back to it.

**Comment by UniversalSuperBox** [comment] 2019-08-21 15:43
If you can reproduce the issue with creating a PIN, please file another issue. It will only be lost here.

There are two ways that this could occur. 

1. Something bumps the power button and the screen turns on. There is nothing we can do to prevent this being a problem.
1. A notification is received by the device and the screen turns on. This should not happen if there is something very close to the device, such as when it is in your pocket. However, we are unable to assume it is your case. 

Adding another unlock method will not make "swipe" more secure or less prone to accidental unlocking. Swiping in a different direction (Android uses a swipe up) may help, but probably would not.

If you can test receiving a notification with your hand over the phone's sensor area, give that a try. The phone should not wake up the screen until your hand leaves the area or you press the power button. If it does wake up, please file another issue.

Otherwise, Swipe is designed to be easy to unlock. There is really nothing we can do if the problem is that it is easy to unlock. Please use a lock method that is harder to unlock.

I'm going to close this as "wontfix" because making Swipe harder to unlock goes against its design.

**Closed by UniversalSuperBox** 2019-08-21 15:43 UTC

**Comment by dobey** [comment] 2019-08-21 17:05
Additionally, if you want to request a "pattern" unlock feature, please open a feature request specifically for that, rather than to complain that swipe is too easy to unlock or pin/passphrase is too complex.
