### ISSUE TITLE
Make Background dull optional

### ISSUE THREAD

**Issue by ChloeWolfieGirl** [ubports/ubuntu-touch#196] opened 2017-08-04 16:53 UTC
There's a huge difference between the colours between the original photo, and the photo shown on the background.

This is an effect added by the system, which is very useful, and helps with readability with many backgrounds, but even backgrounds which wouldn't affect readability gets dulled, underneath the option to make the background work on the scopes, should be an option to add/remove the fade effect.

![photo_2017-08-03_23-34-48](https://user-images.githubusercontent.com/8162805/28978396-c65ebb20-793d-11e7-943b-d3c622bcfbe8.jpg)
![photo_2017-08-03_23-36-46](https://user-images.githubusercontent.com/8162805/28978397-c65ee848-793d-11e7-9382-fa7e22726311.jpg)

**Comment by Flohack74** [comment] 2017-08-04 18:35
We could start with a simple alpha level slider.

**Comment by ChloeWolfieGirl** [comment] 2017-08-04 18:39
That sounds good!

**Comment by Flohack74** [comment] 2017-12-26 23:27
Some progress: https://github.com/ubports/unity8/pull/8

**Comment by nfsprodriver** [comment] 2017-12-26 23:27
Attempt in these commits:
https://github.com/ubports/unity8/pull/8
https://github.com/ubports/system-settings/pull/33

**Comment by Flohack74** [comment] 2017-12-26 23:28
Just saw it, great ;)

**Comment by nfsprodriver** [comment] 2017-12-26 23:28
@Flohack74 you got me ;)

**Comment by nfsprodriver** [comment] 2017-12-26 23:39
[video_2017-12-27_00-37-30.zip](https://github.com/ubports/ubuntu-touch/files/1588031/video_2017-12-27_00-37-30.zip)

Video. Sorry, it's 270°

**Comment by nfsprodriver** [comment] 2017-12-28 00:32
Commits merged to xenial branch. Might be testable in 16.04/devel within the next few builds (or manually install system-settings and unity8 from latest ci debs. This issue can be marked as In QA

**Comment by NeoTheThird** [comment] 2018-02-22 16:54
Closing this due to [changed issue tracking process](https://github.com/ubports/docs.ubports.com/pull/92). Can someone confirmed this is fixed?

**Closed by NeoTheThird** 2018-02-22 16:54 UTC
Labels: enhancement, good first issue, team: ui

**Comment by NeoTheThird** [comment] 2018-02-27 11:11
Great job @sverzegnassi!
