### ISSUE TITLE
"Not authorized/401" error downloading files with web browser

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#372] opened 2017-12-20 16:45 UTC
- Device: Meizu MX4
- Channel: stable
- Build: OTA-2

### Steps to reproduce
- start Ubuntu touch web browser and go to https://rkupper.no-ip.org
- This is my private nextcloud instance. I have created a guest account for you:
        your login is "ubportsguest", password the same.
- There is only one file: "About.odt". Try downloading it.
- Observe that download fails with "401/unauthorized".
- Observe that all works well doing the same from Ubuntu desktop.

### Expected behavoir
You should be able to download the file.

### Actual behavior
Since a few weeks ago, I cannot download some files with the web browser of Ubuntu touch. In particular, I cannot download any file from my nextcloud instance. The browser always reports "not authorized/401".
Downloading works fine with desktop Ubuntu, so the problem must be with Ubuntu touch. As far as I can tell, the problem appeared 5-6 weeks ago.

**Comment by Flohack74** [comment] 2017-12-20 18:37
I get 503 service unavailable xD

**Comment by ruedigerkupper** [comment] 2017-12-20 19:22
You're right, I get 503 on the first try. If I try again, I get 401 in all following tries.

**Comment by mariogrip** [comment] 2017-12-20 21:09
Humm, i wonder if maybe oxide/webbrowser is not using the cookies (or session storage) when downloading.

**Comment by mauricioduarte01** [comment] 2017-12-20 21:40
same problem over here with my nextcloud account: HttpsError: 503 - Service unavailable

**Comment by ernesst** [comment] 2017-12-26 22:30
Already mentioned here : https://github.com/ubports/webbrowser-app/issues/5

**Comment by ruedigerkupper** [comment] 2017-12-27 10:55
Thanks ernesst, that's obviously the same bug. Could someone mark as a duplicate?
Do you know of there any progress? (The first report is from Feb. 2016.)

**Comment by Flohack74** [comment] 2017-12-27 14:54
Duplicate of ubports/webbrowser-app#5

**Closed by Flohack74** 2017-12-27 14:54 UTC
Labels: duplicate
