### ISSUE TITLE
colors of the folder names are not shown correctly in dark mode

### ISSUE THREAD

**Issue by KrisbyZottle** [ubports/ubuntu-touch#1510] opened 2020-07-07 11:46 UTC
e.g. when you choose a file out of the file system in suru black, the letters are not readable. The highlighted one is the one I accidentally pressed.
![screenshot20200705_183242940](https://user-images.githubusercontent.com/62804855/86776061-31993280-c058-11ea-9df4-10515b2cefbe.png)

**Comment by laborim** [comment] 2020-07-11 10:10
Device: oneplus 3
2020-07-11/2

I can't reproduce this error.

In File Manager the colours apear correctly.

**Comment by KrisbyZottle** [comment] 2020-07-15 13:21
Device: Nexus 5
Theme Colour: Suru Dark
Maybe there you can see the colour error in the file manager.
It's a real screenshot I took &#x1F61F;

**Comment by Danfro** [comment] 2020-07-22 18:02
E5 devel.

I can not reproduce this issue. Also file manager does look very different here compared to the screenshot given above. I did try to attach a file to FluffyChat for this test.

![screenshot20200722_200035857](https://user-images.githubusercontent.com/37637312/88211580-2f3cf800-cc56-11ea-94d9-338c954cb2e7.png)

**Comment by Danfro** [comment] 2020-07-22 18:03
@KrisbyZottle are we talking about system file manager for picking files or do you refer to some other app?

**Comment by KrisbyZottle** [comment] 2020-07-22 20:21
@Danfro It happens espacially when I pick up a key for the vpn connection in the . So in -manual vpn configuration - private key - click Dropdown - choose certificate - and then the (wrong coloured) file picker appears.

**Comment by Danfro** [comment] 2020-07-22 20:26
Ah, ok. Yes, in that place I can confirm the issue.

Looks like that is not using the content hub, but a build in file picker that is not theming correctly. Great, at least we did narrow it down a bit.

**Comment by UniversalSuperBox** [comment] 2020-08-07 18:22
Hi @KrisbyZottle, thank you for your report!

I thought this looked familiar, and indeed this has already been filed at https://github.com/ubports/system-settings/issues/244. I'll close this report in favor of that one to keep issue tracking easier. Please continue any discussion at the linked report.

Thanks again!

**Closed by UniversalSuperBox** 2020-08-07 18:22 UTC
