### ISSUE TITLE
Unable to boot halium devices on latest rootfs builds.

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-touch#1459] opened 2020-05-22 00:59 UTC
### Illustrations

- Device: hammerhead
- Channel: 
- Build: ubports-touch.rootfs-xenial-armhf.tar.gz #1086

### Steps to reproduce
Flash the device using halium-standalone script and test builds https://github.com/rubencarneiro/halium-test-hammerhead/releases
- Boot the device first time will work
- Reboot and the device

### Expected behavior
- Rebooting the device should work as normal device booting and start the unity like older build of rootfs does like https://ci.ubports.com/job/xenial-rootfs-armhf/1041/
- The device only boots again in data is wiped on recovery

### Actual behavior
- When device is rebooting get stuck at bootlogo img with backlight running and shutdown etc like a fully booted device does.

### Logfiles and additional information
dmesg: https://pastebin.com/r0SkPVSE
Unity 8: https://pastebin.com/fdv6jCVc

**Comment by APokorny** [comment] 2020-05-26 11:27
The Unity8 log would be more telling if it contained the unity 8 startup messages - It seems to be rather far down in the process.

**Comment by Flohack74** [comment] 2020-06-13 09:07
@APokorny sorry to say, that is the full unity9 log. Seems it gets cleared? at least I reproduced the problem here, and I just get this tiny log.

**Comment by Flohack74** [comment] 2020-06-13 09:24
I added lightdm here in case its of interest: https://pastebin.com/25wbdtVe

**Comment by Flohack74** [comment] 2020-06-13 11:45
Closed in favor of #1438

**Closed by Flohack74** 2020-06-13 11:45 UTC
