### ISSUE TITLE
You can add multiple Google accounts but not multiple Ubuntu One accounts

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#501] opened 2018-03-04 01:17 UTC
- Device: hammerhead
- Channel: xenial/devel
- Build: r273

### Steps to reproduce
System Settings -> Accounts -> Add account...
(after adding one Ubuntu One account and one Google account)

### Expected behavior
I should be able to add multiple of each account shown.

### Actual behavior
"Ubuntu One" is grayed out and "Google" isn't. I should be able to add multiple of both.

**Comment by Flohack74** [comment] 2018-03-04 17:19
This will probably create other issues, since Canonical has hooked up the Ubuntu One account to some things. I can just think about notifications subsystem at the moment. Could get confused and stop sending you notifications or the like. Also, I dont see the need for multiple Ubuntu One accounts. Its not like an Email provider.

**Comment by dobey** [comment] 2018-03-10 21:14
This is not new, and by design. We should also probably just get rid of the Ubuntu One account stuff. It's only going to get more difficult to support in the future, and it's not _really_ used for anything.

**Comment by mardy** [comment] 2018-03-11 13:03
I thought it was still being used for Telegram notifications?

**Comment by Flohack74** [comment] 2018-03-11 14:38
Notification server does not enforce it. It doesnt even check if the token is valid.

**Comment by dobey** [comment] 2018-03-11 14:57
It's not really being used for anything. Yes, ubuntu-push-client requires an account to exist locally, but it's not actually being used for anything. It's just sort of there, and not useful. The code is way too complicated, and extraneous maintenance cost for Ubports. Removing it will make it easier for apps to use push notifications (in the cases where the server side could be fixed to enable it), and it will reduce the burden of ownership for Ubports devs.

I was (slowly) working to get rid of it before we got dropped, and now that the Canonical app store is gone, and ubports has its own push server instance, I think it's the perfect time to just get rid of the U1 account plugin completely.

**Comment by dobey** [comment] 2019-06-11 12:58
Closing this as it is designed this way, and we will be getting rid of the U1 account anyway.

**Closed by dobey** 2019-06-11 12:58 UTC
Labels: bug
