### ISSUE TITLE
MacOS installer leaves Nexus 7 with "This phone needs restoring"

### ISSUE THREAD

**Issue by ploum** [ubports/ubuntu-touch#1209] opened 2019-08-27 11:45 UTC
Looks similar to #1089

1. Install UBports on MacOS
2. Plug Nexus 7 2013 wifi (flo)
3. Let the installer does its magic (with the "wipe" box checked)
4. Installer tells me everything is fine.
5. Device is stuck on boot with a "this phone needs restoring from a PC or a service center"

![2019-08-27 13 17 21](https://user-images.githubusercontent.com/1233155/63768398-62ed9180-c8d0-11e9-9061-623594d9b481.jpg)

**Comment by ploum** [comment] 2019-08-27 12:03
Also very similar to #300

**Comment by NeoTheThird** [comment] 2019-08-27 13:30
Thank you for reporting, duplicate of https://github.com/ubports/ubports-installer/issues/855.

**Closed by NeoTheThird** 2019-08-27 13:30 UTC
