### ISSUE TITLE
Messaging app: After sending a SMS, the thread is scrolled to top

### ISSUE THREAD

**Issue by howmanycharacters** [ubports/ubuntu-touch#1282] opened 2019-10-30 10:02 UTC
### Illustrations

- Device:  Nexus 5
- Channel:  Stable
- Build:  OTA 11

### Steps to reproduce
Send a message to anyone and observe screen going up to top of the thread by itself.

### Expected behavior
Screen remained where it is. On the bottom with latest messages.

### Actual behavior
Screen goes up by itself after sending a message.

**Comment by lduboeuf** [comment] 2019-10-30 10:38
confirmed also here

**Comment by james-lyon** [comment] 2019-10-31 07:13
This is almost the same as https://github.com/ubports/messaging-app/issues/66

**Comment by UniversalSuperBox** [comment] 2019-11-02 00:51
Yes, while the steps to reproduce the bug are slightly different, I think it may be the same cause. Closing as a duplicate of https://github.com/ubports/messaging-app/issues/66

**Closed by UniversalSuperBox** 2019-11-02 00:51 UTC
