### ISSUE TITLE
Camera flash not working on OnePlus One

### ISSUE THREAD

**Issue by UKPhil** [ubports/ubuntu-touch#534] opened 2018-03-19 06:22 UTC
When taking a photo with the Ubuntu Camera app with a OnePlus One, the flash is not working.

Turning the flash on, off and to auto doea yon make any difference, there is just no flash 

OnePlus One 
OS Build rc22

**Comment by lfortanet** [comment] 2018-03-19 08:48
Confirmed, doesn't work on any option.
With 16.04 either.

**Comment by Flohack74** [comment] 2018-03-19 19:50
Yes confirmed, on 15.04 also.

**Comment by UKPhil** [comment] 2018-03-19 20:23
Thay is good that it has been confirmed and that iy is noy just my device.

**Comment by Berlinuxer** [comment] 2018-03-27 14:29
Hi, same with my OPO on 15.04. And Tagger shows the same behavior, no light although switched on via the icon on the taggers right bottom corner. There is an entry in the Launchers accu-menu, which will work correct.

**Comment by rubencarneiro** [comment] 2018-03-27 14:39
That maybe a pernissions issue.

**Comment by Berlinuxer** [comment] 2018-03-27 15:12
maybe, my systemsettings shows '0' apps at camera. But i can take photos and movies. So, how to solve this issue?

**Comment by Flohack74** [comment] 2018-03-28 19:07
@rubencarneiro thinks that this is a permission issue on the low-level layer (Android container), it has nothing to do with the settings you can make to allow or revoke camera access. Some of our Android guys need to take a look at this. Because every phone has lots of different device permissions in udev, we cannot compare with a working one, unfortunately.

**Comment by rubencarneiro** [comment] 2018-03-30 14:03
@Flohack74 have you tooka look at permission in the init.rc?

**Comment by Flohack74** [comment] 2018-04-02 17:42
Ok will try. just a sec

**Comment by Flohack74** [comment] 2018-04-02 17:50
There is no group camera but it is android_input, I changed it to system.system with perms 0666 but nothing changed...

Where do I find the init.rc on the device?

**Comment by rubencarneiro** [comment] 2018-04-03 19:45
Init.bacon.RC and it is 0660 system camera

**Comment by Flohack74** [comment] 2018-04-04 11:31
Big sorry @rubencarneiro that we forgot about this one. Just merged it. However, we need to bring it tothe 16.04 builds also. And maybe I can convince our guys to make a maintenance devel release now, we got a lot of stuff pending for testing in 15.04

**Comment by Flohack74** [comment] 2018-04-04 12:27
Duplicate of #258 btw... Please try to find existing bugs before opening new ones.

**Comment by Berlinuxer** [comment] 2018-04-05 18:09
Don't know if this is the right place for a discussion like this. But, if it's only a wrong entry in a refile, is it not possible that the user correct the wrong line?

**Comment by UKPhil** [comment] 2018-04-05 20:57
I personally don't think it is the right place to discuss it. Also I do not think that it is right to ask the end user to make such changes to make basic phone functionality work. This should be something that works out of the box.

**Comment by Flohack74** [comment] 2018-04-06 13:11
Its more complex, as Ruben and I tried yesterday and it´s not only a permission problem, sad but true. It needs more work probably...

**Comment by UniversalSuperBox** [comment] 2021-02-01 00:15
Sorry for the delay, but closing as this is a duplicate of https://github.com/ubports/ubuntu-touch/issues/258

**Closed by UniversalSuperBox** 2021-02-01 00:15 UTC
Labels: bug, device: bacon, duplicate
