### ISSUE TITLE
Bluetooth speakers do not work during phone call or while playing mp3

### ISSUE THREAD

**Issue by WillemHexspoor** [ubports/ubuntu-touch#993] opened 2018-12-06 20:46 UTC
- Device: Nexus 5 Hammerhead
- Channel: Stable
- Build: Ubuntu 16.04 (OTA-5)

### Steps to reproduce
Connect bluetooth speakers

### Expected behavior
Speakers should produce sound from all sources, i.e. web, mp3 and phone calls

### Actual behavior
Speakers do produce sound from web, e.g. youtube through Morph.
Speakers do not produce any sound if playing mp3 with standard Music app or during phone calls. During phone call the microphone of the phone also doesn't work. As a result both sides of the line can't hear eachother.

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2654849/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2654850/UTlogcat.txt)

**Comment by UniversalSuperBox** [comment] 2018-12-08 15:40
Does the audio output work *once* after the device is initially paired, as in https://github.com/ubports/ubuntu-touch/issues/994?

**Comment by WillemHexspoor** [comment] 2018-12-09 19:10
Audio output works for music player and morph after initial pairing or reconnecting by disconnecting and reconnecting with the phone. It seems the phone app breaks the bluetooth connection.

### Updated actual behavior

Bluetooth speakers do produce sound if playing mp3 with standard Music app or streaming someting from web, e.g. youtube through Morph.
Bluetooth speakers do not produce any sound during phone calls. During phone call the microphone of the phone also doesn't work. As a result both sides of the line can't hear each other. It seems the problem starts as soon as the phone app starts any sound either the ringtone or sound from the other end of the line. At this moment also the volume indicator changes from "Bluetooth headphones" to "speakers". 

From this moment on audio from web or music app comes from the phone speakers while the bluetooth connection is still alive. Re-connecting the bluetooth speakers makes sound from morph or music app go through the bluetooth speakers again, but as soon as the phone app is used the problem reoccurs.

Also when receiving a call, after initial pairing or re-connecting the bluetooth speakers, there is a short loud hiss on the bluetooth speakers after which the problem reoccurs.

**Comment by hummlbach** [comment] 2019-01-22 14:06
Duplicate of #830?

**Comment by UniversalSuperBox** [comment] 2019-08-01 18:59
Yes, I believe this is a duplicate of https://github.com/ubports/ubuntu-touch/issues/830 and https://github.com/ubports/ubuntu-touch/issues/994

**Closed by UniversalSuperBox** 2019-08-01 18:59 UTC
