### ISSUE TITLE
Meizu Pro 5 does not record 4k videos

### ISSUE THREAD

**Issue by jor1196** [ubports/ubuntu-touch#934] opened 2018-10-26 01:28 UTC
Hello good, when I installed xenial in my Meizu I realized when recording a video that the highest quality that is available is 1080p but in the version of Flyme OS 6 allowed to record already at 4k

- Device: Meizu Pro 5
- Channel: Stable
- Build: Xenial

**Comment by UniversalSuperBox** [comment] 2018-12-16 02:37
Has this ever worked for the Pro 5? If anything, we'll need someone who has the Ubuntu Edition.

If this has never been an option, it is likely expected behavior and won't be fixed.

**Comment by UniversalSuperBox** [comment] 2018-12-16 17:31
Yes, I'm asking if it has ever worked on the Ubuntu Edition of the Pro 5. That would make this a regression, something that worked before does not work now. If 4K video recording was never an option on the Meizu Pro 5 Ubuntu Edition under Ubuntu Touch, it is highly unlikely we will be able to add it.

**Comment by dark-eye** [comment] 2018-12-16 19:35
@UniversalSuperBox  4k was never available in Meizo Pro 5 Ubuntu Touch.
I made some test to see if it possible and  at the moment it seem to not be supported ( maybe further investigation will reveal some  unknown API settings... ) as the video it produce has some weird artifacts in them.

**Comment by UniversalSuperBox** [comment] 2018-12-21 17:48
Since 4K video recording was never available on the Meizu Pro 5 running Ubuntu Touch, even on the original builds from Canonical, this is an enhancement request rather than a bug. Since we do not have the source code used to make the Android compatibility layer on the Pro 5, it is highly unlikely we will be able to bring 4K video recording to the device. For that reason, I'm closing this issue as "Won't Fix".

**Closed by UniversalSuperBox** 2018-12-21 17:48 UTC
Labels: wontfix
