### ISSUE TITLE
[xenial] wi-fi switch missing

### ISSUE THREAD

**Issue by stefanomelchior** [ubports/ubuntu-touch#422] opened 2018-01-09 11:21 UTC
- Device: krillin
- Channel: ubports-touch/16.04/devel
- Build: r9, r10, r11, r12

### Steps to reproduce
$ ubuntu-device-flash -v --server=http://system-image.ubports.com touch --device=frieza --channel=ubports-touch/16.04/devel
to upgrade my system.

### Expected behavior
Expected to have on-off wifi switch available and a list of home wifi network to connect to.

### Actual behavior
After boot, no wifi detected.
No on/off wifi switch available (see attached picture)

![photo5949318613599103841](https://user-images.githubusercontent.com/32157542/34718424-78939880-f52e-11e7-934d-b07032ef3e95.jpeg)

From terminal:
phablet@ubuntu-phablet:~$ nmcli -p dev wifi connect blablabla password blablabla
 wifi connect blablabla password p 
Error: No Wi-Fi device found.

Further action:
Deleted /home/phablet/.cache directory and reboot
Nothing happened again.
In System setting/wifi/Previous network canceled all the home networks and reboot: nothing happened. System can't detect any network.

Note: NOT sure it can be related with issue #414 (https://github.com/ubports/ubuntu-touch/issues/414)

### Logfiles and additional information

[UTsyslog-frieza-xenial-r9.txt](https://github.com/ubports/ubuntu-touch/files/1614876/UTsyslog-frieza-xenial-r9.txt)
[UTdmesg-frieza-xenial-r9.txt](https://github.com/ubports/ubuntu-touch/files/1614877/UTdmesg-frieza-xenial-r9.txt)

**Comment by mardy** [comment] 2018-01-10 16:22
I see the same on my `krillin`.

**Comment by stefanomelchior** [comment] 2018-01-11 21:17
In r15 (frizza), the issue isn’t present anymore

**Comment by stefanomelchior** [comment] 2018-01-12 23:14
[frieza] In r16 it is still present.

**Comment by gabriel-lucas** [comment] 2018-01-13 02:50
Hi, I found a way to get around this issue. I tested in r16.

If you go to Settings -> Battery. There is a Wifi switch. When enabled, the wifi switch in the top menu comes back. Hope it helps.

**Comment by stefanomelchior** [comment] 2018-01-13 10:54
@gabriel-lucas I tested your workaround and it works
You can reproduce the weird behaviour as follows:
1) You switch back to vivid
2) then you upgrade again to xenial, at this point the on/off wifi switch "reappear"
3) you set flight mode on and then off, this makes on/off wifi switch desaperar!!!
4) as you explained, you go to battery setting and you switch on the wifi
5) then you go to wifi setting and the on/off wifi switch reappears and also the wifi networks will be accessible
The nice or expected behaviour would be:
1) when you turn on flight mode
2) on/off wifi switch will be there again in the same menu

**Comment by zubozrout** [comment] 2018-01-21 20:33
I've just experienced this on MX4 with version 22 but the switch was there after next reboot and when I turned WiFi on it connected and started working as expected.

**Comment by mebruno** [comment] 2018-01-27 16:30
In r23 (frieza), the issue isn’t present anymore

**Comment by gabriel-lucas** [comment] 2018-02-10 01:52
In r26 (frieza) the bug is not resolved.

**Comment by stefanomelchior** [comment] 2018-02-15 13:35
@gabriel-lucas gabriel-lucas If we assume there is a workaround, the bug could be closed for frieza. I don't know for krillin. That is why I would like to keep it open

**Comment by mariogrip** [comment] 2018-03-08 13:13
Can someone check if this is fixed? I wonder if this fixed this one also https://github.com/ubports/lxc-android-config/commit/3e1871df5e784c7aec9d29103c6769b71d9884cb

**Comment by tsimonq2** [comment] 2018-03-08 23:07
Yes, this is fixed.

**Comment by Flohack74** [comment] 2018-03-09 16:45
@stefanomelchior Was this krillin or frieza, see your original post, you specified both device IDs there.

**Comment by tsimonq2** [comment] 2018-03-11 09:07
Actually, I don't think this is fixed.

**Comment by mebruno** [comment] 2018-03-11 09:21
It was no issue for me up to 1604 devel  r48. Then it was introduced in frieza.Workaround:Settings/battery wifiswitch helpsOp 11 mrt. 2018 10:07 schreef Simon Quigley <notifications@github.com>:Actually, I don't think this is fixed.

**Comment by mariogrip** [comment] 2018-03-11 12:59
This change has not yet landed in the images, since it was a downgrade it took a little longer to land. next version should include this fix.

**Closed by mariogrip** 2018-03-11 12:59 UTC
Labels: device: krillin, needs confirmation

**Comment by stefanomelchior** [comment] 2018-03-18 09:46
It originally was frieza, then it was added krill in, that is why I didn’t close it

Stefano Melchior


On 9 Mar 2018, at 17:45, Florian Leeber <notifications@github.com> wrote:

@stefanomelchior Was this krillin or frieza, see your original post, you specified both device IDs there.

**Comment by advocatux** [comment] 2018-05-04 15:41
I don't have this bug in Krillin (BQ E4.5 16.04 (r67))

**Comment by helguson** [comment] 2018-08-02 20:48
Missing wifi switch happened to me on FP2 with 16.04rc (2018-W29).

The switch in battery section helps me to toggle wifi. The regular buttons are still missing.
