### ISSUE TITLE
problems with bluetooth headset implementation in pulseaudio

### ISSUE THREAD

**Issue by hoh61** [ubports/ubuntu-touch#581] opened 2018-05-03 21:56 UTC
- Device:BQ M10 FHD (frieza)
- Channel:16.04/devel
- Build:r67

### Steps to reproduce

bluetooth headset cannot be used for playback

### Expected behavior

blayback over BT headset

### Actual behavior

Nothing

### Logfiles and additional information

A dump of the pacmd gives the following feedback: https://paste.ubuntu.com/p/KDpqqrkTBM/

**Comment by NeoTheThird** [comment] 2018-05-05 15:07
Thanks for the detailed bugreport, but please use an attatchment or a service like paste.ubuntu.com for the log in the future ;) I'll edit your report.

**Comment by NeoTheThird** [comment] 2018-05-05 15:10
Also, you might want to give [this](https://docs.ubports.com/en/latest/contribute/bugreporting.html) a read if you're bored some time.

**Comment by NeoTheThird** [comment] 2018-05-05 15:16
Can someone try and reproduce this, both on xenial and vivid?

**Comment by Flohack74** [comment] 2018-05-05 16:42
Duplicate of #528

**Closed by Flohack74** 2018-05-05 16:42 UTC
Labels: duplicate
