### ISSUE TITLE
wrong apps window size on desktop mode/HDMI

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#364] opened 2017-12-16 10:39 UTC
bq M10 FHD / ota2
connect the M10 tablet over HDMI to a random TV in desktop mode, launch terminal, file-manager or whatever. you'll see that when they open they have a weird small size (see screenshot). 

screenshot https://i.imgur.com/eBAGuKQ.jpg

**Comment by dpniel** [comment] 2017-12-16 10:57
This is likely because these apps don't have a default width/height set and also doesn't cache the window width/height changes to be restored across launches.

I would file bugs against the apps in question. Should be a trivial fix

**Comment by NeoTheThird** [comment] 2017-12-16 11:24
Maybe we could set a default property to be used when no window size is defined.

**Comment by dpniel** [comment] 2017-12-16 11:40
Personally I think it's up to a developer to decide what an apps default width/height should be, just the same as they are to decide what orientation the app supports. What if an app defaults to a landscape layout but a portrait or squared window size is the default. We are only talking a couple of properties they need to change. :-)

```qml
MainView {
   width: units.gu(40)
   height: units.gu(60)
}
```

And to cache the values as well as the window position if the user changes them you can do.

```qml
import qt.labs.settings ..
MainView {
   id: mainView
   width: units.gu(40)
   height: units.gu(60)

    Settings {
        property alias windowWidth: mainView.width
        property alias windowHeight: mainView.height
        property alias windowX: mainView.x
        property alias windowY: mainView.y
    }
}
```

The cached settings will repopulate the properties on load.

Maybe we could add sane defaults to the app templates in clickable going forward? This wouldn't fix the current apps but we also wouldn't need to go changing uitk components either.

**Comment by NeoTheThird** [comment] 2017-12-16 12:53
> Personally I think it's up to a developer to decide what an apps default width/height should be, just the same as they are to decide what orientation the app supports.

Sure it is, but nobody wants their app to start in one-square-centimeter-mode. I know it's an easy fix, but it's an easy fix that needs to be applied in many many locations. Adding it to the templates is a good idea, it will help with new apps, but since most developers only test in staged mode, many current apps don't set window size. That's why i think having a fallback default that is only used when no window properties are defined is a good idea.

**Comment by dpniel** [comment] 2017-12-16 14:07
It's not like all apps have no default window dimensions. It's only a minority, but ok.. :-)

**Comment by NeoTheThird** [comment] 2017-12-16 14:46
(not merged yet)

**Comment by mariogrip** [comment] 2018-01-05 12:56
Fix commited https://github.com/ubports/ubuntu-ui-toolkit/commit/a0b3c32c2d67fe864b0f9d0bff13bddacde8faed

**Comment by kugiigi** [comment] 2018-01-19 19:22
I'm not sure if I undertood it right and if this comment still makes sense.
The fix was to simply put a hint on the width and height?
My apps have explicit setting of width and height in the MainView but still opens in a small square window.
Also I believe caching of the window size should happen system-wide. If I remember it correctly, there was already an implementation before to cache each app's last window size and position but just broken again.

**Comment by NeoTheThird** [comment] 2018-02-22 16:59
Closing this due to [changed issue tracking process](https://github.com/ubports/docs.ubports.com/pull/92). Can someone confirmed this works?

@kugiigi You should still be able to override it by setting the values yourself, this should just define sane defaults if the developer did not account for the app running in window mode. You should be able to store the last window size (for example using qt.labs.settings) and set them dynamically directly in your app. I'm not aware of a standardized system for this, but maybe I'm wrong. I'm also not sure if every developer will want their app to remember the window size. The only thing I know is that nobody will want their app window to be smaller than a fingertip.

**Closed by NeoTheThird** 2018-02-22 16:59 UTC
Labels: bug
