### ISSUE TITLE
Lock screen does not rotate

### ISSUE THREAD

**Issue by UKPhil** [ubports/ubuntu-touch#275] opened 2017-09-25 21:34 UTC
- Device:
bq M10

## Steps to reproduce

1. ...lock your device
2. ...on the lock/password screen rotate your device

## Expected behavoir
For the lock screen to rotate with the device 
...

## Actual behavior
The device does not rotate as you move the device. As a result you can end up having to input your password upside down.
...

## Logfiles and additional information

...

**Comment by block8437** [comment] 2017-10-08 03:27
I have experienced this as well on a Nexus 7. It's rotated 90 degrees so I have to turn my tablet sideways in order to type in the pass code, but once that is typed in the rotation fixes itself.

**Comment by Flohack74** [comment] 2017-10-08 13:36
The lock screen does not rotate on any device right now ;)

**Comment by UKPhil** [comment] 2017-10-08 20:32
That is the problem currently. With phones it is not too bad but when the os is being used on tablets, the lock screen needs to rotate to the way the user has their tablet.

**Comment by mateosalta** [comment] 2018-01-22 04:23
It should on phones too, for example take a scenario where you have the phone mounted landscape for navigation( you would need to unmount turn sideways, unlock, then remount), or in a stand landscape for media watching(maybe turn head sideways?), you using the device in that orientation and expect the lock/unlock method to work in that view.

**Comment by UKPhil** [comment] 2018-01-22 12:18
I totally agree with the comments above and we should have this as standard on all devices that use UT.

**Comment by dobey** [comment] 2018-03-03 21:17
Does this happen on Android on tablets? It certainly doesn't work this way on any of my phones. I don't think it makes sense to enable rotation either. The layout and behavior changes completely, for Ubuntu. To support this would require a re-design of the lock screen to handle both cases the same way, so it will look and behave the same for both orientations.

**Comment by UKPhil** [comment] 2018-03-04 00:25
I can see that this may be a bit of a new design issue, from what you are saying. However, for example  when you have the M10 up on its stand and the screen locks, the unlock screen is upside down and you have to type the passcode in upside down. Not ideal by any means.

**Comment by ruedigerkupper** [comment] 2018-03-04 10:58
I agree with UKPhil: I often have my Phone on a stand in sideways orientation for reading. When the screen locks and I want to unlock it, I have to type my passoword "sideways": Meaning not only the password box is upside down, but also the screen keyboard is upside down. It's really hard to type your password in this position.
So perhaps, not the full lock screen should rotate, but at least the screen keyboard and password box.

**Comment by dobey** [comment] 2018-03-06 13:11
Can you answer the posed question though? What is the behavior on Android? If you don't have an alternate device to compare, that's fine, but for me, Android also does not rotate the lock screen. I do not think iOS does either. I think they may just always force the lock screen to be in portrait mode though, too?

Also, I don't think you actually mean "upside down" here either. You mean sideways, AFAICT. Having the lock screen rotate will also make it more difficult to unlock when you don't have the device sitting on a stand. So I don't think auto rotate is the solution here.

**Comment by ruedigerkupper** [comment] 2018-03-06 20:41
@dobey: Thank you for your comment.

> Can you answer the posed question though? What is the behavior on Android? [...]
No, I can't. The only mobile phone I have ever owned was an Ubuntu phone, and I have never felt inklined to get an Android of iOS phone. Why should I?

> Android also does not rotate the lock screen. I do not think iOS does either.
So, are Android and iOS some kind of "standards" that Ubuntu Mobile should aim to meet? If I remember right, Ubuntu Mobile was designed to be different from existing OSes. Take it the other way round: why would you want to imitate the flaws of Android and iOS?
Do you think this will improve acceptance? Like: "Man, what always annoyed my about my Android phone was that the lock screen does not rotate. But, hey, look, Ubuntu Mobile doesn't either, so let's buy an Ubuntu Phone next!"...(?)

> Also, I don't think you actually mean "upside down" here either. You mean sideways, AFAICT.
That's correct. However, turn your phone 180° and you will really have to type your password upside down.

> Having the lock screen rotate will also make it more difficult to unlock when you don't have the device sitting on a stand.
Sorry, I'm lost here, what makes you think that?

Virtually all apps rotate with orientation: Notepad, phone app, system settings, browser, ... -- anything displaying text or requiring text being entered should do it.
Can you tell me only one single argument why the lock screen should not rotate?

Regards,
Rüdiger

**Comment by mateosalta** [comment] 2018-03-07 01:33
the cords on the M10 are on the top, so using it in a stand "upside down" with the cords routing on the bottom is the a great option for siting it on a desk stand.

**Comment by UKPhil** [comment] 2018-03-07 20:23
@Rüdiger I totally agree with all your comments here. Just because Android and iOS  do not, does that make them the gold standard?? Most, if nit all the people here have started using Ubuntu because they want something different.

**Comment by mateosalta** [comment] 2018-05-28 02:20
yes, good point. orientation of charging or docking keeps coming up.

Also note that in the wild at Ubucon Europe, I have observed several people charging their phones with the battery pack cord coming out on top. Since the main ui allows this orientation on the ubuntu phones, many naturally were using their phone in this way, just to keep the cord out of the way.

![image20180427_191346568](https://user-images.githubusercontent.com/1965279/40594150-f5a16a38-61f2-11e8-8e1e-37ee212b7123.jpg)

Even though landscape/portrait phone/tablet any direction option would introduce quite a bit of work, I still support any orientation you have the device on the lockscreen is the way to go.

**Comment by mateosalta** [comment] 2018-07-25 02:33
And yes, I have seen in the wild "Android does this", all rotations on a samsung tablet that even docks upside down - it will rotate the lock screen to all orientations. 
![image20180724_211120901](https://user-images.githubusercontent.com/1965279/43176400-1a8733b4-8f89-11e8-8d5d-235315abc6aa.jpg)
![image20180724_211131365](https://user-images.githubusercontent.com/1965279/43176401-1a96b60e-8f89-11e8-97cf-aa91c7f85ddf.jpg)

**Comment by UKPhil** [comment] 2018-07-25 06:44
Wow I had forgetten that this conversation was still going and got a bit of a shock when I got the email notification.

Hopefully with all the new builds/releases that are coming out now, this will be resolved.

**Comment by PhoenixLandPirate** [comment] 2018-07-26 16:23
In android most of the launchers don't even rotate, where as on ubuntu touch it does.
Limiting yourself to what android can/cant do isn't a good way to manage a project, imagine if google decided to stop people from using different launchers, just because they're the only phone that had that feature?

their are how ever, ways to make the locks-screen, and the launcher rotate.
https://www.youtube.com/watch?v=b7pY43eVr0E
https://www.youtube.com/watch?v=9vGfj2WZZxE

**Comment by Aurnytoraink** [comment] 2019-07-06 14:06
Is there any update on this issue ?

**Comment by keitalbame** [comment] 2019-08-31 18:39
I'm using a N7 LTE and IMO lock screen should not be displayed in landscape mode by default, since the aspect ratio of the display is not suited to that.

**Comment by jug007** [comment] 2019-09-25 16:57
I feel like the rotation settings have a lot of unused space, that could be used for a "lock screen rotation" setting.
Similar to the opening post of https://github.com/ubports/ubuntu-touch/issues/69
I would suggest, just filling the rotation settings with some actual settings.
Here is how this could look like:
![bb72da92-454f-11e7-86bd-4db8ab89790f](https://user-images.githubusercontent.com/11144627/65622554-2f348300-dfc6-11e9-86fe-809fd4ecb3a3.png)

**Comment by ruedigerkupper** [comment] 2019-09-25 17:02
Nice idea.

**Comment by mateosalta** [comment] 2020-02-12 17:06
I found how to allow rotation: https://github.com/ubports/unity8/pull/273

Now we can address the graphical issues :) but this should enable testing of a rotating lock screen.

**Comment by ruedigerkupper** [comment] 2022-01-22 15:15
Yeah, we have a nice rotating lock screen now! (On the devel channel, don't know if it has landed in stable yet.)

**Comment by Flohack74** [comment] 2022-01-22 20:30
So shall we keep this open? I would rather like to split out any remaining issues in a new ticket TBH.

**Comment by ruedigerkupper** [comment] 2022-01-23 16:32
The issue as stated in the bug description is fixed, so I'd say: close. But I can't really judge all of the comments and suggestions above.
Keeping tickets as focussed as possible is certainly a good idea.

**Comment by Flohack74** [comment] 2022-01-24 23:32
DUe to the age of this issue: closed. Feel free to continue on a new one :)

**Closed by Flohack74** 2022-01-24 23:32 UTC
Labels: opinion
