### ISSUE TITLE
Custom SMS sound

### ISSUE THREAD

**Issue by the-Mitu** [ubports/ubuntu-touch#202] opened 2017-08-05 19:18 UTC
Currently we can set the custom ringtone. It shouldn't be that hard to implement custom SMS sound alike, and it's important improvement especially that builtin notification sounds are quite quiet.

**Comment by TronFourtyTwo** [comment] 2017-08-06 10:23
It is not already available in settings>sound>message received ?

**Comment by the-Mitu** [comment] 2017-08-06 10:27
On stable OTA-1 I can only choose from among the default sounds and I cannot add my own.
I have not tested devel and RC channels - but I also haven't heard any news about it being introduced. Could someone on devel channel confirm if it is possible to set *custom* sound form SMS?

**Comment by Flohack74** [comment] 2017-08-06 10:30
Also not on devel. Its somehow bug & enhancement at the same time. But definitely it should not be hard to do, it´s the same like for ringtone.

**Comment by TronFourtyTwo** [comment] 2017-08-06 11:23
@the-Mitu Sorry. I misread thus I haven't noticed 'custom'

**Comment by the-Mitu** [comment] 2017-09-12 06:39
Now that we have notifications for Dekko, could it be possible to introduce choosable notification sound per-app (for example on the Settings -> Notifications panel) at once too? Currently Dekko sends notification, but there is no sound at all.

Or should I rather report it as an another issue?

**Comment by Sparkpin** [comment] 2020-07-28 00:45
Custom message/notification sounds still seem to be unavailable on PinePhone (UBPorts CE), OS build 2020-07-04.

**Comment by Arc676** [comment] 2020-07-28 07:45
I can confirm that it's also not available on Nexus 5/hammerhead on build 2020-07-23/2 (`devel`) so it's not PinePhone specific.

**Comment by Flohack74** [comment] 2020-07-29 12:34
You dont have this on N5 @Arc676 ???
![grafik](https://user-images.githubusercontent.com/16186470/88800548-a4558380-d1a8-11ea-8bca-816c68b1d7ca.png)
It is in system-settings / sounds?

**Comment by Arc676** [comment] 2020-07-29 14:36
@Flohack74 I believe the intended meaning of the issue is the inability to set custom SMS tones. I can indeed choose from among the provided ones but I can't import an audio file, whereas for the phone ringtone this is possible (Klingelton > [ganz unten] Eigener Klingelton). Under SMS tones (Nachricht Empfangen > ...) there is no such option; you can only choose from the existing tones.

**Comment by lduboeuf** [comment] 2020-07-29 15:26
yes, see the PR above. Hope it fix it

**Comment by Flohack74** [comment] 2020-07-29 16:45
@Arc676 ah sorry true I forgot that. Yes that´s still not possible...

**Comment by Flohack74** [comment] 2020-07-29 17:02
@lduboeuf I can only imagine that you can choose a very long sound so that by the time the display would turn off and the device should suspend again it would still be played. That could either be successful or it would just kill the sound. And maybe later when it wakes up it would overlap again :) but we can try this. I would merge it and see what happens with a few ppl.

**Comment by lduboeuf** [comment] 2020-07-30 07:28
Yeah i've tried with a long sound duration, it plays until the end and no way to cut it, even if suspend.  Sound does not overlap if i receive another sms

**Comment by Flohack74** [comment] 2020-07-30 11:40
Ok then lets go. We need to test it a bit with QA people though. Maybe we overlooked smth.

**Comment by Bolly** [comment] 2020-08-13 15:57
Checked this on a BQM10FHD running RC 2020 W-33.
It doesn't work
I tried a podcast (long audio) and it didn't work.
I tried a short audio and it didn't work.
I can't delete the previous one. Personal sounds are overwritten in the ringtones.

**Comment by Flohack74** [comment] 2020-08-15 16:35
@lduboeuf what dou you think?

**Comment by lduboeuf** [comment] 2020-08-15 17:00
humm can't reproduce here

**Comment by Flohack74** [comment] 2020-08-16 09:15
I tested here with my OPO and Halium 7.1, armhf devel rootfs. It plays the sound during selection, but then when a notification comes it does not work. Does it need to be a wav sound? I tried MP3 and OGG.

**Comment by lduboeuf** [comment] 2020-08-16 09:19
humm both ogg and mp3 works for me

**Comment by Flohack74** [comment] 2020-08-16 09:26
Additionally I cannot select a new custom notifiction tone anymore. So I could do it one time, but clicking again on the line does nothing :)

**Comment by Bolly** [comment] 2020-08-16 09:39
> I tested here with my OPO and Halium 7.1, armhf devel rootfs. It plays the sound during selection, but then when a notification comes it does not work. Does it need to be a wav sound? I tried MP3 and OGG.

Yes, I forget to say, It plays the sound during selection, but then when a notification comes it does not work.

**Comment by Flohack74** [comment] 2020-08-26 14:33
I am afraid we have to revert it for OTA-13, as we want to freeze the code and prepare a release soon.

**Comment by mariogrip** [comment] 2020-08-26 17:01
Yeah, we need to revert this for OTA-13, as we are in a freeze and *hopefully* release next week. So lets move this to OTA-14 :)

Here is the revert https://github.com/ubports/system-settings/pull/252

**Comment by kugiigi** [comment] 2020-08-27 19:07
This feature is present in the Tweak Tool and I remember doing some improvements in this particular feature. I'm trying to find the actual PR/MR but I think it was long ago and it was in github..can't remember anymore :sweat_smile: I believe I have detailed comments there about my findings.

Anyway, what I remember is that the file had to be located at `/usr/share/sounds/ubuntu/notifications` otherwise, it doesn't work in push notifications (i.e. TELEports,FluffyChat), only in SMS. And also, it has to be  in `OGG` format otherwise, the same issue as I mentioned earlier. Okay I cheated, I did not really remember these, I got them from the warning messages in UTTT :laughing:

**Comment by Flohack74** [comment] 2020-08-27 20:14
I thought ringtones and sms sounds would be copied to the right folder? Hmm when you select a custom ringtone from Music folder and then delete it, your ringtone is gone?

**Comment by Bolly** [comment] 2020-08-27 21:35
> I thought ringtones and sms sounds would be copied to the right folder? Hmm when you select a custom ringtone from Music folder and then delete it, your ringtone is gone?

No, does not disappear.

**Comment by Bolly** [comment] 2021-03-10 11:45
> What's the status of this, guys?

I guess it's at a standstill, there are a lot of priority changes like the jump to 20.04...
You can change the sound with https://open-store.io/app/ut-tweak-tool.sverzegnassi

**Comment by lduboeuf** [comment] 2021-09-23 11:52
if anyone want to give a try. I've tried to work on it again.
From RC or Devel just do `sudo ubports-qa install PR_lomiri-system-settings_304` reboot might be needed.

**Comment by Flohack74** [comment] 2021-09-23 22:14
First impression:
- Selection and playback works from system settings. Translation is wrong, saying "Own ringtone", this needs a new string
- However, push client cannot play it back
I think the reason is that system sounds are in URI: file:///usr/share/sounds/ubuntu/notifications/A440.ogg where as cutom one is in file:///home/phablet/.local/share/ubuntu-system-settings/Music/Message/2021-09-23-23-59-36-042.ogg and thats a path that push client probably is not allowed to access. How is this solved for custom ringtone? It comes also from similar location file:///home/phablet/.local/share/ubuntu-system-settings/Music/
I checked media-hub log, it is reacting on a push notif with the usual infos, but for the custom tone it does not spit out a single line, so the problem starts already much before that.
- Maybe dont try to put it into subdir /Message?

**Comment by Flohack74** [comment] 2021-09-23 22:20
PS made this test n Halium 10.

**Comment by lduboeuf** [comment] 2021-09-24 07:40
@Flohack74 Thanks for the feedback. 
- For the Translation, mine in French is fine and it is the same string as for Ringtones.
- If we use the same folder than the custom Ringtone we will have ringtone with message notification sound in the same list, which is not really fine.

Yes, probably a permission issue, i will try to find info about it. At least for sms it works for me,

**Comment by Flohack74** [comment] 2021-09-24 08:10
Strange now it work on text message! I will have a look into various classes of notifications.

**Comment by lduboeuf** [comment] 2021-09-24 13:19
It works only for sms/mms but for apps that use the push-client it won't work.

push-client just look for the song file within the caller app directory ( e.g local teleport app dir ) or within XDG default directories which the sound file is not part of ( stored in ~.local/share/ubuntu-system-settings/Music )

**Comment by Flohack74** [comment] 2021-09-29 18:33
Merged in https://gitlab.com/ubports/core/lomiri-system-settings/-/merge_requests/304

**Closed by Flohack74** 2021-09-29 18:33 UTC
Labels: enhancement

**Comment by Flohack74** [comment] 2021-09-30 14:07
Merged in https://gitlab.com/ubports/core/lomiri-push-service/-/merge_requests/38

**Comment by lduboeuf** [comment] 2021-09-30 17:11
confirm it works on N5 devel :)

**Comment by josevidalrt** [comment] 2021-10-09 14:13
It works.

    Device: BQ E4.5
    Channel: rc
    Build: 2021-w40

**Comment by Danfro** [comment] 2021-11-05 19:51
Good news, the sound does work.

Two small regressions for this:
1. the selected custom sound is instantly played but I could not find a button to stop that playback. It does stop after a while. But even if I go back into the sound setting, select the sound again and press the "stop" button at the bottom, that does not respond. Also selecting another sound does not stop playing the sound before. (Use a song for testing that last a while).
2. there seems to be some sort of bottom edge rectangle blocking the access to the custom sound option when tapping on it. I need to swipe up a bit to be able to access the option. See screenshot.

**Comment by lduboeuf** [comment] 2021-11-05 19:56
For the 2nd part, the layout issue is fixed here: https://gitlab.com/ubports/core/lomiri-system-settings/-/merge_requests/305
Idk if it will be merged on OTA-20

**Comment by cibersheep** [comment] 2021-11-11 17:32
Device: Arale
Channel: RC 2021-W45
Result: I can select a file and it displays in the list.

Little issues: layout of ContentHub, the player area underneath the list and the text not being translated (which can be addressed on next OTA)

**Comment by Flohack74** [comment] 2021-11-11 19:26
@lduboeuf no sorry we missed that. If you have PRs on Github or MRs on Gitlab and you think they should be merged rather soon please ping anyone like me to add it to the project trackers so we see it before we close an OTA. We have hundreds of PRs/MRs open, its impossible to know everything going on.

**Comment by lduboeuf** [comment] 2021-11-11 19:32
@Flohack74 Yes i did it, then Dalton started reviewing it but probably get lost after. I've noted that it happens often when there is a "change requested" and after we mark it as resolved,  it doesn't seems to notify clearly the reviewer

**Comment by Flohack74** [comment] 2021-11-11 20:30
Even if it does, a reviewer might miss that. It needs to be on the project board of the next OTA, which we review multiple times before freeze.

**Comment by Flohack74** [comment] 2021-11-13 16:16
@danfro not being able to stop that sound is a separate issue, and you might want to file this against https://gitlab.com/ubports/core/lomiri-system-settings

**Comment by Danfro** [comment] 2021-11-15 10:56
@Flohack74 I am not sure I agree. Stopping the sound works for default messages. It only does not work for the new custom message sound. So this in my opinion belongs to this new option. Unless we want to introduce a new function with broken parts?

Of course we can ship the option with OTA20, I would not call it a breaker. Then we would have to sort this out as a new issue.

**Comment by lduboeuf** [comment] 2021-11-15 13:00
@Flohack74 @Danfro
Just tested now, the same behavior applies for custom ringtones and notification sound, so this is not a regression. When you select a sound file, it is played and the UI is moving to the Sound Setting main page, the connection with MediaPlayer is probably lost here.

This issue does not happen if a custom sound was already imported and we just select it from the sound list.

**Comment by Danfro** [comment] 2021-11-15 16:34
@lduboeuf here on my Xperia only when selecting a new custom sound it goes back to the sound settings main page. If I select a default sound from the list (or the listed older custom sound), the "select sound" view stays, the sound is played and can be stopped with the button at the bottom. I need to tap the back icon to go back to the main sound settings page.

**Comment by Flohack74** [comment] 2021-11-15 16:54
Ok definitely a separate issue. This one here stays as tested OK then ;)
