### ISSUE TITLE
FR: Ability to specify time format for messages and other date stamps

### ISSUE THREAD

**Issue by Hypexed** [ubports/ubuntu-touch#927] opened 2018-10-19 00:12 UTC
### Description of the feature
Submitting a feature request to specify time format for displayed time and date stamps.

So that the date format for messages and other time stamps displayed on screen can be changed to suit user. In particular so the time format can be changed so that seconds are also displayed. Such as in a format of:
HH:MM:SS

Is this a setting that can be edited on the filesystem itself?

**Comment by UniversalSuperBox** [comment] 2018-12-16 02:09
Closing as duplicate of https://github.com/ubports/ubuntu-touch/issues/863

**Closed by UniversalSuperBox** 2018-12-16 02:09 UTC
Labels: duplicate
