### ISSUE TITLE
Date & Time Format settings independent from display language

### ISSUE THREAD

**Issue by ZergerZ** [ubports/ubuntu-touch#863] opened 2018-09-05 22:32 UTC
### Description of the feature
There is currently no way to set different clock format (Ex: 12 to 24 hour) rather than to change the display language.

It might be useful feature of the operating system to be able to change this via GUI

forum topic as reference:
https://forums.ubports.com/topic/1646/change-clock-to-24-hour-format-16-04-ota-4

**Comment by Danfro** [comment] 2019-06-01 20:04
duplicate of #729

**Comment by mateosalta** [comment] 2020-05-31 16:57
this might have some relevant work https://code.launchpad.net/~attente/ubuntu-system-settings/1392699/+merge/296271

**Comment by Flohack74** [comment] 2020-07-30 15:22
Closed in favour of #729

**Closed by Flohack74** 2020-07-30 15:22 UTC
Labels: duplicate
