### ISSUE TITLE
OTA-16 Meizu pro 5 no icons app on desktop

### ISSUE THREAD

**Issue by vokaliz** [ubports/ubuntu-touch#1694] opened 2021-03-24 05:35 UTC
After update from OTA-15 to OTA-16 no icons app on desktop (Meizu pro 5). I see my apps only on the left slide side.

**Comment by UniversalSuperBox** [comment] 2021-03-24 15:46
Hi @vokaliz,

From which release of Ubuntu Touch did you upgrade your Pro 5? Are you able to swipe the App Drawer from the left side of the screen or by tapping the Ubuntu logo?

**Comment by vokaliz** [comment] 2021-03-25 03:27
I upgraded pro 5 from OTA-15 (december 2020) to OTA-16 (23.03.2021), App Drawer able to swipe, I see all my apps after slide of the screen and Ubuntu logo able for tapping, I am sending message from Morph Browser right now. Desktop clean, no one icon app. One more problem: after updrade Net Speed app not start for example, Launcher modular work well, can see apps, but some of apps not start after tapping.

**Comment by UniversalSuperBox** [comment] 2021-03-25 13:46
@vokaliz,

Ubuntu Touch hasn't had a desktop ever. Scopes were removed quite a while ago, and definitely before OTA-15. Might you have a screenshot of what you expect to see in this new version of Ubuntu Touch?

**Comment by vokaliz** [comment] 2021-03-25 17:31
The desktop, in my understanding, is a screen with application icons that is displayed immediately upon startup.
![screenshot20210325_201027489](https://user-images.githubusercontent.com/39481201/112517017-e58a4b80-8da8-11eb-8dfb-abf25398725e.png)
![screenshot20210325_201133743](https://user-images.githubusercontent.com/39481201/112517034-ea4eff80-8da8-11eb-8c91-12a91ba89fdb.png)
![screenshot20210325_201046185](https://user-images.githubusercontent.com/39481201/112517044-ed49f000-8da8-11eb-8752-16fe038b2cc4.png)

**Comment by UniversalSuperBox** [comment] 2021-04-02 16:09
@vokaliz, I am having trouble understanding what the problem with your update to Ubuntu Touch created:

If you are having trouble with launcher-modular, you should contact the developers of launcher-modular. We do not provide support for using that app in this bug tracker.

Ubuntu Touch has not had desktop icons ever. Up to 2019, Ubuntu Touch *had* Scopes, including the Apps Scope which appeared when you performed a long swipe from the left edge of the screen. This App Scope looked a bit like this:

![image](https://user-images.githubusercontent.com/21966173/113432909-d22c4100-93a3-11eb-9d10-ff6f2328cd3f.png)

Is the App Scope the thing that you are missing?

Or, are you requesting a new feature? Do you expect that you cannot put icons on your desktop (because Ubuntu Touch has never had that) and you would prefer to do so?

**Comment by vokaliz** [comment] 2021-04-03 14:02
Hi, USB! There are no problems with Launcher Modular. In previous OTA before OTA-16, all application icons were on my desktop (as in your picture). Now they are gone. If the icons disappeared due to the fact that this is the result of innovation, then this is not the best solution to improve UBports :) After loading OS, I want to use the applications immediately without unnecessary swipes. The desktop, as in my screenshot, is not very convenient.
![screenshot20210403_170008681](https://user-images.githubusercontent.com/39481201/113480647-1d2a7f00-949e-11eb-990e-8293df6c1511.png)

**Comment by UniversalSuperBox** [comment] 2021-04-03 16:18
Hi @vokaliz,

The "home screen" of Ubuntu Touch changed in Ubuntu Touch OTA-12, released May 13, 2020. You can read more about this release here: https://ubports.com/blog/ubport-blogs-news-1/post/ubuntu-touch-ota-12-release-151

I'll close this report now since this is expected behavior of Ubuntu Touch. I'm not sure why you haven't received this update until now, is it possible that you were still running Ubuntu Touch from Canonical?

Thank you for your feedback on the new Drawer interface. If you would like to discuss more about it, please note the previous discussion in https://forums.ubports.com/topic/2579/i-wanna-go-home and many other places on our forum. Then, find us in [the UBports Forum design section](https://forums.ubports.com/category/40/design) for further discussion.

**Closed by UniversalSuperBox** 2021-04-03 16:18 UTC
