### ISSUE TITLE
Bluetooth not working after new RC update.

### ISSUE THREAD

**Issue by captainzer0** [ubports/ubuntu-touch#1371] opened 2020-02-15 01:30 UTC
- Device: Nexus 5
- Channel: rc
- Build: 65

I just installed the RC update ver 65 on my N5, and I now cannot get any bluetooth devices to connect. I get device not discoverable and the slider will not stay green. Don't know if this is related to the update but this has never been an issue in the past. Thanks for all the great work.

**Comment by UniversalSuperBox** [comment] 2020-03-04 01:13
Hi @captainzer0,

I hope you don't mind, but I've updated your issue description to match the format we're more used to.

I just tested the newest devel on my Nexus 5 and it seems like I'm able to turn on Bluetooth and connect to my cheap Bluetooth car kit. Could you please check to see if this is still an issue?

Thank you!

**Comment by Rargente** [comment] 2020-03-04 20:14
I have a Nexus 5 that was working without issue on RC 65, but since updating to 66 I am now experiencing the same problem. Toggle in settings will not stay on.

**Comment by UniversalSuperBox** [comment] 2020-03-04 20:17
This appears to be related to https://github.com/ubports/bluez-packaging/pull/6, but in a completely unexpected way. System-image is unpacking the newer `hciattach` from the new bluez package over what's already there... which happens to be a custom version of `hciattach` with special support for specifying a firmware directory for Broadcom. Without that patched version of `hciattach`, we're unable to initialize Bluetooth.

The patched `hciattach` is shipped as a prebuilt and it appears to have been built at Canonical for the Broadcom Touch devices. Finding the source will be interesting at best, I suspect.

**Comment by ruedigerkupper** [comment] 2020-03-07 13:35
Confirmed on the Xperia X: Most devices will connect, then immediately disconnect again. 
Interestingly, I have one single device that works (connects and stays connected): a bluetooth headset.

**Comment by UniversalSuperBox** [comment] 2020-03-07 15:13
@ruedigerkupper, that is probably a separate issue. This issue is about Bluetooth never becoming active on the Nexus 5. Could you please ask Alfred about the Xperia X and where to file that issue more appropriately?

**Comment by lutin11** [comment] 2020-03-08 19:47
I confirm te issue on last rc with N5

**Comment by Flohack74** [comment] 2020-03-08 22:54
We will try to release a fix with next RC, though it is still not working as we would wish. Sorry and thx for your patience

**Closed** 2020-03-09 18:45 UTC
Labels: bug, critical (rc)

**Comment by lutin11** [comment] 2020-03-10 19:29
I've installed the last RC today and the phone is now running on 2020-w11, unfortunately bluetooth stil not working.

**Comment by UniversalSuperBox** [comment] 2020-03-10 21:14
Rather drastic measure, I've deleted the delta update from RC version 66 to 67. This will fix the issue for all upgraders.

If you've already upgraded to the RC image but experience this problem, either run `sudo system-image-cli -b 0 --progress=dots` from an ADB or SSH shell (it will not work from the on-device terminal) or use the UBports Installer to reinstall the RC channel on your device. In either case, you will not lose data (as long as you don't check that option).

**Comment by lutin11** [comment] 2020-03-11 07:58
Thanks for your replied, running 
> `sudo system-image-cli -b 0 --progress=dots`

solved the problem !
