### ISSUE TITLE
WLAN service/cell network service crashes and demands 100% cpu load after booting

### ISSUE THREAD

**Issue by Rom4nB** [ubports/ubuntu-touch#304] opened 2017-10-19 09:35 UTC
- Device: Nexus 5 (Model LG-D821, FCC ID: ZNFD821)
- Channel: Stable Channel
- Build: Ubuntu 15.04 (r2)

## Steps to reproduce

1. Switch on phone: WLAN might be crashed, even also cell phone network (no cell phone network seen), flight mode does not work either -> switch off to reboot
OR
swtich on phone after having it charged over night

## Expected behavoir

Phone boots normally, incorrect 1970 date (see other known bug for hammerhead) is swiftly swichted to correct date, mobile network and WIFI working, phone not getting warm

## Actual behavior

1. Google logo seen for unusal long time
2. Ubports loading screen, App Scope loading, fetching correct date etc. takes all unusal long
3. WIFI not working (service not started)
4. Phone gets warm with 100% cpu load, phone hardly usable, doesn't even shut down properly often (shut down then forced via recovery mode)
5. after about 5 attempts to boot the phone, at one time the phone won't be a hand warmer anymore, cpu is not at 100%, cell phone network and wifi connects normally

## Logfiles and additional information

Screenshot 1: cell phone network and wifi crashed during stand by -> cell phone settings not seen neither in top bar nor in settings, flight mode not working
![screenshot20171019_102759160](https://user-images.githubusercontent.com/19626851/31764426-6c7a968c-b4c1-11e7-8be6-e136f08847b8.png)
Screenshot 2: top shows 100% cpu load caused by the process 'wlan_event_handle', note that time/date did not automatically switch from wrong '1970' date
![screenshot19700128_230631101](https://user-images.githubusercontent.com/19626851/31764446-7eb2fe84-b4c1-11e7-8abc-8a7810ae6f3e.png)

**Comment by rubencarneiro** [comment] 2017-10-19 18:46
Time and data bug is now fixed.
https://github.com/ubports/android_device_lge_hammerhead/pull/14

**Comment by HendriXXX** [comment] 2017-10-20 07:11
I have experienced this bug once in my N5 with ota2. Just like Rom4nB described.

**Comment by HendriXXX** [comment] 2017-10-23 20:19
In couple of days I had again few times this hanging CPU 100%- problem. If I try to boot it normally, I have non-opening apps, phone heating, stuttering after couple reboots and sometimes it has to reboot MANY times to get it working again properly.

This workaround works for me, I reboot it first to fastboot mode and then start it from there. Phone works after first boot perfectly..

Next time I try to get some logcat print..

**Comment by Rom4nB** [comment] 2017-10-24 07:33
I continue struggling with this bug. :/

On sunday in the morning I didn't notice instantly that phone did not boot properly, got hot, mobile network service did not connect and calls didnt come through.

After several reboots it finally worked but battery was drain to 60% (from fully charged).

At afternoon, I noticed in the pocket that the phone got warm again. I assume roaming could have caused trouble again (I was in France) - reboot and airplane mode safed me to get home with 2% battery in the evening.

Yesterday and today the same as usual that it takes several boot attempts until it works properly.

Unfortunately, the phone is very unreliable

**Comment by Rom4nB** [comment] 2017-10-24 07:36
... sorry I accidently hit the close button. ^^

Continue: My phone is very unreliable with Ubuntu. With LineageOS or stock my N5 worked fine, so I do not think the hardware itself is damaged.

I really consider flashing LineageOS again as the phone is not really usable as a daily driver in the current state. :(

Is there a way to help you guys with further information to track this bug? My issue seems to be very similar to what HendriXXX described.

**Comment by Rom4nB** [comment] 2017-10-25 16:59
Today, my phoen worked fine until during Podbird-ing the 100% cpu load crash caused by wl_event_handle came in.

Now I'm still trying to boot my phone properly (had several attempts now). It got stuck in the Google boot screen first, as the battery got drain too deep by the crash and the Nexus 5 doesn't boot properly on low battery. 

Recovery mode permitted to switch off the phone and let it charge a while. Now I can boot the phone again but with about 5 attempts now it keeps crashing.

I managed creating logs now but I dunno if this can help.

They are attached below.

[UTDmesg.txt](https://github.com/ubports/ubuntu-touch/files/1415453/UTDmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1415454/UTlogcat.txt)

**Comment by UniversalSuperBox** [comment] 2018-05-19 15:38
I can still confirm this on my D820 hammerhead (so we know it's both revisions) with Baseband version `M8974A-2.0.50.2.30`. The issue occurs on both 15.04 (all tested revisions) and 16.04 (all tested revisions). When anything attempts to work with the Wi-Fi chipset, we get this extreme use of CPU.

I was able to observe the load changing from one process to another, but I don't know why that happens. On boot, `wl_event_handle` was using 100% of one core. A few minutes later, it stopped and `wpa_supplicant` took its place. When I tried to turn off Wi-Fi by turning on Flight Mode or flipping the Wi-Fi switch, `urfkilld` took `wpa_supplicant`'s place.

**Comment by fourloop2002** [comment] 2018-06-15 08:14
I can confirm @UniversalSuperBox comments above.  In addition when the CPU was overloaded with process urfkilld, I could not open another adb shell session which was just hung and no connection was made.

Plus the Actual Behaviour description in the bug definition matches my experience.  The Google splash screen lasted for a number of minutes before Unbuntu loading screen appeared.

**Comment by Zig-03** [comment] 2018-10-05 09:27
This seems like a huge issue, no? Should we avoid buying Nexus 5 for now (if we only wanna buy them to install UT on them)?

**Closed** 2019-09-26 13:54 UTC
Labels: bug, device: hammerhead
