### ISSUE TITLE
[xenial] - Cellular data carrier selection error

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#620] opened 2018-05-21 04:48 UTC
- Device: Hammerhead
- Channel: Xenial
- Build: 391

### Steps to reproduce

On Settings > Cellular Network.

### Expected behavior

Connection type lists the ones available and allows to select one.
Having internet through data. 

I've test this sim card on N5 Vivid and N4 Xenial no issue.

### Actual behavior

 Only 2G/3G  (faster) is shown and not ticked. 

The phone see the 3G data connection, but impossible to get the 3G data sign in the top bar and no internet. 

When i select the only option available, ofono fails.
`TechnologyPreference :  QDBusError("org.ofono.Error.Failed", "Operation failed")`

### Logfiles and additional information
indicator-network.log && application-legacy-ubuntu-system-settings-.log
https://paste.ubuntu.com/p/Rs7N49hNkt/

Test-modem got stuck
https://paste.ubuntu.com/p/vjhWBTXH7P/

List-modems
https://paste.ubuntu.com/p/HSh8gTHPFY/

Syslog (when selecting Only 2G/3G

```
May 20 23:42:27 ubuntu-phablet repowerd[986]: LibsuspendSuspendControl: disallow_suspend(UnityScreenService)
May 20 23:42:27 ubuntu-phablet repowerd[986]: UnityScreenService: dbus_requestSysState(:1.91,active,1) => 124
May 20 23:42:28 ubuntu-phablet repowerd[986]: UnityScreenService: dbus_clearSysState(:1.54,123)
May 20 23:42:29 ubuntu-phablet repowerd[986]: DefaultStateMachine: handle_user_activity_extending_power_state
May 20 23:42:29 ubuntu-phablet ofonod[2400]: ril_set_rat_mode: unable to set rat mode
```

Seems to be related to #405 

![screenshot20180520_215059925](https://user-images.githubusercontent.com/11337464/40291076-3ff0c1da-5c88-11e8-80b4-b68ca59e5f16.png)
![screenshot20180520_202415909](https://user-images.githubusercontent.com/11337464/40291081-43fd955a-5c88-11e8-8ba6-3e2e88bc551a.png)

**Comment by fourloop2002** [comment] 2018-05-21 07:57
Is this related to #598

**Comment by Flohack74** [comment] 2018-06-02 19:27
I think this is even a duplicate of #598 ...

**Comment by UniversalSuperBox** [comment] 2018-06-03 00:53
Closing as duplicate of #598

**Closed by UniversalSuperBox** 2018-06-03 00:53 UTC
Labels: bug, critical (devel), device: hammerhead
