### ISSUE TITLE
Missing window (keypad, red button, etc.) on all incoming calls

### ISSUE THREAD

**Issue by FlavioMala** [ubports/ubuntu-touch#1451] opened 2020-05-14 21:27 UTC
After accepting an incoming call, the keypad window (with the red button to end the call) is missing. 
Usually nothing on screen (while you are in conversation!), sometime the green bar at the top: tapping on it (or phone icon on left bar), the keypad appears for a moment than crashes again. See also report in OTA-12 call for testing forum.

It happens with about 95% of incoming calls. No problem with outgoing calls.

- Device: bq Aquaris E5 HD
- Channel: stabil (and rc from w18; previous w17 was OK)
- Build: OTA-12 (released 13 May 2020)

### Steps to reproduce
Accept an incomig call (any type).

### Expected behavior
After accepting a call, the white “phone“ window should appear for a moment, than the keypad window with the red button (+ sim, number on name, etc).

### Actual behavior
No red button to end a call !

**Comment by FlavioMala** [comment] 2020-05-16 08:13
Can anyone suggest me where to find useful logs?

**Comment by lduboeuf** [comment] 2020-06-10 07:26
might be related https://github.com/ubports/ubuntu-touch/issues/195

**Comment by UniversalSuperBox** [comment] 2020-06-14 20:41
This appears to be a duplicate of https://github.com/ubports/ubuntu-touch/issues/195

**Closed by UniversalSuperBox** 2020-06-14 20:41 UTC
