### ISSUE TITLE
[xenial] Clock displays a different time than set globally

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#502] opened 2018-03-04 01:20 UTC
- Device: hammerhead
- Channel: xenial/devel
- Build: r273

### Steps to reproduce
Set the system time to a time other than UTC and open the Clock app.

### Expected behavior
The Clock app should show the time as the globally set time, not as the UTC time.

### Actual behavior
When the time is e.g. 7:20 PM (UTC-6), the Clock app shows 1:20 AM rather than 7:20 PM which is at the top right of the screen.

**Comment by padraic7a** [comment] 2018-03-04 13:33
Can confirm this on my BQM10 running 16.04 r41.

If you try to change the system settings window you can see that every location comes up as "UTC+0"

![screenshot20180304_133051387](https://user-images.githubusercontent.com/3010391/36946169-9b4827ea-1fb0-11e8-9b3a-5f9600593ea1.png)

**Comment by Flohack74** [comment] 2018-03-04 17:13
@tsimonq2 Please dont add bug level yourself, it will be done by the QA team. Unless we got more than one report for an issue we will not mark it as bug at all...

**Comment by mariogrip** [comment] 2018-03-06 10:23
Duplicate of https://github.com/ubports/ubuntu-touch/issues/447

**Closed by mariogrip** 2018-03-06 10:23 UTC
Labels: bug
