### ISSUE TITLE
Audio stops playing on network change

### ISSUE THREAD

**Issue by userj** [ubports/ubuntu-touch#887] opened 2018-09-24 01:25 UTC
### Illustrations

- Device: Hammerhead
- Channel: 16.04/devel
- Build: 2018-09-23

### Steps to reproduce

- Start playing and episode in podbird (even downloaded/not streaming)
- Change network: airplane mode, or connect/disconnect from wifi

### Expected behavior

- Audio keeps playing with no relation to the network connection

### Actual behavior

- Audio stops playing. Have to restart app and play again.

**Comment by vpzomtrrfrt** [comment] 2019-01-19 16:55
I think I may have experienced this, but can't reproduce it now.  May also be related to https://bugs.launchpad.net/podbird/+bug/1446859

**Comment by Flohack74** [comment] 2019-02-02 18:56
If an application gets interrupted in their audio stream, it needs to take measures to reconnect. Thats also the same on desktop. The operating is of limited help here. You need to find a support for podbird, and open a bug there, though I dont know about any maintainer right now.

**Comment by hummlbach** [comment] 2019-02-02 21:02
@userj so lets close this as it seems not to be a problem in the os. You could open a "call for podbird maintainer" thread in the forum.

**Closed by hummlbach** 2019-02-02 21:02 UTC
Labels: needs confirmation
