### ISSUE TITLE
[edge] search results hidden behind OSK

### ISSUE THREAD

**Issue by Danfro** [ubports/ubuntu-touch#1238] opened 2019-10-02 18:29 UTC
- Device: E5
- Channel: Edge
- Build: 2019-10-01/2

### Steps to reproduce
- Open the drawer
- Type one letter into the search bar that yields many results
- Scroll in drawer down towards the bottom
[the OSK stays raised when scrolling in the drawer]

### Expected behavior
- All apps/search results are accessible/visible in the visible drawer area above the OSK

### Actual behavior
- I can not scroll down to the bottom of the drawer, some apps/search results stay hidden behind the OSK.

### Possible solutions
1. When the search bar leaves focus OR when the drawer gets the focus the OSK is dismissed
2. The drawer area is resized so drawer bottom matches top of OSK

**Comment by Danfro** [comment] 2019-10-02 20:48
Example for option 1: OpenStore
Examples for option 2: Teleports
Example featuring both: FluffyChat

**Comment by UniversalSuperBox** [comment] 2019-10-14 19:09
This is a duplicate of #1245, since in either case the keyboard is blocking the content.

**Comment by UniversalSuperBox** [comment] 2019-10-14 19:10
No, I can't read, or remember that the Drawer and Launcher are separate.

**Comment by UniversalSuperBox** [comment] 2019-10-18 19:52
Fixed by https://github.com/ubports/unity8/pull/206

**Closed by UniversalSuperBox** 2019-10-18 19:52 UTC
Labels: bug, edge
