### ISSUE TITLE
Sign in to google account

### ISSUE THREAD

**Issue by diabolo81** [ubports/ubuntu-touch#1813] opened 2021-08-27 10:20 UTC
It's not able to sign in to the google account with the feature accounts on ubuntu touch

### Illustrations

- Device:
- Channel:
- Build:

**Comment by mardy** [comment] 2021-08-31 16:52
This sounds like a duplicate of https://github.com/ubports/account-plugins/issues/40

If it isn't please reopen adding more information.

**Closed by mardy** 2021-08-31 16:52 UTC
