### ISSUE TITLE
Sound gauge not always stable

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1339] opened 2020-01-10 12:33 UTC
Dear all,

I noticed that when a video started in MorphBrowser, the sound gauge automatically goes up to half power, yet I reduced it few sec ago to a minimal power.

- Device: mako, Nexus4
- Channel: Stable

### Steps to reproduce
? --> random
Sorry for the poorly detailed issue... but there is no solid steps to reproduce.
Maybe this one: Start the video with that
https://www.aubert.com/p/01056144/transat-balance-soft-gris-fonce-gris-coton-jersey-babybjorn

**Comment by UniversalSuperBox** [comment] 2020-01-12 21:27
Hi @Thieb67k,

This may happen because there are multiple volume gauges in Ubuntu Touch: Notifications, media, and alarms. Notification volume is what you're adjusting by default. You can only adjust a volume when the type of media is playing.

I believe this is a duplicate of https://github.com/ubports/ubuntu-touch/issues/81, making it easier to adjust each volume separately.

**Closed** 2020-01-12 21:27 UTC
