### ISSUE TITLE
screen rotation does not work

### ISSUE THREAD

**Issue by timpppa** [ubports/ubuntu-touch#489] opened 2018-02-28 18:59 UTC
- Device: Frieza 
- Channel: 16.04/devel
- Build: all 

### Steps to reproduce
None needed

### Expected behavior
When device is rotated from portrait to landscape or the other way around screen should rotate accordingly.

### Actual behavior
Screen stays in landscape orientation.

**Comment by NeoTheThird** [comment] 2018-02-28 19:00
This should actually work now, are you sure you are running the latest version? Duplicate of #393.

**Closed by NeoTheThird** 2018-02-28 19:00 UTC

**Comment by NeoTheThird** [comment] 2018-02-28 19:02
You might have to re-flash from your PC, if you are running a very old version.
