### ISSUE TITLE
[PRO-5] LED notifications are all the same, so it's a spam

### ISSUE THREAD

**Issue by cm-t** [ubports/ubuntu-touch#1377] opened 2020-02-21 16:21 UTC
- Device:  turbo (PRO 5 internnationale)
- Channel: candidate
- Build: 2020-W08

### Steps to reproduce

 * phone is switched on
 * phone is **not plugged**
 * switch on the screen, white&black messaging icon
 * switch off the screen
 * new message received
 * LED blinks in and out with white color
 * switch on the screen, green messaging icon.

 * **plug** the phone
 * switch on screen, white&black messaging icon
 * switch off the screen
 * LED blinks in and out with white color
 * switch on the screen, white&black messaging icon
 * swittch off screen
 * new message received
 * switch on the screen, green messaging icon

 * 

### Expected behavior

 charging LED notification should be different than LED messaging notification.
If there are hardware/android limitations, charging LED notification should just be disabled by defaut on this device (pro5)

### Actual behavior

same behavior with LED charging notifications and LED messaging notifications.
user doesnt know if new message arrived, must switch on the plugged phone every single time there is a doubt. doubt and frustration ^^

**Comment by zubozrout** [comment] 2020-02-23 22:20
Same as this one: https://github.com/ubports/ubuntu-touch/issues/1336

**Comment by UniversalSuperBox** [comment] 2020-03-30 21:44
Duplicate of https://github.com/ubports/ubuntu-touch/issues/1336

**Closed by UniversalSuperBox** 2020-03-30 21:44 UTC
Labels: bug, device: arale, device: turbo
