### ISSUE TITLE
[xenial] - Web Browser fails on a URL

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#626] opened 2018-05-24 03:05 UTC
- Device: N5
- Channel: 398
- Build: Xenial

### Steps to reproduce
Open https://www.nouvelobs.com/ with the webbrowser

### Expected behavior
Able to read the page

### Actual behavior
Page fails : The rendering process has been closed for this tab, something went wrong while displaying....

### Logfiles and additional information
http://paste.ubuntu.com/p/MvcSnwny8P/

**Comment by Arc676** [comment] 2018-05-24 09:52
Can't reproduce on Nexus 5 on build r397. Will update if updating device to r398 changes anything.

**Comment by Arc676** [comment] 2018-05-24 10:35
Updated to r398, can still open the same webpage.

What other applications do you have open at the same time? The logs appear to mention memory issues.

**Comment by Flohack74** [comment] 2018-05-24 17:44
This sounds like out of memory which happens frequently on non-mobile-websites in the browser.

**Comment by ernesst** [comment] 2018-05-25 00:13
But it does not happen on vivid...

**Comment by Flohack74** [comment] 2018-05-25 09:46
@ernesst Who said that xenial will not use more memory than vivid :)

**Comment by ernesst** [comment] 2018-05-25 20:36
Haha... I can reproduce the bug on my N4 Xenial.

**Comment by advocatux** [comment] 2018-05-26 10:32
Yeah, it looks like the browser runs out of memory. That website is like a long truck.

Tested on BQ E4.5 (Krillin) running Ubuntu 16.04 (r85).

**Comment by PhoenixLandPirate** [comment] 2018-05-28 19:01
This sometimes happens on imgur links but not always.

**Comment by ernesst** [comment] 2018-06-01 02:57
With browser next, I don't have issue on this website ... ;)

**Comment by Flohack74** [comment] 2018-06-02 20:12
The page works for me in latest xenial on FP2. Will later test N5.

**Comment by Flohack74** [comment] 2018-06-02 20:13
Ok confirmed on FP2. Just that it needs a few seconds longer to crash...

**Comment by abkro** [comment] 2018-06-04 18:40
Tested on Nexus 5 / hammerhead running Xenial r412 and on BQ E4.5 krillin running Xenial r88. The bug appears on both devices.
Looked fine at first, but after approximately 45 seconds to a minute the issue appeared on both devices. Choosing "reload page" momentarily redisplays the web page, but then the error message reappears just a few seconds later.

**Comment by abkro** [comment] 2018-06-10 09:00
I get the same error for this site: www.finn.no. I made a web app for it a short while back, but I have now switched it to not active in the Openstore because this happens and it's useless in this state.

When I access the site through the browser, it loads the main page and then crashes with the error message mentioned above when it's just about finished loading.

When I use the web app it loads the main page, after which a popup appears. Then the screen goes completely blank without any error message. The popup is something this site recently implemented. It's a message to the user about how their usage data/info are stored and used by the owner of the website.

**Comment by NeoTheThird** [comment] 2018-06-10 09:50
We won't fix this in OTA-4, since we will be moving off of oxide (our own packaged version of chrome) to QtWebEngine (from upstream). See #653. An experimental browser based on that can already be installed [from the OpenStore](https://uappexplorer.com/app/com.ubports.browserng), and the [QtWebEngine](https://wiki.qt.io/QtWebEngine) library can be used in apps on xenial.

For reference and to avoid duplicate reports, we'll leave this issue open with the `wontfix` label.

**Comment by mariogrip** [comment] 2018-06-10 13:19
Closing since we are tracking QtWebEngine impl here https://github.com/ubports/ubuntu-touch/issues/653

**Closed by mariogrip** 2018-06-10 13:19 UTC
Labels: bug, wontfix

**Comment by ernesst** [comment] 2018-09-24 16:31
A workaround : 
Delete everything except :  index and index-dir
in  /home/phablet/.local/share/webbrowser-app/Service Worker/ScriptCache/

Then the app seems to not crash anymore on the website. 

Thanks to FreeInside
