### ISSUE TITLE
Wifi drops

### ISSUE THREAD

**Issue by TexasGuy1988** [ubports/ubuntu-touch#1348] opened 2020-01-17 17:06 UTC
- Device: Nexus 5
- Channel:???
- Build:???

### Steps to reproduce

sign in to  secure wifi connection.  use phone

### Expected behavior

maintain connection until i physcially turn off wifi, or go out of range of my wifi

### Actual behavior

wifi drop randomly and I have to manually enter the list of available wifi connections and manually enter the password each time.

**Comment by UniversalSuperBox** [comment] 2020-02-11 19:15
Hi @TexasGuy1988,

Does this issue sound similar to your report? https://github.com/ubports/ubuntu-touch/issues/1018

**Comment by TexasGuy1988** [comment] 2020-02-12 14:09
It is exactly what happens to the T.  I also randomly lose 4g service in addition to WiFi.  They always come back monetarily, but it is rather irksome.



Respectfully,
Kevin Dickerson
-- 
Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
https://tutanota.com



Feb 11, 2020, 13:15 by notifications@github.com:

**Comment by UniversalSuperBox** [comment] 2020-02-12 14:45
Thanks for that report, @TexasGuy1988. If you don't mind, I'll close this issue as a duplicate of https://github.com/ubports/ubuntu-touch/issues/1018. That will help keep our issue tracker more focused and readable.

The 4G issue sounds separate, does that only occur when the device has been sleeping for a long time?

**Closed by UniversalSuperBox** 2020-02-12 14:45 UTC

**Comment by TexasGuy1988** [comment] 2020-02-12 16:50
I haven't noticed it while I was using it, only when I pick it up to use it.

Respectfully,
Kevin Dickerson
-- 
Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
https://tutanota.com



Feb 12, 2020, 08:45 by notifications@github.com:
