### ISSUE TITLE
Proximity sensor OPO

### ISSUE THREAD

**Issue by rocky58** [ubports/ubuntu-touch#426] opened 2018-01-11 13:26 UTC
- Device: Oneplus One
- Channel: RC
- Build: 20, 21

### Steps to reproduce

During a phone call screen don't become black and don't light at call end

### Expected behavior
During call when put my phone near my ear the screen must go off and at the end must go on

### Actual behavior
Screen remain always on

**Comment by NeoTheThird** [comment] 2018-01-11 14:19
Could you actually fill in the information, please?

**Comment by Flohack74** [comment] 2018-09-01 19:55
I am using OPO daily and cannot reproduce this.

**Comment by Xray1970** [comment] 2018-09-01 20:11
I have it on 2 devices with RC/DEVEL/SATBLE.
I reinstall Android on it again and test that out and then i dont have the problem, it's seems something wierd....

**Comment by tomoqv** [comment] 2018-09-04 08:36
This appears to be two different bugs:
@rocky58 The screen won't turn off by the proximity sensor
@Xray1970 The screen won't turn back on when proximity sensor is cleared
For me, on my Pro5, I have noticed that the proximity sensor is indeed very sensitive, which means it is difficult to access the top bar without turning the screen off. Otherwise, the only similar problem I have encountered is when answering a phone call when the screen is off and locked, it takes a while after the call ends until I get the unlock screen to show up.

**Comment by Flohack74** [comment] 2018-11-16 20:00
Ok I can reproduce it now, sad but true. I will take a look into this more closely, seems the proximity does not work at all...

**Comment by Xray1970** [comment] 2018-11-16 20:06
Oh ok thanks!

**Comment by Flohack74** [comment] 2019-05-23 09:11
Proximity works sometimes, the sensor HAL seems to be OK, just that we dont recognize FAR state and think its NEAR already when the call starts...

**Comment by Flohack74** [comment] 2019-05-23 09:12
Actually its a duplicate of #118

**Closed by Flohack74** 2019-05-23 09:12 UTC
Labels: bug, device: bacon
