### ISSUE TITLE
Ueventd-as-a-udevtrigger causes long boot on OP3T

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#1396] opened 2020-03-12 04:13 UTC
- Device:OP3T
- Channel:EDGE

### Steps to reproduce
Flash op3t with halium base and install https://forums.ubports.com/topic/3257/how-to-test-gstreamer-droid-based-camera-support-in-ubuntu-touch-for-halium-7-1-based-port
It updates the system via APT

### Expected behavior
Boot right away

### Actual behavior
Waiting 2 minutes to boot

### Logfiles and additional information

https://paste.ubuntu.com/p/2p4nznJNcb/

Issue seems to be around 1626

**Comment by ernesst** [comment] 2020-03-13 04:17
Not relevant, as now `UPDATED: This is no longer required. The correct fix is now in the GStreamer.`

**Comment by ernesst** [comment] 2020-03-14 04:07
Even without halium based not modified and the installation as per https://forums.ubports.com/topic/3257/how-to-test-gstreamer-droid-based-camera-support-in-ubuntu-touch-for-halium-7-1-based-port the boot takes 2 min.

**Comment by peat-psuwit** [comment] 2020-06-24 18:30
Root cause determined to be outside of 
Ueventd-as-a-udevtrigger change. Closing.

**Closed by peat-psuwit** 2020-06-24 18:30 UTC
