### ISSUE TITLE
Alarm not ringing

### ISSUE THREAD

**Issue by nomoreAndroid** [ubports/ubuntu-touch#982] opened 2018-12-03 20:00 UTC
- Device: Nexus 5
- Channel: RC
- Build: 2018-W48

Alarm clock was flawlessly working until 2018-W46.

### Steps to reproduce
Set up alarm: 
- every weekday, 7:10
- custom name
- sound: Alarm clock (default)

Second alarm is also set (once 6:45), but not active.

Alarm sound is very low, vibration on.

Phone is on current, clock app was opened in the evening, screen turned off.

### Expected behavior
Alarm should vibrate and ring very silently.

### Actual behavior
No vibration, no sound. Some minutes later it indicates that the alarm was missed. 

### Logfiles and additional information

[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2641036/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2641037/UTlogcat.txt)

**Comment by UniversalSuperBox** [comment] 2018-12-05 17:50
I've heard @wayneoutthere report a similar problem that was fixed after removing and re-adding the alarm. On the forum, @nomoreAndroid reports that their alarms work after removing and re-adding them.

To test if this was a problem with an upgrade, I did the following:
1. Flash Ubuntu Touch OTA-5 on my Nexus 5 with a wipe
1. Set two alarms: one in two minutes, one in fifteen minutes which repeats daily
1. Wait for the alarm in two minutes to ring. This confirms alarm functionality.
1. Flash RC 2018/W48 - The OTA-6 release candidate
1. Wait for the other alarm to ring

I tried this on my FP2 as well.

Both alarms rang in both cases, so it does not seem that this issue is caused by a change which has been introduced in the OTA-6 cycle (or the change was reverted, or fixed during the cycle).

I'll mark this as "Needs confirmation" for now.

**Comment by wayneoutthere** [comment] 2018-12-05 19:15
that sounds about right.  It seems that whenever I have an alarm issue, it follows an OTA.  It was not the first time.  Happened on the release before the last one.

**Comment by balcy** [comment] 2018-12-06 07:10
ok today the alarm worked correctly  (no software change)

**Comment by nomoreAndroid** [comment] 2018-12-09 19:40
After erasing the existing alarms and creating new ones they work again. (tested for 3 days).
So somehow the settings were ignored. 
The indicator on the lock screen does just recognize the first alarm, repeating alarms on weekdays are ignored.
Maybe this should be changed.

**Comment by Flohack74** [comment] 2019-01-06 00:10
So can we close this one? Regarding the repeating alarms display, plz file a new issue.

**Comment by UniversalSuperBox** [comment] 2019-01-14 17:41
I believe this can be closed.

**Closed by UniversalSuperBox** 2019-01-14 17:41 UTC
Labels: needs confirmation
