### ISSUE TITLE
Random Unity 8 crashes while using ubuntu touch

### ISSUE THREAD

**Issue by Rom4nB** [ubports/ubuntu-touch#1011] opened 2018-12-30 14:41 UTC
### Illustrations

- Device: Fairphone 2
- Channel: Stable
- Build: OTA-6

### Steps to reproduce
Use the device: browse around web, write E-Mail in Dekko, write SMS, chat in Telegram (Telegram or Telegram Plus).

### Expected behavior
Device should just work fine.

### Actual behavior
There are random Unity 8 crashes occurring. Unity will crash and reload immediately (Ubuntu sign with moving dots). Usually the phone can be used normally again as soon as Unity 8 restarted. Sometimes, there are multiple crashes in a row.
I have the impression that the crash often happens when I'm typing (e.g. writing an SMS or Telegram message).

### Logfiles and additional information
I checked with 'Logviewer' app some logs, e.g. from unity8.log but didn't find any hints. When you have a suggestion which logs to check, please let me know.
I already had this issue with OTA-5. The random reboots on the FP2 were heavily decreased with OTA-5, but since then I notice these quite frequent Unity 8 crashes.
I don't remember this when I still had a BQ E4.5 in 2015-2017 with Canonical/early 15.04 ubports Ubuntu Touch.

**Comment by luksus42** [comment] 2019-01-04 14:05
I can confirm that.
But for me the reboots happen more often than the unity crashs.

**Comment by giiba** [comment] 2019-04-13 23:18
I was having the same trouble. Unity would randomly crash (though often when navigating with a map app) multiple times a day and most threads about this issue on a hammerhead device blame the power button issue (hardware fault). However, I could reliably turn the screen on/off while Unity was rebooting so it isn't hardware issue.

Then I noticed that there is only 32mb of swap space constantly full...

So I created a second swap file (1Gb for testing), activated it, thrash tested by opening all the apps, and no crash. Now I'm going on 3 days without a crash, when before I thought there was a bug with the location service or something. Turns out my peak swap usage is while using uNav for turn-by-turn (600'ish mb), and this was when a crash was most likely.

Is there a reason there is so little swap space by default? Or is this making some other memory management bug?

Hammerhead on 16.04 (2019-w15)

**Comment by dobey** [comment] 2019-04-14 11:24
> Is there a reason there is so little swap space by default?

Swap is not used because it is bad for flash. Instead, zram (compressed RAM) is used. It sounds like perhaps uNav could use some optimization work, and OOM killer settings need some adjustment, as it should generally avoid killing the shell. Perhaps also for some reason the zram is not getting activated on your device.

**Comment by giiba** [comment] 2019-04-14 16:14
To preface, I am not an expert 😉

I see no evidence of a zram anywhere; I assume 'swapon -s' or 'free' in terminal should show it?

I wouldn't blame uNav, as the Unity restart certainly happened at other times and with other apps.

Since adding the second swap I also find multi-tasking is far better, with the browser maintaining a couple pages instead of needing to reload them should I switch to another app and back. For now I'm sticking with the setup because it is a distinct improvement over the default, sdcard be damned as this is a 6 year old phone anyways.

**Comment by Flohack74** [comment] 2019-04-16 20:54
We know that unity8 is crashing a lot, especially with devices below 2G RAM. But there are so many possible reasons, and we are far from being able to optimize unity8 and fix all memleaks. Please excuse the dust.
I will close this ticket here as it does not add new information, and also has no reproducible scenario attached.
Please turn off your 2nd swapfile again or your flash will get corrupted and your phone will be then a wonderful doorstop.
BR Florian

**Closed by Flohack74** 2019-04-16 20:54 UTC
Labels: needs confirmation
