### ISSUE TITLE
Device wont sleep

### ISSUE THREAD

**Issue by ghost** [ubports/ubuntu-touch#113] opened 2017-06-14 23:17 UTC
Device wont sleep, maybe a repowerd issue.

**Comment by rubencarneiro** [comment] 2017-06-14 23:22
Ok fixed by doing:
sudo chmod +x /usr/sbin/repowerd

**Comment by Flohack74** [comment] 2017-06-15 07:32
Sleep: you mean if display is turned off? I saw around 1.7% of CPU when connected with ADB and looking at top. Seems normal to me

**Comment by ChloeWolfieGirl** [comment] 2017-07-22 21:06
Have you considered telling it a bed time story? Or getting into a sleep time routine?

**Comment by ChloeWolfieGirl** [comment] 2017-07-22 21:06
I didnt mean to do that, sorry

**Comment by mariogrip** [comment] 2017-08-02 23:29
I cannot reproduce this? is this still an issue?

**Comment by userj** [comment] 2018-09-25 01:38
I had this happen just today. Although I don't know to to reproduce this. This is what happened:
1. Connected devices to car bluetooth
2. Tried to make a call (which failed because of bluetooth issues).
3. Made another call and failed
4. Device screen remained on and would not sleep until I pressed power button.

I think this happened another time regarding a missed or failed call. This caused the battery to drain completely.

**Comment by talmai** [comment] 2020-05-18 03:37
I have not been able to reproduce this. CPU usage was greater than the 1.7% reported by @Flohack74, but I definitively saw a CPU usage drop. Spiked when background activities were ran (dekkod, etc), but dropped again after they completed. I suggest we close this ticket.

**Comment by Flohack74** [comment] 2020-07-28 21:37
Closed.

**Closed by Flohack74** 2020-07-28 21:37 UTC
Labels: bug, device: hammerhead
