### ISSUE TITLE
Ubuntu Touch camera issues on OnePlus One; inward camera zoom delay.

### ISSUE THREAD

**Issue by nerd7473** [ubports/ubuntu-touch#891] opened 2018-09-26 21:01 UTC
### Illustrations

- Device: OnePlus One
- Channel: 16.04 Testing
- Build: 2018-w40

### Steps to reproduce

Zooming in and out in camera, works somewhat in "selfie" mode with a roughly 5 second delay. Outward camera still has no zoom (despite waiting about 15 seconds) on the latest update of Testing.

### Expected behavior

To zoom in real time.

### Actual behavior

Zoom on outward camera is nonexistent, and zoom on "selfie" or inward camera is working but with a delay of several seconds.

### Logfiles and additional information

http://paste.ubuntu.com/p/94ccYn77Vj
http://paste.ubuntu.com/p/tSX9Pw6nNN/

**Comment by UniversalSuperBox** [comment] 2018-12-16 01:39
Duplicate of #355

**Closed by UniversalSuperBox** 2018-12-16 01:39 UTC
Labels: duplicate
