### ISSUE TITLE
[xenial] Default browser does not render some pages

### ISSUE THREAD

**Issue by tatonuta** [ubports/ubuntu-touch#749] opened 2018-07-07 12:01 UTC
- Device: Krillin - Bq Aquaris E4.5
- Channel: 16.04 RC
- Build: 2018-W27

### Steps to reproduce
Open default browser and go to http://theguardian.com

### Expected behavior
The webpage of The Guardian should appear in the browser. 

### Actual behavior
The webpage starts to load and just at the end of loading it turns into an error message page:

> The rendering process has been closed for this tab. Something went wrong while displaying https://www.theguardian.com/international.

![screenshot20180703_134953086](https://user-images.githubusercontent.com/40709402/42410649-49d2d136-81ed-11e8-9fb3-c35de319c117.png)

The same problem occures with a number of other pages, including e.g. Google Maps (https://www.google.com/maps). 

What's more important, it seems that this problem influences webapps - many of them (but not all) are show only a blank screen (white screen) instead of the contents.

**Comment by ruedigerkupper** [comment] 2018-07-07 12:53
Duplicate of #626 and #734.

**Closed** 2018-07-07 17:46 UTC
Labels: duplicate
