### ISSUE TITLE
Extend the login pin length

### ISSUE THREAD

**Issue by aparatext** [ubports/ubuntu-touch#1983] opened 2022-05-07 21:50 UTC
4 digit pins are way too easy to brute-force, even by a person. While the rate limit already makes pin codes relatively secure, extending the pin length to 6 or 8 digits could be a simple way to make it better.

**Comment by aparatext** [comment] 2022-05-08 10:20
You can customize pin length by changing `pinHint.text`, if statement in `onDisplayTextChanged`, and `passwordInput.validator.regExp` in `/usr/share/unity8/Greeter/PinPrompt.qml`. And of course change your password through `passwd`.

**Comment by lduboeuf** [comment] 2022-06-04 13:48
duplicate of https://github.com/ubports/ubuntu-touch/issues/1027

**Closed as completed by lduboeuf** 2022-06-04 13:48 UTC
