### ISSUE TITLE
Something drains the battery

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1785] opened 2021-07-27 05:19 UTC
- Device: Xperia X, Meizu MX4
- Channel: stable
- Build: OTA17/18

### Steps to reproduce
I have no definite way to replicate it.

### Expected behavior
Battery drains normally

### Actual behavior
Occasionally, the device stays warm even when not in use and locked. In this state, the battery drains considerably faster than usual.

### Logfiles and additional information
This has happened on my Xperia X a few times and I use this daily for usual stuffs like TELEports, browsing, SMS, calls, etc. It now also happened on my MX4 once which has no sim,stays offline, very minimal use and only used for a specific app. However I used it for some tasks before it happened. I went online with it and used TELEports, browser, terminal, openstore, pesbuk...that's all I remember 😅 I will try to observe it more when it happens again and update this.

**Comment by UniversalSuperBox** [comment] 2021-07-28 01:05
Duplicate of https://github.com/ubports/ubuntu-touch/issues/1779

**Closed by UniversalSuperBox** 2021-07-28 01:05 UTC
