### ISSUE TITLE
notif leds no longer blinking when there are notifications

### ISSUE THREAD

**Issue by Fuseteam** [ubports/ubuntu-touch#1651] opened 2021-01-22 21:33 UTC
- Device: BQ E5
- Channel: Devel
- Build: 2021-01-22

### Steps to reproduce

trigger and notification by sending an SMS to oneself, or enabling teleports notifications
### Expected behavior

when the screen is off the led will blink green when there are unread notifications

### Actual behavior

the led does not turn on at all when there are notifications

### Logfiles and additional information

when the battery is low the does blink(orange)
when plugged in to charge the led does turn on (white)
when fully charged the led is on as well(green)

**Comment by Danfro** [comment] 2021-01-22 21:36
Confirmed on E5 with devel later than 2021-01-22 (with Qt5.12 state).

Not confirmed with Xperia X devel 2021-01-18 (before Qt5.12 state)

**Comment by Fuseteam** [comment] 2021-01-22 21:51
wait does the led work on xperia before qt5.12?

**Comment by Danfro** [comment] 2021-01-22 22:01
Yes. It still does. I am not updating that currently. Still on working "old" devel.

**Comment by Danfro** [comment] 2021-01-22 22:02
Not sure if the Qt5.12 change is to blame. Can we revert our E5 back to pre-Qt5.12 devel to test?

**Comment by wdehoog** [comment] 2021-01-23 15:12
In [IndicatorsLight.qml](https://github.com/ubports/unity8/blob/ac69b162683ecd80d4bcfe877d4444797f1f6930/qml/Panel/Indicators/IndicatorsLight.qml#L191) onHasMessagesChanged does not seem to be triggered anymore.

dbus-monitor shows the event happens, logging extra shows the info reaches the object. I added:
```
       onIconsChanged: {
            console.log("onIconsChanged: " + String(icons))
            console.log("         valid: " + valid)
            var idx = String(icons).indexOf("indicator-messages-new")
            console.log("           idx: " + idx)
            var hasMessages = valid && (String(icons).indexOf("indicator-messages-new") != -1)
            console.log("   hasMessages: " + hasMessages)
        }
``` 
results in:
```
[2021-01-23:16:05:41.274] qml: onIconsChanged: image://theme/indicator-messages-new-offline,indicator-messages-new,indicator-messages,indicator
[2021-01-23:16:05:41.274] qml:          valid: true
[2021-01-23:16:05:41.275] qml:            idx: 14
[2021-01-23:16:05:41.275] qml:    hasMessages: true
```

**Comment by wdehoog** [comment] 2021-01-23 15:38
With this added it works again
```
        onIconsChanged: {
            var idx = String(icons).indexOf("indicator-messages-new")
            hasMessages = valid && idx != -1
            console.log("onIconsChanged: " + String(icons))
            console.log("         valid: " + valid)
            console.log("           idx: " + idx)
            console.log("   hasMessages: " + hasMessages)
        }
```

But why is the original binding not working anymore?

**Comment by wdehoog** [comment] 2021-01-23 15:56
Or maybe a bit cleaner:
```
    property var _rootState: Indicators.ActionRootState {
        actionGroup: _actionGroup
        actionName: "messages"
        Component.onCompleted: actionGroup.start()
        onIconsChanged: {
            root.hasMessages = valid && String(icons).indexOf("indicator-messages-new") > -1
            updateLightState("onHasMessagesChanged")
        }
    }
```

Btw this problem should have make IndicatorsLight fail the tests. Why didn't it?

**Comment by j2g2rp** [comment] 2021-01-23 20:30
I just can confirm that I'm experiencing the same regression on Nexus 5 and M10FHD on the  latest devel updates.

**Comment by FlavioMala** [comment] 2021-01-25 09:47
The same (BQ E5)

**Comment by just-carlod** [comment] 2021-01-25 12:24
Same on Xiaomi mi a2, however notification led is blinking when device has low battery level, so I guess it's not hal problem

**Comment by dobey** [comment] 2021-01-25 19:46
The issue is not device specific. You don't need to keep adding comments that it's not working on XX devices. Thanks. :)

**Comment by Danfro** [comment] 2021-01-25 19:49
@dobey But then why does the led still work on Xperia X devel?

**Comment by dobey** [comment] 2021-01-25 22:58
> @dobey But then why does the led still work on Xperia X devel?

If it blinks when battery is low, that is separate code. If it's blinking for regular notifications that stick in the messaging menu, then I don't know what to tell you. I guess it means you're lucky.

**Comment by Fuseteam** [comment] 2021-01-26 12:20
sorry I asked them to add their comment because some reported it working on some devices at first

**Comment by dobey** [comment] 2021-01-26 21:12
Fixed by ubports/unity8#359

**Closed by dobey** 2021-01-26 21:12 UTC
Labels: critical (devel)

**Comment by dadandalive** [comment] 2021-03-11 21:29
I confirm, on Nexus 5, RC 2021-W10, the notification LED blinks after receiving SMS and switching off screen.

**Comment by Fuseteam** [comment] 2021-03-12 14:49
also confirmed it is working on the e5 and nexus5 latest devel
