### ISSUE TITLE
 displaced screen 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#27] opened 2017-05-27 16:44 UTC
Top 'has wandered' to the end (attachement). After shutting on/off screen via power button it's back to normal.
Btw. screenshot picture showed the screen properly, had to do some 'gimping' to reconstruct the scenario.

https://bugs.launchpad.net/ubports-n5/+bug/1692268/+attachment/4880458/+files/screenshot19700309_035036627.jpeg

I've already flashed the phone with Lineage OS to see if it's a hardware failure. Everything's working fine under Android.
And yes, I had flashed the device twice with ubuntu.

reported by https://launchpad.net/~f4tmike

**Comment by Flohack74** [comment] 2017-05-29 13:05
Cobfirmed. Got this on every boot. After unity comes up part of the top screen is on the bottom.

**Comment by Flohack74** [comment] 2017-06-03 20:44
BTW Turning the device off & on again helps to get the screen right.

**Comment by Flohack74** [comment] 2017-06-20 18:33
![photo_2017-06-20_20-32-52](https://user-images.githubusercontent.com/16186470/27349478-aef72d78-55f7-11e7-8d0c-782536c8da22.jpg)
Some illustration :)

**Comment by iambumblehead** [comment] 2017-07-07 20:53
I installed Ubports on three nexus 5 devices in the last two weeks --all of them had this issue :)

**Comment by Flohack74** [comment] 2017-07-07 21:02
@rubencarneiro @APokorny any ideas what this can be?

**Comment by rubencarneiro** [comment] 2017-07-07 21:16
Does it have screen tearing when moving betheen apps etc?

**Comment by Flohack74** [comment] 2017-07-07 21:59
No, no screen tearing, its totally perfect. After the first switch off - switch on the screen is OK.

**Comment by NeoTheThird** [comment] 2017-07-19 12:34
@iambumblehead @Flohack74 Have you considered the possibility that your phones suffer from an evil curse? Mine doesn't have this...

**Comment by usoltau** [comment] 2017-08-12 15:42
![image20170812_171821483](https://user-images.githubusercontent.com/28947310/29242020-77cd1dd2-7f85-11e7-8967-2e82ccb46612.jpg)
I am cursed too, happens as mentioned most of the time but not always

**Comment by mariogrip** [comment] 2017-08-12 16:18
I cannot seem to reproduce this issue. can someone send me some logs when this happens.

I need logcat
`/system/bin/logcat`
and syslog
`/var/log/syslog`

**Comment by usoltau** [comment] 2017-08-12 16:46
[syslog.txt](https://github.com/ubports/ubports-touch/files/1219919/syslog.txt)
I had to renome it to a txt file because without ending git wouldn't let me upload it

**Comment by NeoTheThird** [comment] 2017-08-13 21:04
@usoltau Logcat is a program that produces logs, you can start it by calling `/system/bin/logcat` and provide its output. You can find more info [here](https://wiki.ubports.com/wiki/Writing-a-Good-Bug-Report).

**Comment by APokorny** [comment] 2017-08-14 14:01
Issues like those are usually an error in the timing setup of the scan out hardware. Turning the screen off and on again, resets that and the problem disappears.

**Comment by Flohack74** [comment] 2017-08-15 10:26
I am checking here with Marius. It seems there are different hardware version. Can you please turn over your device and look for a number together with if it is affected or not.

**D821 is affected**

Thats mine.

BR

**Comment by iambumblehead** [comment] 2017-08-16 05:09
dmesg and logcat from **LG-D821** taken while the screen is displaced

[UTdmesg.txt](https://github.com/ubports/ubports-touch/files/1227113/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubports-touch/files/1227112/UTlogcat.txt)

**Comment by usoltau** [comment] 2017-08-16 18:16
mine is a D821 too, maybe note, it is the 32 GB one.

**Comment by NeoTheThird** [comment] 2017-10-06 18:29
Sorry guys, lost track of this thread for a while. Mine is LG-D821 as well, and to this date i have not experienced this issue. So whatever this is, it's not connected to the model number...

**Comment by abkro** [comment] 2018-04-21 09:31
I just purchased a Nexus 5, flashed it with IT OTA-3 3 days ago and I have experienced this issue twice out of approximately 6-8 reboots to date.

**Comment by abkro** [comment] 2018-04-21 09:32
Should have been "UT OTA-3" in previous comment.

**Comment by abkro** [comment] 2018-04-21 16:28
Today, I triedtimes bootingbooting and got this issue 5 timesissue in a row. Finally, I chose to reset the device (not the complete factory reset option but the first one). That did the trick. Hope this helps to narrow it down!

**Comment by abkro** [comment] 2018-04-21 16:31
Previous comment written on my Nexus 5. The typos weren't there before I hit the comment button. :(

**Comment by abkro** [comment] 2018-06-02 09:10
The issue is still present in Xenial r408 on hammerhead.

**Comment by Flohack74** [comment] 2018-06-10 19:32
Please do not make repetitive negative testing confirmations. If it is "present in rXYZ" then we consider it broken from thereon. Only if the status changes you may report it here. We get hundreds of notifications otherwise saying that it is still present ;)

**Comment by abkro** [comment] 2018-06-10 19:34
@Flohack74 Sorry, wasn't aware of this. But got it now. Makes things a lot simpler. :)

**Comment by gbdomubpkm** [comment] 2019-08-10 19:24
OTA-9. This bug is still there for me.

**Comment by Flohack74** [comment] 2019-08-30 10:38
@gbdomubpkm did you read my message on June 10th above? Obviously not.... :(

**Comment by gbdomubpkm** [comment] 2019-10-05 00:29
Something new :  I reflashed a UT Nexus 5 with the last androïd factory image 6.0.1 (M4B30Z dec 2016), then reflashed UT by following. I have since restarted at least 10 times my phone and no sign of this bug! Passed out!

**Comment by Flohack74** [comment] 2019-10-16 18:05
Ok I will try to do this, can we find out which part of the firmware changed? Then users dont need to go back to Android but just can flash the firmware upgrade. Can you provide me a link for download?

**Comment by gbdomubpkm** [comment] 2019-10-16 19:21
https://dl.google.com/dl/android/aosp/hammerhead-m4b30z-factory-625c027b.zip

I can confirm zero reappearances of the bug.
I can also say that my nexus 5 has a lot less overheating.

What i did:
   - extraction of the file
   - connection of the tel to the comp and adb reboot bootloader
   - in the directory containing the extracted files, i run the script   ./flash-all.sh
   - i let the installation run until the end ; several minutes for having installed android 6.0.1
   - i reflashed UT with the installer

**Comment by abkro** [comment] 2019-10-19 07:44
I also tried reflashing with the newest Android and then reinstalling UT. It's been roughly a week, but I have had no reappearances of the displaced screen either.

**Comment by Flohack74** [comment] 2019-10-29 22:32
So Android 6.0.1 is the latest available? I will try to extract firmware then from there ^^

**Comment by Flohack74** [comment] 2020-01-04 00:06
I am closing this, since we have a fix for this now. Also, seems with the Halium 7.1 port that we are currently developing this will also be adressed.

**Closed by Flohack74** 2020-01-04 00:06 UTC
Labels: bug, device: hammerhead
