### ISSUE TITLE
[xenial] Terminal keyboard can't be summoned after unlocking

### ISSUE THREAD

**Issue by Arc676** [ubports/ubuntu-touch#595] opened 2018-05-13 06:18 UTC
- Device: Nexus 5 hammerhead
- Channel: 16.04 devel
- Build: r367

### Steps to reproduce
Open the Terminal app. Lock the device. Unlock the device. Try to summon the OSK with the button.

### Expected behavior
Keyboard appears. 

### Actual behavior
Keyboard doesn’t appear, regardless of how many times the button is tapped. 

### Logfiles and additional information
Sometimes summoning the launcher by swiping from the left edge or creating a new terminal window solves the problem, but this doesn’t seem to work 100% of the time.

**Comment by Arc676** [comment] 2018-05-13 09:36
Still happens on r377.

**Comment by fourloop2002** [comment] 2018-05-17 12:30
Happens on my Hammerhead Xenial (r383).  Reproduced as follows: Lock the screen with the keyboard active (displayed), apps tested Telegram (sending a message), System Settings (Switch to passphrase) and Openstore (search).  Unlock the screen screen frozen, reboot required to restart.  The underlying OS is still running as I can connect (adb shell, clickable shell) and run top, etc.

**Comment by fourloop2002** [comment] 2018-05-17 12:37
I can retrieve log files if some one could identify which ones may show relevant information

**Comment by fourloop2002** [comment] 2018-05-18 13:48
Updated to r387 based on #606 and tested.  On Openstore webapp>Search keyboard appears, lock screen, unlock screen.  Keyboard gone but does reappear after a few taps.  Same thing happens on System Settings test.  On Telegram test the keyboard does not appear at all - doh.

**Comment by Arc676** [comment] 2018-09-02 07:52
Update: I know the issue was opened indicating the `devel` channel, but I'd like to note that this still happens after updating to OTA-4 on `stable` (congrats btw).

Something I didn't notice the last time: it appears that this issue only occurs if the keyboard was visible *before* locking. If I dismiss the OSK before locking the device, then unlock and summon it again, it does appear.

Perhaps it's caused by something about keyboard state? It appears that summoning the OSK fails when the keyboard was previously visible. The workarounds I mentioned in my original post are all cases in which the OSK would be dismissed.

**Comment by giiba** [comment] 2019-04-13 20:55
I've been having this issue. As a new user I wound up here and after some quick testing the keyboard visibility sure seems to be the problem.

I'm having trouble in the messaging app too and couldn't figure out why I didn't have this trouble for the first few days using UT. Then I remembered that's about when I first set a screen lock code.

Sure enough setting a passcode seems to trigger this bug. So...

with PasscodeSet:
- keyboard visible on locking = problems
- keyboard hiddenbefore locking = keyboard fine

remove PassCode:
- no problems regardless of visibility

**Comment by Danfro** [comment] 2019-06-01 20:09
Using E5 on release channel (16.04 2019-W22)

I had this issue too. Now I can not reproduce it any more. It seems to be fixed with one of the last updates. 

Can anyone confirm that this is solved or if this issue does still remain?

**Comment by Arc676** [comment] 2019-06-01 21:52
Updated to `2019-06-01/2` on Hammerhead on `devel` channel. Can confirm that locking the device while the OSK is visible in Terminal still prevents the keyboard from being summoned upon unlocking. Tapping the "change tab" button and reselecting the same terminal still works as a workaround; the OSK can be summoned when the terminal regains focus.

**Comment by mariogrip** [comment] 2019-06-29 13:55
Fixed on edge: https://github.com/ubports/unity8/pull/156

**Closed by mariogrip** 2019-06-29 13:55 UTC
Labels: bug
