### ISSUE TITLE
Screen doesn't wake on power button, but does after screen touched

### ISSUE THREAD

**Issue by userj** [ubports/ubuntu-touch#305] opened 2017-10-21 16:05 UTC
- Device: Bacon
- Channel: 15.04/devel
- Build: r185

## Steps to reproduce

1. Lock device / wait for screen to timeout and go black
2. Press Power button to wake
3. Touch Screen

## Expected behavoir
- Screen should wake on power button press
OR
- Screen wake on double tap of screen (I know this is not implemented...yet?)
...

## Actual behavior
- Screen stays blank/black after power button press
- BUT Screen wakes up when screen touched after power button has been pressed
...

## Logfiles and additional information

[EDIT]
Related: https://github.com/ubports/ubuntu-touch/issues/65
Seems to be only if autobrightness is enabled. The screen is not actually black but VERY dark when power button is pressed.
...

**Comment by startcloud** [comment] 2017-10-23 20:15
Issue reproduced on Nexus 5 
First I can confirm that this issue happens only if Adjust brightness automatically is selected.
It gives the impressions to be a random issue some more tests:
- After a fresh reboot, issue is not reproduced, on/off button is able to wake up the screen 
- Wait until the screen turn off automatically and wait for a while then the issue is reproduced 
- With a fast off/on of the screen the issue is not reproduced 
- After few seconds the issue is reproduced again

**Comment by juanx0** [comment] 2017-11-03 10:05
Yes, Nexus 5 here. For me it works sometimes (with brightness automatically). Then after three o four times, you have to touch/swipe to wake up the screen, like if it's working but screen is not on untill you touch it.

**Comment by Flohack74** [comment] 2017-11-06 22:55
I cant reproduce on OPO but on N5 its now standard behaviour ;)

**Comment by UKPhil** [comment] 2017-11-08 21:03
The other night I did an update and since then I have not had any isues. I did set my phone up to receive rc updates but it still says r2. So I am not sure what release I have, but I know it is working g fine now.

**Comment by UKPhil** [comment] 2017-11-08 21:04
Suggest that is it cannot be reproduced we look at putting this on hold as there is a workaround for the one use affected.

**Comment by stekalb** [comment] 2017-12-17 21:13
I also have this behaviour on OPO (r17). It just appears when auto brightness is activated.

**Comment by mariogrip** [comment] 2017-12-17 21:44
Sorry for the close, but it did it automaticly

**Comment by Flohack74** [comment] 2017-12-17 22:21
Isn´t that a dupe of https://github.com/ubports/ubuntu-touch/issues/65 - By the way, I still cannot reproduce this on OPO

**Comment by Flohack74** [comment] 2017-12-18 22:18
@userj can you please try the latest devel if the problem persists?

**Comment by NeoTheThird** [comment] 2017-12-18 23:35
There's already #65 for hammerhead.

**Comment by Flohack74** [comment] 2017-12-19 08:21
If we do not get a confirmation for this bug on OPO I will close latest tomorrow

**Comment by NeoTheThird** [comment] 2017-12-19 09:29
Fixed.

**Closed by NeoTheThird** 2017-12-19 09:29 UTC
Labels: device: bacon

**Comment by Flohack74** [comment] 2017-12-19 12:38
I would have resolved it with duplicate but ok ^^

**Comment by NeoTheThird** [comment] 2017-12-19 22:02
^^ don't rob me of the archievement
