### ISSUE TITLE
[feature request] incoming call blocklist

### ISSUE THREAD

**Issue by Niubbo** [ubports/ubuntu-touch#1294] opened 2019-11-21 09:18 UTC
I think adding this feature should be a priority after years of development, this will allow to block robocalls stalkers and unknown numbers, will make the experience with our phones really good.

I whould like to have the options to block with separate toggle:
unknown numbers
well defined number
numbers with wildcards, i.e. if i set up +44* all call/sms coming from england will be blocked
contact whitelist, able to receive calling/sms from contact only

these toggle whould filter call and sms

**Comment by UniversalSuperBox** [comment] 2019-11-22 01:57
I believe this is a duplicate of https://github.com/ubports/ubuntu-touch/issues/1294, do you agree?

**Comment by mateosalta** [comment] 2019-11-22 05:27
reminder that it seems our friends over here have done some work with ofono - I think to implement this https://git.merproject.org/mer-core/ofono/commit/fa8002200c5a5e3fab5f0d6214eb2fe87cdd5649

**Comment by Flohack74** [comment] 2019-11-22 08:41
@UniversalSuperBox did you mean #738 ? And yes, its a duplicate...

**Closed by Flohack74** 2019-11-22 08:41 UTC
Labels: duplicate

**Comment by mateosalta** [comment] 2019-11-24 00:24
well, ignore via ring, and block at system level... similar - I would prefer block at system level
