### ISSUE TITLE
Button colors when switching display language are not consistent with the design guideline

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1247] opened 2019-10-07 16:19 UTC
### Steps to reproduce
1. Open system settings app
2. Go to Language & Text > Display language
3. Select a language.

### Expected behavior
The buttons should conform with the design guideline.

### Actual behavior
All buttons are gray.

**Comment by UniversalSuperBox** [comment] 2019-10-14 19:11
The entire menu is still made with the Components 1.2 design, it seems.

**Comment by mateosalta** [comment] 2019-11-28 18:35
updated in https://github.com/ubports/system-settings/pull/182#event-2830133223

**Comment by UniversalSuperBox** [comment] 2019-11-30 02:11
Closed by https://github.com/ubports/system-settings/pull/182

**Closed by UniversalSuperBox** 2019-11-30 02:11 UTC
Labels: enhancement, team: ui

**Comment by Danfro** [comment] 2020-03-16 21:40
E5 RC.

Which buttons do we refer to? The ones on the screen where I pick the language? Those are still both grey.

Or the ones for confirming reboot to apply the new language? There "cancel" is grey, "reboot now" is red.

![screenshot20200316_223744439](https://user-images.githubusercontent.com/37637312/76801989-ffc53d00-67d6-11ea-843b-3e710d88c268.png)
![screenshot20200316_223753389](https://user-images.githubusercontent.com/37637312/76801991-00f66a00-67d7-11ea-8565-93f5e4b6cadf.png)

**Comment by mateosalta** [comment] 2020-03-17 13:02
@Danfro the whole page was light grey before
the dark grey buttons do now need to be fixed for the new theme though

**Comment by cibersheep** [comment] 2020-03-17 21:18
Update works correctly on N5 RC

**Comment by Bolly** [comment] 2020-03-19 16:26
Just like in @Danfro's pictures. 
BQM10FHD RC

**Comment by Flohack74** [comment] 2020-03-21 08:22
So @cibersheep the 2 select buttons will stay grey? This is intended behaviour?

**Comment by cibersheep** [comment] 2020-03-22 12:01
> So @cibersheep the 2 select buttons will stay grey? This is intended behaviour?

The idea would be using header back to cancel and tick to apply as the rest of the system. Mateo was working on that. So, I think it's ok for now. Let's go step by step

**Comment by Danfro** [comment] 2020-03-22 16:42
Hm. But isn't in most places "confirm" a green button? So shouldn't the button on the language pick page not be green as well?

**Comment by cibersheep** [comment] 2020-03-22 18:47
Yes

**Comment by mateosalta** [comment] 2020-03-23 13:00
confirm in this case might not be a positive action, but yes the plan is to remove those buttons

**Comment by Flohack74** [comment] 2020-03-23 23:16
Ok then I move this to Done, but please keep track of the next steps ^^

**Comment by mateosalta** [comment] 2020-05-31 15:46
ok, I have completed the task: https://github.com/ubports/system-settings/pull/234
