### ISSUE TITLE
No bluetooth (car) audio output after reconnecting if pair already exists without phone reboot.

### ISSUE THREAD

**Issue by ghost** [ubports/ubuntu-touch#994] opened 2018-12-07 20:12 UTC
- Device: bacon
- Channel: stable
- Build: OTA-5

### Steps to reproduce
Pair phone with car audio system via bluetooth OR enter car with existing pairing if the phone has been rebooted since the last time I was in the car. Car outputs audio (from PodBird) as expected. 
Turn off and exit car. 
Later when reentering car, car audio system automatically establishes connection with phone. 
Car indicates that the phone has established a connection and displays podcast info, and phone has "Bluetooth speaker" pop-up.
Audio outputs through the phone speakers.

Deleting the pairing, and reestablishing pair in any order has no effect.

To get audio to output via bluetooth again, a phone reboot is required.

### Expected behavior
Phone should automatically reconnect to bluetooth speaker, and output audio to bluetooth speakers.

### Actual behavior
Phone requires a reboot to output audio on reestablished connection.

### Logfiles and additional information
Car audio system information:
2017 Volksagen Jetta S
Device part number: 561035150A
Hardware: 055
Software: 7085
Bluetooth: D460

This also occured on a messed up hammerhead I used to have (stable, OTA-5) , so this is probably related to the way my car is functioning. However, both of these phones perform correctly when they are Android devices. (hammerhead also had https://github.com/ubports/ubuntu-touch/issues/649)

I'm having flashbacks to the state of bluetooth under Linux a few years ago! Please let me know which logs would be most helpful.

**Comment by raccspoons** [comment] 2018-12-12 02:20
To update this: The issue still exists in OTA-6. Additionally, making a call over bluetooth results in neither the sender nor receiver can hear anything 100% over the time, even after a reboot. The phone and car report that the call is in progress, and I can initiate a call, end a call and dial a number using the touchscreen in the car, but no sound is ever heard. 

I bring am including this, because my OnePlus One AND the Nexus 5 (OTA-5) I used to have are behaving in exactly the same way with my car's bluetooth system. As many hammerhead and bacon owners are discussing successfully making calls over bluetooth and are not reporting the issue above, this makes me think that something about the way my car is handling bluetooth that is causing this.

I'll test this out on other bluetooth audio devices and another (older) car model, to see if the behavior differs.

**Comment by tomoqv** [comment] 2018-12-17 08:41
> The phone and car report that the call is in progress, and I can initiate a call, end a call and dial a number using the touchscreen in the car, but no sound is ever heard.

I can confirm this behaviour on my Pro 5 on whatever build I have tried, RC or devel. It pairs fine with Volvo My Car and Skoda, but no sound at all.

**Comment by energius** [comment] 2018-12-25 00:09
The same bug but:
1. another Bluetooth device - Marshall Mid Bluetooth Headphones
2. Deleting the pairing, and reestablishing pair in any order HAS effect.

**Comment by ulrichard** [comment] 2019-01-27 06:55
I have a similar problem:
Beginning of January I read something about an over the air update on Jan 8th. After I didn't receive it, I switched from the stable channel to the release candidate.
Since then, whenever I receive a call in the car, I get the audio for 3 or 4 seconds and then everything is mute. This always worked flawlessly in the past with the original Ubuntu Touch and with ubports. 
Last week, I received another over the air system update, but it is still the same. 
I have a bq aquaris 4.5 original ubuntu edition and a Tesla Model S.

**Comment by xqqy** [comment] 2019-02-12 12:14
Similar problem in Nexus7 wifi(flo) 
OTA6 RC 2019-w06
Not the car but the Bluetooth Speaker(XiaoMi's Mi AI box)
If I connect the speaker by operate on the tablet, the Bluetooth will not work anymore until reboot.
But if I operate the Speaker connect the tablet, the problem will not happen.

**Comment by GithubGrisen** [comment] 2019-04-12 07:35
Same here on OPO and Tesla Model S. Sound in browser works, but phone calls are a no-go.

**Comment by BlueKenny** [comment] 2019-04-14 05:35
Same with my OPO and my car , no sound or voice over Bluetooth on both... I don't tryed rebooting... On a simple bluetooth player without Mic . it works ...

**Comment by mateosalta** [comment] 2021-02-24 12:12
Confirmed on volla. pairs and connects and works, but upon trying to reconnect it will no longer work, have to forget the pair and start again.

**Comment by UniversalSuperBox** [comment] 2021-04-08 15:31
I believe the original issue listed here, the Nexus 5 failing to send audio to a connected Bluetooth device, was resolved in OTA-14. In fact, I think the original issue was duplicated by https://github.com/ubports/ubuntu-touch/issues/1045.

Issues with Bluetooth calls were not resolved by that update, nor were issues with pairing.

The original issue report specified that the device reconnected to Bluetooth, so it is not the same problem you are experiencing @mateosalta. I believe there are other, more appropriate issue reports for that issue. But if there is not, please file a new report.

I'm closing this issue as it was duplicated by https://github.com/ubports/ubuntu-touch/issues/1045, which happens to also be closed

**Closed by UniversalSuperBox** 2021-04-08 15:31 UTC
Labels: bug

**Comment by mateosalta** [comment] 2021-04-10 14:45
> I believe the original issue listed here, the Nexus 5 failing to send audio to a connected Bluetooth device, was resolved in OTA-14. In fact, I think the original issue was duplicated by #1045.
> 
> Issues with Bluetooth calls were not resolved by that update, nor were issues with pairing.
> 
> The original issue report specified that the device reconnected to Bluetooth, so it is not the same problem you are experiencing @mateosalta. I believe there are other, more appropriate issue reports for that issue. But if there is not, please file a new report.
> 
> I'm closing this issue as it was duplicated by #1045, which happens to also be closed

It sounded similar enough, my car or bluetooth device would pair, and show connected, but would not play audio, so was trying to pass on a potential thing to try.
