### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by laurentGarry** [ubports/ubuntu-touch#334] opened 2017-11-03 18:11 UTC
- Device:
- Channel:
- Build:

## Steps to reproduce

1. ...
2. ...
3. ...

## Expected behavoir

...

## Actual behavior

...

## Logfiles and additional information

...

Libreoffice ne fonctionne pas, il s'allume puis s'éteint de suite.
VLC ne reconnait aucun support vidéo
Libreoffice does not work, it turns on and off.
VLC does not recognize any video support

**Comment by NeoTheThird** [comment] 2017-11-06 10:46
Duplicate of #22.

**Closed by NeoTheThird** 2017-11-06 10:46 UTC
