### ISSUE TITLE
device pixel ratio is off by one on Meizu Pro 5

### ISSUE THREAD

**Issue by mzanetti** [ubports/ubuntu-touch#921] opened 2018-10-16 13:39 UTC
Ever since there is support for device pixel ratio (I think since UBPorts OTA5) there seems to be a rounding error on some devices, currently the only one known is the Meizu Pro 5. This causes a one pixel white border on the right and top of the app.

Before there was upstream DPR support I added it myself to an app and saw the same issue. I got around it by rounding up, which probably causes one pixel to be cut off at the border so I'm not exactly sure if that's way to go but at least it looked better than the current state:

My code looked like this and this seemed to work (even though I got reports from users that this fails for some devices too)

```
    QByteArray gridUnits = qgetenv("GRID_UNIT_PX");
    qDebug() << "grid units" << gridUnits;
    bool ok;
    int gu = gridUnits.toInt(&ok);
    if (ok && gu > 0) {
        // Round up by multiplying 
        qreal scale = 1.0 * qRound(2.0 * gu / 8) / 2;
        qDebug() << "Setting scale factor to" << scale;
        qputenv("QT_SCALE_FACTOR", QByteArray::number(scale));
    }
``` 

To reproduce you can install nymea:app from the OpenStore on a Pro 5 and go to App Settings  and switch to the dark theme. It should be obvious to see then.

Perhaps its also reproducible by setting another device to GRID_UNIT_PX=21 (or whatever it takes nowadays to mimic a Pro 5)

**Comment by UniversalSuperBox** [comment] 2018-10-16 13:43
I can also confirm this on the Nexus 7 tablet ('flo'). There is a one-pixel white border on the right and top edge. This occurs when the app is staged, in fullscreen, or maximized while in desktop mode.

**Comment by CesarHerreraG** [comment] 2018-10-26 12:09
An upper line in BQ E4.5

**Comment by UniversalSuperBox** [comment] 2018-12-07 20:54
I don't believe so. Try downloading nymea:app from the OpenStore and putting it in dark mode:

![screenshot20181207_145401332](https://user-images.githubusercontent.com/21966173/49672193-f2e06800-fa2f-11e8-8609-f7da6e3d5117.png)

**Comment by hummlbach** [comment] 2018-12-07 22:34
Mhmm, okay, I tried so many other apps with dark background/night mode and none of them showed the problem, so I thought it was gone. But I just saw it with content hub an I think its also there in webtelegram... so: sorry.

**Comment by UniversalSuperBox** [comment] 2019-03-05 01:57
I think this problem may be inherent to Qt autoscaling... @dobey reports that it happens even on a desktop app when sized (in)correctly with the appropriate QT_SCALE_FACTOR set.

The Qt documentation recommends that users do not take advantage of its auto scaling features. https://doc.qt.io/qt-5/highdpi.html states (emphasis mine) "Qt 5.6 supports cross-platform high-DPI scaling for **legacy** applications" and "In the longer term, the application should be adapted to run unmodified," recommending that you "Replace hard-coded sizes in layouts and drawing code by values calculated from font metrics or screen size." QtUbuntu (and hopefully QtWayland in the future) correctly return an approprate scale factor as `Window.pixelDensity` in QML. It is best to use this value and decide on an appropriate UI scale for your application. Using the UITK's `Units.gu()` will solve the problem for you.

I'll close this report for now since I believe the issue is both upstream and a fact of its design. Please use Qt auto scaling only when absolutely necessary.

**Closed by UniversalSuperBox** 2019-03-05 01:57 UTC
Labels: bug
