### ISSUE TITLE
Video/audio (in web browser)

### ISSUE THREAD

**Issue by FlavioMala** [ubports/ubuntu-touch#2120] opened 2023-03-23 09:32 UTC
BUG-REPORT (?) 

- Device: BQ E5
- Channel: RC & Devel (between various tests, I tried to switch to the RC channel -from Devel-, but nothing changed)
- Build: RC > 2023-W12/2; Devel > the last one (I don't remember the code)

### Steps to reproduce
Video on Morph (or Tor/Onion) Browser (for example a YouTube video, etc.)

### Expected behavior
Video/audio plays...

### Actual behavior
The video (/audio) doesn't play:
it seems to be on an overlay window (it's noticeable if you scroll down the page - see screenshot below); after a while, an error message appears.
Sometimes it seems possible to advance in the playback bar and the "static" image corresponding to that playback point appears.
![screenshot20230322_rid](https://user-images.githubusercontent.com/50835740/227157160-8de4e167-178b-4bb6-b3ec-52734c5d9b48.png)

### Additional information
It seems to me that the problem appeared by modifying some parameters (later restored to the previous value) with UT Tweak Tool and Libertine Tweak Tool, trying to use alternative browsers (Midori, Firefox, Dillo, etc.) for the problem (Tutanota email) reported here:
https://gitlab.com/ubports/development/core/morph-browser/-/issues/549
and here:
https://github.com/tutao/tutanota/issues/5221
https://github.com/tutao/tutanota/issues/5223

Note: local videos (on the phone memory) are correctly played by the respective apps

### Logfiles
Let me know which ones are useful, if any.

**Comment by fredldotme** [comment] 2023-03-23 10:43
We don't really support people after they have messed around with UT Tweak Tool. If you use that you must be very well aware of what you are doing.

**Comment by FlavioMala** [comment] 2023-03-23 11:13
Maybe I used the wrong words: "It seems to me that the problem appeared by modifying some parameters..." was an idea/guessing.

I'm not an avid internet video user. I noticed the problem and the only thing that occurred to me is that several days before I installed Browsers in Libertine container and also used Libertine Tweak Tool.

About UT Tweak Tool I used the "scaling" which has never given me problems so far...

But maybe all these things have nothing to do with it.

Another strange thing that happens lately with updates (they are frequent on the Devel channel)  is that the system often doesn't restart well by itself: the white screen with the BQ logo remains (tested for 10 or more minutes) and you have to hold down the power button to restart the phone...

**Comment by FlavioMala** [comment] 2023-03-23 12:01
Mhhhh...maybe it's something related to the yes/no desktop mode of the browser?

Switching "desktop" on/off something changes (restoring to off).
Furthermore, if I set full screen in the video window it is not really full screen (the top bar remains, etc.)

Some time ago switching to desktop and then switching back I had problems with emails on "mail.com": it is no longer possible to have phone mode (tried to clear cache, history, etc. I also tried with UT Tweak, without results)

**Comment by lduboeuf** [comment] 2023-03-23 14:40
Confirmed, with latest devel on a BQ4.5, can't play video on YT within Morph, but OK on N5 stable

**Comment by lduboeuf** [comment] 2023-03-23 14:58
> Confirmed, with latest devel on a BQ4.5, can't play video on YT within Morph, but OK on N5 stable

Confirmed on N5 RC too, can't play YT video

**Comment by FlavioMala** [comment] 2023-03-23 15:36
Ahhhh...... thank you very much! Moving on stable... it works!

So it's a "problem" that appeared recently: I was on "Devel", but I don't update to every release, sometimes "jump" of 2, 5 or even more ... it depends on the "real life", if I can risk malfunctions of the phone, etc.
So it can be 3...5 releases ago? (I don't think "more").

**Comment by arubislander** [comment] 2023-03-23 15:37
Confirmed also on Meizu Pro 5. Can play YT videos on stable, but not on RC nor the latest devel.

**Comment by arubislander** [comment] 2023-03-23 15:42
@FlavioMala,, please try to stick to one bug per issue. This one you opened concerning video / audio not playing in the browser, which has now been confirmed by several users on several devices. The other bugs you are mentioning can better be discussed under their own issues, just like you opened this one. Well done on that, by the way.

**Comment by FlavioMala** [comment] 2023-03-23 15:58
Sure, it was only for additional information/s.
I can add: this time the phone restart well by itself.
(problem with "desktop mode" on mail.com still present, also Tutanota access problem)

**Comment by peat-psuwit** [comment] 2023-03-23 17:54
Ok. So I can't reproduce this on Xperia X or (original) Volla Phone, but on bq Aquaris E4.5. This indicates that it's the software decoding path that fails, which is strange because I would imagine that the hardware decoding path would be more likely to fail (it's ported from Canonical's code IIRC). Or maybe it's HW-or-SW selector.

When playing back, the following message appears in `~/.cache/upstart/application-legacy-morph-browser-.log`:

```
[6770:6770:0324/004156.051783:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":12}
```

So that's something to begin with.

**Comment by peat-psuwit** [comment] 2023-03-23 18:22
Oh... I forgot that the hardware decoding patch for QtWebEngine haven't landed in Xenial. 🤦

So it could be something else. As for other differences between E4.5 and (e.g.) Volla Phone, adding `--disable-gpu-compositing --disable-gpu` to `QTWEBENGINE_CHROMIUM_FLAGS` on Volla Phone doesn't break the video playback.

**Comment by fredldotme** [comment] 2023-03-23 18:57
> Ok. So I can't reproduce this on Xperia X or (original) Volla Phone, but on bq Aquaris E4.5. This indicates that it's the software decoding path that fails, which is strange because I would imagine that the hardware decoding path would be more likely to fail (it's ported from Canonical's code IIRC). Or maybe it's HW-or-SW selector.
> 
> When playing back, the following message appears in `~/.cache/upstart/application-legacy-morph-browser-.log`:
> 
> ```
> [6770:6770:0324/004156.051783:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":12}
> ```
> 
> So that's something to begin with.

I haven't had the time to read through all of the issue, just wanted to chip in:

Do I understand correctly that the HW acceleration patches from focal are also now in xenial? If any of the OMX hardware decoding patches to QtWebEngine are at fault, it needs Mojo decoders support enabled through `QTWEBENGINE_CHROMIUM_FLAGS ` (the sole reason causing me to make this whole patch from scratch).

**Comment by peat-psuwit** [comment] 2023-03-23 19:08
So, according to `chrome://media-internals`, `"pipeline_error": 12` seems to correspond to `DEMUXER_ERROR_COULD_NOT_OPEN`. What could it not open?

I tried putting Morph's AppArmor profile to complain mode; still doesn't work.

<details>
<summary>Full info from chrome://media-internals </summary>
<pre>
{
  "id": "15:1",
  "properties": {
    "render_id": 15,
    "player_id": 1,
    "origin_url": "http://commondatastorage.googleapis.com/",
    "kFrameUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "kFrameTitle": "",
    "url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "kTextTracks": [],
    "kTotalBytes": 158008374,
    "kIsStreaming": false,
    "kIsSingleOrigin": true,
    "kIsRangeHeaderSupported": true,
    "pipeline_error": "DEMUXER_ERROR_COULD_NOT_OPEN"
  },
  "allEvents": [
    {
      "time": 0,
      "key": "origin_url",
      "value": "http://commondatastorage.googleapis.com/"
    },
    {
      "time": 0.0719999996945262,
      "key": "kFrameUrl",
      "value": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    },
    {
      "time": 0.09999999962747097,
      "key": "kFrameTitle",
      "value": ""
    },
    {
      "time": 0.7209999999031425,
      "key": "url",
      "value": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    },
    {
      "time": 0.7599999997764826,
      "key": "kTextTracks",
      "value": []
    },
    {
      "time": 65.77900000009686,
      "key": "kTotalBytes",
      "value": 158008374
    },
    {
      "time": 65.82299999985844,
      "key": "kIsStreaming",
      "value": false
    },
    {
      "time": 65.83799999952316,
      "key": "kIsSingleOrigin",
      "value": true
    },
    {
      "time": 65.84800000023097,
      "key": "kIsRangeHeaderSupported",
      "value": true
    },
    {
      "time": 71.17899999953806,
      "key": "pipeline_error",
      "value": "DEMUXER_ERROR_COULD_NOT_OPEN"
    }
  ],
  "lastRendered": 0,
  "firstTimestamp_": 5005775.091
}
</pre>
</details>

@fredldotme:

> Do I understand correctly that the HW acceleration patches from focal are also now in xenial?

No, it's not in. The earlier message was just my memory fault (pun intended).

**Comment by peat-psuwit** [comment] 2023-03-23 19:43
No. I think I know what's more likely to create a problem: FFmpeg. Both Xperia X and Volla Phone use arm64 rootfs, while E4.5 uses armhf rootfs. And we have some changes related to FFmpeg from Debian which leads me to remove one of our patch [1].

When this builds in the next ~8 hours, please give this MR a try with `ubports-qa install PR_qtwebengine_24`. That said, I'm not certain that it's the cause of the problem, but I'm going to bed now. So...

https://gitlab.com/ubports/development/core/packaging/qtwebengine/-/merge_requests/24

[1] https://gitlab.com/ubports/development/core/packaging/qtwebengine/-/merge_requests/22/diffs?commit_id=972851b62cafa4e95af4a3cef2954b6e78b8657c

**Comment by lduboeuf** [comment] 2023-03-24 09:09
@peat-psuwit confirm it works on N5 and BQ4.5

**Comment by arubislander** [comment] 2023-03-24 09:44
will be able to test on my Pro5 after 18:30 CET. Will edit this post then.

EDIT: Finally got around to it. Works on Meizu Pro5.

**Comment by FlavioMala** [comment] 2023-03-24 13:35
Sorry for the late reply, but it was necessary to resize/process screenshoots on PC.

First of all, on "stable":
Open Morph, search "jump video", open link Van Halen (for example), test it...
Everything works, even full screen, including desktop mode.

Download "devel", then install  (FYI: phone do no restart itself... holding power button was necessary)
Open Morph.... Van  Halen, it doesn't work as expected

 **sudo ubports-qa install PR_qtwebengine_24**
(wait a lot...)
Open Morph.... Van  Halen, it works, but:

first time I open Morph (desktop off) the video is in an overlay window (it is noticed by scrolling on the page), see in the red line in the following picture
![1b](https://user-images.githubusercontent.com/50835740/227532174-251c01ec-5b48-458a-8e5f-c9e697704b3c.png)

fullscreen seems to work
(mmhhh maybe there is something different, compared to "stable"...)
![2](https://user-images.githubusercontent.com/50835740/227532569-59a75fd0-44e5-40ca-ae6e-d065f6f44e98.png)

also in landscape
![3](https://user-images.githubusercontent.com/50835740/227532700-ecb538ac-0743-44cd-ba35-f2f757aac0fe.png)

Now... for this https://gitlab.com/ubports/development/core/morph-browser/-/issues/127
i tried desktop mode "on" and then "off" again
So... what happens by setting "desktop on" then reloading "Jump":
![5](https://user-images.githubusercontent.com/50835740/227533201-e2eb4e63-f113-4715-98d9-9f34d4679339.png)

after a while (it's quite slow) the page settles down like this
![6](https://user-images.githubusercontent.com/50835740/227533406-e6e650a5-3b44-4496-a02b-a1ad6ffbda3c.png)

now in fullscreen:
![7](https://user-images.githubusercontent.com/50835740/227533542-81fe255d-6e21-453c-a2cb-61e5a9ec0586.png)
**--- > PLEASE NOTE the gray bar at the bottom of the picture!**

and landscape
![8](https://user-images.githubusercontent.com/50835740/227534018-c7935ed3-8e2e-45d6-be65-99b916851f2b.png)

Now... what happens by resetting desktop "off" again (then reloading "Jump"):
![9](https://user-images.githubusercontent.com/50835740/227534109-d5d230b3-47dd-4962-8d52-b7a8e836c6ff.png)

Something has changed, in fact scrolling the page you notice that the video is no longer in an overlapping window
![10](https://user-images.githubusercontent.com/50835740/227534414-cf7d77f9-328d-489b-acaf-e23efee4d62d.png)

also in fullscreen something has changed (the gray bar...)
![11](https://user-images.githubusercontent.com/50835740/227534601-5b3e1963-5ca8-4fa4-ac28-d2ed4e42f15d.png)

landscape:
![12](https://user-images.githubusercontent.com/50835740/227534728-962e9ff9-12a8-4576-85fe-f9a0e8d454fc.png)

Note (FYI): checking user agent (with duckduck or whatsmybrowser.org ) I see no difference between the first time Morph is in desktop "off" and the last one with "desktop off" after switching to "on".

(In any case, it's fine for me, thank you very much!... I have detailed everything if you think it is appropriate to improve)

**Comment by Flohack74** [comment] 2023-03-24 20:50
@FlavioMala can you please install the branch with ubports-qa and try it out?

**Comment by FlavioMala** [comment] 2023-03-24 22:31
What branch?  PR_qtwebengine_24? The screenshoots above are after Installation, as I wrote just before the first one:
"[omissis]
sudo ubports-qa install PR_qtwebengine_24
(wait a lot...)
Open Morph.... Van Halen, it works, but:
[omissis]"
Without installation devel/RC does not work (play) at all !
After installation it works, but with these "small problems" highlighted.

**Comment by FlavioMala** [comment] 2023-03-26 15:38
I did other tests: I reloaded "stable" and the behavior is **the same** by switching from deskt on->off->on, so the gray bar in the fullscreen with "desktop on" maybe has always been shown (maybe I never seen videos in desktop mode, so I've never noticed it).

About the behavior returning to desktop off, I discovered that reloading the web page after the switch is not enough: after resetting "desktop off" you need to close the browser and reopen it, or open a new browser window and from there access the web page of the video. Alternatively you can also open a new browser window from the first one in desktop mode, then on the new window set desktop off, then open the video web page (in this new window).
**So it has nothing to do with this issue**
(Maybe it is Morph that has some problems with the ON/OFF Desktop passage; even if the user agent changes it is not enough and it is necessary to act as above, and for certain sites it does not even seem enough anyway, E.G. Mail.com and also
https://ubports.atlassian.net/jira/software/c/projects/YUMI/issues/YUMI-6 in desktop view, regardless of Morph's settings)

**Comment by Flohack74** [comment] 2023-03-26 18:27
@FlavioMala plz can you switch to RC and test this again in approx 2hrs?

**Comment by FlavioMala** [comment] 2023-03-27 06:01
Yesterday (26) I tried on "Dev" (build 2023-03-25): OK
Now I try on RC, then I will relate the result...

**Comment by arubislander** [comment] 2023-03-27 07:03
And please keep the results you relate restricted to just video playback
for this ticket.

**Comment by FlavioMala** [comment] 2023-03-27 09:18
OK, RC (on BQ E5 HD) now "works" with the same behavior as "stable", "devel" 25/03 (and previous RC+PR...).
Thanks!

**Closed as completed** 2023-03-30 20:16 UTC
Labels: bug, critical (rc)
