### ISSUE TITLE
[xenial] Since r81 update in Krillin, scrolling is very slow

### ISSUE THREAD

**Issue by advocatux** [ubports/ubuntu-touch#615] opened 2018-05-20 11:48 UTC
- Device: BQ E4.5 (krillin)
- Channel: 16.04 (devel)
- Build: since r81

### Steps to reproduce
Scroll up & down on the screen

### Expected behavior
Scrolling should be very fluid, like it was until now

### Actual behavior
When scrolling up & down, the movement is very very slow, kind of jerky. Instead of being fluid it stops every few rows.

### Logfiles and additional information
I can see in `unity8.log` that the following line is printed every time I touch the screen `qtmir.surfaces: MirSurface[0x1ba8ac0,"unity8-dash"]::setCursor(Arrow)`

Probably related to https://bugs.launchpad.net/canonical-devices-system-image/+bug/1664151 ([performance] unity8.log flooded with debug messages about window position and cursor shape - Fix released).

**Comment by dark-eye** [comment] 2018-05-20 12:10
Same on Meizu PRO 5

**Comment by BlueKenny** [comment] 2018-05-20 15:02
Same on OnePlus One

**Comment by tydell** [comment] 2018-05-20 21:34
I see the same behaviour on N5 hammerhead 16.04 on r388 and newer. Scrolling isn't smooth anymore :(

**Comment by fourloop2002** [comment] 2018-05-21 08:10
Can't see this behaviour on Nexus 5 hammerhead 16.04  on r387.  Not sure what screen is being scrolled but log files in Logviewer app scroll smoothly.

**Comment by tydell** [comment] 2018-05-21 08:39
On r387 there was no such issue, was only #606 issue. On r388 scrolling and newer scrolling is laggy (apps scope, webapps, browser-app and more). Update your UT and see if there is some regression in this case.

**Comment by hummlbach** [comment] 2018-05-21 20:34
Same on nexus 4

**Comment by dark-eye** [comment] 2018-05-22 05:42
One thing I noticed is that this issue doesn't affect webapps

**Comment by abkro** [comment] 2018-06-02 10:46
Same on hammerhead running Xenial r408.
Log files: 
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2064913/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2064914/UTlogcat.txt)
Video that shows behavior:
[https://www.youtube.com/watch?v=VSgPCUU1tvw](url)

**Comment by abkro** [comment] 2018-06-04 08:27
Still present in Xenial, build 412 on hammerhead.

**Comment by advocatux** [comment] 2018-06-04 08:31
Yep, this bug is still present in BQ E4.5 (krillin) running UT 16.04 (r88) too.

**Comment by zubozrout** [comment] 2018-06-06 08:19
Much better now on r89 (arale) :+1:

Thought it still has some issues (maybe unrelated to this) and if I do a swipe gesture in any app (settings or home scope) the scrolling sometimes continues after I end swipe gesture but mostly stops right where my finger leaves the screen.

The faster I do the gesture the higher chance of a smooth scroll termination or however it is called there are :)

**Comment by abkro** [comment] 2018-06-06 16:11
On Krillin r89 and Hammerhead r415 there seems to be a bit of improvement, but still not where it should be. This goes for the app view and the settings menu. But when you browse the web, scrolling on a webpage with the browser works better and almost the way it should.

**Comment by abkro** [comment] 2018-06-07 08:41
R416 on Hammerhead: There is a definite improvement. Here's what happens now:

When you attempt to scroll with a quick very short touch to the screen, the image moves in a smooth fluid manner and gradually comes to a stop. By 'short' I mean that the time your finger is in contact with the screen and the distance it moves while it touches the screen must be very short.

If your finger travels slightly further without leaving the screen, the resulting movement of the image comes to an abrupt halt. This still happens most of the time simply because it's hard to perform this action with so little and short contact time with the screen.

The other consequence of this state of things is that when you try to perfom the action in this way your action is sometimes interpreted by the device as a tap on an icon, thus resulting in an app being launched. This has already happened to me a number of times.

So, there is definite improvement, but we're not there yet. :)

**Comment by UniversalSuperBox** [comment] 2018-06-09 19:53
Some things which we've been able to figure out:

* This issue does not happen in pure QML apps. For example, [this QML](https://paste.ubuntu.com/p/w6WYMPFng3/) which uses no Ubuntu.Components, scrolls normally (minus the occasional "having no momentum" which isn't the problem we're tracking here.)
* This issue does not happen if your drag begins **and** ends on a non-interactive point in a List. For example, if you touch beginning on one of the section headings in Settings and swipe, you will get normal momentum. The momentum will be incorrect if you start and finish the swipe on any of the interactive items.
* It seems like the issue is that Ubuntu.Components ListItems do not properly implement handling of touches. The handling has changed quite a bit from Qt 5.3 (vivid) to 5.9.5 especially in the private API. That's why you see that the interactive items in the list will occasionally get clicked or do something else strange while scrolling.

I don't think I have the expertise to implement the required touch handling in UITK. At this point, I'm going to pass the assignment.

**Comment by abkro** [comment] 2018-06-10 09:05
R421 now. There is still more improvement. It seems that scrolling up (pulling the screen image downwards) more often has the desired result compared to scrolling down (pushing the screen image up). Neither are near consistently good, though.

**Comment by dpniel** [comment] 2018-06-10 14:53
@UniversalSuperBox i can take this one but it might have to wait until Friday. If someone want's to take it on before then, please do! :-)

**Comment by mauricioduarte01** [comment] 2018-06-18 15:59
Hi, I just wanted to report that until the last update from today, this issue is still present. The lags is there even when browsing, in system settings etc. Thanks :)

**Comment by mariogrip** [comment] 2018-07-03 21:42
Ok so i have found the issue, it seems like qt is generating a "hover event" when it's not supposed to, this messes with "flickable" making the scroll slow. but now we have to find out why it does this.

This is an example where i disabled hover events: https://github.com/ubports/qtmir/commit/9088f9ce6d3f88b3055ad10223a5d0493be79130

@dpniel any ideas?

**Comment by dark-eye** [comment] 2018-07-03 22:43
@mariogrip just a guess but maybe Qt::WA_Hover was used some where in the code that it wasn't there before the update?

**Comment by mariogrip** [comment] 2018-07-20 19:56
@dark-eye Humm maybe, but it was not an issue before we upgraded to 5.9.5. but will try messing with those settings.

**Comment by mariogrip** [comment] 2018-07-22 22:31
Fixed with temporarily workaround: See https://github.com/ubports/ubuntu-touch/issues/787

**Closed by mariogrip** 2018-07-22 22:31 UTC
Labels: bug, critical (rc)

**Comment by dark-eye** [comment] 2018-07-24 09:20
Thank you @mariogrip !! it`s a lot more  fun to scroll around now :P
