### ISSUE TITLE
Huge delays when changing the background

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#500] opened 2018-03-04 01:11 UTC
- Device: hammerhead
- Channel: xenial/devel
- Build: r273

### Steps to reproduce
System Settings -> Background
Then, select any background.

### Expected behavior
After tapping any one of the images, it should (within a half a second) snap to the background being fullscreen.

### Actual behavior
It takes a second or two for the background to load, making me think the app completely froze (which, well, it did for a few seconds).

**Comment by NeoTheThird** [comment] 2018-03-04 11:49
I can confirm this for vivid as well. Thanks for reporting.

**Comment by lduboeuf** [comment] 2020-05-17 09:21
seems to be fixed now ( OTA-12)

**Closed by lduboeuf** 2020-05-17 09:21 UTC
Labels: bug
