### ISSUE TITLE
Timekeeper not working on Halium 7.1 Builds

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-touch#1534] opened 2020-08-22 10:03 UTC
- Device: hammerhead, fp2
- Channel: devel
- Build: halium 7.1

### Steps to reproduce
boot the phone connect to wifi until time and data are set, disconnect from wifi and reboot the phone, device time will be reser 1970 ( the year of unix) loooll
the /etc/init/timekeeper.conf is doing nothing
i can store using sudo /usr/bin/timekeeper store
and restore after reboot  sudo /usr/bin/timekeeper restore

### Expected behavior
save time between reboots without be connected to wifi

### Actual behavior
after reboot times is lost unless you are connected to wifi

**Comment by UniversalSuperBox** [comment] 2020-11-16 15:55
Hello @rubencarneiro,

I'm unable to reproduce this on the Xperia X running a Halium 7.1 build. Do you have a better place to track issues related to the unreleased builds on the Nexus 5, Fairphone 2, and Oneplus One?

**Comment by rubencarneiro** [comment] 2020-11-16 16:11
I think nexus 6p has also this issue.

A segunda, 16/11/2020, 15:55, Dalton Durst <notifications@github.com>
escreveu:

**Comment by Flohack74** [comment] 2020-11-16 20:42
No I was able to fix it @rubencarneiro, basically with what you did: Remove the old timekeeper script, change permissions to the data file :)

**Comment by rubencarneiro** [comment] 2020-11-16 20:45
Did you try to reboot tge device with no mobile data on and no wifi?

A segunda, 16/11/2020, 20:43, Florian Leeber <notifications@github.com>
escreveu:

**Comment by Flohack74** [comment] 2020-11-16 20:46
Yes. it works with that changes: https://github.com/Flohack74/android_device_huawei_angler/commit/60d285e384b7dd70763cd42a1caf1f5f8752b97c

**Comment by Flohack74** [comment] 2020-11-16 20:46
Disable Android timekeeper, set permissions. Using the timekeeper.conf override did not work.

**Comment by rubencarneiro** [comment] 2020-11-16 20:50
Ok was the same i did to nexus 5, but still didnt work

A segunda, 16/11/2020, 20:47, Florian Leeber <notifications@github.com>
escreveu:

**Comment by BadAngelZ** [comment] 2021-03-18 11:59
Hi ! I have the same issue on my Xiaomi Redmi note 7.
I tried to do a "hwclock -w" which is supposed to write the system clock into the hardware clock, but I says:

```
root@ubuntu-phablet:/system# hwclock -w
hwclock: ioctl(RTC_SET_TIME) to /dev/rtc to set the time failed.:
Invalid argument
```

The following syntax gives the same result:

`hwclock --set --date="2011-08-14 16:45:05"`

I've also strace the hwclock for which you'll find attached the strace.log:
`root@ubuntu-phablet:~# strace -f -v -o /tmp/trace.log hwclock -w`
[strace.log](https://github.com/ubports/ubuntu-touch/files/6163810/strace.log)

**Comment by BadAngelZ** [comment] 2021-04-06 09:54
Update: this behavior happens only on my phone. My wife's phone (which is the same model, with the same ubuntu touch release) does not have this problem ... I cannot understand why ...

**Comment by UniversalSuperBox** [comment] 2021-04-09 19:44
Hi @BadAngelZ,

Could you please post the output of the following command on your phone: `sudo ls -l /userdata/android-data/time/`

On my phone, it is:

```
$ sudo ls -l /userdata/android-data/time/
total 4
-rw-r--r-- 1 root root 10 Apr  9 14:24 timekeep
```

**Comment by rubencarneiro** [comment] 2021-04-09 20:47
Time related issue may be related to init.rc /data/time folder permissions.

**Comment by BadAngelZ** [comment] 2021-04-09 21:48
> Hi @BadAngelZ,
> 
> Could you please post the output of the following command on your phone: `sudo ls -l /userdata/android-data/time/`

Of course :)
On my phone, it is nearly the same (only time changes: it seems to be the date of the last boot) :
 
```
$ ls -l /userdata/android-data/time/
 total 4
 -rw-r--r-- 1 root root 10 Apr  9 18:13 timekeep
```
Note: /data is symbolic link to /android/data

Write permission differ : 
```
phablet@ubuntu-phablet:~$ ls -l / | grep data
lrwxrwxrwx    1 root        root                13 août  15  1971 data -> /android/data
lrwxrwxrwx    1 root        root                17 août  15  1971 metadata -> /android/metadata
drwxr-xr-x    7 root        root              4096 juil.  1  1971 userdata
```

What I can see is that the links data and metadata have the time of the hardware clock, where userdata is the "zero" time.
I tried to change /userdata permissions (remount / rw, then chmod go+w on it), but hwclock -w always return an error:
```
$ sudo hwclock -w
hwclock: ioctl(RTC_SET_TIME) to /dev/rtc to set the time failed.: Invalid argument
```
I also changed permission to /android/data (own by system:system) with no success.
I looked at the content of /userdata/android-data/time/timekeep
It's a timestamp: 1565020200 (which is the date: 5/8/2019 15:50:00 )

**Comment by BadAngelZ** [comment] 2021-07-26 11:55
After last OTA update, hardware clock is correctly working. So I guess the problem I had was related to a "failed" install.

**Comment by Flohack74** [comment] 2021-08-12 15:12
I close this now since its always a device-specific issue and not solveable by only doing changes in the rootfs.

**Closed by Flohack74** 2021-08-12 15:12 UTC
Labels: needs confirmation
