### ISSUE TITLE
Last updated shows wrong/old date

### ISSUE THREAD

**Issue by toehold** [ubports/ubuntu-touch#685] opened 2018-06-18 07:18 UTC
- Device: Nexus 5/hammerhead
- Channel: 16.04/devel
- Build: 2018-06-18

### Steps to reproduce
Go to Settings --> About

### Expected behavior
Last updated should display latest date when device was updated

### Actual behavior
Shows: 29/02/1972

**Comment by Flohack74** [comment] 2018-06-18 10:50
@NeoTheThird an old friend is back ;)

**Comment by NeoTheThird** [comment] 2018-06-18 11:44
There is no more @NeoTheThird. His soul left his body when it saw this bugreport. I am now just an empty shell.

**Comment by mariogrip** [comment] 2018-06-18 12:28
This was also a problem on vivid, in fact this is a problem on all our qcom devices due to read only RTC clock. So the time is simply wrong when it upgrades, timekeeper is there to try to workaround this, but will not work unless it has the correct clock in the first place to work with. For now i'll move this to ota-5.

**Comment by zubozrout** [comment] 2018-07-14 08:50
@mariogrip Well, isn't MX4 Mediatek? https://www.gsmarena.com/meizu_mx4-6627.php
It affects that device too (and has also been there on Canonical images).

**Comment by tatonuta** [comment] 2018-07-25 19:48
The same here on:

    Device: Nexus 5/hammerhead
    Channel: 16.04/rc
    OS build: 2018-W30

But the last update date is different - it's 23.12.1971 (and not 29/02/1972 as in original bug report).

**Comment by UniversalSuperBox** [comment] 2018-10-02 17:04
Closed via ubports/system-image#8

**Closed by UniversalSuperBox** 2018-10-02 17:04 UTC
Labels: device: FP2, device: bacon, device: hammerhead

**Comment by padraic7a** [comment] 2018-10-02 22:01
Checked it on Nexus 5 running 16.04 development, build 2018-10-02.

This is still a problem. In ```System Settings``` >  ```About``` the last updated date is 1/31/70.

If I go to ```Updates``` I can see that the most recent update was updated 2 October.

I will check again in the coming days in case the fix just hasn't landed in Devel yet.

**Comment by UniversalSuperBox** [comment] 2018-10-02 23:51
For future reference, `devel` builds occur every day at 0700 UTC. PRs merged into a release branch will not be in the image before that time following their merge.

**Comment by padraic7a** [comment] 2018-10-03 21:08
Cool, thanks for letting me know.
Tested just now on Nexus 5 running 16.04, build 2018-10-03 and the issue is fixed.

**Comment by 216066** [comment] 2018-10-04 09:52
Hello. Just switched to RC and downloaded and installed **2018-W40** on **anbox-boot-hammerhead.img** kernel. Last update shows correct OS but wrong date (05/01/70).
