### ISSUE TITLE
[Xenial] Copy and paste not working

### ISSUE THREAD

**Issue by StefWe** [ubports/ubuntu-touch#735] opened 2018-07-01 19:22 UTC
- Device: hammerhead
- Channel: dev
- Build: 2018-07-01/2

### Steps to reproduce

Copy text in the note app or in the web browser or in telegram and try to paste it on another place.

**Comment by advocatux** [comment] 2018-07-01 19:45
I can't reproduce this bug since it was fixed (#658)

Copy & paste works fine on my BQ E4.5 (krillin) running UT 16.04 (2018-07-01)

**Comment by Flohack74** [comment] 2018-07-01 19:47
Should be fixed and is duplicate of #658 probably.

**Closed by Flohack74** 2018-07-01 19:47 UTC

**Comment by StefWe** [comment] 2018-07-01 20:03
Sorry for duplicate a closed/fixed issue. My fault...
