### ISSUE TITLE
[xenial] Calendar app confuses time zones when synced to Google Calendar

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#765] opened 2018-07-13 15:34 UTC
- Device: Turbo
- Channel: xenial
- Build: RC4

### Steps to reproduce
Add google account in system settings. Enable calendar sync.

### Expected behavior
Events to show up on the same time/date on the phone as in google calendar

### Actual behavior
Timed events appear to hours later (than CET/UTC+2) in the phone than in the online google calendar.

**Comment by NeoTheThird** [comment] 2018-07-13 16:16
Was this the case in vivid as well?

**Comment by tomoqv** [comment] 2018-07-13 16:33
No, not for me.

**Comment by NeoTheThird** [comment] 2018-07-13 16:43
Ok. Are you sure the events are set to the same timezone? Because the calDAV standard allows for events to specify their own timezone.

**Comment by tomoqv** [comment] 2018-07-13 16:51
They should be. All I can see is that if I look at a specific event in G Calendar in Chrome on my PC, it states e.g. 14:30-18:40. That same event on the UT calendar displays as 16:30-20:40. I am in Spain at the moment, which is in the same time zone as Stockholm (UTC+2). It seems odd that my G Calendar on the PC suddenly should start showing events in some other time zone.

**Comment by tomoqv** [comment] 2018-07-13 16:52
The really odd thing is that when I started to look into this yesterday, all my events were in the correct time zone, but because of some time zone bug my all day events showed up in the UT calendar on the day after.

**Comment by NeoTheThird** [comment] 2018-07-13 16:59
Duplicate of #760. Works in devel and will be fixed in the next RC.

**Closed by NeoTheThird** 2018-07-13 16:59 UTC
Labels: needs confirmation

**Comment by tomoqv** [comment] 2018-07-13 17:23
Ok, got it. Seems to be the same. Switching to devel now.
