### ISSUE TITLE
2G internet connection regression

### ISSUE THREAD

**Issue by c4pp4** [ubports/ubuntu-touch#1816] opened 2021-08-29 13:32 UTC
- Device: Xiaomi Mi A2
- Channel: devel (arm64, halium 9)
- Build: 2021-08-29

### Steps to reproduce
set System Settings -> Cellular -> 2G only (saves battery)

### Expected behavior
internet connection works (I think it's GPRS or EDGE)

### Actual behavior
- when on stable OTA-18 - internet connection works
- when on devel - no internet connection at all

**Comment by mardy** [comment] 2021-09-02 19:46
I can confirm this on the Redmi Note 7 (lavender). I'm attaching the syslog; you can see that network manager attempts to connect every few seconds, but never succeeds.
[syslog.txt](https://github.com/ubports/ubuntu-touch/files/7101369/syslog.txt)

**Comment by mardy** [comment] 2021-09-02 20:28
Reverting `libgrilio-binder` and `ofono-ril-binder-plugin` to version `1.0.16+ubports1+0~20210123002728.2~1.gbp68c1d0` fixes the issue.

**Comment by mariogrip** [comment] 2021-09-03 23:09
Here is a fix https://github.com/mer-hybris/ofono-ril-binder-plugin/pull/29

I made a branch with it, please try out `xenial_-_android9_-_fix2gdata`

using:
`sudo ubports-qa install xenial_-_android9_-_fix2gdata`

**Comment by c4pp4** [comment] 2021-09-04 07:31
@mariogrip I can confirm it works with radio@1.1 on RC (20210827).

**Comment by mlehtima** [comment] 2021-09-04 13:03
Just noting that the pull request above is for devices which use radio@1.4 interface and that needs to be enabled in ofono configuration as mentioned in the pull request.

**Comment by mardy** [comment] 2021-09-04 13:44
> Here is a fix [mer-hybris/ofono-ril-binder-plugin#29](https://github.com/mer-hybris/ofono-ril-binder-plugin/pull/29)
> 
> I made a branch with it, please try out `xenial_-_android9_-_fix2gdata`

Nope, this does not appear to be working for me: I installed the new packages (`1.2.5+ubports1+0~20210903230851.1~1.gbpbd3837`),  then edited the `etc/ofono/ril_subscription.conf` file to be

```conf
[ril_0]
transport=binder:name=slot1;interface=radio@1.4
name=slot1

[ril_1]
transport=binder:name=slot2;interface=radio@1.4
name=slot2
```
then rebooted, but the 2G connection could never be established. I also tried without the `;interface=radio@1.4` bit, and it didn't work either.

**Comment by gbdomubpkm** [comment] 2021-09-04 16:00
I'm not sure I understood from which date and channel some (all) halium 9 devices are affected by this bug.
But the Volla in RC 31 (i am on it)  built 20210827 is not affected. Internet in 2g works.

**Comment by c4pp4** [comment] 2021-09-04 17:07
> > Here is a fix [mer-hybris/ofono-ril-binder-plugin#29](https://github.com/mer-hybris/ofono-ril-binder-plugin/pull/29)
> > I made a branch with it, please try out `xenial_-_android9_-_fix2gdata`
> 
> Nope, this does not appear to be working for me: I installed the new packages (`1.2.5+ubports1+0~20210903230851.1~1.gbpbd3837`), then edited the `etc/ofono/ril_subscription.conf` file to be
> 
> ```
> [ril_0]
> transport=binder:name=slot1;interface=radio@1.4
> name=slot1
> 
> [ril_1]
> transport=binder:name=slot2;interface=radio@1.4
> name=slot2
> ```
> 
> then rebooted, but the 2G connection could never be established. I also tried without the `;interface=radio@1.4` bit, and it didn't work either.

It doesn't work with radio@1.4, try radio@1.1 instead.

**Comment by c4pp4** [comment] 2021-09-04 20:24
> @mariogrip I can confirm it works with radio@1.1 on RC (20210827).

With radio@1.0 as well.

**Comment by mardy** [comment] 2021-09-05 05:54
Even the package we currently have on RC works with `radio@1.0` and `radio@1.1`. The point here is trying to make a fix that would work with the latest version.

**Comment by mlehtima** [comment] 2021-09-06 18:34
Could someone test if this helps https://github.com/sailfishos/ofono/pull/5 with the issue?

**Comment by mariogrip** [comment] 2021-09-07 05:53
Thanks @mlehtima 

I have pushed the fix from @mlehtima to `xenial_-_android9_-_fix2gdata`, can someone retest it? i currently don't have a with this issue, so i cannot test myself.

https://github.com/ubports/ofono/commits/xenial_-_android9_-_fix2gdata

**Comment by mardy** [comment] 2021-09-07 06:22
> I have pushed the fix from @mlehtima to `xenial_-_android9_-_fix2gdata`, can someone retest it? i currently don't have a with this issue, so i cannot test myself.

I'll try it tonight!

**Comment by Flohack74** [comment] 2021-09-07 06:47
I have retargeted this bug to be non-critical, since though its a regression its not catastrophic.

**Comment by c4pp4** [comment] 2021-09-07 11:54
> Thanks @mlehtima
> 
> I have pushed the fix from @mlehtima to `xenial_-_android9_-_fix2gdata`, can someone retest it? i currently don't have a with this issue, so i cannot test myself.
> 
> https://github.com/ubports/ofono/commits/xenial_-_android9_-_fix2gdata

I can confirm it works.

**Comment by mardy** [comment] 2021-09-07 15:58
> Thanks @mlehtima
> 
> I have pushed the fix from @mlehtima to `xenial_-_android9_-_fix2gdata`, can someone retest it? i currently don't have a with this issue, so i cannot test myself.
> 
> https://github.com/ubports/ofono/commits/xenial_-_android9_-_fix2gdata

I also confirm that it works, and it does not require a change in the configuration. That is, this configuration works:
```
[ril_0]
transport=binder:name=slot1
name=slot1

[ril_1]
transport=binder:name=slot2
name=slot2
```

**Comment by mlehtima** [comment] 2021-09-07 18:07
Yes, the fix to ofono fix doesn't require the other pull request or any configuration changes.

**Comment by mariogrip** [comment] 2021-09-08 00:48
The fix should be in next devel, please test there also :) please reopen if the issue still persists.

**Closed by mariogrip** 2021-09-08 00:48 UTC
Labels: bug, team: android9

**Comment by Flohack74** [comment] 2021-09-08 15:22
Works for me at least after ubports-qa ;)

**Comment by dadandalive** [comment] 2021-09-13 21:16
For what it's worth: 2G Internet works on Nexus 5, build 2021-W36/2

**Comment by c4pp4** [comment] 2021-09-15 15:01
> For what it's worth: 2G Internet works on Nexus 5, build 2021-W36/2

The same: RC 2021-W36/2 works on Mi A2.

**Comment by mardy** [comment] 2021-09-15 18:34
> The same: RC 2021-W36/2 works on Mi A2.

Same here: RC 2021-W36/2 has 2G data connection working on Redmi Note 7.
