### ISSUE TITLE
WIFI password. password is always needed to be input on reboot of tablet, everytime

### ISSUE THREAD

**Issue by ernmander** [ubports/ubuntu-touch#1040] opened 2019-01-25 16:08 UTC
### Illustrations

- Device:
- Channel:
- Build:

**Comment by ernmander** [comment] 2019-01-25 16:13
BQ M10 HD RC build

**Comment by simoxxx** [comment] 2019-02-11 18:04
this is my last week experience:
-i bought two of these tablets.
-they came with oreo preinstalled and i "fastly" flashed ubuntu-touch.
-this bug appears, i can not live with it!
-going back to android i understand this is a bug that affects many mediatek devices.. you can find information about it duckduckgoing "NVRAM ERROR 0X010"
-i tried alltheways (twrp,supersu) , nearly bricking, since i succeed in rooting it to modify some system files as they say on some tutorial.
-the error was gone but as soon as i reflashed ubuntu it was there again.
-this bug persist after flashing new things...
-after i said: why shall i root my phone when i can be root in ubuntu's terminal?
-**i made the system rw and with root i moved those files to nvram and changed their permissions.** 
-two easy steps and the MAC address is permanent again.

**Comment by Flohack74** [comment] 2019-02-12 22:08
Duplicate of a lot of other bugs...

**Closed by Flohack74** 2019-02-12 22:08 UTC
Labels: duplicate

**Comment by 1896er** [comment] 2019-10-08 08:28
Is this issue really solved? Where can I get more instructions to solve?

**Comment by simoxxx** [comment] 2019-10-09 21:22
Flashing ubports on your M10 HD (NON UBUNTU TOUCH VERSION) you probably corrupted 2 files where the wifi MAC address was written. Following my instructions above, you can find some informations on XDA.

**Comment by ezze** [comment] 2019-11-16 22:24
@1896er, I was also searching for exact steps to fix it on my brand dew Aquaris BQ M10 HD just flashed from Android 8.1.0 to Ubuntu Touch, and finally got it! Thanks to guys who posted a solution in [this UBports thread](https://forums.ubports.com/topic/3250/wifi-not-connectiong-after-reboot). It's something @simoxxx told about but these are steps that worked for me.

1. Download an archive with `WIFI` and `WIFI_CUSTOM` file to your tablet. Please note that `zip` archive rather than `rar` can be extracted on UT. So I had to repack it on my PC first:

    - [nvram-by-skyneel.com.zip](https://github.com/ubports/ubuntu-touch/files/3854789/nvram-by-skyneel.com.zip)

2. Open Terminal and switch to `root` user:

    ```bash
    $ sudo -i
    ```

3. Go to `Downloads` folder:

    ```bash
    $ cd /home/phablet/Downloads

    ```

4. Extract downloaded archive there:

    ```bash
    $ unzip nvram-by-skyneel.com.zip
    ```

    ![01](https://user-images.githubusercontent.com/665479/68999804-08fcd680-08d7-11ea-8bb0-ef73a5f2bf87.png)

5. Go to `/data/nvram/APCFG/APRDEB` directory:

    ```bash
    $ cd /data/nvram/APCFG/ARPDEB
    ```

6. You will probably see `WIFI` and `WIFI_CUSTOM` files there. Backup them:

    ```bash
    $ mv WIFI WIFI.backup
    $ mv WIFI_CUSTOM WIFI_CUSTOM.backup
    ```

7. Now copy these files extracted from the archive:

    ```bash
    $ cp /home/phablet/Downloads/WIFI* ./
    ```

8. Change files' permissions:

    ```bash
    $ chmod 660 WIFI*
    ```

    ![02](https://user-images.githubusercontent.com/665479/68999841-80326a80-08d7-11ea-809f-9bbb1985a6b0.png)

9. Now close everything and reboot the system. After reboot go to WI-FI settings, remove all previously used networks `<your wi-fi name>`, `<your wi-fi name 1>`, `<your wi-fi name 2>`, etc... Finally, connect to your WI-FI network again entering a password (hopefully last time).

10. Go to "System Settings" > "About" and check your device's MAC address. Reboot the tablet. Now it has to connect to your WI-FI automatically on startup and MAC address has to be left unchanged.

    ![03](https://user-images.githubusercontent.com/665479/68999926-ccca7580-08d8-11ea-8dd9-db6f5ae01d40.png)

Sources:

https://www.skyneel.com/how-to-fix-nvram-error-in-all-mediatek-devices
https://forum.xda-developers.com/showthread.php?t=2730486

**Comment by Flohack74** [comment] 2019-11-16 23:51
So to be clear here, does that mean that now all devices will have the same MAC address?

**Comment by simoxxx** [comment] 2019-11-17 00:11
Yes. I have two of these devices. i managed to find a file with a different mac for the second. But i was not able to modify the file and use the mac i like.

**Comment by Flohack74** [comment] 2019-11-17 08:20
So then thats not considered a real fix. It will make WiFi again unusable for 2 people in the same WLAN.

**Comment by ezze** [comment] 2019-11-17 15:12
@Flohack74, I agree with you but it was the only working fix I found so far.

As I mentioned above, I backed up the original `WIFI` file, and decided to make a little investigation. I opened the new (downloaded from Internet) `WIFI` file with Bless HEX Editor and compared it with the old one.

![Screenshot_20191117_175755](https://user-images.githubusercontent.com/665479/69009219-655a0780-0964-11ea-802d-297db6b15902.png)

As you can see (comparing with my previous "About" screenshot), MAC address is stored in six 16-bit characters starting from 4th position (zero-based). It's `D0 B3 3F 7D 95 B0` in our case. Looking at original `WIFI.backup` we get zeros only there. That's why MAC address was new on each reboot.

I guess that if you knew the original MAC address you can restore it easily using your favorite HEX editor. You also can change it to something different for a few devices in one network.

So you, guys, who want to have an original MAC address of device, please, get to know it from Android before flashing UT firmware.

**Comment by devonman01** [comment] 2019-11-18 21:16
https://www.youtube.com/watch?v=n49kukPf8HI

This is a well made explanation of a problem with 16:04

is this in any way related to what we are repeatedly fixing,
or is it a way of getting it to fix itself .
please delete this if i am going off the rails here

**Comment by Flohack74** [comment] 2019-11-19 07:40
No thats only for desktops that are being hibernated or on standby, and the resume doesn´t work. The problem you are facing here is that the file storing the MAC was lost or the nvram deleted. We know cases that caused in wrong usage of the MTK flash tool to reflash Ubuntu Touch version over from Android version. In such cases you need to be super careful with which options you select on the flash tool.
