### ISSUE TITLE
Keyboard sometimes disappears when writing SMS

### ISSUE THREAD

**Issue by Fazarel** [ubports/ubuntu-touch#2050] opened 2022-09-09 15:47 UTC
- Device:  [Pixel 3a (sargo)](https://devices.ubuntu-touch.io/device/sargo/)
- Channel: stable
- Build: OTA-23

### Steps to reproduce
Write an SMS of a few lines. The bug appears sometimes, it seems random, I did not spot any particular pattern. The virtual keyboard simply disappears. I have to close the SMS application and reopen it to use the keyboard again.

### Expected behavior
The virtual keyboard remains accessible while the message is being typed.

### Additional information
Maybe related to this issue? #1444 "Keyboard don't show everytime"

**Comment by lduboeuf** [comment] 2022-09-09 21:56
I notice that also on other apps (Telegram at least for sure) and since a long time ago. So this is a global issue i would say.

**Comment by lduboeuf** [comment] 2022-10-13 08:59
I have heard an interesting work around that may help find the root cause
If it happens, go back, enter again in the TextArea focus, tap on "space" first , you should be able to write again.

**Comment by lduboeuf** [comment] 2022-10-13 09:09
duplicate of https://github.com/ubports/ubuntu-touch/issues/1244

**Closed as completed by lduboeuf** 2022-10-13 09:09 UTC
