### ISSUE TITLE
[xenial] Error while recording Video 

### ISSUE THREAD

**Issue by strangerer** [ubports/ubuntu-touch#730] opened 2018-07-01 08:48 UTC
### Description of the feature
not able to live preview while  video recording

### Illustrations

- Device: hammerhead
- Channel:16.04
- Build:2018-w26

### Steps to reproduce
 camera -> video mode -> press record button

### Expected behavior
 live preview the things which is  happening before camera

  record and save the video with av

### Actual behavior

Not able to live preview while shooting
No video only audio is playing when playing recorded file
Gallery app does not shows the tile preview of video , only black title

**Comment by Flohack74** [comment] 2018-07-01 10:54
Probably related to #611 if not a duplicate of it. The guy there mentioned briefly also video issues.

**Comment by mauricioduarte01** [comment] 2018-07-01 11:01
Duplicated for sure. This bug appeared since day one on xenial.

**Closed** 2018-07-01 20:32 UTC
Labels: duplicate
