### ISSUE TITLE
[xenial] long click isn't working in uNav

### ISSUE THREAD

**Issue by GI9VANNI** [ubports/ubuntu-touch#747] opened 2018-07-05 12:57 UTC
Hi,
I point out that uNav is not currently available for Ubuntu Touch 16.04

https://open-store.io/app/navigator.costales

Although it's not a pre-installed app, I think it's important to fix this app before the release of Ubuntu Touch 16.04 stable.

**Comment by hummlbach** [comment] 2018-07-05 14:20
I ran the 15.04 build on mako@16.04 some time ago and it seem to work.

**Comment by GI9VANNI** [comment] 2018-07-05 15:25
I confirm that using the vivid version on xenial, the voices can not be downloaded and the button to exit uNav settings does not work.

**Comment by hummlbach** [comment] 2018-07-05 16:35
@costales i hope we see an official 16.04 version in the openstore soon(?) :)
@GI9VANNI I also rely on uNav and looking forward to having an official 16.04 build. But actually here is not the right place to request it. ;-) If and how app maintainers should be asked for providing an 16.04 build was covered in general in #706. Therefor I'm closing that one.

**Comment by costales** [comment] 2018-07-05 17:08
Hi,
@hummlbach You should not be closed this bug yet.
I already released it in Xenial, but it was a mess. The most critical bug was that the app hasn't the long click (regular javascript code) and if you click on voices, it will call a python (compiled, but in same arch) module.
IMHO This is coming from the OS and uNav should work in Xenial as in Vivid.
Best regards.

**Comment by hummlbach** [comment] 2018-07-05 17:55
Okay I renamed and reopened it. Then we should have a look why the long touch isn't working. Regarding the compiled python module(s) I'm a sceptical. Could or could not work. We already had both cases when we were messing with mycroft. There we could reuse mimic (pure c/c++) but not mycroft core (a lot [compiled] python modules).

**Comment by hummlbach** [comment] 2018-07-05 19:42
[application-click-navigator.costales_navigator_1.3.log](https://github.com/ubports/ubuntu-touch/files/2167981/application-click-navigator.costales_navigator_1.3.log)

Some python stuff seems to be linked against libpython3.4m.so.1.0 but in xenial we have 3.5 installed:
```
phablet@ubuntu-phablet:~$ find /usr -name "libpython3.*m.so*"
/usr/lib/arm-linux-gnueabihf/libpython3.5m.so.1.0
/usr/lib/arm-linux-gnueabihf/libpython3.5m.so.1
/usr/lib/python3.5/config-3.5m-arm-linux-gnueabihf/libpython3.5m.so
```
This is indeed the vivid version... @costales Where can i get the xenial version for debugging? Have you already tried to rebuild the python module(s) against an xenial rootfs? What errors did you get?

Unfortunately we don't see anything concerning the failing of the long touch.

**Comment by Flohack74** [comment] 2018-07-05 22:19
I consider this as an in-app problem unless some evidence is found that it is caused by the root fs or smth similar. So basically this is the wrong place to report it.

**Comment by costales** [comment] 2018-07-06 13:17
Hi @hummlbach 

> Where can i get the xenial version for debugging?


You can get the [current version](https://open-store.io/api/v3/apps/navigator.costales/download/vivid) as Xenial.

Thanks in advance!

**Comment by costales** [comment] 2018-07-07 15:48
Hi,

@hummlbach fixed the python issue.

About the long click, the setTimeout function is not working, for example, this will never be launched in a HTML app on phone:

`setTimeout(function(){ console.log('##### TIMER!! #####'); }, 4000);`

The dump message is:

`QObject:startTimer: Timers cannot be started from another thread`

The weird thing, it's working on desktop 16.04 with `qmlscene`. Any idea?

Thanks in advance!

**Comment by balcy** [comment] 2018-07-07 21:54
if I'm reading oxide-packaging correct, ubports xenial is using the 1.19.8 version of oxide.
Could this patch of oxide_qt_browser_thread_q_event_dispatcher.cc (https://github.com/ubports/oxide/commit/054a462c8ef0d2c9378e1894343ba3fa8497cd20#diff-cd38efd84e63aa141ab4302e1980244f) which came in a later version of oxide be relevant to the setTimeout problem ? (partly guessing here!) Maybe it can even be merged to our old oxide version...

**Comment by hummlbach** [comment] 2018-07-08 22:10
I don't get the `timers cannot be started from another thread` message... 
But I played around a little bit and it seems the problem is, that there are move and drag events killing the timer. (while there's no substantial drag or move indeed)
Anyone any idea on that?

**Comment by balcy** [comment] 2018-07-09 17:22
@hummlbach does https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_settimeout work in webbrowser-app (not browser-ng) on a device with xenial ? (works with aquaris 4.5 vivid)

**Comment by balcy** [comment] 2018-07-09 17:50
that it works on the desktop could be because the oxide (maybe qt as well?) version is different, or the problem is touch specific...
could it detect HTML5 drag events ? Then a workaround might be http://stackoverflow.com/questions/704564/ddg#13745199 in the html. But I don t know why the events are present..

**Comment by hummlbach** [comment] 2018-07-09 19:08
@balcy we actually want the timer to be cleared by these events, so diabling the events isn't really an option...
(Its really just guessing, but perhaps its an scaling issue and the threshold for drag and move events too small somehow.)

**Comment by hummlbach** [comment] 2018-07-10 15:10
@costales your workaround seems to work well... so can we close this as wontfix?

**Comment by costales** [comment] 2018-07-10 15:34
@hummlbach Yes, thanks for your support!

Anyway, another bug should be opened for the setTimeout (?).

Best regards.

**Comment by hummlbach** [comment] 2018-07-10 15:55
@costales the setTimeout works, but the timeout is cleared by drag/move events... Since the assumption is that this is caused by oxide, I close it...

**Closed by hummlbach** 2018-07-10 15:55 UTC
