### ISSUE TITLE
[xenial] Pro 5 won't boot properly after OTA update

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#425] opened 2018-01-11 08:45 UTC
- Device: Turbo
- Channel: 16.04/devel
- Build: 15?

### Steps to reproduce
Flash the phone with UBPorts installer and wait for it to complete.
After reboot it briefly shows the splash screen after which screen goes black, phone not responding to any taps or button presses
Unplug the phone and reboot
After reboot it briefly shows the splash screen after which screen goes black, phone not responding to any taps or button presses

### Expected behavior
Phone to boot into Ubuntu Touch UI

### Actual behavior
After reboot it briefly shows the splash screen after which screen goes black, phone not responding to any taps or button presses

### Logfiles and additional information
The phone is alive somehow, as PC shows the dialog:
**## Could not mount Pro5 Ubuntu Edition**
Could not open MTP device ”[usb:002,029]”

Also, from terminal, adb devices show the following:
```
~$ adb devices
List of devices attached 
GNU/Linux Device on rndis0 10.15.19.82	offline
```

**Comment by BigET** [comment] 2018-01-11 20:14
I can confirm that this is happening to my device also, but with no splash screen of ubports, just "meizu powered by ubuntu",

I can hear some clicks in the speaker like the one that you hear when you shortcircuit a speaker.

It seams that the audio hw is not initializing well.
[dmesg.log](https://github.com/ubports/ubuntu-touch/files/1623979/dmesg.log)
[logcat.log](https://github.com/ubports/ubuntu-touch/files/1623982/logcat.log)

**Comment by tomoqv** [comment] 2018-01-11 20:30
I meant also the "meizu powered by ubuntu" screen, not UBPorts. 
@BigET How did you extract the logs?

**Comment by kelmes** [comment] 2018-01-12 06:27
Wiping /system before installing solved this for me, but I had to manually extracting ubports-*.xz etc. to get it to install at all, so it might not have been the same issue.

**Comment by BigET** [comment] 2018-01-12 07:14
@tomoqv 
Just follow the instructions on:
https://docs.ubports.com/en/latest/contribute/bugreporting.html
since the adb works you can run the log extracting commands.

**Comment by tomoqv** [comment] 2018-01-12 08:26
@BigET 
My Pro 5 doesn't expose any adb interface. I will try to flash it back to 15.04.

**Comment by tomoqv** [comment] 2018-01-12 08:46
I succesfully flashed back to 15.04. After flashing (with wipe option) again to 16.04 gives me the same issue as above. Still no adb interface.

**Comment by mihaelmilea** [comment] 2018-01-12 13:05
How is it with the new r16 from today?

**Comment by tomoqv** [comment] 2018-01-12 13:18
I succesfully flashed back to 15.04. After flashing (with wipe option) again to 16.04 gives me the same issue as above. Still no adb interface.

**Comment by tomoqv** [comment] 2018-01-12 13:19
@mihaelmilea 
I don't know which version is the latest, but I flashed my Pro 5 this morning and the above issue persists.

**Comment by mihaelmilea** [comment] 2018-01-12 13:21
@tomoqv at 9:30 this morning a new version was released so I was curious if anything was fixed.

**Comment by tomoqv** [comment] 2018-01-12 13:51
Flashing right now, doesn't seem to be downloading any files though, just pushing to device...

**Comment by mihaelmilea** [comment] 2018-01-12 13:54
@tomoqv Ok, let me know... Thank you for testing it...

**Comment by tomoqv** [comment] 2018-01-12 13:58
Same issue after reflash at 14:50 CET.

**Comment by mihaelmilea** [comment] 2018-01-12 14:00
oh... Sorry...
If you check http://system-image.ubports.com/ubports-touch/16.04/devel/turbo/ you can see when a new version is available.

**Comment by tomoqv** [comment] 2018-01-12 14:03
I thought UBPorts automatically downloaded the latest version before flashing. I don't know where the downloaded xz files are stored, but when I find out I can delete them.

**Comment by mihaelmilea** [comment] 2018-01-12 14:07
Yes, the installer downloads the latest version. But by accessing that url you can see if a new version is available. Usually there is a new version every day around 9:30AM.

**Comment by tomoqv** [comment] 2018-01-12 14:10
Ok, then I think we can conclude that the problem persists with today's version.

**Comment by kelmes** [comment] 2018-01-13 03:30
The trouble I had installing was just a too small /cache partition. A fresh install of r16 with ubuntu-device-flash now boots to a black screen with no adb.

**Comment by kelmes** [comment] 2018-01-13 05:58
installing r14 works, but r15 gives a black screen. Updating in settings to r16 (from r14) breaks as well.

**Comment by kelmes** [comment] 2018-01-13 07:56
installing anbox in r14 then rebooting seems to have the same effect.

**Comment by mihaelmilea** [comment] 2018-01-13 08:47
r17 was released....

**Comment by kelmes** [comment] 2018-01-13 09:35
r17 is the same

**Comment by kelmes** [comment] 2018-01-13 09:37
although adb devices now shows:
GNU/Linux Device on rndis0 10.15.19.82	offline

**Comment by mihaelmilea** [comment] 2018-01-13 09:43
Well, I know @mariogrip has a Pro 5 and does tests on it so I hope this will be fixed soon...

**Comment by tomoqv** [comment] 2018-01-14 12:17
New flash with 'wipe' today with the same problem. It would be really nice to get this fixed in order to test 16.04 more and Anbox.

**Comment by mihaelmilea** [comment] 2018-01-14 12:24
There is no new version for today so you flashed the same version from yesterday.

**Comment by mihaelmilea** [comment] 2018-01-15 10:04
There is now a new version...

**Comment by tomoqv** [comment] 2018-01-15 10:16
Already tried it. Nothing has changed.

**Comment by mihaelmilea** [comment] 2018-01-15 10:19
:(

**Comment by mihaelmilea** [comment] 2018-01-16 10:13
Any news for today?

**Comment by kelmes** [comment] 2018-01-17 06:01
No change.

**Comment by kelmes** [comment] 2018-01-17 07:57
installing the update to libmirprotobuf3 (which gets pulled by anbox-ubuntu-touch) in r14 has exactly this effect.

**Comment by Flohack74** [comment] 2018-01-17 08:28
@tomoqv Did you also install Anbox?

**Comment by tomoqv** [comment] 2018-01-17 08:41
@Flohack74 
No, just "plain vanilla" Xenial with wipe option.

**Comment by Flohack74** [comment] 2018-01-17 09:21
Ok can you then please check if you have this lib also installed?

**Comment by tomoqv** [comment] 2018-01-17 09:34
@Flohack74 
I don't have my Pro 5 with me today, but how can I check that when my phone doesn't expose any adb interface? I have a black screen and when attached to my PC i get:
## Could not mount Pro5 Ubuntu Edition
Could not open MTP device ”[usb:002,029]”
and no adb devices are listed.

**Comment by Flohack74** [comment] 2018-01-17 09:44
Hmm a difficult case, but in theory you could boot into recovery. But then I dont know if the standard recovery even has ADB. With TWRP I could go inside, loop-mount the image and start investigating in a chroot. Ok its easier to look into our imagebuilder maybe :) - What I dont understand, does this affect now all Pro 5 users? @mariogrip Can you take a look at this plz?

**Comment by Ruditimmermans** [comment] 2018-01-17 10:24
@ Flohack74, i have the same problem when i install the lasted build on my Pro 5, when i install the r14 it works, but when i try install then Anbox en doe anbox setup anbox keep spinning and it dont start, so mabay it need the lasted build i dont know...

**Comment by kelmes** [comment] 2018-01-18 03:04
libmirprotobuf3 is installed in r14 and r20, just different versions. The version r14 updates to with apt at the moment is different to either of these.

 r14 has version:
0.24.20ubuntu11+ubports+0~20180105162913.9~1.gbp713a61 from http://repo.ubports.com 

installing anbox-ubuntu-touch pulls version:
0.26.2+16.04.20170322.1-0ubuntu1 from  http://ppa.launchpad.net/ci-train-ppa-service/stable-phone-overlay/ubuntu xenial/main

r20 has:
0.24.20ubuntu11+ubports+0~20180110152441.10~1.gbp713a61 from http://repo.ubports.com

**Comment by kelmes** [comment] 2018-01-18 03:32
Installing the r20 version in r14 doesn't break anything, so I'm guessing this is a different issue.

**Comment by Ruditimmermans** [comment] 2018-01-20 11:26
Anyone try the lasted r22 ?

**Comment by kelmes** [comment] 2018-01-21 03:12
No difference on r22.

Looking at http://ci.ubports.com/, it looks like rootfs [build 202](http://ci.ubports.com/job/xenial-rootfs-armhf/202/) triggered r15. Comparing the manifests for rootfs 202 and 201, the differences seem to be:

libmirclient9
libmircommon6
libmircookie2
libmirplatform13
libmirprotobuf3
libmirserver41
mir-client-platform-android5
mir-graphics-drivers-android
mir-platform-graphics-android10
mir-platform-input-evdev5
mir-utils
unity-system-compositor

are all `0.24.20ubuntu11+ubports+0~20180110152441`, instead of `0.24.20ubuntu11+ubports+0~20180105162913`

Installing these one at a time in r14 works for everything except `mir-platform-graphics-android10:armhf (0.24.20ubuntu11+ubports+0~20180110152441.10~1.gbp713a61)`, which appears to be installed in r15 and up, and causes this bug if installed in r14.

**Comment by kelmes** [comment] 2018-01-21 03:18
Interestingly, I seem to still have adb this way, logs attached

[dmesg.txt](https://github.com/ubports/ubuntu-touch/files/1649488/dmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1649487/UTlogcat.txt)

**Comment by kelmes** [comment] 2018-01-21 04:39
installing mir26 (a complete apt upgrade from [here](http://repo.ubports.com/pool/xenial_-_mir26/main/)) solves this, including on r22, although now I don't have a keyboard. Given that the anbox package seems to depend on some mir 0.26 components as well, are we planning to upgrade any time soon?

**Comment by kelmes** [comment] 2018-01-21 05:56
For a less drastic solution, installing `mir-platform-graphics-android10:armhf (0.24.20ubuntu11+ubports+0~20180105162913.9~1.gbp713a61)` in r22 works as well

**Comment by kelmes** [comment] 2018-01-21 06:19
From what I can tell [build 10](http://ci.ubports.com/job/ubports/job/mir/job/xenial/10/) and [build 9](http://ci.ubports.com/job/ubports/job/mir/job/xenial/9/) were build from the same source [here](https://github.com/ubports/mir/tree/713a61529af29a6246e19ea15618af78645ead67), but the .deb files are definitely different, and somehow build 10 seems to be broken.

**Comment by tomoqv** [comment] 2018-01-23 08:49
Any progress on this? Flashed latest version a few minutes ago and still unable to boot. I would be happy to help testing 16.04 and Anbox.

**Comment by Ruditimmermans** [comment] 2018-01-23 18:52
I like to see this also fixed asap...

**Comment by Stefano0101** [comment] 2018-01-23 20:31
kelmes 
How did you you increased the size of he cache partition(recovery) ??? Could you explain how to do that, please? Step by step, if possible. Thanks.

**Comment by BigET** [comment] 2018-01-24 12:11
> How did you you increased the size of he cache partition(recovery) ??? Could you explain how to do that, please? Step by step, if possible. Thanks.

This is not the right place to ask these questions. ask on the telegram group. However:

https://askubuntu.com/questions/514913/how-to-get-a-larger-root-partition-on-touch/781246?s=1|18.2028#781246

Look at the E.Timotei's answers.

**Comment by Ruditimmermans** [comment] 2018-01-25 12:02
Someone got more news it is fixed yet?

**Comment by tomoqv** [comment] 2018-01-26 08:46
r24: It boots again! Great job @mariogrip !

**Comment by mihaelmilea** [comment] 2018-01-26 08:51
Really? Wow! A big Thank You @mariogrip !!! This means the developement goes on... We are waiting for the fingerprint to work now :)

@BigET : check https://forums.ubports.com/topic/927/how-to-increase-cache-partition-or-any-partition-on-ubuntu-touch-phone-question/5

**Comment by Ruditimmermans** [comment] 2018-01-26 15:40
Great work @mariogrip !

**Comment by tomoqv** [comment] 2018-02-06 12:00
I would consider this fixed. The Pro 5 boots after OTA upgrade as well as after UBPorts installer flash. However, there is one slight issue after OTA upgrade. The phone doesn't boot until after a hard reset following the upgrade. Happened to me after the last couple of upgrades.

**Closed** 2018-02-22 22:44 UTC
Labels: bug, device: turbo
