### ISSUE TITLE
[xenial] Constant crashing of service "ubuntu-location"

### ISSUE THREAD

**Issue by hoh61** [ubports/ubuntu-touch#582] opened 2018-05-03 22:06 UTC
### Illustrations

- Device:BQ M10 FHD (frieza)
- Channel:16.04/devel
- Build:R67

### Steps to reproduce

constant error message 
cannot switch on GPS

### Logfiles and additional information

mtp://[usb:001,015]/Aquaris%20M10%20FHD%20Ubuntu%20Edition/Documents/android.log

mtp://[usb:001,015]/Aquaris%20M10%20FHD%20Ubuntu%20Edition/Documents/syslog
[android.log](https://github.com/ubports/ubuntu-touch/files/1972787/android.log)
[syslog.txt](https://github.com/ubports/ubuntu-touch/files/1972788/syslog.txt)

**Comment by NeoTheThird** [comment] 2018-05-04 10:36
The Fairphone 2 is not affected either, nor is the Nexus 5. When reproducing, make sure the location toggle *does not turn at all*. If it does, and location simply takes long to be read, that is a different issue.

**Comment by advocatux** [comment] 2018-05-04 14:29
I can't reproduce this bug on a BQ E4.5 16.04 (r67). It seems the GPS is working fine.
I can switch the GPS on and off, uNav works, etc

**Comment by hoh61** [comment] 2018-05-04 16:30
To NeoTheThird:
I saw these error messages when I was going through the other irregularities I found and notified. GPS was constantly off. Before issuing this bug I checked the GPS switch. Sorry for having overseen the old bug report.

**Comment by mariogrip** [comment] 2018-05-05 16:02
This: https://github.com/ubports/ubuntu-location-provider-geoclue2/pull/1 seems to fix it

**Comment by mariogrip** [comment] 2018-05-05 16:40
Merged, closing for qa to confirm.

**Comment by NeoTheThird** [comment] 2018-05-06 08:26
Still an issue on cooler in r68.

**Comment by hoh61** [comment] 2018-05-06 12:09
Still an issue  in R68 on frieza. No change in /etc/init/ubuntu-location-service.override found.

**Comment by NeoTheThird** [comment] 2018-05-07 10:14
Still an issue on cooler in r69.

**Comment by mariogrip** [comment] 2018-06-18 12:01
Fixed by https://github.com/ubports/libhybris/pull/5

**Closed by mariogrip** 2018-06-18 12:01 UTC
Labels: bug, critical (rc), device: cooler, device: frieza

**Comment by hoh61** [comment] 2018-06-19 22:45
location service is working on my frieza with revision 2018-w25
