### ISSUE TITLE
Adding new contact phone number from messaging app defaults to Skype

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#878] opened 2018-09-11 09:55 UTC
- Device: Turbo
- Channel: 16.04 RC
- Build: 2018-W35

### Steps to reproduce
Open a text message from a phone number not in your phone book
Tap the "add contact" button
Select "+Add new" from the contacts window

### Expected behavior
A new contact card with the phone number added as "Mobile"

### Actual behavior
A new contact card with the phone number added as "Skype"

In order to add the new phone number as "Mobile", you have to manually add a new contacts field "Mobile" and enter the phone number in that field before saving.

**Comment by UniversalSuperBox** [comment] 2018-09-11 17:33
Confirmed on Nexus 5 and Fairphone 2

**Comment by mardy** [comment] 2018-09-11 20:56
Confirming on the BQ 4.5 too. Another weirdness, is that the page to add the contact has a "Delete contact" button, as if we were modifying an existing contact and not creating a new one.

**Comment by mardy** [comment] 2018-09-12 20:19
I don't think that this is caused by the QtPim update; it would be nice if someone wanted to try to reproduce this bug with the OTA4 release, but I'm quite sure that the bug would also be there. It's a bug in messaging app, caused by this commit:
https://bazaar.launchpad.net/~phablet-team/messaging-app/staging/revision/660#src/qml/messaging-app.qml

Note that this commit is not in the `master` (or `trunk`, in Launchpad terminology) branch, but only in the `staging` (unstable) branch. I'm now trying to understand if it's better to partially revert that commit, or to fix it. It was made to support the IRC protocol, but I'm not sure that we want to handle IRC in messaging-app...

**Comment by mardy** [comment] 2018-09-13 21:17
A full fix for this issue requires changes in three components. Please see the merge proposals linked to this issue.

**Closed** 2018-09-14 21:04 UTC
Labels: bug, good first issue, help wanted
