### ISSUE TITLE
Indicator opening in blank area won't open

### ISSUE THREAD

**Issue by cm-t** [ubports/ubuntu-touch#1366] opened 2020-02-14 07:18 UTC
- Device: Meizu PRO5 internationnal - turbo
- Channel: candidate
- Build: 2020-W07/2

### Steps to reproduce

descibed behavior affect phone only unity's behavior. But maybe there is a discussion on tablet/desktop to enlarge the left side of triggering indicator, but not my focus here.

behabior described is (in my memory) a regression

* phone is switched on
* unlocked, you can succesfully swipe in an out the app menu.
* try to open any indicator by swiping from top to bottom. Before reaching the middle of screen, if you selected wrong indicator, you can during this same swipe and without releasing the finger, swipe sides to the indicator you wanted then continu the bottom swipe
* now try to open messaging indicator with your potatoe finger
* if you add it perfect: you open it
* if you was a bit on the right side: you can, as mentionned before, reselect the wanted indicator during the opening
* if you was a bit on the left side : nothing happen, can't even fix your swipe as mentionned before.

### Expected behavior

* if finger is on the top panel but at the left side, it should open the indicator panel, with the one the most at left (here : messaging notification)

### Actual behavior

* if finger a bit at left of messaging indicator, nothing happend. it creates a small but daily frustration: user thinks he is clever so he doesnt need to focus too hard to open message notifications, swipe at the very left side. nothing happen. must focus better for an action he will do a lot daily.

### Logfiles and additional information

* N/A

**Comment by hummlbach** [comment] 2020-02-14 07:25
Yes already talked to others... somehow we tend to swipe down from slightly left of the envelop icon and then nothing happens ofc. Maybe we can add a liitle extra space for opening the most left indicator...?

**Comment by cm-t** [comment] 2020-02-14 07:31
@hummlbach adding this extra space is a good discussion, but imho, until there is a new design reason to reduce it (or an existing one but i,m not aware of it), it should be the same as before **(on phone)**: all the screen size.

i'm pretty sure the behavior before this update was discussed at canonical to make on purpose an exception to allow all screensize when it is phone, just to make sure the most used indicator will got the love it needs ^^

**Comment by hummlbach** [comment] 2020-02-14 07:34
@cm-t i think we created a duplicate of #1233 here. Lets close this and add our comments to #1233.

**Closed by hummlbach** 2020-02-14 07:34 UTC
