### ISSUE TITLE
Multitask in mobile mode

### ISSUE THREAD

**Issue by GermanAizek** [ubports/ubuntu-touch#1823] opened 2021-09-08 13:52 UTC
Device: Xiaomi Redmi Note 7
Ubuntu Touch: 16.04 dev branch

Please add the ability to multitask in step-by-step (mobile) mode like window mode.
Example: There is no way to listen to music and communicate in the messenger.

**Comment by Flohack74** [comment] 2021-09-09 08:38
What app are you using for music? Music will play fine in the background with the official music app or cloud music app, e.g. Proper apps implement playback via media-hub, that can run in the background.

**Comment by GermanAizek** [comment] 2021-09-09 09:19
> 
> 
> What app are you using for music? Music will play fine in the background with the official music app or cloud music app, e.g. Proper apps implement playback via media-hub, that can run in the background.

Default web-browser. Youtube tab and anbox app, also does not run in the background. Everything works only in Desktop mode.

**Comment by GermanAizek** [comment] 2021-09-09 09:43
@Flohack74,
So it works in window mode, make a switch that allows you to work in parallel in mobile mode. And you have everything wrapped in containers, it should be so safe considering that Ubuntu Touch on Lineage OS.
My device has 6 GB Ram and I don't care how much is open parallel windows, I have enough and it is convenient.

**Comment by GermanAizek** [comment] 2021-09-12 19:05
@Flohack74,
This problem was still found in the lock screen, if you turn on the pin code, then when you lock the phone, the music disappears, as well as the work of all applications. But if you switch to desktop mode, then everything is fine.

**Comment by mateosalta** [comment] 2021-09-20 14:33
> @Flohack74,
> So it works in window mode, make a switch that allows you to work in parallel in mobile mode. And you have everything wrapped in containers, it should be so safe considering that Ubuntu Touch on Lineage OS.
> My device has 6 GB Ram and I don't care how much is open parallel windows, I have enough and it is convenient.

download ut tweak tool - in there you can allow any app to bypass the app suspension

**Comment by GermanAizek** [comment] 2021-09-20 18:22
> 
> 
> > @Flohack74,
> > So it works in window mode, make a switch that allows you to work in parallel in mobile mode. And you have everything wrapped in containers, it should be so safe considering that Ubuntu Touch on Lineage OS.
> > My device has 6 GB Ram and I don't care how much is open parallel windows, I have enough and it is convenient.
> 
> download ut tweak tool - in there you can allow any app to bypass the app suspension

I do, but it's very uncomfortable

**Comment by dobey** [comment] 2021-09-20 18:39
> My device has 6 GB Ram and I don't care how much is open parallel windows, I have enough and it is convenient.

It's not to save RAM, but for power management. UT doesn't have background applications. Youtube and browser playback on Android also stop when you lock the screen. Windowed mode is not the solution to whatever you think the problem is. Nor is there any problem with "multi-tasking".

It is certainly possible to listen to music while typing in messenger already. For browser, the solution would be to get browser media playback to go through media-hub, which is quite a monumental task, given QtWebEngine is not already using QtMultimedia for audio/video playback.

I'm closing this because this is not an actionable issue, and there are solutions for the specific use case mentioned already. Ubuntu Touch is not a traditional PC Linux distribution, and phones are not traditional PCs.

**Closed by dobey** 2021-09-20 18:39 UTC

**Comment by mateosalta** [comment] 2021-09-21 17:04
> > > @Flohack74,
> > > So it works in window mode, make a switch that allows you to work in parallel in mobile mode. And you have everything wrapped in containers, it should be so safe considering that Ubuntu Touch on Lineage OS.
> > > My device has 6 GB Ram and I don't care how much is open parallel windows, I have enough and it is convenient.
> > 
> > 
> > download ut tweak tool - in there you can allow any app to bypass the app suspension
> 
> @mateosalta I do, but it's very uncomfortable

i mean in apps section, select a app and then the toggel 'prevent app suspension' with that you can still use mobile mode instead of windowed
