### ISSUE TITLE
Missing wifi on-off switch on FP2

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#703] opened 2018-06-21 10:21 UTC
fairphone2 with xenial RC
the wifi switch is missing, not sure what happened, the wifi did work right after flashing the phone. restarting the phone doesn't help. how can i debug this?

**Comment by pixelr0** [comment] 2018-06-21 13:16
managed to get wifi back again by reseting and erasing from System Settings. still better than reflashing :D

**Comment by pixelr0** [comment] 2018-06-30 19:17
and again the wifi switch is missing :(
i just powered off the phone for a couple of days and now when i powered on i don't have wifi
i'll let it in this state. 
not sure how to debug nor trigger the bug, but if you need some logs i can upload them

**Comment by NeoTheThird** [comment] 2018-06-30 21:06
It might be also the race condition we see on the nexus 5. Thoughts @mariogrip?

**Comment by Flohack74** [comment] 2018-07-01 10:56
Confirmed on my FP2...

**Comment by pixelr0** [comment] 2018-07-06 18:56
workaround to enable wifi, go to settings -> battery -> turn on wifi but the switch in the panel is still missing

**Comment by pixelr0** [comment] 2018-07-11 13:21
rc4/fp2 same

**Comment by UniversalSuperBox** [comment] 2018-07-11 17:21
I had hoped that the fix to urfkill for the Nexus 5 would fix this as well. Unfortunately the switch has gone away again for me. Back to the drawing board.

**Comment by pixelr0** [comment] 2018-07-11 18:00
oh well, better luck next time :P

**Comment by pixelr0** [comment] 2018-07-23 08:16
yep, seems to be fixed now.
o/

**Comment by Don-Jojo** [comment] 2018-11-19 08:30
Hello, same bug here: FP2 with OTA-5. I just flashed the phone, but the wifi on-off button is missing. The workaround with going to system settings -> battery -> wifi on/off works. The wifi is working, only the button for turning it on off is missing in the black panel that you can pull down from the top and in system settings -> wifi.

**Comment by UniversalSuperBox** [comment] 2018-12-16 03:54
Closing as this is a duplicate of #168

It sounds like a workaround is to use the switch in the Battery settings for now. We'll continue tracking the bug at #168.

**Closed by UniversalSuperBox** 2018-12-16 03:54 UTC
Labels: bug, device: FP2
