### ISSUE TITLE
Text input in the browser

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubuntu-touch#270] opened 2017-09-25 07:59 UTC
- Device:Nexus 4
- Channel:Stable
- Build:Rev. 1

## Steps to reproduce

1. Write any text in the browser

## Expected behavoir

...

## Actual behavior

When rewriting, the last written word appears.

## Logfiles and additional information

...

**Comment by giovanoiannotti** [comment] 2017-09-25 08:54
That happens to me too, using bq 4.5. But, that's not new. This has always happened, since I first got the telephone, years ago.

**Comment by Flohack74** [comment] 2017-09-26 20:03
This is a duplicate of one or more other bugs already reported here or in keyboard-component project.

**Comment by balcy** [comment] 2017-10-01 16:24
https://github.com/ubports/oxide/issues/1

there is a temporary workaround: for me the problem does not occur, if all keyboard features (spell checking, correction...) are switched off

if someone can help me getting started with compiling oxide, please help by posting it here : https://forums.ubports.com/topic/583/build-oxide

**Comment by balcy** [comment] 2017-10-01 16:28
@giovanoiannotti are you sure it happens for the telegram app as well ? For me only in the browser version of telegram.

**Comment by Flohack74** [comment] 2017-10-02 06:35
It happens only in the browser or in webapps, which might be WebTelegram ofc.

**Comment by JCLemme** [comment] 2017-10-03 19:50
I've noticed this too - I'm on r166 on the devel branch.

**Comment by giovanoiannotti** [comment] 2017-10-04 06:56
@balcy, @flohack74 is right. It's webtelegram.

**Comment by userj** [comment] 2017-10-22 22:00
Related issue https://github.com/ubports/keyboard-component/issues/7

Still happening.

**Comment by NeoTheThird** [comment] 2017-10-23 15:57
duplicate of https://github.com/ubports/keyboard-component/issues/7.

**Closed by NeoTheThird** 2017-10-23 15:57 UTC
Labels: duplicate
