### ISSUE TITLE
Add screenshot delay

### ISSUE THREAD

**Issue by dieharddan** [ubports/ubuntu-touch#1380] opened 2020-02-24 15:14 UTC
Hello, I think there should be a slight delay of a second or so when taking a screenshot with the volume buttons as I have probably a dozen or more unintended screenshots in my photo album. A lot of times I take a screenshot instead of changing the volume or take one when grabbing the phone off the table for example

Thanks

**Comment by UniversalSuperBox** [comment] 2020-02-24 21:08
Hi @dieharddan,

I think this is a duplicate of https://github.com/ubports/ubuntu-touch/issues/1015, "Significant numbers of unintentional screenshots occurring". For that reason, I'll close this one in favor of keeping one place to track an issue.

**Closed by UniversalSuperBox** 2020-02-24 21:08 UTC
Labels: enhancement
