### ISSUE TITLE
Network details does not close after forgetting a network

### ISSUE THREAD

**Issue by vlladdrakk** [ubports/ubuntu-touch#879] opened 2018-09-11 23:31 UTC
- Device: Nexus 4 (Mako)
- Channel: Development
- Build: 2018-09-11

### Steps to reproduce

1. Open the settings app.
2. Tap 'Wifi.'
3. Scroll down to the bottom of the page and tap 'Previous networks.'
4. Select a network from the list (tap on it).
5. Tap the 'Forget this network' button.

### Expected behavior

The 'Network details' screen should close and the 'Previous networks' screen should display without the network that was just forgotten.

### Actual behavior

It appears that nothing happens until you go back to the previous screen and see that the network was indeed removed from the 'previous networks' list.

**Comment by Flohack74** [comment] 2019-07-03 19:55
Can you retest with latest OTA? I cannot reproduce this anymore... I just deleted 12 WiFi entries and for all the current details were closed and i was taken back to the list.

**Comment by Flohack74** [comment] 2019-07-03 20:07
Duplicate of https://github.com/ubports/system-settings/issues/68

**Closed by Flohack74** 2019-07-03 20:07 UTC
Labels: bug, team: ui
