### ISSUE TITLE
[xenial] - Calendar Online account

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#589] opened 2018-05-09 16:48 UTC
### Illustrations

- Device: Hammerhead
- Channel: devel
- Build: 368

### Steps to reproduce

Try to add an new calendar account

### Expected behavior
Allow to create or connect to an online account (Caldav or Nextcloud Online account)

### Actual behavior
Doesn't offer possibility to create or connect, popup empty.

This feature works on Xenial for Umark, so it seems to be related to the calendar app itself. 

### Logfiles and additional information
I'll try to get something

**Comment by UniversalSuperBox** [comment] 2018-05-19 18:06
I can confirm this on the Nexus 5 and Fairphone 2. Watching the log when opening the Online Accounts screen gives the following error repeated a bunch of times:

`(process:5552): accounts-glib-CRITICAL **: ag_application_get_service_usage: assertion 'self != NULL' failed`

**Comment by mariogrip** [comment] 2018-05-20 15:16
@mardy any idea about this one? :)

**Comment by NeoTheThird** [comment] 2018-06-09 14:37
Duplicate of #602

**Closed** 2018-06-09 14:37 UTC
Labels: duplicate
