### ISSUE TITLE
Bug report in BQ 4.5 phone not working

### ISSUE THREAD

**Issue by chrisburmajster** [ubports/ubuntu-touch#1002] opened 2018-12-14 19:23 UTC
<The phone in the BQ 4.5 is not working. It's paired with the Citroen C6 and it logs on but when it rings it doesn't ring through the car's audio and I can't get it to come through the car's audio.!------------------------------------------------------------------------------
--------------------------------------------------------------------------------

Thank you for wanting to file an issue! If you have a minute, please take the time to read our guide on writing a good bug-report:

    https://docs.ubports.com/en/latest/contribute/bugreporting.html

If not and you just want to get this over with, that's also quite alright. But please try to format your issue correctly, to make it easier for us to read. Below, we provide a template for a feature-request and a bug-report. Use common sense to determine what category your issue falls under and delete the template you don't need. Also, you don't need to stick to the templates under all circumstances. If you don't need a heading, remove it. If you think a new section will provide valuable information, add a new heading. We're not dogmatists, we're pragmatists who just want to be able to efficiently work with new issues.

--------------------------------------------------------------------------------
------------------------------------------------------------------------------->

### Illustrations

- Device:
- Channel:
- Build:

**Comment by UniversalSuperBox** [comment] 2018-12-14 19:47
Duplicate of #994

**Closed by UniversalSuperBox** 2018-12-14 19:47 UTC
