### ISSUE TITLE
Add turkish keyboard

### ISSUE THREAD

**Issue by turanmahmudov** [ubports/ubuntu-touch#373] opened 2017-12-20 23:41 UTC
https://github.com/ubports/keyboard-component/pull/17

**Comment by NeoTheThird** [comment] 2018-05-06 23:13
Should be fixed https://github.com/ubports/keyboard-component/pull/41

**Closed by NeoTheThird** 2018-05-06 23:13 UTC
Labels: enhancement, team: ui

**Comment by Flohack74** [comment] 2018-05-21 14:51
@turanmahmudov the keyboard is now added to the xenial 16.04 devel channel. Can you check (from tomorrow) if it works as intended?

**Comment by turanmahmudov** [comment] 2018-05-22 09:53
@Flohack74 thanks. Sure I will check it this evening.
