### ISSUE TITLE
Random crashing 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#29] opened 2017-05-27 22:23 UTC
I thought this was browser/webapp related but I have also had it happen when on the Apps scope when I'm pretty sure there is no online activity or web services being consumed.

Basically the phone's UI freezes for a few seconds and the phone reboots itself. Happens a couple of times a day to me.

reported by https://launchpad.net/~tom-rhodes.
https://launchpad.net/~mgc.lude adds:
Likewise, same conditions. Happens to me at least 1 / 2 times a day. Before it reboots it becomes unresponsive and sluggish. Could be a regular crash from overload.

https://launchpad.net/~tom-rhodes adds:
Attaching some logs, these are directly after a crash (well a couple of minutes - the time it took to fire up the laptop and pull them etc)
https://bugs.launchpad.net/ubports-fp2/+bug/1662931/+attachment/4835437/+files/syslog
https://bugs.launchpad.net/ubports-fp2/+bug/1662931/+attachment/4835438/+files/unity8.log
https://bugs.launchpad.net/ubports-fp2/+bug/1662931/+attachment/4835440/+files/unity8-dash.log
https://bugs.launchpad.net/ubports-fp2/+bug/1662931/+attachment/4835441/+files/unity8-dash.log.1

https://launchpad.net/~andybleaden adds:
Have you tried editing the app inactivity suspend option via one of the open store Unity Tweak Tools
https://open.uappexplorer.com/app/ut-tweak-tool.sverzegnassi
and seeing if that helps
Must say the Fp2 appears to crash/restart more often than my Nexus 5 when inactive but that could be me

**Comment by Stefano0101** [comment] 2017-06-04 20:50
I have experienced a crash when using Ubports web app. Device became unresponsive and rebooted after short while.

**Comment by Flohack74** [comment] 2017-06-04 21:17
I have this rarely, too. But on E5: Out of nothing suddenly unity 8 reboots. I suspect somewhere there might be a memory leak and that leads to a OOM kill....

**Comment by sverzegnassi** [comment] 2017-06-04 21:38
@Flohack74 Once it happened to me too, on BQ E5. I had a quick look before the phone became completely unresponsive, and I've spotted an suspicious CPU/MEM usage from unity8-dash.

However I'm not sure whether this is the direct cause of the issue or not, as many services are invoked by U8 scopes during runtime. Also, given the different status of the devices involved, there might be different issues triggering the same behavior

**Comment by bastos77** [comment] 2017-10-04 12:42
Happend sometimes on FP2 rc6

**Comment by NeoTheThird** [comment] 2017-10-04 15:27
It just happened on my latest-batch FP2 running the latest devel several times. Here's a [dmesg](https://github.com/ubports/ubports-touch/files/1356370/UTdmesg.txt).

**Comment by bastos77** [comment] 2017-11-06 10:28
Random reboots also here FP2 rc11

**Comment by derkleinemannvomfeldweg** [comment] 2018-01-24 09:04
I can't confirm the randomness of the reboots on FP2 (rc21). It seems really related to usage of browser and webapps and especially closing them (but not limited to closing)

Steps to reproduce:
1. Open browser and e.g. Twitter
2. Close one of the two Apps

Expected behavior:
The phone should close the app and continue working.

Observed behavior:
The phone freezes for a moment, then reboots. First, it boots till the Fairphone splash screen, then it gets dark again and again reboots to Fairphone splash screen and then to ubuntu. (Does it enter fastboot mode in between?)

I observe this behavior up to 15 timrs/day. If necessary, I can provide logs.

**Comment by bastos77** [comment] 2018-01-24 18:14
I can confirm derkleinemannvomfeldweg observations :-(

**Comment by Flohack74** [comment] 2018-01-24 18:51
Ok can we maybe outrule a few things like it crashes only with web browser or web apps? Unfortunately I dont feel like its the case...

**Comment by derkleinemannvomfeldweg** [comment] 2018-01-24 19:01
Ate there any logs to check which could be of relevance?

**Comment by Flohack74** [comment] 2018-01-24 19:36
None that I know of. Probably the restart happens in the Android part. Its then not so easy to get a logcat of it.

**Comment by kwah-gh** [comment] 2018-09-17 21:40
Might be related.

In a couple of days I observed degradation in apps, which I could run. First web-app that I use on a day-to-day basis started to crash, until at some point I could not start it anymore... So, I was in a situation, where I could not start: aforementioned web-app, browser, telegram app, at the same time terminal was still working (these are just a few, I have checked). Got via adb to syslog, while trying to start browser. Here is the log snippet, where browser got killed:

`Sep 17 23:20:47 ubuntu-phablet kernel: [1350922.391830]select 'unity8-dash' (9732), adj 50, size 12737, to kill
Sep 17 23:20:47 ubuntu-phablet kernel: [1350922.391886]select 'webbrowser-app' (23988), adj 110, size 16565, to kill
Sep 17 23:20:47 ubuntu-phablet kernel: [1350922.391924]Killing 'webbrowser-app' (23988), adj 110,
Sep 17 23:20:47 ubuntu-phablet kernel: [1350922.391929]   to free 66260kB on behalf of 'oxide-renderer' (24076) because
Sep 17 23:20:47 ubuntu-phablet kernel: [1350922.391934]   cache 65268kB is below limit 65536kB for oom_score_adj 12
Sep 17 23:20:47 ubuntu-phablet kernel: [1350922.391939]   Free memory is -1960kB above reserved [gfp(0x200da)]
`
After reboot I can run all apps again.

BQ e4.5. 15.04 (r3)

**Comment by zubozrout** [comment] 2018-09-18 08:11
I am experiencing similar issues for about the same time this has been reported but I thought that it had something to do with Telegram (or more precisely networking) - because I was lucky it usually happened when I received a message (I saw a notification on desktop and before it was displayed on my phone it rebooted itself). It also happens from time to time in a subway when it goes offline in tunnels in between stations with no mobile coverage.

Sometimes only Unity crashes - sometimes the whole system reboots itself.

I am on MX4 (arale) - usually the latest devel release for more fun :).

**Comment by Flohack74** [comment] 2018-09-18 08:59
@kwah-gh Can you check the free space on the main partition? We had cases when this was causes by having no space left on the storage.

**Comment by kwah-gh** [comment] 2018-09-18 19:03
@Flohack74 That was first thing I've looked at.
Here it is:
```
Filesystem                                   Size  Used Avail Use% Mounted on
udev                                         479M  4.0K  479M   1% /dev
tmpfs                                         97M  328K   96M   1% /run
/dev/mmcblk0p7                               4.4G  2.1G  2.2G  50% /userdata
/dev/mmcblk0p6                               2.0G  1.7G  382M  82% /
/dev/loop0                                   141M  139M  1.8M  99% /android/system
none                                         4.0K     0  4.0K   0% /android
tmpfs                                        481M  4.0K  481M   1% /etc/fstab
tmpfs                                        481M  1.1M  480M   1% /var/lib/lxc/android/rootfs
/dev/disk/by-path/platform-mtk-msdc.0-part5  689M   17M  637M   3% /android/cache
none                                         4.0K     0  4.0K   0% /sys/fs/cgroup
tmpfs                                        481M   40K  481M   1% /tmp
none                                         5.0M     0  5.0M   0% /run/lock
none                                         481M  112K  481M   1% /run/shm
none                                         100M     0  100M   0% /run/user
cgmfs                                        100K     0  100K   0% /run/cgmanager/fs
tmpfs                                        481M     0  481M   0% /media
tmpfs                                        481M  4.0K  481M   1% /var/lib/sudo
tmpfs                                         97M   40K   97M   1% /run/user/32011
tmpfs                                         97M     0   97M   0% /run/user/0
```
Do you see anything wrong?

**Comment by Thieb67k** [comment] 2019-05-15 11:29
Random crashing happens to me as well, on mako with OTA-9 (and previously with OTA-8 and 7).
When device restart, there is the ubuntu screen but no need to write the SIM code.

**Comment by zubozrout** [comment] 2019-06-22 13:40
This unfortunately also persists on the Edge channel with the latest Mir and Unity8.

**Comment by doniks** [comment] 2020-06-14 09:10
should this be closed? I mean I am sure that between 2017 and now there were a few different "random crashes", some of them might even be still around ... but is this issue going to help anybody with fixing it? Especially with hard to reproduce issues, I would caution against mixing reports from different users and after some time ... well, it just timed out

**Comment by skeever** [comment] 2020-06-14 17:19
It won't help me if it's fixed, I have moved off the OS. Thank you for
asking!

**Comment by dobey** [comment] 2020-06-14 18:52
Yes, I think this is not an actionable issue report, and is too vague. I think if there are still any issues similar to this "random crashing," then an issue should be opened for each of those cases, perhaps against the apps themselves. So I'll go ahead and close this.

Please open new issues for any further crashes, even if it might seem similar to comments here.

**Closed by dobey** 2020-06-14 18:52 UTC
Labels: bug
