### ISSUE TITLE
Xenial rc Video on phone not playing

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubuntu-touch#716] opened 2018-06-25 13:48 UTC
Bacon
16.04 rc
2018-W25

Video on phone doesn't play at all from gallery gives "An error has occured attempting to load media" and from Video Scope gives "Error playing video Video format is not supported".
When files transferred to Laptop video plays but sound extremely choppy.

### Illustrations

- Device:
- Channel:
- Build:

**Comment by Marathon2422** [comment] 2018-06-25 18:28
Pro5
16.04Rc
2018-06-25
Video scope finds movies/vids (on sdcard,and plays them no problem).
Using Media Player,it does not find anthing,but links to apps to look in

**Comment by hoh61** [comment] 2018-06-30 07:36
@Dave1152000 : How did you run the update: including wiping or not?
This kind of problem has been reported on several other issued and was often related to invalid cache content. So you may remove the following cache content:
.cache/mediascanner/* .cache/gstreamer/*, .cache/thumbnailer/*, and maye also .cache/*gallery/*.
The restart the device. It would be nice if you could report the result.

**Comment by NeoTheThird** [comment] 2018-06-30 08:07
Duplicate of #661, see my comment there for the exact folders to remove.

**Closed by NeoTheThird** 2018-06-30 08:07 UTC
