### ISSUE TITLE
Indicator menuitem selects different settings panel

### ISSUE THREAD

**Issue by FeZoli** [ubports/ubuntu-touch#1364] opened 2020-02-10 11:43 UTC
- Device: BQ Aquaris E4.5
- Channel: edge
- Build: 2020-02-09 (JU12489)

### Steps to reproduce
1. Switch the device on
2. Use it for a while
3. Use the indicator menu
4. After a while touching a menuitem selects different settings panel  than expected.
For example touch 'Keyboard Layout', and the device opens 'Notification' instead. Select 'Time and Date' and the 'Network' gets selected.

The slip between touching point and displayed menu is increasing over time. After a while it gets unusable.
Rebooting the device resets the behaviour (kind of workaround).

### Expected behavior
The indicator menu should display exactly the content of selected menuitem.

**Comment by cibersheep** [comment] 2020-02-10 20:41
Confirmed with Arale.
Needs more than a whole day without rebooting. I didn't get yet why this happens

**Comment by Flohack74** [comment] 2020-02-10 21:30
First of all please switch to devel channel, edge is in parking position and wont get further updates since a few months. So when we fix such stuff, it will only happen for devel.
Then, yes I saw this a few times. I somehow feel its a race condition between pulling down and moving left/right at the same time.

**Comment by FeZoli** [comment] 2020-02-12 10:00
I confirm the problem persists in the development channel, too.

**Comment by cibersheep** [comment] 2020-02-13 09:38
Oh, narrowing down, I have the time when this happened last night.

- Current indicators: notifications, network, sound, battery, time

- Yesterday indicators panel was ok. I set up an alarm turned on flight mode.
- This morning, turned off first alarm, when I turned off flight mode, panels had the offset (2 indicators offset)

![imatge](https://user-images.githubusercontent.com/6640041/74421249-00238e80-4e4d-11ea-9fb4-11ebc83d4101.png)

**Comment by cibersheep** [comment] 2020-02-13 09:51
Update, I tried to reproduce with no success... I have a screenshot when I realize of the offset:

![imatge](https://user-images.githubusercontent.com/6640041/74422265-a2904180-4e4e-11ea-8031-e2d5978d4e82.png)

I'm thinking: could it be related to the size of the time indicator? Changing from `00:00' to `9:00` as I can't see anything else different

**Comment by cibersheep** [comment] 2020-02-15 04:55
@FeZoli do you have any hint on how are you using the indicators for them to offset?

**Comment by cibersheep** [comment] 2020-02-15 05:00
Got it... it's actually pulling down repetedly like a crazy sheep

**Comment by FeZoli** [comment] 2020-02-15 07:24
Honestly I can't reproduce after the update on 13rd. Anyrthing happened in the code?
I'll be back if I'd experience the issue again.

**Comment by cibersheep** [comment] 2020-02-16 00:47
More observations: _misusing_ the panel like I explained, produces a random offset.
- Today I've been swiping the notifications (more than 20)
- Received a call.

When I hanged up, the offset was again 2 indicators. I will test again if I can reproduce this

**Comment by Flohack74** [comment] 2020-02-16 19:22
@cibersheep we need to decide if this will be a blocker for the OTA-12 upcoming soon. And frankly, it feels like a blocker since its really a major usability impact.

**Comment by cibersheep** [comment] 2020-02-16 19:42
To be honest, it makes feel the system «not cooked» enough even if it's easy workable with a reboot.
On the other hand, is so random that I don't know if is on specific devices / conditions.

Do you think we can do a copule of days hunt?

**Comment by Flohack74** [comment] 2020-02-16 23:40
Sure, we got at least time until Wed. But I will bring it up so that the others are aware of it.

**Comment by FeZoli** [comment] 2020-02-20 15:31
> 
> 
> Honestly I can't reproduce after the update on 13rd. Anyrthing happened in the code?
> I'll be back if I'd experience the issue again.

I experience the problem again. Build Feb. 20.

**Comment by UniversalSuperBox** [comment] 2020-02-24 21:21
I believe that this may have been solved by https://github.com/ubports/unity8/pull/276. Please let us know if you experience the problem again after tonight's build.

**Comment by UniversalSuperBox** [comment] 2020-02-26 16:02
This was not fixed by https://github.com/ubports/unity8/pull/276. The issue is still reproducible in the tests, and occurs after QML detects a binding loop on the row of icons that expands to become the top of the indicator interface (https://github.com/ubports/unity8/blob/44ad5cef81ca9fc6169cbe25936d133d65e9f7f7/qml/Panel/PanelItemRow.qml#L166).

**Closed** 2020-03-26 18:10 UTC
Labels: bug

**Comment by Flohack74** [comment] 2020-03-26 23:25
Shall we add this to the OTA-12 tracker? Its a significant improvement

**Comment by UniversalSuperBox** [comment] 2020-03-28 19:59
Sure. It's fixed as part of something else is all. :)

**Comment by cibersheep** [comment] 2020-03-30 16:38
I didn't experiment this issue anymore

**Comment by abkro** [comment] 2020-03-30 16:56
I can't reproduce it on my E4.5, so I guess it's fixed.

**Comment by Flohack74** [comment] 2020-03-30 18:34
I will move it to done, its hard to rreproduce and we can also be optimistic sometimes ;)
