### ISSUE TITLE
Screen recognizes touch input when in sleep mode

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#1087] opened 2019-04-03 12:09 UTC
- Device: cooler
- Channel: edge

### Steps to reproduce

- Lock device
- Touch the screen

### Expected behavior

Screen does not react to touch events

### Actual behavior

Screen reacts to touch events. It is even possible to unlock the device without the screen lighting up.

**Comment by NeoTheThird** [comment] 2019-04-03 12:10
FP2 does not seem to be affected.

**Comment by zubozrout** [comment] 2019-04-25 16:12
Well, I am not sure if this relates, but if I lock the screen keyboard is up and even if it is black (screen off), I can type on it. So I do have to be very careful about hiding the keyboard each time I lock the device. I am on MX4 (arale). Unfortunately that means that even with the locked screen I can type in the last focused app :(. But I am not sure if I can unlock the device ... other touch input seems not possible of I wasn't able to tap in the right order on correct screen positions :).

**Comment by mariogrip** [comment] 2019-06-27 00:02
I cannot seem to reproduce this (on frieza), can you check if the issue magically got fixed or if it's just a cooler issue?

**Comment by zubozrout** [comment] 2019-06-27 10:17
@mariogrip I suppose you didn't mean me. Nonetheless I can confirm the issue still persists for me on latest edge revision. Switching the screen off with keyboard up I can then type on it and all the input is inserted into the last focused app. Doesn't work in dash as it apparently hides itself after locking the screen (= also hides the keyboard) but does work in Teleports for instance. I can also wee what I am typing as the keyboard stays visible on the lock screen after I switch it off and on again.

**Comment by mariogrip** [comment] 2019-06-27 13:35
> @mariogrip I suppose you didn't mean me. Nonetheless I can confirm the issue still persists for me on latest edge revision. Switching the screen off with keyboard up I can then type on it and all the input is inserted into the last focused app. Doesn't work in dash as it apparently hides itself after locking the screen (= also hides the keyboard) but does work in Teleports for instance. I can also wee what I am typing as the keyboard stays visible on the lock screen after I switch it off and on again.

That is a separate issue that should be fixed by: https://github.com/ubports/unity8/pull/156
This issue is when the screen is completely off/black but you can still touch the screen.

**Comment by zubozrout** [comment] 2019-06-27 14:06
Right, thank you for the link. Although that keyboard issue I mentioned is also reproducible with screen off, since keyboard stays up for the last focused app. Nonetheless I can touch nothing else but the keyboard when the screen is off.

**Comment by mariogrip** [comment] 2019-06-29 00:13
> Right, thank you for the link. Although that keyboard issue I mentioned is also reproducible with screen off, since keyboard stays up for the last focused app. Nonetheless I can touch nothing else but the keyboard when the screen is off.

This is interesting! The pr (https://github.com/ubports/unity8/pull/156) might fix this issue as well, as i read from you it's only the keyboard that reacts to touch inputs when screen is off, as without my pr the app still stays focused and active, this might be the reason mir still handles touch inputs as it might expect them since the app is "active" per mir's understanding.

**Comment by mariogrip** [comment] 2019-07-25 00:21
I cannot seem to reproduce this, can someone confirm if this is fixed or not? (after ubports/unity8#156)

**Comment by prog66** [comment] 2019-07-26 08:34
I can't reproduce that in hammerhead device

**Comment by zubozrout** [comment] 2019-07-26 09:00
The last few edge builds I am experiencing random "pocket touch inputs" - entering login code via keyboard or even worse emergency call screen. When I turn the screen off while tapping on the bellow-screen capacitive "button" on my Meizu MX4 the screen wakes up. It probably only happens when I am too quick putting the phone to my pocket, but nonetheless I am successfully doing this quite often.

If you simultaneously shut the screen off and tap on the bellow screen button the button keeps flickering until the screen lightens up again. And this is not that hard to bump into when handling the phone in everyday rush.

So I would say this is not a desirable behaviour and also I am not sure it is a new issue but I am only experiencing this like the last 1 or 2 weeks.

**Comment by mariogrip** [comment] 2019-08-03 00:18
> The last few edge builds I am experiencing random "pocket touch inputs" - entering login code via keyboard or even worse emergency call screen. When I turn the screen off while tapping on the bellow-screen capacitive "button" on my Meizu MX4 the screen wakes up. It probably only happens when I am too quick putting the phone to my pocket, but nonetheless I am successfully doing this quite often.
> 
> If you simultaneously shut the screen off and tap on the bellow screen button the button keeps flickering until the screen lightens up again. And this is not that hard to bump into when handling the phone in everyday rush.
> 
> So I would say this is not a desirable behaviour and also I am not sure it is a new issue but I am only experiencing this like the last 1 or 2 weeks.

Could you open a new bug for this? :) This seems to be an issue with the button waking up the screen, not touch input while the screen is black. 

Closing this as it cannot be reproduced anymore.

**Comment by NeoTheThird** [comment] 2019-09-02 23:06
Original problem still present in latest edge build on cooler.

**Comment by Flohack74** [comment] 2020-01-24 07:56
Can we remove needs confirmation here?

**Comment by VenKamikaze** [comment] 2020-02-26 22:06
I also use an MX4, I just tested opening the keyboard (while in the browser), switching off the screen and trying to type. I was not able to reproduce the issue with an MX4.

**Comment by thilovv** [comment] 2020-03-02 13:09
If I lock the screen and touch it immediately the screen is on again (but locked at least).
Oneplus 3T

**Comment by cibersheep** [comment] 2020-03-16 20:32
I can reproduce this with Arale (dev channel)
taiebot, with nexus 4

**Comment by Flohack74** [comment] 2020-03-21 08:37
So its not device dependent? What is the thing those devices have in common?

**Comment by cibersheep** [comment] 2020-03-22 11:58
In Arale and E5 usually happens during (and sometimes after) using MediaHub.
- Run Podbird and play an episode
- Lock the device
- Swipe (with the screen off)

**Comment by hendrikscheewel** [comment] 2020-03-27 23:38
Can confirm this for N4 and the S3Neo. I could replicate @cibersheep's steps. During and after using the MediaHub it is possible to "blindly" access e.g. the dialer app. Not sure if somehow related: On the S3Neo also the LED remains active...

**Comment by peat-psuwit** [comment] 2020-04-08 08:38
Warning, brain dump ahead...

So, the problem starts because the input device still feeds events into U-S-C. Both Qualcomm's and Mediatek's touchscreen driver in the kernel have a provision that will disable it if the framebuffer is blanked. However, for some reason, Mediatek's HWC does _not_ blank the FB when it's told to turn the screen off [1], allowing the touchscreen to work while the screen itself is off.

But why it happens only sometimes? See, the touchscreen driver also listens to the `early_suspend` signal that will fire when the phone is going to sleep and turn the touch off on that. This makes the problem not manifests most of the time where the phone just goes to sleep. But, if something holds a wakelock (such as when playing music), now the touches just go to U-S-C.

But why this isn't a problem with the old Mir? Well, to understand this we'll have to understand [how U-S-C turns off the screen](https://github.com/ubports/unity-system-compositor/blob/fe448818bd0fb15bc007e84ef7ad606f75254e3a/src/mir_screen.cpp#L232-L237): it fetches and modifies the display configuration, stops the compositor, applies the configuration to the display directly, and starts the compositor if there are any active outputs. Notice that if all the screen is off, then the compositor stays stopped. And if the compositor is stopped, Mir considers all surfaces' visibility "occluded".

Now, the old Mir would [skip the occluded surface](https://github.com/ubports/mir/blob/xenial-before-2019-edge-merge/src/server/scene/surface_stack.cpp#L312) when it looked for the target surface for touch input. This means no touch input when the screen is off. However, [this commit](https://github.com/ubports/mir/commit/f90480f41ade66e39c802a00ae6a94c9ab7046b5) make sure occluded surfaces aren't skipped, saying the users "... always test for visibility". But [the visibility it checked](https://github.com/ubports/mir/blob/547baef2ba9c67c95b10ea2d1c5bef674c7766fc/src/server/scene/basic_surface.cpp#L363) is different visibility than the visibility attribute. This changes the behavior to allow input to occluded surfaces.

So, I decided to add a check for occlusion in that function and restore the old behavior. It seems to work, but it fails [an acceptance test](https://github.com/ubports/mir/blob/547baef2ba9c67c95b10ea2d1c5bef674c7766fc/tests/acceptance-tests/test_client_input.cpp#L594). And rightly so. See, the reason occlusion is tied with the compositor is that it test the occlusion of the _renderables_ i.e. the buffer that the client sends. However, the touch is supposed to work on the whole surface/window, which can be bigger or smaller than its renderable. So, we can have a situation where a window's renderable occludes another window's, but the whole window doesn't, and the touch is supposed to work on the non-occluded part. Tests save my day.

So, I looked the other way and noticed that [Mir does something with the input bound when the display configuration changes](https://github.com/ubports/mir/blob/547baef2ba9c67c95b10ea2d1c5bef674c7766fc/src/server/input/basic_seat.cpp#L100). Thus, I started to modify the U-S-C to use "display configuration controller", which will send a display configuration change signal, instead of just talk to the display directly. But, as it turns out, Unity8 will interpret the configuration change in U-S-C as a "hardware change", apply a policy to it, and force the screen to stay on (in Mir's thought). This also seems to have a side effect of just blanking the screen when the screen is turned back on.

My next attempt is now to make U-S-C just hide all surfaces when the screen is off. However, if anyone has a better idea to fix this, please comment.

[1] But I assumed that it has some other mechanism to turn the screen off. I don't know.

**Closed** 2020-04-14 21:21 UTC
Labels: bug, device: arale, device: cooler, device: mako

**Comment by hendrikscheewel** [comment] 2020-04-15 12:33
It's fixed on N4 devel after today's update!

**Comment by cibersheep** [comment] 2020-04-15 13:11
Fixed on Arale dev :)
