### ISSUE TITLE
 No video recording possible 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#23] opened 2017-05-27 16:35 UTC
Recording of a video is not possible.

log: https://bugs.launchpad.net/ubports-n5/+bug/1682783/+attachment/4873848/+files/cameralogcat.log
dmesg: https://bugs.launchpad.net/ubports-n5/+bug/1682783/+attachment/4873849/+files/cameradmesg.log

Interesting, through the web browser I have access to the camera feature...

Reported by https://launchpad.net/~firstcome-lastserve.

**Comment by ebeton-ro** [comment] 2017-06-04 20:59
Confirmed on my N5 also It sayd "Capture failed  Restarting your device might fix the problem" and a button to Cancel .

**Comment by rubencarneiro** [comment] 2017-06-06 00:37
/system/etc/media_codecs_ffmpeg.xml does not exist on the 12.1 branch.
Also n5 does not have some blobs:
libstagefright_soft_h264dec.so
libstagefright_soft_hevcdec.so
libstagefright_soft_vpxdec.so
libstagefright_soft_vpxenc.so

These blobs are provided by libstagefright

**Comment by ebeton-ro** [comment] 2017-06-28 15:09
I just found out that if someone try to record video he should flip camera to front and after that back to back camera and the recording is working (no more errors). I didn't find any way to playback that video on the N5 himself but as you can see the video is there.
[video20170628_180549192.mp4.zip](https://github.com/ubports/ubports-touch/files/1109172/video20170628_180549192.mp4.zip)

**Comment by nfsprodriver** [comment] 2017-07-10 00:58
#7

**Comment by matosaure** [comment] 2017-09-26 19:46
The same bug, Capture failed Restarting your device might fix the problem" on  my MX4

**Comment by HendriXXX** [comment] 2017-10-22 07:01
Seems like only **libstagefright_soft_hevcdec.so** is missing in N5 in following folders.
```
/android/system/lib/
/var/lib/lxc/android/rootfs/system/lib/
```
I found patched libstagefright files from xda-devs forums.
https://forum.xda-developers.com/showpost.php?p=62083530&postcount=3
[stagefright_libs_patched_for_LMY48B_august14.tar.gz](https://github.com/ubports/ubuntu-touch/files/1404664/stagefright_libs_patched_for_LMY48B_august14.tar.gz)

Can we use those in UBports?

**Comment by NeoTheThird** [comment] 2017-10-23 16:27
@HendriXXX Could you create a pull request? @rubencarneiro can probably provide some guidance here.

**Comment by HendriXXX** [comment] 2017-10-24 04:01
@NeoTheThird Sorry, but I have no idea how to do it.

**Comment by nfsprodriver** [comment] 2017-11-18 01:37
Tried to figure that out also without success. We may try that in order to solve that issue in OTA3. Recording itself works, but we need to reswitch between cameras (aspect ratio issue?). Well is that still a valid issue?

**Comment by mariogrip** [comment] 2017-12-19 19:21
So this is where i am so far, it seems to have a broken pipe on switch, I have not been able to find out the cause just yet, this was a bit more difficult the i expected. So this will be moved to next release, Im really sorry about that, but we cannot block ota-3.

**Comment by GI9VANNI** [comment] 2017-12-29 10:18
I do not know if it's the same problem, but when I try to record a video with the Nexus 5 (15.04 stable) the screen freezes and I have to close the app.

**Comment by mauricioduarte01** [comment] 2017-12-29 10:36
@GI9VANNI what I do when that happen is just wipe the screen from right to left and re-enter the camera app.

**Comment by matosaure** [comment] 2017-12-30 12:52
The problem is not present after flashing devices with spflashtools on my Mx4 ?? Why ? I don't know...

**Comment by GI9VANNI** [comment] 2018-01-24 20:36
> what I do when that happen is just wipe the screen from right to left and re-enter the camera app.
@mauricioduarte01 Your method works. I will do so until the resolution of this bug.

**Comment by GI9VANNI** [comment] 2018-01-24 20:37
> what I do when that happen is just wipe the screen from right to left and re-enter the camera app.

@mauricioduarte01 Your method works. I will do so until the resolution of this bug.

**Comment by advocatux** [comment] 2018-02-18 11:44
An UBp fellow asked me in the Spanish group to report here that the video recording still doesn't work in 16.04, as expected, but with the main difference that those workarounds working in 15.04 don't work in 16.04

Do you need any log? If yes, which one/s?"

**Comment by lduboeuf** [comment] 2018-12-18 08:02
> Confirmed on my N5 also It sayd "Capture failed Restarting your device might fix the problem" and a button to Cancel .

Same on N5 OTA 6 devel (2018-12-17)

**Comment by Flohack74** [comment] 2019-04-09 21:58
Fixed by https://github.com/ubports/android_device_lge_hammerhead/pull/18

**Closed by Flohack74** 2019-04-09 21:58 UTC
Labels: bug, device: hammerhead

**Comment by advocatux** [comment] 2019-05-01 17:47
Just for the record, no put intended, (OTA-9): I confirm that it's possible to record a video now.
- Device: Nexus 5 (`hammerhead`)
- Channel: `rc`
- Build: Ubuntu 16.04 (`2019-W18`)
