### ISSUE TITLE
OPO : Battery Display was locked in 50%

### ISSUE THREAD

**Issue by Lnpo** [ubports/ubuntu-touch#1387] opened 2020-03-05 05:12 UTC
- Device: OnePlus One
- Channel: may all,and devel and edge count
- Build: devel 1314 and 1315 ( the former I don't know)

**Steps to reproduce**
After new flashing,I update Apps.
(The Wifi Switch Doesn't work still.issue #995 has way to solve)

**Expected behavior**
Display in charging or actually battery

**Actual behavior**
Sometimes Battery Display was locked.Just like Android's System UI demo mode.But it was set 50%.

**Comment by Lnpo** [comment] 2020-03-06 14:03
build 1318 may fix the problem,but still need to confirm

**Comment by Lnpo** [comment] 2020-03-06 14:12
oh,it haven't been solved.

**Comment by Flohack74** [comment] 2020-03-12 08:12
@Lnpo The WiFi switch problem is unlikely to be solved as no developer can get hold of an affected device. So please do the workaround described in the issue to generate yourself a new config file with a proper MAC address and place it into the persist partition.

**Comment by Flaburgan** [comment] 2020-03-19 19:09
Isn't that a duplicate of https://github.com/ubports/ubuntu-touch/issues/533 ?

**Comment by Flohack74** [comment] 2020-03-21 15:02
Duplicate of #533

**Closed by Flohack74** 2020-03-21 15:02 UTC
Labels: duplicate
