### ISSUE TITLE
[Request for `indicator-display`] Allow orientation to be selectable alongside `Rotation Lock`

### ISSUE THREAD

**Issue by myii** [ubports/ubuntu-touch#957] opened 2018-11-18 07:25 UTC
### Description of the feature

Intended to file this against https://github.com/ubports/indicator-display (The "Rotation" indicator for Ubuntu Touch) but no Issues tab there.

#### Proposal

Add an option below `Rotation Lock`, to allow selecting the orientation to lock to, with one of the following four options selectable:

1. Portrait
1. Landscape
1. Inverse portrait
1. Inverse landscape

#### Use Case 1

The idea started from a question on the [main Telegram group](https://t.me/ubports):

> Martin, [17.11.18 23:48]
> Hello. I think my accelerometer's broken.  Is there a way to force the rotation of the screen?

* I tried to assist but there was no output for the accelerometer using the `SensorsStatus` app

While this use case is rare, it would be invaluable to have this feature in this situation.

#### Use Case 2

This is general UX improvement for all users.  There are numerous times one wants the maintain the rotation lock but in a different orientation.  The current steps to achieve this:

1. Pull down the indicator
1. Unlock the rotation
1. Push up
1. Rotate
1. Pull down on some other indicator (since the rotation lock indicator is no longer visible)
1. Navigate to `Rotation`
1. Lock the rotation

This could be simplified to:

1. Pull down the indicator
1. Select the desired orientation
1. Push up

#### A tangential proposal

Instead/Additionally, provide an indicator showing "Rotation unlocked", so that the `Rotation` menu can be accessed directly rather than having to navigate to it.  Similar to the indicator displayed on Android, differentiating between locked and unlocked.

#### Conclusion

Starting with an issue rather than attempting a PR since this feature request may be rejected.

**Comment by Arc676** [comment] 2018-11-18 10:17
Potentially a duplicate of #69?

**Comment by myii** [comment] 2018-11-18 10:42
@Arc676, you're right.  I'm going to merge this into #69 and close this issue.  Thanks for your attention.

**Closed** 2018-11-18 10:58 UTC
