### ISSUE TITLE
Thumbnails pictures  - not appears 

### ISSUE THREAD

**Issue by amebablues-nexus** [ubports/ubuntu-touch#1514] opened 2020-07-15 00:34 UTC
![Nexus 5 01](https://user-images.githubusercontent.com/67522079/87489928-ae10b000-c61a-11ea-9bab-060c12cd3ab1.jpg)
![Nexus 05 001](https://user-images.githubusercontent.com/67522079/87489969-c54f9d80-c61a-11ea-8903-b8f9bcac4e53.png)

### Illustrations

- Device: Nexus 5
- Channel: Devel
- Build: 14/07/2020

### Steps to reproduce
When i copy the picturtes to PC and open any file, the others only shows some blur images. When i open on gallery app on device, same thing happens.

### Expected behavior
The thumbnails files appears in both cases

### Actual behavior
Same thing described in reproduce.

**Comment by UniversalSuperBox** [comment] 2020-10-01 16:51
Hi @amebablues-nexus, apologies for the long wait.

I'm unable to reproduce this problem by opening the Gallery app on my Nexus 5 or by copying the images from my device to my laptop.

![Pictures from Nexus 5 viewed as thumbnails in Nautilus](https://user-images.githubusercontent.com/21966173/94838934-ec2c9d00-03db-11eb-8b20-a1bfff40cca5.png)

![Nexus 5 pictures viewed in Nexus 5 gallery app](https://user-images.githubusercontent.com/21966173/94839034-13836a00-03dc-11eb-906b-3dccd3c7ddd3.png)

If you are viewing your images directly on your device over MTP, you may see problems with thumbnail generation. This also occurs on Android devices, PC software does it to make file transfer and directory browsing faster. However, once those images are copied to your PC, thumbnails should be generated normally.

Since I am unable to reproduce this problem given the steps provided, I will close this report for now. Please let me know if you are still experiencing the problem on images you have copied to your PC, and also which software you are using to view the images.

**Closed by UniversalSuperBox** 2020-10-01 16:51 UTC
