### ISSUE TITLE
One plus One wake up issue

### ISSUE THREAD

**Issue by UKPhil** [ubports/ubuntu-touch#332] opened 2017-11-01 23:58 UTC
- One plus One 
- UBPorts
- R2

## Steps to reproduce

1. Lock and power down the screen by clicking the power button (do not turn off)
2. Press the power button to wake the screen up

## Expected behavoir
For the phone lock screen to be lit up when the power button is clicked on phone sleep screen

## Actual behavior

On my OnePlus One when I press the power button to wake the phone screen up, nothing happens. I have to then top the phone screen itself to wake it up. So there is a double action to wake the phone up. Is this a setting that I have set on or is it a known issue?

**Comment by siucdude** [comment] 2017-11-02 02:55
Same issue on mine, sometimes if i reboot my phone 2 or more times it works correctly.

**Comment by Flohack74** [comment] 2017-11-02 19:42
Works for me, can someone share a video =)

**Comment by ChloeWolfieGirl** [comment] 2017-11-02 19:44
On rc I'm not having problems either

**Comment by stekalb** [comment] 2017-11-04 20:16
On mine (rc) it happens sometimes. Mostly I can workaround by 
1. clicking power button -> screen remains dark
2. touch onto display -> screen awakes, passcode is asked

**Comment by stekalb** [comment] 2017-11-04 20:19
duplicate of #305 ?

**Comment by UKPhil** [comment] 2017-11-06 08:47
Sounds like it may be a duplicate. @Flohack74 if you send me an address I will do the video and send it to you.

**Comment by NeoTheThird** [comment] 2017-11-06 10:50
Duplicate of #305, please continue there.

**Closed by NeoTheThird** 2017-11-06 10:50 UTC
Labels: device: bacon, needs confirmation

**Comment by UKPhil** [comment] 2017-11-08 21:02
The other night I did an update and since then I have not had any isues. I did set my phone up to  receive rc updates but it still says r2. So I am not sure what release I have, but I know it is working g fine.
