### ISSUE TITLE
[ Xenial ] OpenStore is not rendering apps correctly

### ISSUE THREAD

**Issue by mebruno** [ubports/ubuntu-touch#520] opened 2018-03-11 11:12 UTC
BUG-REPORT

- Device: bqm10 frieza
- Channel: 16.04 devel
- Build: r49

### Steps to reproduce
start openstore
No apps are visible

### Expected behavior
Apps for installation are visible
Click on app to install

![screenshot20180311_103632096](https://user-images.githubusercontent.com/35872205/37252663-72475d0a-2525-11e8-9d41-62e32b7ce37f.png)

### Actual behavior
No app visible
click in empty space
app to install visible
Click button to install
App is installed

![screenshot20180309_125441659](https://user-images.githubusercontent.com/35872205/37252669-81eb98e8-2525-11e8-82fd-bec86ec3c5b4.png)

**Comment by HendriXXX** [comment] 2018-03-15 09:06
After todays Xenial update (r53), Openstore started to work. It shows apps and installs them too. Phone: Nexus 4.

**Comment by NeoTheThird** [comment] 2018-03-15 13:11
Duplicate of #461. Thanks for reporting :)

**Closed by NeoTheThird** 2018-03-15 13:11 UTC
