### ISSUE TITLE
(not so) spontaneous reboots of FP2 when using browser and webapps

### ISSUE THREAD

**Issue by meisteredermeistereder-the-second** [ubports/ubuntu-touch#464] opened 2018-02-05 14:15 UTC
- Device: FP2 
- Channel: 15.04/rc
- Build:

### Steps to reproduce
1. Open browser and maybe one webapp (e.g. Twitter)
2. Browse some time or use the webapp for some time
3. Close either webapp or browser

### Expected behavior
I would expect the browser or webapp to close and leave the OS unaffected. 

There are spontaneous reboots under LineageOS, too, but they don't occur in specific situations during use (at least not for me, I had them e.g. while charging overnight or so), and much less often. I had 0 or 1 per week. UT is much worse in this respect.

### Actual behavior
There are three possibilities:
1. Webapp or browser closes and nothing more happens. The phone can be used normally. (rare)
2. During normal usage of the browser or the webapp the phone freezes for a moment and reboots. (often)
3. The phone freezes and reboots while closing the webapp (very often) or while closing the browser (nearly everytime)

In cases 2 and 3 the screen freezes, goes black, the phone boots to the ubuntu screen (where the dots disappear from left to right), goes dark again, vibrates and starts up to the login screen.

### Logfiles
If I am told which logfiles I should provide, I'll upload them. I would be glad to help by providing logs and testing if I can.

**Comment by derkleinemannvomfeldweg** [comment] 2018-02-08 06:25
I found another quite reliable way to make the phone reboot.
When I have the browser opened and another web-app, I can make reboot the phone (50% chance) by opening a link from Dekko 2.

**Comment by luksus42** [comment] 2018-07-09 08:12
Device: FP2
Channel: 15.04/stable

I can't reproduce it, in the ways how @derkleinemannvomfeldweg describes it.

The fastest ways, to make my FP2 reboot:
1. Watch a stream in the browser... // or
2. Scroll down on youtube...

Before it is restarting, its getting very hot at the top.

**Comment by blaubaer01** [comment] 2018-09-11 18:14
Issue still exist with 16.04

**Comment by garro95** [comment] 2018-10-28 13:12
I can confirm it happens when closing apps based on the browser. OTA5 still has the issue.

**Comment by garro95** [comment] 2019-02-06 14:14
Maybe solved? I am not experiencing this anymore for some time

**Comment by luksus42** [comment] 2019-02-06 17:26
Just encountered this issue while watching this thread.
I have the impression, that it could have something to do with excessive up/down-scrolling.

**Comment by blaubaer01** [comment] 2019-02-08 04:58
In my opinion with upgrade to ubuntu touch 16, the issue is solved

**Comment by garro95** [comment] 2019-03-06 23:43
I encountered it again. I was mostly able to reproduce it in the following steps:
1. Open WebTelegram Application
2. Open a chat where a map was sent and click on the map (-> the map gets opened in uNav)
3. Close WebTelegram

**Comment by Flaburgan** [comment] 2021-02-06 20:05
I'm using the Fairphone 2 for 2 years and didn't have that problem for a long time. I had it a very few times when taking pictures but it was a while ago, I feel like this could be closed.

**Closed** 2021-02-07 09:52 UTC
Labels: bug, device: FP2
