### ISSUE TITLE
Hammerhead - power button 3 times to wake up the device if automatic brightness is enabled

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#65] opened 2017-05-29 23:22 UTC
Gents, 

I didn't see this bug moved from launchpad. 
I need to push, usually, 3 time the power button to wake up the devices.

**Comment by NeoTheThird** [comment] 2017-05-30 05:16
Are you still experiencing this? I marked it as fix released because I wasn't able to reproduce it, so I just assumed. What is version and channel are you on?

**Comment by Flohack74** [comment] 2017-05-30 06:29
I have the same on my test device I think. I will test today. I was always thinking this is because I got a used N5 and the power button is a bit broken xD

**Comment by ernesst** [comment] 2017-05-30 12:09
Yes i still have it daily.
I'm in legacy r19

**Comment by NeoTheThird** [comment] 2017-05-30 13:26
Please check if the issue is also present on Android, so we can be sure it's related to Ubuntu Touch.

**Comment by ernesst** [comment] 2017-05-30 13:35
Impossible, i'll not flash back my nexus 5 to android ;) 
However i doubt that it's hardware issue as i can shutoff the screen with one push and also when the screen just shutoff one push is enough to bring it back to life. 
I guess is linked to the state of the device, deep sleep = 3 push to wake it up

**Comment by NeoTheThird** [comment] 2017-05-30 14:13
What exactly do you mean by deep sleep? When the device is shut down? That's not really a problem then, is it? My device turns on, when i hold the power button for a couple of seconds when it's turned off.

**Comment by ernesst** [comment] 2017-05-30 15:15
Deep sleep means more than 30s / 1 min with screen off, versus light sleep couple of second of screen off. 
I'm not talking about phone being off.

**Comment by NeoTheThird** [comment] 2017-05-30 15:19
I can't reproduce this. Even after a couple of hours, my Nexus 5 comes back to life at the press of one button. @Flohack74 any luck on reproducing this?

**Comment by NeoTheThird** [comment] 2017-05-30 16:05
Don't mind me.

**Comment by ernesst** [comment] 2017-05-30 16:45
Do you know which log file or test command i should look at to capture the phenomena ?

**Comment by Flohack74** [comment] 2017-05-30 17:27
I will try now... N5 powering on...

**Comment by ernesst** [comment] 2017-05-31 00:07
@Flohack74 takes time to powering ... 

4 slow times to wake up the phone : 
https://paste.ubuntu.com/24720385/

2 slow times to wake up the phone : 
https://paste.ubuntu.com/24720398/

8 slow times to wake up the phone : 
https://paste.ubuntu.com/24720441/

The trick is 3 times fast...

**Comment by Flohack74** [comment] 2017-05-31 11:33
Yeah basically I see the same thing, its strange however, as I cant make up a pattern, seems to be totally random. Also long-press is not a good idea, then it opens the shutdown menu.

**Comment by NeoTheThird** [comment] 2017-05-31 14:08
I tried again a couple of times and i still can't reproduce this. I mean, i believe you that that's an issue, given that i heard about it form different people, i'm just wondering why my device is not affected. Are there different versions of the device, or am i just the chosen one?

**Comment by APokorny** [comment] 2017-05-31 19:58
So if I parse the traces correctly i.e. in https://paste.ubuntu.com/24720385/ only the last power button press turns the backlight on. The first sequence just turns touchscreen, screen and other internal states to "on", the second press turns all of that off again.. 
Which part of the system talks to the backlight?

**Comment by Flohack74** [comment] 2017-05-31 20:52
Haha that sounds very confusing but makes sense... It would match the pattern we see.

**Comment by ernesst** [comment] 2017-05-31 22:09
@APokorny 
Could catch, if i push once the button + i swipe the screen off, the backlight goes on ! 

The bug doens't happen with the phone is connected to my computers

**Comment by starstec** [comment] 2017-06-03 04:19
Looks like it happens just when adjust brightness automatically is enabled. As you know previous versions does not have this issue (v4.4.2 I think), neither that issue https://github.com/ubports/ubports-touch/issues/6
_Thank you for your attention._

**Comment by NeoTheThird** [comment] 2017-06-04 07:51
Yep, that's true. If you disable automatic brightness, the issue goes away. If you enable it, it comes back.

**Comment by ebeton-ro** [comment] 2017-06-04 20:32
> Yep, that's true. If you disable automatic brightness, the issue goes away. If you enable it, it comes back.

I can also confirm this!

**Comment by Flohack74** [comment] 2017-06-15 15:00
This seems fixed now in latest devel :)

**Comment by Flohack74** [comment] 2017-06-15 18:59
Unfortuantely not fixed. Its just not happening on ALL presses...

**Comment by ncorella** [comment] 2017-06-19 22:49
Hi,

Can someone show the content of /usr/share/powerd/device_configs/config-default.xml ??

Thanks.

**Comment by rubencarneiro** [comment] 2017-06-19 23:38
@ncorella hi, there no longer /usr/share/powers/device_configs/hammerhead.XML

Since nos se use repowerd is moved to /usr/share/repowerd/davice_configs/hammerhead.xml

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ncorella** [comment] 2017-06-20 00:24
Then... Am i looking in a wrong source code?

**Comment by rubencarneiro** [comment] 2017-06-20 00:59
@ncorella i did changed hammerhead specifi folder to not include that XML file since is already included on rootfs

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ncorella** [comment] 2017-06-20 16:36
Ahm... ok, now i see it.

Do you think it is the same bug that this old bug in krillin and mako?
https://bugs.launchpad.net/ubuntu/+source/powerd/+bug/1429887

At first i thought the bugs are the same, except for 2 strange things, nobody in that bug noticed that with automatic brightness disabled there is no bug. And the fact that in that bug, users said if you press one time the power button and simply wait (sometimes a lot of seconds) the screen goes on. Can anyone try this?

I don't have a nexus 5 yet... but i will have one next week and i hope i can help testing and debugging some things...

Thanks.

**Comment by Flohack74** [comment] 2017-06-20 16:39
Ok will try  at home. How many seconds to wait approx.?

**Comment by ncorella** [comment] 2017-06-20 17:09
Well, i don't know by my self, but in the refered bug, users said the time is totally random, from few seconds to even 1 minute...

**Comment by rubencarneiro** [comment] 2017-06-20 21:47
did you try sudo chmod +x /usr/sbin/repowerd

**Comment by ernesst** [comment] 2017-06-21 22:26
It's already +x in the system.

**Comment by ncorella** [comment] 2017-06-25 21:16
Ok, now that i have a Nexus 5 i can test things.

I have discovered the reason of the random behavior and why it's not happening in all presses: if after power button is pressed (only one time), there is any change in the UI, i.e.: time change, battery change, mobile or wifi range change, etc... then the screen lights on!

Can anyone confirm this?

**Comment by ebeton-ro** [comment] 2017-06-25 22:45
I can cofirm this for time(minutes) change also I can confirm that it took more then 5 seconds for the screen to light up.

**Comment by nomoreAndroid** [comment] 2017-06-28 05:25
Actually i like this bug, it keeps the phone from accidently being powered up in my pocket. Better battery life, and I got quickly used to it. Just press powerbutton and touch the screen. Maybe we can keep this bug as an option? Could be just a better way to wake up the ubuntu-phone. Try it!

**Comment by wagafo** [comment] 2017-06-29 19:24
I moved to 15.04/devel and I am not seeing this issue

**Comment by NeoTheThird** [comment] 2017-07-19 17:24
@wagafo Did you enable automatic brightness?

**Comment by wagafo** [comment] 2017-07-19 19:39
I haven't seen this issue any more since I moved to the 15.04/devel channel.

**Comment by ernesst** [comment] 2017-09-03 13:13
Flo, nothing new. The one time + presd works also on the stable.

**Comment by wagafo** [comment] 2017-09-04 10:53
I confirm that it is solved also for my N5. No need to turn off automatic brightness any more.

**Comment by Flohack74** [comment] 2017-09-04 11:01
Hmm I would not clal it solved. If I press power button the screen does not light up, I have to swipe on the black screen...

**Comment by wagafo** [comment] 2017-09-05 07:14
Again, after some more playing, if automatic brightness is on, it is still not working as expected. This must be the 4th time I think this if fixed but it is not.

**Comment by Rom4nB** [comment] 2017-10-04 13:45
I have a Nexus 5 also and can confirm the bug with OTA2, stable, still present.

Flashed Ubuntu and screen was hard to wake up with the power button. As mentioned by Flohack74, I assumed that I got a damaged 2nd hand phone with worn out power button.

Now I re-flashed LineageOS (also to learn more about battery capacity in Android, which was very low in ubuntu) and the power button works without problems in Android.

**Comment by HendriXXX** [comment] 2017-10-24 06:53
I can also confirm this bug on my N5. When screen doesn't wake up.. I touch/swipe screen even a little bit, backlight comes on. It doesn't matter where I do that touch/swipe, it works every time.

**Comment by mariogrip** [comment] 2017-12-12 09:16
Fix released https://github.com/ubports/repowerd/commit/7689b45b69e53566eb4a48f27cd318de8bd0b724

**Comment by wagafo** [comment] 2017-12-13 09:37
I'm still seeing this issue in 251 Devel version.

**Comment by NeoTheThird** [comment] 2017-12-13 15:15
> I'm still seeing this issue in 251 Devel version.

True. The image might have been built before the fix was committed.

**Comment by mariogrip** [comment] 2017-12-17 21:45
Fix commited https://github.com/ubports/repowerd/commit/854d75cd9d783582a90bb58fe9d468caaf3bb5ae

**Comment by Flohack74** [comment] 2017-12-17 22:20
I hope so much that this time we mailed it haha ;) - Testing tomorrow

**Comment by NeoTheThird** [comment] 2017-12-18 20:33
fixed

**Closed by NeoTheThird** 2017-12-18 20:33 UTC
Labels: bug, device: hammerhead
