### ISSUE TITLE
Installation of OTA23 on Volla Phone X fails

### ISSUE THREAD

**Issue by Silicomancer** [ubports/ubuntu-touch#2005] opened 2022-07-10 21:15 UTC
### Steps to reproduce

Install OTA23 on Volla Phone X with OTA22.

### Expected behavior

Expected installation to work.

### Actual behavior

When visiting the update panel it says "Update failed FileNotFoundError: [Errno 2] No such file or directory "/android/cache/recovery". 

Previous update installed without problems. 

Restart didn't help. "Retry" button does not do anything.

### Logfiles and additional information

I used the "terminal" app and created the directory with sudo mkdir. It downloads the update now but when rebooting for installation it ends stuck in recovery mode doing nothing.

Someone suggested to apply "mount -o bind /userdata/cache /android/cache" to fix the issue but I have no idea if this is the right way. Also I have no idea where the issue came from.

**Comment by koenvervloesem** [comment] 2022-07-10 21:26
See https://github.com/ubports/ubuntu-touch/issues/1999

**Comment by Flohack74** [comment] 2022-07-19 21:11
Duplicate of #1999

**Closed as completed by Flohack74** 2022-07-19 21:11 UTC
