### ISSUE TITLE
device:mako No wifi thetering (OTA 13 stable)

### ISSUE THREAD

**Issue by sc-fx** [ubports/ubuntu-touch#1572] opened 2020-09-27 09:45 UTC
### Description of the feature
WIFI thetering (hotspot)

### Illustrations

- Device:mako
- Channel: stable
- Build: OTA 13

**Comment by UniversalSuperBox** [comment] 2020-10-01 15:37
Hello @sc-fx,

This bug report is not very extensive, so I'm unable to know what the problem is. I'm assuming that you are concerned about there being no "Hotspot" option in system-settings.

The Nexus 4 has always had problems with WiFi tethering, so it was manually disabled years ago. You can see more about the disabling of the hotspot functionality here: https://bugs.launchpad.net/ubuntu/+source/indicator-network/+bug/1487157

It is potentially possible that the bugs in wpa-supplicant have been fixed and the Nexus 4 could have Wi-Fi hotspot enabled again. However, I would need someone to test it out and say what needs to be fixed there.

Since this bug report is incomplete and the underlying issue possibly older than our maintainership of Ubuntu Touch, I will close this report. Please let me know if you have any concerns about this decision.

**Closed by UniversalSuperBox** 2020-10-01 15:37 UTC

**Comment by sc-fx** [comment] 2020-10-03 14:56
Hi Dalton,

On 01/10/2020 17:37, Dalton Durst wrote:
> It is potentially possible that the bugs in wpa-supplicant have been 
> fixed and the Nexus 4 could have Wi-Fi hotspot enabled again. However, 
> I would need someone to test it out and say what needs to be fixed there.

I do not know if I am able to do that, but I could try if I knew what to 
do. So the first thing is: how can I manually activate Wifi hotspot ?

@sc-fx
