### ISSUE TITLE
Predictive writing issue using French Swiss keyboard

### ISSUE THREAD

**Issue by stanwood77** [ubports/ubuntu-touch#1541] opened 2020-09-02 18:21 UTC
When writing a text, using any app, no predictive writing nor correction appear on the top of the text when using the "French (Swiss)" keyboard.
Workaround: Change keyboard to "French", than put back "French (Swiss)" right away. Predictive writing in french will work until next boot.

Steps to reproduce the issue:

. Change device system settings language to french
. Enter in  "Langue et texte"
. Enter in "Agencements du clavier"
. Add keyboard "Français (Suisse)" and remove others
. Reboot device
. Enter any app using keyboard and start to type a text

Note that I'm using Nexus 5 phone on OTA 12 stable.

Many thanks for your support.

**Comment by lduboeuf** [comment] 2020-09-02 21:35
Technical follow up here: https://github.com/ubports/keyboard-component/issues/132

**Comment by UniversalSuperBox** [comment] 2020-09-15 15:19
This is a duplicate of https://github.com/ubports/keyboard-component/issues/132. Please continue further discussion there.

Thank you for your report!

**Closed by UniversalSuperBox** 2020-09-15 15:19 UTC

**Comment by stanwood77** [comment] 2020-09-16 11:07
Ok thank you Dalton.

Steve 

Le Tue, 15 Sep 2020 08:19:48 -0700, Dalton Durst a écrit :
> This is a duplicate of 
> https://github.com/ubports/keyboard-component/issues/132. Please 
> continue further discussion there.
>
> Thank you for your report!
>


-- 
Sent using Dekko from my Ubuntu device
