### ISSUE TITLE
Missing Letters in GPS Permission dialogue 

### ISSUE THREAD

**Issue by nickegg1018** [ubports/ubuntu-touch#1669] opened 2021-02-19 02:10 UTC
- Device: OnePlus 3T
- Channel: Stable
- Build: OTA-15

### Steps to reproduce
Install any app that requests GPS 

### Expected behavior
Screen to "Approve" or "Don't Approve" (or maybe Allow and Don't Allow, I'm not sure, you'll see why) shows those words

### Actual behavior
The vast majority of the letters in the dialogue asking for permission to access GPS don't appear. See (https://imgur.com/0EVRLE0) this is my first use of the "Clock" app

### Logfiles and additional information

Ubuntu-location-service-trust-stored:
http://paste.ubuntu.com/p/C7BBhYYGGW/

**Comment by UniversalSuperBox** [comment] 2021-02-19 15:35
Hi @nickegg1018, thanks for your report!

This issue occurred on OTA-15, but has been fixed in the `devel` and `rc` channels. OTA-16 will be released soon with these fixes.

Since this issue is resolved, I will close this report. Thanks again for letting us know!

**Closed by UniversalSuperBox** 2021-02-19 15:35 UTC

**Comment by CristianSw** [comment] 2021-02-24 20:54
not reproduced on redmi note 7 lavender on current rc version 2021-w08

**Comment by cibersheep** [comment] 2021-02-26 02:59
Looks fixed on E5
