### ISSUE TITLE
[xenial] Red background on content-hub header

### ISSUE THREAD

**Issue by ivoxavier** [ubports/ubuntu-touch#668] opened 2018-06-12 18:41 UTC
- Device: Fairphone2
- Channel: 16.04/devel
- Build:330

### Steps to reproduce
1- Open System Settings
2- Tap on Sound
3- Tap on Ringtone
4- Tap on Custom Ringtone

### Expected behavior
Content-hub header not red

### Actual behavior
Content-hub header gets red background

### Logfiles and additional information
![img_20180612_194100_266](https://user-images.githubusercontent.com/16002474/41310135-8f2245e2-6e78-11e8-8cb3-a76334c1b8cb.jpg)

**Comment by Daniel20000522** [comment] 2018-06-12 23:55
Confirmed on Nexus 4 16.04/devel r92

**Comment by Flohack74** [comment] 2018-06-13 15:58
Huu where does this one come form? This marks a deprecated header component in the SDK, but all of them should have been fixed in 15.04 already... Impressive...

**Comment by dpniel** [comment] 2018-06-13 16:03
It's beacuse it's using the page.title property which uses the deprecated header component. i.e

```qml
Page {
    title: "Blah"
```

It should be using the `page.header.title`

**Comment by Flohack74** [comment] 2018-06-13 16:28
But why it works in 15.04?

**Comment by dpniel** [comment] 2018-06-13 17:27
Because system settings doesn't use `AdaptivePageLayout` on 15.04. https://github.com/ubports/ubuntu-ui-toolkit/commit/4c9e59de5dbfa1b7b24297c5a13775304d64a428 is the commit which brings the deprecation warning in.

**Comment by Flohack74** [comment] 2018-06-13 17:27
Ahhh. Ok lets remember to fix this ;)

**Comment by ivoxavier** [comment] 2018-06-14 14:54
Actually by looking into this screenshot I've found another potential issue, why file manager isn't showing up on the list? It's someway related with the recent change from deb to clicks? Just to anticipate, I've file manager installed.

**Comment by NeoTheThird** [comment] 2018-06-14 16:33
Might be, filemanager is still a deb for the time being, so click hooks aren't executed.

**Comment by toehold** [comment] 2018-06-19 09:05
Same behaviour on N5 (Ubuntu 16.04 (2018-06-19/2)

**Closed** 2018-12-20 20:44 UTC
Labels: bug

**Comment by Ingo-FP-Angel** [comment] 2019-01-01 15:42
Device: FP2
Channel: RC
Version: 2018-W01

I cannot reproduce the issue, i.e. the fix works.

**Comment by 10JML01** [comment] 2019-01-01 17:00
Device: BQ E5HD
Channel: rc
Version: 2018-W01

Fix works, no red borders, though there is extra space under the custom ringtone field, and no spacing in content hub, as seen in the picture by the OP.

**Comment by 10JML01** [comment] 2019-01-01 21:47
Device: BQ M10FHD
Channel: rc
Version: 2018-W01

Red borders still visible.
How to  Reproduce: go to settings -> Background ->  Custom (add image)
there you'll still see the red borders.

**Comment by erik-kueng** [comment] 2019-01-02 18:44
Fairphone 2
rc
2018-W01

Fix works. Could not reproduce issue.
