### ISSUE TITLE
dash missing dot bar [...] in landscape

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#1133] opened 2019-05-09 23:45 UTC
fp2 edge
rotate the phone from portrait to landscape, the 3 dots bar is missing

**Comment by UniversalSuperBox** [comment] 2019-05-10 19:51
This is by design. When the Drawer is wide enough, it is possible to tap outside the Drawer to close it... or at least that was the thought.

**Comment by dobey** [comment] 2019-05-12 01:06
I would say even with the drawer not taking up the full width of the screen, we should still show the handle. I think it would also make sense to keep it, even after the relevant Qt issue is resolved, as it provides a visual hint. However, it might be appropriate to hide it if a touch gesture input device is not available (ie, on a PC with only keyboard/mouse), but that's probably much more difficult to resolve, and worth having a larger thought/discussion session on it.

**Comment by UniversalSuperBox** [comment] 2019-05-30 19:07
Fixed by https://github.com/ubports/unity8/pull/140

**Closed by UniversalSuperBox** 2019-05-30 19:07 UTC
Labels: edge, opinion
