### ISSUE TITLE
Camera zoom not working on OPO

### ISSUE THREAD

**Issue by wagafo** [ubports/ubuntu-touch#548] opened 2018-04-03 12:13 UTC
### Illustrations

- Device: OPO 
- Channel: 15.04/devel
- Build: 281

### Steps to reproduce

Open the camera application, try to zoom the image out

### Expected behavior

The camera should zoom out

### Actual behavior

The camera does not zoom out

**Comment by Berlinuxer** [comment] 2018-04-03 12:57
same with mine OPO.
Possibly same error like flashlight-problem?

**Comment by Flohack74** [comment] 2018-04-04 12:28
Duplicate of #355

**Closed by Flohack74** 2018-04-04 12:28 UTC
Labels: bug, device: bacon, duplicate
