### ISSUE TITLE
Show Wifi login page when needed

### ISSUE THREAD

**Issue by jug007** [ubports/ubuntu-touch#1229] opened 2019-09-19 18:11 UTC
Currently, when connecting to a Wifi network that needs a login page to be used (to accept the terms of use, or to login with credentials), no page opens and there seems to be no obvious way to open it.

There is probably two good options for when to show the login page:
1. Open it automatically when connecting to Wifi
2. Show a notification and open the login page when the notification is opened.

I personally think using a notification to give the option to open the login page would be the best option.

**Comment by UniversalSuperBox** [comment] 2019-09-20 17:27
Hi @jug007, this sounds like a duplicate of https://github.com/ubports/ubuntu-touch/issues/885. Please continue discussion there, and thank you for adding your voice!

**Comment by jug007** [comment] 2019-09-21 06:08
@UniversalSuperBox it is indeed similar and a notification is requested as well, but the topic is different.

That is a feature request for a way to prevent connecting to networks with webforms, since they don't always want to go through the login process. 

The my issue is not being able to reach this webform.

**Comment by UniversalSuperBox** [comment] 2019-09-21 13:08
There is a nod in your direction there:

> If there is some kind of a web form present a popup in a form of notification could also rise up to inform user about that. And not only Android does that but also the current Ubuntu 18.04 with Gnome so maybe some implementation of that could be taken from over there.

But I agree, it's not the focus of the issue.

For most of these forms, going to a site without any SSL (like http://detectportal.firefox.com/) will get you redirected to the form.

If you're having trouble completing the form, that doesn't appear to be mentioned here. Please open a new issue for that.

**Comment by jug007** [comment] 2019-09-21 13:26
> For most of these forms, going to a site without any SSL (like http://detectportal.firefox.com/) will get you redirected to the form.

That is a really good hint. I guess if that works in my case, then that will be my workaround.

**Comment by Flohack74** [comment] 2019-11-14 07:44
You can store it as a favorite on the browser. We have captive portal detection on a long list of needed features, and we will get there, but I dont see it for the next 1 or 2 updates.

I close this in favour of: We know already about it and its an accepted enhancement.

**Closed by Flohack74** 2019-11-14 07:44 UTC
Labels: enhancement

**Comment by jug007** [comment] 2019-11-18 09:32
@Flohack74 wouldn't it be better to mark this as planned, rather than closing the issue?
Personally, when I am looking at the issues and see one that is closed, I would assume that the issue is gone, rather than it just being accepted as an issue.
I also feel like developers willing to contribute, might look at the open issues to find something to do next.
The ideas concerning how to solve this problem might also be of value for a developer and would be more present with an open issue.

**Comment by Flohack74** [comment] 2019-11-18 12:56
I think its still OK to close, we will solve this together with #885 :)

**Comment by abitrolly** [comment] 2021-12-04 10:57
Thanks for the hint.
```
detectportal.firefox.com
```
Typing that manually in Morph browser on Ubuntu OnePlus bacon device allowed my to open browser login page for Hilton hotels. I still had to open my notebook to find this ticket. Typing anything else didn't work for some reason.
