### ISSUE TITLE
UBports app has no bottom margin

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#498] opened 2018-03-04 01:02 UTC
- Device: hammerhead
- Channel: xenial/devel
- Build: r273

### Steps to reproduce
Open the UBports app and scroll to the bottom.

### Expected behavior
There should be some sort of bottom margin so the text doesn't touch the bottom of the phone.

**Comment by tsimonq2** [comment] 2018-03-04 01:03
The same can be said for the Scopes menu.

**Comment by NeoTheThird** [comment] 2018-03-04 11:23
duplicate of https://github.com/ubports/ubports-app/issues/38

**Closed by NeoTheThird** 2018-03-04 11:23 UTC
Labels: enhancement, good first issue, team: ui
