### ISSUE TITLE
FP2 Edge: App drawer is not updated with new apps after installation

### ISSUE THREAD

**Issue by dupplak** [ubports/ubuntu-touch#1138] opened 2019-05-10 20:46 UTC
- Device: FP2
- Channel: Edge
- Build: 16.04

### Steps to reproduce
Install any app from Openstore.

### Expected behavior
New app appears in app drawer.

### Actual behavior
New app won't be shown

**Comment by advocatux** [comment] 2019-05-11 06:52
Duplicate of https://github.com/ubports/ubuntu-touch/issues/1058

**Comment by UniversalSuperBox** [comment] 2019-07-10 17:28
Duplicate of #1058

**Closed by UniversalSuperBox** 2019-07-10 17:28 UTC
