### ISSUE TITLE
Everytime the device restarts, the cellular connection is set to 2G

### ISSUE THREAD

**Issue by Jujuyeh** [ubports/ubuntu-touch#189] opened 2017-07-30 09:31 UTC
I have to set it back to 4G whenever the device has restarted. It wont save that setting if I power it off and then back on, if I restart it or if it hasn't any battery left.

Device: Meizu Pro 5 (turbo)
Version: OTA-1

**Comment by tomoqv** [comment] 2017-07-31 09:48
That is a long standing bug that has been present since the Canonical days. I was hoping it was gone in UBPorts. That's one of the reasons I am using my OPO as a daily driver now and the Pro 5 as a spare phone.

**Comment by Marathon2422** [comment] 2017-08-06 14:19
I remember this on my turbo pro5,it was fixed in one of the updates,aim on r 14t,but not using a sim card

**Comment by mardy** [comment] 2017-08-07 11:14
No, this bug was never fixed by Canonical.

**Comment by speedracer08861** [comment] 2017-08-23 14:36
The fix that i used for this is to have 2 sim cards installed.

**Comment by NeoTheThird** [comment] 2017-08-24 09:05
Can someone who's experiencing this issue [provide some logs](https://docs.ubports.com/en/latest/contribute/bugreporting.html#getting-logs)?

**Comment by kelmes** [comment] 2017-09-08 04:12
logs booting with one sim (where the issue occurs) and with two (where previous settings are loaded normally)

[UTlogcat.single.txt](https://github.com/ubports/ubports-touch/files/1286745/UTlogcat.single.txt)
[UTlogcat.dual.txt](https://github.com/ubports/ubports-touch/files/1286746/UTlogcat.dual.txt)
[UTdmesg.single.txt](https://github.com/ubports/ubports-touch/files/1286743/UTdmesg.single.txt)
[UTdmesg.dual.txt](https://github.com/ubports/ubports-touch/files/1286744/UTdmesg.dual.txt)

**Comment by kelmes** [comment] 2017-09-12 05:41
The ofono section of syslog seems relevant, especially in light of lines like this: [radio-settings.c](https://github.com/ubports/ofono/blob/master/drivers/rilmodem/radio-settings.c#L539)

[ofono_log_dual.txt](https://github.com/ubports/ubports-touch/files/1294822/ofono_log_dual.txt)
[ofonod_log_single.txt](https://github.com/ubports/ubports-touch/files/1294821/ofonod_log_single.txt)

**Comment by kelmes** [comment] 2017-09-12 11:11
using the package ofono-1.17.bzr6912+16.04.20160314.3 from xenial (built from the source package in xenial desktop, not necessarily the one from the phone image), this bug does not occur, presumably a regression somewhere between bzr6912 and bzr6921. Successful log attached.

[ofonod_log_6912.txt](https://github.com/ubports/ubports-touch/files/1295705/ofonod_log_6912.txt)

**Comment by kelmes** [comment] 2017-09-13 04:57
I'm not sure what's causing the error yet, but I can confirm that removing the callback allows the phone to restore settings correctly.

**Comment by Flohack74** [comment] 2017-09-13 07:40
OMG this is poor coding with labels:

`goto error;
`

Since 20 years I am being told you dont need labels in C :) - Anyway, it looks like we need to evaluate the error message there and see whts going on.

**Comment by kelmes** [comment] 2017-09-13 08:22
The actual error is RIL_E_GENERIC_FAILURE, if I have it return instead of callback on that error, everything works. From what I can tell the function is indirectly called from ril_query_rat_mode() below (using g_ril_send, god knows how that works), and ril_msg is generated somewhere between there and ril_rat_mode_cb() actually being called. Haven't figured out where yet.

**Comment by mardy** [comment] 2017-09-13 09:14
In my case (Meizu pro 5 with Canonical OTA-15) I encounter this problem even if I have two SIMs active (and I remember I had the same issue with the BQ, with two SIMs too).
ofono version is `1.17.bzr6921+15.04.20160819`, and I'm attaching the [ofono logs](https://github.com/ubports/ubports-touch/files/1298860/ofono.txt) found in the syslog right after boot. It seems that the error message found by @kelmes is not there in my case.

**Comment by kelmes** [comment] 2017-09-13 09:46
@mardy can you let me know whether [questionable_patch.diff](https://github.com/ubports/ubports-touch/files/1298950/questionable_patch.diff.txt) fixes anything for you? also logs from this version might be helpful.

(zipped .deb below, github is weird about file types apparently)
[ofono_1.17.bzr6921+16.10.20160819.6-0ubuntu1_armhf.zip](https://github.com/ubports/ubports-touch/files/1298953/ofono_1.17.bzr6921.16.10.20160819.6-0ubuntu1_armhf.zip)

**Comment by mardy** [comment] 2017-09-13 10:13
@kelmes no, it doesn't fix the issue here. :-(
I wonder if you'd have time to try to merge the master branch from the upstream repository (https://git.kernel.org/pub/scm/network/ofono/ofono.git), since I see that there have been new commits in that tree, that are not in Canonical's? I could do that myself one of these evenings, but just in case you happen to be faster... ;-)

**Comment by kelmes** [comment] 2017-09-13 10:20
I actually had a go at it earlier today, but I couldn't quite get it to build. I get the impression that we have patches in [this version](https://code.launchpad.net/~phablet-team/ofono/ubuntu) that aren't upstream.

**Comment by Flohack74** [comment] 2017-09-13 10:25
Specifically the https://git.kernel.org/pub/scm/network/ofono/ofono.git/tree/drivers/rilmodem/radio-settings.c file looks totally different, we should probably try to backport latest ofono to 15.04 ;)

**Comment by kelmes** [comment] 2017-09-13 10:58
I've got 1.20 running, but it doesn't do much at the moment: 
[ofono_1.20_log.txt](https://github.com/ubports/ubports-touch/files/1299163/ofono_1.20_log.txt)

no sim detected

**Comment by mardy** [comment] 2017-09-13 11:21
@kelmes is that the 1.20 upstream branch, or does that include Canonical's changes?

**Comment by kelmes** [comment] 2017-09-14 09:50
just upstream

**Comment by kelmes** [comment] 2017-09-17 01:09
The vast majority of the work on rilmodem seems to have been done in the fork on launchpad ([here](https://code.launchpad.net/~phablet-team/ofono/rilmodem) or [here](https://code.launchpad.net/~phablet-team/ofono/ubuntu), these seem to be largely the same). Things definitely work for me up to [revision 7029](http://bazaar.launchpad.net/~phablet-team/ofono/rilmodem/revision/7029), which adds almost all of radio-settings.c ...

**Comment by kelmes** [comment] 2017-09-17 01:10
also from what I can tell requests go into a queue for the android side of things to do something with, and the come back with an exit code, in our case GENERIC_FAILURE (for me at least)

**Comment by kelmes** [comment] 2017-09-17 02:00
This seems like a neater way to deal with it: [nicer-patch.diff.txt](https://github.com/ubports/ubports-touch/files/1308777/nicer-patch.diff.txt)

@mardy can you try this one: 
[ofono.deb.zip](https://github.com/ubports/ubports-touch/files/1308781/ofono.deb.zip)

**Comment by mardy** [comment] 2017-09-18 13:57
Wow, I can't believe my eyes! :-) I reboot twice, and it worked both times. Thanks @kelmes, it would really seems that your patch fixed this bug!

@Flohack74 I see that https://github.com/ubports/ofono does not have all the commits from https://github.com/rilmodem/ofono; is it a mistake, or is there some reason why you didn't include the last commits?

**Comment by kelmes** [comment] 2017-09-19 00:01
we seem to be up to date with this version: https://code.launchpad.net/~phablet-team/ofono/ubuntu, I'm not sure how comparable the two are

**Comment by kelmes** [comment] 2017-09-24 20:26
So what seems to be happening is the radio with no sim returns an unknown/unsupported preferred technology. oFono then correctly detects that it is capable of lte, and sets it to that. The problem being, only one radio can be set to 3g/4g, and the radio we care about gets set to gsm automatically.

**Comment by kelmes** [comment] 2017-09-24 20:36
other than just removing the check altogether, I can have it:

-  only check the network on a radio that has a sim (but this might break emergency calling on phones with only one sim slot),
-  always set a broken radio to gsm (which could be a problem if gsm is unsupported)
- do either of the above, but only if there are two radios available, otherwise set normally.
- (possibly, I haven't tried this) check to see whether another radio is already set to 3g/4g, and if so, only set to gsm.

Unfortunately I can't see a way to distinguish a dual-sim phone where both sims are cabable of all advertised modes simultaneously, from our situation (which I expect is more common), where only one can be set above gsm. For the moment, I'll try to get the last option working, but other suggestions are welcome.

**Comment by mariogrip** [comment] 2017-12-14 06:08
Fix released https://github.com/ubports/ofono/commit/0ca1960b60ba8585f121aff4bfb5e64c58aa96e0 

Thanks to @kelmes for fixing this :)

**Comment by dark-eye** [comment] 2017-12-14 12:51
Thanks guys!  just got the update on devel and seem to work like magic on my device :)

**Comment by NeoTheThird** [comment] 2017-12-14 23:45
Reported fixed. Thanks everyone!

**Closed by NeoTheThird** 2017-12-14 23:45 UTC
Labels: bug, device: turbo
