### ISSUE TITLE
bluetooth not working with ubuntu OS for file transfert

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1005] opened 2018-12-15 14:12 UTC
I cannot transfer any file from Ubuntu desktop to Ubuntu touch using bluetooth. Yet devices are mutually recognized.

- Device: LGE Nexus 4
- Channel: Stable
- Build: OTA-6

 Steps to reproduce
Enable both desktop and ubuntu touch bluetooth.
With Ubuntu desktop, I choose a file to transfert.
A message appear with "timeout" error.

 Expected behavior
To get the file transfered.

 Actual behavior
Connection is lost, not stable. I cannot transfert any file.

**Comment by UniversalSuperBox** [comment] 2018-12-16 03:32
There is nothing built in to the operating system to receive files via Bluetooth. Are you using https://open-store.io/app/ubtd.fourloop2002?

**Comment by UniversalSuperBox** [comment] 2018-12-17 21:09
I am able to send a file to my Nexus 5, Nexus 7 2013 Wi-Fi, and Fairphone 2 with the Bluetooth file transfer app open. The devices must be paired before trying to transfer the file, which can be initiated from either side.

**Comment by LlamasJM** [comment] 2019-01-04 07:32
This issue affects me too. Unable to send an image from my FP2 via Bluetooth File Transfer. Connection not stable.

**Comment by UniversalSuperBox** [comment] 2019-01-04 19:58
Well, it seems like we aren't really able to pin down a device combination or specific bug yet. I did a *lot* of testing today to see if I could find any patterns in the transfer failures. I'd encourage you to add your voice here: https://forums.ubports.com/topic/2222/bluetooth-file-transfer-testing

Since we aren't able to find a reproducible pattern yet, I'll close this issue for now. Hopefully that forum thread will help us to find some patterns and file some actionable bugs!

**Closed by UniversalSuperBox** 2019-01-04 19:58 UTC
Labels: needs confirmation
