### ISSUE TITLE
It is difficult to swipe apps away on android9 / gsi devices

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1568] opened 2020-09-23 17:40 UTC
- Device: yggdrasil, pro1, or any gsi device
- Channel: devel / edge
- Build: any

### Steps to reproduce

1. Open an app
1. Swipe from the right edge to open the app spread
1. Swipe naturally downward or upward to close the app

### Expected behavior

The app follows my finger from the bottom to the top and closes

### Actual behavior

The app follows for a very short time, then stops and returns to its resting position.

### Logfiles and additional information

My original theory was that this issue was caused by the tall aspect ratio of the Volla Phone, but it turns out it also occurs on 16:9 Android9 devices. Also, it *does not* occur on the PinePhone which has a similarly tall screen.

It is possible to work around this by using a very wide touch point (like pressing with the full pad of your finger) and slowly swiping the app away. Swiping *very* quickly from the bottom of the app to the top of the screen can also cause the app to close reliably.

**Comment by mateosalta** [comment] 2020-10-01 17:58
im wondering if this is a side effect of certain types of touchscreen, i experience similar problems with my sony xperia - but only because of some small deadspots on the touchscreen caused by dammage. maybe a minimum detection feature to fix ghost touches?

**Comment by peat-psuwit** [comment] 2020-10-08 12:11
Fixed by https://github.com/ubports/mir-android-platform/commit/732621feb6b9746bb35b79de5ea9c707bc424fc4

So, the problem is that the horizontal SwipeArea is too sensitive to touch recognition and grab the touch away from the vertical touch area. The threshold is derived from the DPI/physical screen size. Turns out, mir-android-platform's HWC2 backend reports DPI incorrectly. The mentioned commit fixed that.

**Closed by peat-psuwit** 2020-10-08 12:11 UTC
Labels: bug

**Comment by TellingBerto** [comment] 2020-10-27 09:21
Device: VollaPhone
Channel: rc
Build: 2020-W43

Result: Issue fixed, also working if multiple apps are opened.

Steps to reproduce

 1. Opened an app
 2. Swiped from the right edge to open the app spread
 3. Swipe naturally downward or upward to close the app
