### ISSUE TITLE
No audio with earphones in PP

### ISSUE THREAD

**Issue by SleepIsLife** [ubports/ubuntu-touch#1499] opened 2020-06-26 21:21 UTC
Hi I recently purchased the pinephone, I tried using my earphones ad noticed no audio is being produced when plugged in. 

### Illustrations

- Device:
- Channel:
- Build:

**Comment by Bugsbane** [comment] 2020-06-27 17:05
Duplicate of the issue on Gitlab [here](https://gitlab.com/ubports/community-ports/pinephone/-/issues/2). I'd suggest closing this issue (as a duplicate) and giving a thumbs up over on Gitlab, as that's where the dev team have asked people to file Pinephone related issues.

**Comment by UniversalSuperBox** [comment] 2020-06-27 18:00
Hi @SleepIsLife, thanks for your report.

As @Bugsbane mentioned, this issue is already filed on the PinePhone GitLab tracker: https://gitlab.com/ubports/community-ports/pinephone/-/issues/2

Please file any new issues that only affect the PinePhone there in the future.

Thanks again!

**Closed by UniversalSuperBox** 2020-06-27 18:00 UTC
