### ISSUE TITLE
Keyboard fluctuate while using in web app (skype).

### ISSUE THREAD

**Issue by 1Mike1** [ubports/ubuntu-touch#1125] opened 2019-05-01 12:41 UTC
### Description of the feature

I love this os I just switched from iPhone to ubuntu touch, it really awesome.

You guys are doing a really great job, I just wish you guys will get succeed in goal.

I just want to add something where I feel why people attach with Android and IOS, I think just because of apps. So team if it's possible please deploy some daily bases app according to Indian market (Paytm, Phonpe, Tez ...etc). The reason behind these apps is digitization in India. People just to go cashless so if you guys will target these apps. I hope in meantime you guys will rock in the market. Also, add Social networking apps, I understand Ubuntu is mainly used for development but if you guys will target the end user you guys will be the best because you guys will have the power of developer and support from the end users, that's what required to stay in the market.

 Thanks. 

### Illustrations

- Device: Nexus 5
- Channel:
- Build: 16.04(OTA 8)

### Steps to reproduce

Hi Team,

I am running ubuntu touch on my Nexus 5. when I was using skype (web app) I was not able to send a proper text because of the keyboard, it just hides by its own when I was trying to delete something and pop up again.

**Comment by UniversalSuperBox** [comment] 2019-05-01 19:57
Hmm. @balcy, have you seen or heard of behavior like this from the OSK inside a Morph webapp?

**Comment by balcy** [comment] 2019-05-02 16:50
No, I have not heard/seen that so far.
But I can confirm that behavior for the skype webapp. (BQ Aquaris 4.5)
Pressing the back button in the OSK removes the last letter, but then the OSK is automatically closed.

In morph-browser with desktop mode (= desktop user agent) enabled, I see the same problem (https://web.skype.com)
Without desktop mode, the page just shows a "Device not supported" info page (before and after login)

**Comment by kugiigi** [comment] 2019-12-01 11:50
Probably related to #1244 ?

**Comment by boriseto** [comment] 2020-11-19 20:05
Since the devices can handle more complex desktop sites and we actiually want to use the deaktop user agent in specific webapps, this becomes a bigger issue lately. Just leaving a comment becausr skype isn't the only app that benefits from desktop mode.

**Comment by UniversalSuperBox** [comment] 2021-02-20 20:10
I believe this issue is the same as https://github.com/ubports/morph-browser/issues/468, and it is becoming more pronounced as time goes on (maybe it's a race condition?)

Since more investigation has happened on the morph-browser tracker, I will close this report in favor of that one.

**Closed by UniversalSuperBox** 2021-02-20 20:10 UTC
Labels: needs confirmation
