### ISSUE TITLE
USB tethering not working

### ISSUE THREAD

**Issue by Fazarel** [ubports/ubuntu-touch#1031] opened 2019-01-12 19:39 UTC
- Device: arale / Meizu MX4
- Channel: Stable
- Build: 16.04, OTA-6 (20181126)

### Steps to reproduce
Connect the phone via USB.
Enable USB tethering in a terminal:
`android-gadget-service enable rndis`
or by using [UT Tweak Tool ](https://ubports.com/es_ES/blog/nuestro-blog-1/post/ut-tweak-tool-109).

### Expected behavior
Internet on the computer.

### Actual behavior
No Internet on the computer.

**Comment by kugiigi** [comment] 2019-01-22 10:15
Can you try this again on OTA-7?
Libhybris was updated and maybe this one was solved with it.

**Comment by kugiigi** [comment] 2019-01-22 10:21
Also, this is a duplicate of #798

**Comment by hummlbach** [comment] 2019-01-22 11:45
Thanks for pointing that out @kugiigi. @Fazarale you can add a comment to #798 that it doesn't work with arale either if you like.

**Closed by hummlbach** 2019-01-22 11:45 UTC
