### ISSUE TITLE
Volla Phone X: indicator bar partly not visible

### ISSUE THREAD

**Issue by 4c2** [ubports/ubuntu-touch#1820] opened 2021-09-05 22:13 UTC
### Illustrations

- Device: Volla Phone X
- Channel:
- Build:2021-08-24/5

### Steps to reproduce
Trun on the phone and log in. 

### Expected behavior
Everything in the status bar (indicator bar) is visible. 

### Actual behavior
Parts of the indicator bar are hidden by the curved corners of the display and by the camera. As you can see in the picture, the time is only partly visible and the green mail indicator is hidden by the camera. 
![image20210906_001824176](https://user-images.githubusercontent.com/76594587/132142981-a4a12b8d-03be-4bdc-80b4-6a25bca14c0a.jpg)

**Comment by Quget** [comment] 2021-09-21 16:26
Same with regular Volla Phone.

On twitter someone send me this link with a temporary fix. It is not perfect, but it does make more things visible.
https://github.com/JamiKettunen/unity8-notch-hax

I do hope for a official fix to solve the issues with rounded corners and notches on phones.

**Comment by Flohack74** [comment] 2022-07-14 14:49
Kinda a duplicate of https://github.com/ubports/ubuntu-touch/issues/523 since it affects all phones that have a notch

**Comment by Flohack74** [comment] 2022-07-14 14:50
Note that we have a conceptual idea now how to fix it and will track it in aforementioned issue.

**Closed by Flohack74** 2022-07-14 14:49 UTC
