### ISSUE TITLE
OS update button not responsive after failure

### ISSUE THREAD

**Issue by Arc676** [ubports/ubuntu-touch#698] opened 2018-06-21 02:53 UTC
- Device: Nexus 5 (hammerhead)
- Channel: 16.04/devel
- Build: r401

### Steps to reproduce
Try to update to the latest build. The update failed because the WiFi signal was weak and connection was lost. Reconnect to the network and update again.

### Expected behavior
Device restarts download.

### Actual behavior
It says the update failed and the button is non-responsive. The update is just stuck there on "update failed".

### Logfiles and additional information
![screenshot](https://user-images.githubusercontent.com/30745465/41695237-ceb9aa0a-7540-11e8-8bbe-f2ca6d600bae.png)

This doesn't seem to happen 100% of the time. Additionally, a simple workaround is going to the About section and tapping "check for updates". This usually gets the device to check for updates again and this removes the stuck entry from the list, but this also doesn't always work.

I haven't updated my device in a while; I'll update this thread if it happens again on r442.

**Comment by advocatux** [comment] 2018-06-21 06:30
This looks like a duplicate of  #693 Can you confirm it (or not) in that bug report? Thank you

**Closed** 2018-06-21 17:33 UTC
Labels: duplicate
