### ISSUE TITLE
Touchpad does not work when using SlimPort

### ISSUE THREAD

**Issue by 3arn0wl** [ubports/ubuntu-touch#301] opened 2017-10-17 09:20 UTC
- Device: Nexus 5 - Hammerhead
- Channel: stable
- Build: OTA-2

## Steps to reproduce

Connect the device to a screen using a SlimPort adapter.

## Expected behaviour

The devices screen turns into a touchpad and a cursor shows up on the screen it's connected to.

## Actual behaviour

Touch-pad does not work, no cursor shows up.

**Comment by samzanemesis** [comment] 2017-10-18 13:46
I would like to add to this issue, the real bug is that the screen can't be used as a touchpad, a bluetooth mouse works fine

Seems touchscreen works, as the indicator to use the screen as a touchpad fades away when you swipe it, but there is no activity on the mains creen

I'm with a Hammerhead on devel

**Comment by NeoTheThird** [comment] 2017-10-19 11:27
Thanks @samzanemesis, i updated the report. Can someone reproduce and confirm this?

**Comment by scastren** [comment] 2017-10-19 16:18
This happened to me as well. I flashed my Nexus 5 right after the first version of UT of UBports was released. When I tested my N5 with SlimPort adapter (which work nicely with the UT version from Canonical) there was no mouse activity when touching the screen of the phone.

**Comment by mauricioduarte01** [comment] 2017-11-19 15:23
Hi,
I can reconfirm this. I though this was fixed or something like that because I was seeing some users in the UBports Telegram SG talking about this, but as soon I tried connect my N5 via Slimport to my TV, the device screen just fade out and nothing else happens, I just can use the screen keyboard to unblock the session and thats it

**Comment by SwizzleMaster** [comment] 2018-02-06 11:17
I have the same issue on a fresh hammerhead installation, OTA3 （ I tried both stable and dev channel ） + slimport cable

**Comment by ezickler** [comment] 2018-03-15 10:27
Same here

**Comment by ruedigerkupper** [comment] 2018-03-18 15:23
Confirmed.

**Comment by simoxxx** [comment] 2018-03-19 13:26
I can confirm this bug on xenial too. 
(on nexus 4 this feature works fine on both releases vivid and xenial)

**Comment by pom3ranc86** [comment] 2018-04-20 18:58
Confirmed.

**Comment by abkro** [comment] 2018-06-06 17:35
Confirmed on Nexus 5 hammerhead running Xenial r415. @NeoTheThird do you need logs or something? I could post them...

**Comment by NeoTheThird** [comment] 2018-06-09 08:36
@abkro Not sure if it will log something, but [dmesg and logcat](https://docs.ubports.com/en/latest/contribute/bugreporting.html?highlight=logcat#getting-logs) never hurt.

**Comment by abkro** [comment] 2018-06-09 16:10
OK. Just confirmed that there's no change on r419. I'll update here and post the logs within a couple of hours. I'll just edit this comment and paste them in here.

**Comment by abkro** [comment] 2018-06-09 20:17
@NeoTheThird I connected my Nexus 5 now running r419 today. Here are the logs.

[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2087296/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2087297/UTlogcat.txt)

**Comment by samzanemesis** [comment] 2018-09-15 23:10
Works in Xenial, please close this issue 👍  @UniversalSuperBox

**Comment by UniversalSuperBox** [comment] 2018-09-16 20:49
I'm not able to confirm that. Still doesn't work for me with data from before the latest updates. Did you flash with wipe @samzanemesis?

**Comment by nfsprodriver** [comment] 2018-09-16 21:39
Also can confirm that. Seems to be fixed with the today's scaling fix.

**Comment by 3arn0wl** [comment] 2018-09-16 22:01
It's not working for me yet either - Hammerhead.16:04.dev

**Comment by nfsprodriver** [comment] 2018-09-16 23:37
Have you updated your system via apt?

**Comment by MK1973** [comment] 2018-09-17 08:16
Confirm the screen does not work as a touchpad.

I can insert my passcode from the touchscreen keyboard that appears pressing the power button or volume, but than there is no any pointer to interact with.

device: N5
channel: devel, update version 594
OS: Xenial 16.04

**Comment by 3arn0wl** [comment] 2018-09-17 08:30
"Have you updated your system via apt?" 

I got the automatic update, and I have installed the latest dev image this morning.
I have just tried it again on two monitors, and it doesn't appear to be working.

**Comment by APokorny** [comment] 2018-11-04 16:39
We would need unity8 logs (home/phablet/.cache/upstart/unity8.log of while the slim port is attached. 
Additionally /var/log/lightdm/unity-system-compositor.log would help.

For the touchpad simulation unity8 crates a userspace input device via /dev/uinput and turns it into a mouse. 
If that succeeds usc should tell us about the new device. And we should see error traces otherwise in unity8.log

Also you could login to the device via ssh while the slimport adapter is plugged in and look for the simulated device in /dev/input/

**Comment by SwizzleMaster** [comment] 2018-11-04 17:17
> We would need unity8 logs (home/phablet/.cache/upstart/unity8.log of while the slim port is attached.
> Additionally /var/log/lightdm/unity-system-compositor.log would help.

Logs; as requested.

[unity8.log](https://github.com/ubports/ubuntu-touch/files/2546065/unity8.log)
[unity-system-compositor.log](https://github.com/ubports/ubuntu-touch/files/2546066/unity-system-compositor.log)

**Comment by APokorny** [comment] 2018-11-05 16:39
Hmm I dont see "Virtual uinput mouse device created". And no traces of another input devices being opened.

**Comment by SwizzleMaster** [comment] 2018-11-11 10:16
> Hmm I dont see "Virtual uinput mouse device created". And no traces of another input devices being opened

ok. i retried it... check near the [2018-11-11 17:52:50] timestamp

i also ran " ls /dev/u* " to check if the uinput device is present. it's there.
[ls_dev_u*.log](https://github.com/ubports/ubuntu-touch/files/2569238/ls_dev_u.log)
[unity8.log](https://github.com/ubports/ubuntu-touch/files/2569239/unity8.log)
[unity-system-compositor.log](https://github.com/ubports/ubuntu-touch/files/2569240/unity-system-compositor.log)

**Comment by mauricioduarte01** [comment] 2019-06-28 00:13
Tried edge today and I noticed a new interface and even a first time tutorial about how to use the touchpad. I notice that you can control the pointer but the touch area is not centered. I think now is a good time to review this issue because this feature is finally almost there. @MK1973

**Comment by 3arn0wl** [comment] 2019-07-03 21:51
Being able to control the pointed with the phone as a touchpad is clear development! I wonder if the centering issue is a difficult one to sort out?

**Comment by kugiigi** [comment] 2021-03-23 06:42
I tried this again on my Nexus 5 (devel 2021-03-21/2) and it now works again. Can anyone else try it too?

**Comment by kugiigi** [comment] 2021-03-23 18:58
Nevermind, looks like ubports/android_device_lge_hammerhead#30 actually fixed this 
I applied that manually before and I tried removing it and the touchpad stopped working again.

**Comment by UniversalSuperBox** [comment] 2021-05-25 16:49
Fixed by https://github.com/ubports/android_device_lge_hammerhead/pull/30

**Closed by UniversalSuperBox** 2021-05-25 16:49 UTC
Labels: bug, device: hammerhead
