### ISSUE TITLE
Terminal asks for password when opening from lock screen but not when already logged in

### ISSUE THREAD

**Issue by mr-growl** [ubports/ubuntu-touch#1411] opened 2020-04-01 00:19 UTC
BUILD: 2020-W13
DEVICE: nexus 5 ( hammerhead)

PREREQUISITES: 
-have a pin set for locking the phone
-have a short cut to terminal in the side bar

TO REPRODUCE
-lock the screen (press power button momentarily to turn off screen)
-press power button again to wake up the screen
-click on the terminal shortcut in the sidebar
-enter pin when prompted

At this point, currently, terminal also prompts me for my pin (so I'm entering it twice in a row). This is how I remember it working since I first started using ubuntu touch.  The thing is, though, if I close terminal and open it again while the phone is unlocked (not from the lock screen) then terminal does not ask for a pin, which is actually really nice (i think this is a new behavior as of this release candidate series).

I'm mentiong this because it would be nice if it behaved the same both from the lock screen and when not locked.  My opinion is that not having to enter the pin is a nicer experience, but just having a consistent experience is more what this is about.

**Comment by peat-psuwit** [comment] 2020-04-01 12:31
I believe this is the duplicate of #1406 and should  be fixed in the 2020-W14 image from the RC channel.

**Closed** 2020-04-02 07:34 UTC
Labels: duplicate
