### ISSUE TITLE
When adding google account,its not opening keyboard to type

### ISSUE THREAD

**Issue by himank3127** [ubports/ubuntu-touch#1607] opened 2020-11-23 03:59 UTC
When trying to add google account its not opening keyboard layout to enter

**Comment by UniversalSuperBox** [comment] 2020-11-23 15:32
Hello @himank3127, thanks for your report.

I'm unable to reproduce this issue on the OnePlus One, and you have not specified which device you are having trouble with. Could you please specify the device, OS version, and release channel you are having trouble with?

Thank you!

**Comment by UniversalSuperBox** [comment] 2021-02-05 00:10
Hello @himank3127,

Thanks again for your report. Unfortunately, since you have not specified your device, we are unable to confirm your report. I'll close it for now, but please let us know if this issue still exists.

**Closed by UniversalSuperBox** 2021-02-05 00:10 UTC
