### ISSUE TITLE
Unable to receive texts ( randomly )

### ISSUE THREAD

**Issue by alistair23** [ubports/ubuntu-touch#2080] opened 2022-12-01 01:40 UTC
- Device: Pixel 3a
- Channel: Release candidate
- Build: 2022-W47

### Steps to reproduce
Have a text message sent to a Pixel 3a on the Vodadone AU network.

### Expected behavior

Receive all text messages as they happen

### Actual behavior

Since updating to the OTA version 56 (I'm pretty sure 55 didn't have this issue) I am unable to receive text messages.

It doesn't seem to happen all the time though. It seems like I will receive texts for a little bit, then it will stop working.

If I put my SIM card in a new phone, I get the missed texts since it has stopped working. The process of receiving messages on a different phone sometimes gets the messages working again on the Pixel, but not always.

### Logfiles and additional information

I can't find any logs that seem relevant. Let me know if there are any I should include

**Comment by alistair23** [comment] 2022-12-01 01:43
@fredldotme and @Flohack74 as you two seem to be the Pixel 3a maintainers

**Comment by lduboeuf** [comment] 2023-01-07 10:27
confirmed on 20.04 as well. Sometimes i can receive them, sometimes not which makes this device not enough reliable.

**Comment by ivoxavier** [comment] 2023-01-12 15:45
Had this issue on OnePlus 6T (Xenial) and Fairphone4 (xenial/focal).

Since 2021 I'm daily driving the 6t, and it always had this issue. You could use it for three weeks without this issue, but in the next it happen. But, this patch[1] reduced the problem and now things are more stable, but still happens with less frequency.

[1] https://gitlab.com/ubports/porting/community-ports/android9/oneplus-6/kernel-oneplus-sdm845/-/commit/7dfa9f9062e6266d71c950a04d194a8ce10bb3a2

**Comment by rusins** [comment] 2023-01-17 12:07
I am also experiencing such an issue. I've noticed (both on stable Ubuntu 16.04, OTA-24, and on RC 16.04 2022-W47) that restarting the phone will often put the phone in a state where I am unable to receive any SMS messages. Sending SMS works, and making and receiving phone calls works. Only receiving SMS fails.

I've also noticed that doing a software update (for example, switching from stable to RC branch, or from RC to stable) makes the issue go away, and turning flight mode on and off also fixes the issue.

Unfortunately, the text messages that should have been received during the bug being active, do not come back after the bug is suppressed. This makes me believe that the phone is telling the carrier that it received those messages, so they do not get retried later when the phone is in working order.

I never experienced such issues before the stable OTA-24 update at the start of December 2022.

**Comment by 45bcdf** [comment] 2023-01-17 17:32
I am having the same issue (receiving SMS) here in Canada (on Public Mobile). When I swap SIM to my Nexus 5, I have fully reliable SMS again. I have not tried toggling flight mode to see if this fixes the issue. I will try and report back with my findings.

**Comment by lduboeuf** [comment] 2023-01-19 14:10
From Telegram P3a group:

> I think you are right. SMS has been working absolutely fine for me on stable. Restarted my phone today while it was on 2G/3G/4G and when it came back on I could no longer receive text messages. I could send them, and they were received by the recipient, but no messages sent to me arrived. I could also make calls. I fixed this by switching to 2G only, and turning flight mode on and off again. I then sent more messages, and received them, along with most of the missing messages. It seems to be working OK now.

**Comment by kdcllc** [comment] 2023-02-03 02:30
> From Telegram P3a group:
> 
> > I think you are right. SMS has been working absolutely fine for me on stable. Restarted my phone today while it was on 2G/3G/4G and when it came back on I could no longer receive text messages. I could send them, and they were received by the recipient, but no messages sent to me arrived. I could also make calls. I fixed this by switching to 2G only, and turning flight mode on and off again. I then sent more messages, and received them, along with most of the missing messages. It seems to be working OK now.

@lduboeuf thanks for this tip! It solved my issue with not receiving text messages. I was able to send sms and msms fine but not receiving them. This little trick did it.

I spent hours trying to configure my Pixel 3a today. 

I was able to follow the following article to get APN setup correctly  https://forums.ubports.com/topic/6286/mms-on-mint-mobile-does-not-work/2 like so
![image](https://user-images.githubusercontent.com/13120940/216497012-25a0859b-679e-473c-a3b6-a28c243b08f7.png)
![image](https://user-images.githubusercontent.com/13120940/216497038-0018027c-6d32-4933-b7fa-9aa082e226bf.png)

- https://github.com/ubports/ubuntu-touch/issues/1752

**Comment by kdcllc** [comment] 2023-02-03 02:31
> From Telegram P3a group:
> 
> > I think you are right. SMS has been working absolutely fine for me on stable. Restarted my phone today while it was on 2G/3G/4G and when it came back on I could no longer receive text messages. I could send them, and they were received by the recipient, but no messages sent to me arrived. I could also make calls. I fixed this by switching to 2G only, and turning flight mode on and off again. I then sent more messages, and received them, along with most of the missing messages. It seems to be working OK now.

@lduboeuf thanks for this tip! It solved my issue with not receiving text messages. I was able to send sms and msms fine but not receiving them. This little trick did it.

I spent hours trying to configure my Pixel 3a today. 

I was able to follow the following article to get APN setup correctly  https://forums.ubports.com/topic/6286/mms-on-mint-mobile-does-not-work/2 like so
![image](https://user-images.githubusercontent.com/13120940/216497012-25a0859b-679e-473c-a3b6-a28c243b08f7.png)
![image](https://user-images.githubusercontent.com/13120940/216497038-0018027c-6d32-4933-b7fa-9aa082e226bf.png)

- https://github.com/ubports/ubuntu-touch/issues/1752
- https://github.com/ubports/ubuntu-touch/issues/1794

**Comment by Flohack74** [comment] 2023-02-11 15:03
@alistair23 can you please run `ps -ax | grep ims` in a console and tell me the result? Thx!

**Comment by lduboeuf** [comment] 2023-02-13 12:46
to complete, here is my full log from yesterday's failure on 20.04: https://gitlab.com/ubports/development/core/packaging/ofono-sailfish/-/issues/5#note_1275916151

**Comment by lduboeuf** [comment] 2023-02-13 14:28
@Flohack74 This occurs since OTA-24 stable

**Comment by Barry-T** [comment] 2023-03-01 14:12
I have also had this SMS issue on my Pixel 3a running 16.04 stable channel (OTA24). Turning Flight Mode on and off gave a temporary fix, but it did not last for long. I upgraded to the 20.04 Development channel (currently at version 468) and the SMS system is working perfectly; texts are delivered within a few seconds of being sent.
Thanks for all your hard work, Focal is looking great.

**Comment by Flohack74** [comment] 2023-03-26 18:26
Since this is no regression in OTA-25 but sadly already from before, I remove the blocker here. As OTA-25 is the final OTA for xenial, lets see how we can improve this in 20.04

**Comment by alistair23** [comment] 2023-03-27 23:53
> @alistair23 can you please run `ps -ax | grep ims` in a console and tell me the result? Thx!

Nothing, `ims` isn't running.

Note that I don't have a SIM card in the phone at the moment (as texts aren't working)

**Comment by lduboeuf** [comment] 2023-05-03 04:20
This issue seems to be fixed now.

**Closed as completed by lduboeuf** 2023-05-03 04:20 UTC
Labels: team: android9, device: sargo, device: FP4
