### ISSUE TITLE
[xenial] system settings main list does not remember the scrolling position

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#707] opened 2018-06-22 12:30 UTC
xenial RC on Fairphone2
open System Settings app, scroll down (until you see Reset)
tap on Battery > then tap on back < Battery
the list in the main system settings in now scrolled up, the last entry is Notification
fix: don't reset the scroll position when you press back

**Comment by advocatux** [comment] 2018-06-22 15:11
This is a duplicate of #634 
It has been moved to OTA-5

**Comment by pixelr0** [comment] 2018-06-22 15:34
great. thanks!

**Closed** 2018-06-22 17:36 UTC
