### ISSUE TITLE
Upgrade to OTA-25 boot problems

### ISSUE THREAD

**Issue by dtarrant2019** [ubports/ubuntu-touch#2124] opened 2023-04-02 10:38 UTC
After upgrading my Nexus-4 and BQ M10 devices to OTA-25 xenix stable, I noticed that both of them now have a boot problem which never occurred under OTA-24. Now when I press the button to start from a power-off state, they appear to begin the boot process and then the screen goes black. To recover from this requires a very long power button press and then they start and run as expected.-

- Device:
- Channel:
- Build:

**Comment by lduboeuf** [comment] 2023-04-03 07:06
Many devices seems affected
https://forums.ubports.com/topic/8750/ota-25-call-for-testing-companion-post/11?_=1680505442249

https://forums.ubports.com/topic/8827/maybe-be-have-a-thread-for-ota-25-non-boot-issues/3

Reinstall from the installer does not fix the issue

**Comment by dtarrant2019** [comment] 2023-04-03 08:48
Interesting. I would be concerned that a reinstall might not preserve all of the stuff stored on my BQ tablet.
I suppose I could try the reinstall approach on my Nexas-4 and see what happens.

**Comment by dtarrant2019** [comment] 2023-04-03 11:08
Commented on GitHub.

Sent from Samsung Galaxy-A51 Powered by Three
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lduboeuf** [comment] 2023-04-06 11:36
Confirmed on BQ4.5 too. Nexus 5.
It appears it affects armhf devices if i'm not wrong

**Comment by lduboeuf** [comment] 2023-04-07 06:52
By trying to install previous version with `ubuntu-device-flash` on BQ4.5 it appears that RC version "20221121" doesn't have the boot issue.
Here is the output of `dpkg -l` for the revision "20221121" and the next RC that already have the issue "20230312"

[20221121.txt](https://github.com/ubports/ubuntu-touch/files/11176682/20221121.txt)
[20230312.txt](https://github.com/ubports/ubuntu-touch/files/11176678/20230312.txt)

diff online ( left is 20221121, right is 20230312): https://www.diffchecker.com/CmPve3ST/

syslog for stuck boot:
[syslog.log](https://github.com/ubports/ubuntu-touch/files/11177878/syslog.log)

**Comment by FlavioMala** [comment] 2023-04-07 13:44
Confirmed on BQ E5 HD ch dev or RC (stable OK).
The phone: has the problem with **restart, power off > on, upgrade** (no matter); hangs **at different points**; needs **2 or 3 "loops"** to resume (hold the on/off button for a long time).

**Comment by FlavioMala** [comment] 2023-04-11 10:42
Today around 11:54 I did a "reboot", here's what happened:
(NB: ch dev v. 585 build 2023-03-25)
[step 0 shutdown]
step 1 - "hangs" on white screen with BQ logo, (then long press power [on/off] button)
step 2 - pressed "power" to restart... the BQ logo appears, after a while the red UBports startup screen appears, but approximately after about 20 seconds (about twenty "white dots") the phone turned off (by itself), then turned it back on (by itself), then the BQ logo reappeared, then the red screen... and this time it finally started again.

Syslog attachment (only the part from about 11:53):
[syslog_part.txt](https://github.com/ubports/ubuntu-touch/files/11199403/syslog_part.txt)

I have noticed that the "time" often rolls back, for example (NB: line 1 blank !) at line 5 (11:53:58 > 09:03:47), 1273 (about 30 seconds), 3192 (about 1.5 minutes, at line 4324 it jumps forward)

at 4837 up to 4842 no time recorded, only
"continue after 5 seconds ...
continue after 4 seconds ...
continue after 3 seconds ...
continue after 2 seconds ...
continue after 1 seconds ...
continue after 0 seconds ..."

at 5745 jump back (about 1.5 minutes), etc. 

**Is all this "normal"?**

notice this 3 lines from the end (remember, I did a reboot, the phone didn't stay off for a long time!):
[6744] Apr 11 11:5**2**:37 ubuntu-phablet kernel: [   43.277388][lcm_esd_check]buffer[0]=0x1c
[6745] Apr 11 11:5**7**:11 ubuntu-phablet ntpdate[3805]: step time server 185.125.190.58 offset 270.814954 sec

**Comment by dtarrant2019** [comment] 2023-04-11 15:08
Not normal. Compared to my BQ M10 which behaved flawlessly on OTA-24 stable, it's now a pain to start with OTA-25. My concern is that it will be considered too much bother to fix. For me, that will be a shame as it was great for my use case.

**Comment by dtarrant2019** [comment] 2023-04-11 17:45
Good news, just tried a fix suggested by @Danfro:
Switched from Stable to RC channel and my BQ M10 tablet now boots sweetly again! ☺

**Comment by lduboeuf** [comment] 2023-04-11 20:30
> Good news, just tried a fix suggested by @Danfro: Switched from Stable to RC channel and my BQ M10 tablet now boots sweetly again! ☺

Please test several cold boot, i've also tested several previous RC but while it was working the first time, It get stuck again on another try...

**Comment by dtarrant2019** [comment] 2023-04-11 20:57
Further good news: I've just tried this fix on my Nexus-4 and that now boots ok too.
Will do as you suggest Lionel and try a few cold boots. Done 3 ok so far with the BQ M10 tablet.
See also recent post at 21h20 by Danfro on Teleports UBports Welcome and Install Help.

**Comment by dtarrant2019** [comment] 2023-04-12 05:31
Lionel, done a couple more cold boots with my BQ M10 tablet and have had one failure so far. So, like you, I've confirmed the fix isn't infallible.

**Comment by lduboeuf** [comment] 2023-04-12 13:29
Some investigation done:

I confirm, from a stable RC version (20221121) and by installing biometryd with version 0.0.3\~20221125174438.5~4d8024d+ubports16.04 it starts to have boot issues.
Some logs:
```
Apr  7 11:26:24 ubuntu-phablet kernel: [   31.260365]init: biometryd main process (2016) terminated with status 78
Apr  7 11:26:24 ubuntu-phablet kernel: [   31.260551]init: biometryd respawning too fast, stopped
Apr  7 11:26:24 ubuntu-phablet kernel: [   31.425044]mtkfb_ioctl, display_id=0
Apr  7 11:26:24 ubuntu-phablet kernel: [   31.425063][wwy]lcm_parms->physical_height = 0
Apr  7 11:26:24 ubuntu-phablet kernel: [   31.425073][wwy]lcm_parms->physical_width = 0
Apr  7 11:26:24 ubuntu-phablet watchdog: 'biometryd' (instance '') hit respawn limit - rebooting
```

The fact that the second boot is ok is due to upstart that recorded a previous failure of that service and ignore it

**Comment by gbdomubpkm** [comment] 2023-04-12 14:06
I confirm that mainly, the problem is the cold boot on the BQ (OTA-25 or last RC) which cannot remain with this boot problem. Unimaginable !

**Comment by lduboeuf** [comment] 2023-04-13 22:51
good news, we've found the root cause. A fix is in progress. A RC will come soon

**Comment by gbdomubpkm** [comment] 2023-04-14 07:21
THANKS. Interesting to understand in simple terms what the nature of the problem is and which smartphones are more or less affected outside BQ.

**Comment by dtarrant2019** [comment] 2023-04-14 09:48
Great news Lionel. Thank you so much for all your efforts, great work!

**Comment by lduboeuf** [comment] 2023-04-14 12:09
> THANKS. Interesting to understand in simple terms what the nature of the problem is and which smartphones are more or less affected outside BQ.

The issue was due to a service (biometryd) that was not properly shipped to UT image and failed to start. 
The system is trying the first time ( cold boot ) to indefinitly start it and when fails try to reboot the device ( and fail for another reason) making the UI black-ish.
The next boot, the system know that this service have issue and decide to start UT regardless.

For the phone that have issues. I think pretty much all of current devices...

**Comment by gbdomubpkm** [comment] 2023-04-14 12:37
@lduboeuf The issue is not solved for the Volla. Since the last RC of this morning, the Volla, that worked before this update in RC, doesn't boot now. Blocked on the Volla Logo and doesn't boot !!! https://forums.ubports.com/topic/8858/ota-25-hotfix/7

**Comment by lduboeuf** [comment] 2023-04-14 12:39
@gbdomubpkm yes it is known issue sorry, RC get built too early. Another one will come today. Meanwhile you can switch to devel or stable.

**Comment by gbdomubpkm** [comment] 2023-04-14 12:53
@lduboeuf Yes, bad surprise because i'm at work without phone. I must stay in RC, so please tell me when the next RC will be there here or in the forum. Thanks !!

**Comment by lduboeuf** [comment] 2023-04-14 12:54
> @lduboeuf Yes, bad surprise because i'm at work without phone. I must stay in RC, so please tell me when the next RC will be there here or in the forum. Thanks !!

This is a process i don't know as it is sent in batch, but via installer should be straight forward

**Comment by gbdomubpkm** [comment] 2023-04-14 13:12
When can i use the installer to flash the working RC (if you know this) ? In one hour, two hours... more ? Thanks

**Comment by lduboeuf** [comment] 2023-04-14 13:14
> When can i use the installer to flash the working RC (if you know this) ? In one hour, two hours... more ? Thanks

Just now. Image is already here ( via the installer at least )

**Comment by gbdomubpkm** [comment] 2023-04-14 15:15
The Volla has booted well. Everything seems ok, at least for the Volla. THANKS

**Comment by dtarrant2019** [comment] 2023-04-14 17:50
BQ M10 tablet: Checked for updates and installed latest. Tablet now boots smoothly as it should. I'm very happy. Many thanks lduboeuf and all others that made this fix possible.

**Comment by FlavioMala** [comment] 2023-04-14 18:33
[BQ E5]
Today I downloaded Dev 987 (previous 985, see my previous post).

In the automatic restart after the upgrade the phone made two loops (by itself; no on/off button pressed).

With Reboot (done 2 tests) it starts normally.

Turning OFF and then ON, the same.

For me the problem is over.
Thank you!

**Comment by dtarrant2019** [comment] 2023-04-14 19:34
Bonus: Latest upgrade has also fixed boot problem on my trusty Nexus-4.
What a great day! What a great Community!

**Closed as completed** 2023-04-15 21:18 UTC
Labels: bug
