### ISSUE TITLE
[Nexus 7 flo] Screen turns on on it's own on standy

### ISSUE THREAD

**Issue by SaulNunez** [ubports/ubuntu-touch#1146] opened 2019-05-22 17:42 UTC
- Device: Nexus 7 2013 Wifi
- Channel: Ubuntu 16.04 LTS
- Build: OTA-9

### Steps to reproduce
Put the device on standby.

### Expected behavior
That the screen stays turned off.

### Actual behavior
The device looks like it comes out of standby. The screen turns on for a while on the lock screen then goes to sleep again.

### Logfiles and additional information
(Appended files, sorry for the zip)

[flo_logs.zip](https://github.com/ubports/ubuntu-touch/files/3208614/flo_logs.zip)

**Comment by Arc676** [comment] 2019-05-22 18:16
Duplicate of #291 (to be reopened if this is confirmed).

**Comment by SaulNunez** [comment] 2019-05-22 21:56
[repowerd.log](https://github.com/ubports/ubuntu-touch/files/3209444/repowerd.log)
I've peeked a bit on your posted issue and about the utility of `repowerd.log` for debugging this, hope this one can shred some additional light around the issue. They talked about probably calendar sync being the cause, but I with limited testing I couldn't correlate, I added Google as a account in system in the morning (when I reported this issue) and about an hour ago deleted it, and it had the same symptoms, rebooted and until right now it still turns on occasionally.

**Comment by Fuseteam** [comment] 2019-05-24 15:21
do you have notifications on?
if yes are "notifications bubbles" enabled?

**Comment by ziggutas** [comment] 2019-06-01 11:48
My Nexus 7 (flo) OTA-9 stable has had this issue for quite some time. Turning on flight mode when not in use as suggested in https://github.com/ubports/ubuntu-touch/issues/291 is a good workaround. 
I have sound, bubbles and notifications list on for 7 apps. Turning off bubbles for all apps makes no difference.

**Comment by SaulNunez** [comment] 2019-06-04 15:46
Same as ziggutas, turned off notification bubbles and still have this issue.

**Comment by Aurnytoraink** [comment] 2019-07-06 13:54
I get the same things, sometimes the screen wake up looking like I receive notification but in fact nothing

**Comment by UniversalSuperBox** [comment] 2019-08-01 19:41
Alright, this seems to be a duplicate of #291. I'll reopen that one, please take any discussion there.

**Closed by UniversalSuperBox** 2019-08-01 19:41 UTC
