### ISSUE TITLE
[xenial] Video play links between apps not not connecting

### ISSUE THREAD

**Issue by lionelb123** [ubports/ubuntu-touch#614] opened 2018-05-20 10:49 UTC
### Illustrations

- Device: BQ M10 FHD
- Channel: Devel
- Build: Xenial revision 78

### Steps to reproduce
A valid video [created on the device] opens when selected in FileManager, choosing MediaPlayer to play it. When examined in the Gallery app, it shows as a generic image icon, not as a movie. It cannot be opened. When MediaPlayer app is pointed at the file in Gallery app, again nothing happens. The file does not play.

### Expected behavior
It should be possible to open and play a playable movie file, whether selected from FileManager or Gallery or via MediaPlayer.

### Actual behavior
When seen directly within Gallery app, the movie file is not identified as such. When the list in Gallery app is the source for MediaPlayer, movie files are not seen.

**Comment by Flohack74** [comment] 2018-05-20 17:26
Sir, this bug report contains no useful information that is essential in helping to resolve an issue.

**Comment by hoh61** [comment] 2018-05-24 18:35
hello lionelb,
you are a lucky guy. You got a thumbnail from your video. Even this is not working for me (see issue 578). Actually running r86 of 16.04 on frieza.
With my freshly activated camera I did a short video, which can be seen in the gallery app as a black box (no thumbnail). Starting this movie results in an error message (format not known).

The movie can be played using the video app, but once again without thumbnail preview.
So the problem of playing the video is confirmed, although I suggest that this will have two different reasons.

**Comment by lionelb123** [comment] 2018-05-25 08:48
I do not get a thumbnail. It is a generic placeholder, monochrome mountain and sun, not a frame from the video.

**Comment by hoh61** [comment] 2018-05-25 18:30
So this is a confirmation for my issue #578.

**Comment by mariogrip** [comment] 2018-06-16 01:34
Since we have have updated alot of the apps to click, can you test this again?

**Comment by hoh61** [comment] 2018-06-16 07:07
@mariogrip : I updated to r97 and tested the mediaplayer and gallery:

- thumbnail generation fails.
- starting mediaplayer is ok, the selection screen for a video source is shown.
- selecting the gallery is giving an overview of black thunmbnails.
- selecting a thumbnail is freezing the app.

That's a little bit provocating since the mediaplayer now is copying hundrets of megabytes from the SD card to an internal file. This is bloody nonsens and makes the app unhandy for video playing. 
Because of this I am too impatient to test this feature for all my different video formats. It worked for a FLV file.

**Comment by lionelb123** [comment] 2018-06-16 09:53
On Frieza, my gallery app had disappeared on r97 so I reinstalled. Movie made on the device has the same problem as before. Mountain/sun placeholder instead of thumbnail. Error when I try to open it

**Comment by hoh61** [comment] 2018-06-16 11:30
@lionelb123 : please take care on the topic: the link between the different apps seems to work. In this case the gallery app only works as selector. The video playing directly from the gallery app is still not working for me too. This may become a separate issue.

**Comment by hoh61** [comment] 2018-06-20 07:28
@lionelb123 
Please check the behaviour after the yesterday system update . Unfortunately I had to re-flash my device to get this system running, but after that it is nearly perfect. Specially your failure is solved on my device. 
But have in mind: when using the gallery as mediaplayer source, the mediaplayer is copying (!!!!!!!!) the video to a local storage (SD card is not recofniseede as local storage!) before playing. This may cause some long delay for starting depending of the sice of the video file. Fortunately a pop-up window appears after a while indicating the transfer of the file. For me this is a major drawback for the mediaplayer.

**Comment by mariogrip** [comment] 2018-06-22 00:10
This seems to be fixed, closing for QA. Please open if you still have this issue.

**Closed by mariogrip** 2018-06-22 00:10 UTC
Labels: needs confirmation

**Comment by hoh61** [comment] 2018-06-22 05:18
I can confirm the closure.
