### ISSUE TITLE
Desktop applications in Libertine-conteiner is unuseable (popup menu problem)

### ISSUE THREAD

**Issue by Abrekkos** [ubports/ubuntu-touch#1093] opened 2019-04-11 12:31 UTC
Desktop applications in Libertine-conteiner is unuseable.
Popup menus is open in separate modal window. 
Sometimes this modal window is hidden. So application absolutelly blocked.
**As result Ubuntu-touh is mostly unuseful.**

Build: 
- Device: BQ M10 FHD
- Channel: Default for   ubports-installer.0.2.2-beta.exe
- Build: 16.04/stable

### Steps to reproduce
1. Install 16.04/stable (with wipe storage)
2. Install Libertine-conteiner (in Libertine manager)
3. Install Libreoffice (for example) or GIMP  (for example)

### Expected behavior
Solving problem

### Actual behavior
UBport is dropped

**Comment by Abrekkos** [comment] 2019-04-12 19:19
I found work-around in UBPorts forum that reverts from the always-open-a-new-window behaviour to the old everything-in-one-single-windows.  This way, menus in libertine kinda work again.  Open /usr/bin/libertine-xmir in an editor and change

sudo nano mount -o remount, rw /

exec Xmir -rootless $@
   to
exec Xmir -rootless -flatten $@
This is the command with which libertine launches the Xmir instance. The -flatten parameter "Flatten(s) rootless X windows into a single surface" (from the Xmir --help). 
Note that the root partition must be writable, otherwise you can't edit the file.

Make root partition writable:    mount -o remount, rw /

**Comment by TartanSpartan** [comment] 2019-04-16 13:54
This is related/a duplicate of my issue #1029 . Please @Abrekkos comment on mine to say that the issue is confirmed for you and that will help speed up the response time from Ubports to fix it.

**Comment by UniversalSuperBox** [comment] 2019-08-01 19:02
Yes, this appears to be a duplicate of https://github.com/ubports/ubuntu-touch/issues/1029. If I'm reading that wrong, please let me know so I can reopen.

**Closed by UniversalSuperBox** 2019-08-01 19:02 UTC
