### ISSUE TITLE
Random crashes in multiple components due to ABI breakage

### ISSUE THREAD

**Issue by fredldotme** [ubports/ubuntu-touch#1928] opened 2022-01-25 13:39 UTC
- Device: sargo
- Channel: devel
- Build: 2022-01-25/2

### Steps to reproduce

Various apps (Notes, Clock) and system components crash during or right after startup

### Expected behavior

No it crash

### Actual behavior

It crash

### Logfiles and additional information

```
/usr/lib/qt5/bin/qmlscene: relocation error: /usr/lib/aarch64-linux-gnu/libUbuntuToolkit.so.5: symbol _ZN11QtOrganizer17QOrganizerManager11collectionsEv, version Qt_5 not defined in file libQt5Organizer.so.5 with link time reference
```

**Comment by josevidalrt** [comment] 2022-01-26 18:57
I don't know if it's due to ABI but since I updated today, the clock application (sending log), the Morph browser and all webapps crashes.
Device: BQ E4.5
Channel: rc
Build: 2022-W04

[application-click-com.ubuntu.clock_clock_3.12.5.log](https://github.com/ubports/ubuntu-touch/files/7944440/application-click-com.ubuntu.clock_clock_3.12.5.log)

**Comment by Flohack74** [comment] 2022-01-26 19:42
Yeah sorry we tagged this issue in a wrong way and it slipped into RC...

**Comment by mardy** [comment] 2022-01-27 21:06
This MR fixes the API on the client side: https://gitlab.com/ubports/core/packaging/qtpim/-/merge_requests/5

There are still crashes though, and I believe they are caused by the internal changes in QtPim, that affect the contacts (maybe; it seems to me that contacts are working) and organizer (a.k.a. calendar): since these plugins are indirectly being loaded by applications, if they crash they bring down the whole app. The solution here is to recompile them (and fix any errors that we might find during compilation):

- Contacts: https://gitlab.com/ubports/core/address-book-service/-/merge_requests/3 (already merged, required just a rebuild with no changes)
- Organizer: https://github.com/ubports/qtorganizer5-eds/pull/14

**Comment by jjmax25** [comment] 2022-01-29 10:25
Hello,
APP "Note" crash at launch.
Pixel 3a 
Candidate
Version 46
Thanks!

**Comment by josevidalrt** [comment] 2022-02-01 21:16
thanks, after today's update Morph and Clock work in the RC channel
Device: BQ E4.5 krillin
Channel: RC
Build: 2022-W05

**Closed** 2022-02-03 20:18 UTC
Labels: critical (rc)
