### ISSUE TITLE
sim pin dialog is often skipped on reboot

### ISSUE THREAD

**Issue by Danfro** [ubports/ubuntu-touch#1303] opened 2019-11-24 08:31 UTC
device E5
channel dev (edge was the same)

**steps to reproduce:**
- reboot phone

**expected behaviour:**
- sim pin dialog is show so sim card(s) can be unlocked

**actual behaviour:**
- sim pin dialog appears for a split second, then dissapears
- the lock screen is shown
- after login sim cards are still locked, they can not be unlocked via the indicator

**occurence:**
randomly, on average on every second reboot
after some updates it does (almost) not happen at all
on other days it needs up to 5 reboots until the sim pin dialog allows input

After installing the [fix](https://forums.ubports.com/topic/3385/call-for-testing-a-new-way-to-ignore-your-problems/) for #1277 it seems to be better. I does still skip the sim pin dialog, but I never needed more than a second attempt to be prompted for the sim pin dialog.

According to Daltons answer on my post in the [forum](https://forums.ubports.com/topic/3385/call-for-testing-a-new-way-to-ignore-your-problems/) this issue is NOT the same as #1277 .

**Comment by UniversalSuperBox** [comment] 2019-11-30 01:42
Hi @Danfro,
This appears to be a duplicate of https://github.com/ubports/ubuntu-touch/issues/1271

**Closed by UniversalSuperBox** 2019-11-30 01:42 UTC

**Comment by Danfro** [comment] 2019-11-30 05:15
Oh, I obviously missed that issue. Sorry.
