### ISSUE TITLE
Could not add nextcloud account - invalid url

### ISSUE THREAD

**Issue by FloVanGH** [ubports/ubuntu-touch#468] opened 2018-02-06 11:18 UTC
Hi, 

I could not add my nextcloud account to the system settings. Every time it shows the message: "Invalid url".

- Device: hammerhad
- Channel: 15.04/stable
- Build: OTA3

### Steps to reproduce
* Go to system settings accounts
* Add account
* Click on nextcloud
* Fill the form

### Expected behavior
* Could successful add nextcloud account

### Actual behavior
* Message: Invalid url

**Comment by 3arn0wl** [comment] 2018-02-15 17:46
I have the same issue. Same harware. Same OTA

**Comment by jonnius** [comment] 2018-02-22 17:42
I just tried to reproduce, but it works as expected for me. 

The message `invalid host url` is a bit misleading though, as you get that if you enter username or password incorrectly. Furthermore make sure, your url is correct (don't forget the `/nextcloud` at the end).

**Comment by jonnius** [comment] 2018-03-03 12:36
@FloVanGH and @3arn0wl, do you both use own nextcloud servers with self signed certificates?

**Comment by FloVanGH** [comment] 2018-03-03 14:47
@jonnius I use a let‘s encrypt certificate. I also tried all possibilities of th url but I still doesn’t work.

**Comment by 3arn0wl** [comment] 2018-03-03 15:43
I haven't got it working yet either. 

There's Syncthing though, which is a partial solution...

On Saturday, 3 March 2018 06:36:19 CST, jonnius <notifications@github.com> 
wrote:
> @FloVanGH and @3arn0wl, do you both use own nextcloud servers 
> with self signed certificates?
> 



-- 
Sent using Dekko from my Ubuntu device

**Comment by jonnius** [comment] 2018-03-04 10:01
Maybe we can cross check. You could let me try to connect to your nextcloud or you to mine. If you are cool with that, text me on telegram (@jonny) or via mail (jonatan_zeidler@gmx.de).

**Comment by 3arn0wl** [comment] 2018-03-05 15:26
I've given up on it for the moment! There seems to be an issue at both 
ends:

I can't get the phone to accept the URL. I've seen that others have this 
problem toilet, so I guess it's a bug. And

I downloaded the snap version for my laptop. It was really easy to get it 
going initially, but apparently there are problems getting other devices 
communicating with it. :/

(I'm not a techie - but it would have been nice if NextCloud worked. )

On Sunday, 4 March 2018 04:01:50 CST, jonnius <notifications@github.com> 
wrote:
> Maybe we can cross check. You could let me try to connect to 
> your nextcloud or you to mine. If you are cool with that, text 
> me on telegram (@jonny) or via mail (jonatan_zeidler@gmx.de).
> 



-- 
Sent using Dekko from my Ubuntu device

**Comment by Amolith** [comment] 2018-03-12 02:26
I'm having this same issue; same device, channel, but my build is r3. I'm using NextCloudPi, it's encrypted using Let'sEncrypt, and the domain is through No-IP.

**Comment by jonnius** [comment] 2018-03-13 12:38
I successfully connected to Amoliths nextcloud with my fp2. So it really seems to be a bug in hammerhad @Flohack74.

**Comment by Amolith** [comment] 2018-03-13 18:44
@Flohack74 I fixed it on my device; I don't know if this will work for everyone. Previously, I used a 50 character password with special characters and pasted it into UT. After many attempts, I have discovered that it was simply the special characters. I tried one password that had an `@` symbol then tried the same password with `a` instead of `@` and I was able to log in. I hope this helps!

**Comment by Flohack74** [comment] 2018-03-14 08:09
I cannot believe that the password field has restrictions :) But ok everyone please try this!

**Comment by UniversalSuperBox** [comment] 2018-03-17 16:36
I can confirm this on hammerhead, 15.04 rc-24. Passwords with special characters always return the 'Invalid url" error.

**Comment by Flohack74** [comment] 2018-03-17 17:39
@mardy can you please have a look where this could come from?

**Comment by ruedigerkupper** [comment] 2018-04-04 12:25
possibly a duplicate of #468?

**Comment by jonnius** [comment] 2018-04-04 13:52
@ruedigerkupper, it is related but not a duplicate. This is about the login failing because of special characters in password, while the other one is about missleading error messages in all cases of a failed login.

**Comment by Flohack74** [comment] 2018-09-08 14:10
resolved by https://github.com/ubports/account-plugins/pull/16

**Closed by Flohack74** 2018-09-08 14:10 UTC
Labels: bug
