### ISSUE TITLE
Start up log in 

### ISSUE THREAD

**Issue by prpldvl67** [ubports/ubuntu-touch#286] opened 2017-10-05 15:45 UTC
- Device: Nexus 5
- Channel: RC[r7]  and [Stable]

![wp_20171005_07_32_20_pro](https://user-images.githubusercontent.com/29064258/31236517-2fdaac9c-a9ec-11e7-978b-2bc1e227be1e.jpg)
- Build:

## Expected behavoir
At startup the screen is not recognising number and in order to log in I must cancel the log in screen and restart or shutdown several times. I have added a photo the screen is wonky. Once logged in thought the device rocks. 

## Actual behavior

...

## Logfiles and additional information

...

**Comment by Flohack74** [comment] 2017-10-05 16:11
The shifted screen is a known bug, but for me it is enough to turn the screen off and on again. Die you try this?

**Comment by prpldvl67** [comment] 2017-10-05 17:16
Hi Florian, yes it works in that way.  Besides that the OS is awsome

**Comment by Flohack74** [comment] 2017-10-05 17:18
Ok then its probably a duplicate of #65 :)

**Closed** 2017-10-06 18:09 UTC
Labels: duplicate

**Comment by NeoTheThird** [comment] 2017-10-06 18:15
It's actually #27, btw ;)

**Comment by Flohack74** [comment] 2017-10-06 18:22
yes sorry ;)
