### ISSUE TITLE
Downloaded OTA Ubuntu Touch update disappear when offline

### ISSUE THREAD

**Issue by Pat-la-Patate** [ubports/ubuntu-touch#1584] opened 2020-10-15 17:50 UTC
### Illustrations

- Device: PinePhone, BQ e4.5
- Channel: Development
- Build: 246
(-auto download on WiFi)

### Steps to reproduce

Download the OTA Ubuntu Touch update
Turn off WiFi (considering WiFi is the only network link)
*see update option disappear* 
Turn on WiFi
When the network is back and after searching for update, it seems the Ubuntu Touch update is once more downloaded and made available. 

### Expected behavior

Update remain available for offline installation.

### Actual behavior

Update option disappear and seems to be deleted.

**Comment by UniversalSuperBox** [comment] 2020-10-15 18:27
Hello @Pat-la-Patate, thanks for your report!

I believe this report is a duplicate of https://github.com/ubports/ubuntu-touch/issues/1584. To keep our issue trackers easier to follow, I will close this report in favor of that one.

**Closed by UniversalSuperBox** 2020-10-15 18:27 UTC

**Comment by Pat-la-Patate** [comment] 2020-10-15 18:38
Hello @UniversalSuperBox, 
Oups, sorry if it a duplicate, I did not see it. Are you sure that is it not linked to another issue # (recursive issue here ;))?
Keep up the good work :)

**Comment by UniversalSuperBox** [comment] 2020-10-15 21:09
Grr. Sometimes my clipboard gets "frozen" between Firefox and elsewhere on my desktop. When it happens, I'll have one URL in the clipboard basically until I reboot.

The correct link is https://github.com/ubports/system-settings/issues/98
