### ISSUE TITLE
web based text input fields + windowed mode = backspace problem in OSK

### ISSUE THREAD

**Issue by YougoCodes** [ubports/ubuntu-touch#1176] opened 2019-07-06 18:57 UTC
### Illustrations

- Device: bq M10
- Channel: stable
- Build: ota9

### Steps to reproduce

Using the OSK to type in a web based input field invokes backspace problem, also possibly capitalisation problem while typing.

### Expected behavior

when typing, and opting to correct the last typed word, pressing backspace should erase one character on each press, but leave the rest of the typed sentence intact. this should work consistently across native apps and web based apps/sites. also behavior should not be affected by use in windowed or staged mode

### Actual behavior

this occurs in a specific setup: while in windowed mode, while using OSK to type in a web based input field. 
1) when typing two or more words separated by spaces, and then pressing backspace, causes the space before the last word to disappear. when continuing to press backspace until the last word is erased, the same happens to the next word, and again, and again

"string of words" --> "string ofwords" --> "string ofw" --> "stringof"

2) when typing a word followed by a space, followed by an interpuction, the interpunction is placed after the word, rather than after the space. i suppose it is meant as a correction, but when it is intended like "a number of .pdf docs..." it is cumbersome.
furthermore, when pressing backspace to correct this, the interpunction is removed, and the last word is repeated, overlapping itself save for the first letter:

"foo ." --> "foo." --> [backspace] --> "ffoo"

### Logfiles and additional information

possibly related to #1038 but imho more specific.
willing to submit logs, follow instructions, install and test things, not afraid of terminal, but no idea where to start.

**Comment by kugiigi** [comment] 2019-07-06 20:16
I think this is really caused by the auto-correction, auto-suggestions, etc. My technical guess is that it is the same cause as in #1157 in which some properties of the editor/input method are not properly updated in QTWebEngine and thus messing up the logic of these features.

**Comment by UniversalSuperBox** [comment] 2019-07-10 02:53
Similarly, I'm unsure this is directly caused by being in windowed mode. I've seen this issue in staged WebTelegram, for example.

**Comment by UniversalSuperBox** [comment] 2019-07-17 15:40
Shall we call this a duplicate of #1157, @kugiigi?

**Comment by kugiigi** [comment] 2019-07-17 17:13
I would say yes. The logic for autocorrect, suggestions, etc. most  likely uses some properties of input method that do not worl correct in QtWebEngine at the moment.

**Comment by UniversalSuperBox** [comment] 2019-07-17 17:13
Sounds good.

Closing as a duplicate of #1157. Please continue any discussion there.

**Closed by UniversalSuperBox** 2019-07-17 17:13 UTC
