### ISSUE TITLE
No OTA-3 for Nexus 7

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#378] opened 2017-12-22 12:14 UTC
- Device: Nexus 7 flo
- Channel: Stable
- Build: 15.04 (r1) armhf 20170923

### Steps to reproduce

Opening the "updates" section in settings

### Expected behavior

Tells me there's an update available (OTA-3 is out! Woooo!)

### Actual behavior

Settings tells me that my software is up to date.

Originally reported by @Arc676 in #375

**Comment by andybleaden** [comment] 2017-12-24 13:11
Just checked in the repos here:

http://system-image.ubports.com/ubports-touch/15.04/stable/flo/

and there is no update to version 3 OTA as not being given an update I assume
![screenshot from 2017-12-24 13-08-13](https://user-images.githubusercontent.com/34811990/34326728-d36effa4-e8ab-11e7-947a-d8539fe79363.png)

So there must be something telling all devices that there is OTA3? even when for some there is none?

**Comment by Flohack74** [comment] 2017-12-24 23:15
Ok interesting this will actually be OTA-2 for N7 as we did not build it before xD unless we bump version number. But still its missing... I take a look with @mariogrip

**Comment by Flohack74** [comment] 2017-12-24 23:17
Hmm the case gets hot, there is also no daily build job for them? See http://ci.ubports.com/blue/pipelines/?search=daily

**Comment by Arc676** [comment] 2017-12-25 11:07
Hm. It’s worth noting that the Nexus 7 is listed as a legacy device. Maybe the builds aren’t prioritized? If it’s not in the daily builds, maybe it’s just that not a lot of people are using it?

**Comment by NeoTheThird** [comment] 2017-12-26 10:51
We just missed setting automation up for these devices after we added support for them in OTA-2. Sorry this was not fixed before Christmas, release will come any day now as the infra team wakes up from holiday-hibernation. ;)

**Comment by Arc676** [comment] 2017-12-26 11:31
Ah, OK. That makes sense. No problem, I can wait for the update. I’ll update this thread once the update appears. Thanks for the info.

**Closed** 2017-12-27 21:05 UTC
Labels: bug, device: deb, device: flo, device: manta, team: infrastructure

**Comment by Flohack74** [comment] 2017-12-27 21:07
@mariogrip Jan also added manta, and what about deb :)

**Comment by rubencarneiro** [comment] 2017-12-27 22:12
I can confirm no ota-3

**Comment by Arc676** [comment] 2017-12-28 02:51
Just checked on my Nexus 7: there *is* an update available, but it says "version 2." I'm guessing this is because "version 1" is OTA-2, which was the first version to support this device? Presumably "version 2" corresponds to OTA-3, right?
![screenshot20171228_104803518](https://user-images.githubusercontent.com/30745465/34398837-1165f2c2-ebbd-11e7-8b99-853490712508.png)

**Comment by mariogrip** [comment] 2017-12-28 02:53
Yes, the OTA and version numbers does not match. version is per device, OTA is global for all devices

**Comment by Arc676** [comment] 2017-12-28 03:00
Successfully updated to `r2`/OTA-3! Thanks for the quick response!

**Comment by Flohack74** [comment] 2017-12-28 13:45
@mariogrip we might want to bump the version to avoid these questions ;)
