### ISSUE TITLE
time of day not entirely visible / cut off by display on Volla Phone

### ISSUE THREAD

**Issue by Smirftsch** [ubports/ubuntu-touch#1920] opened 2022-01-17 16:12 UTC
Device: Volla Phone
OS: Ubuntu 16.04 (2022-W02), also tried on stable version.

This is a rather minor thing but perhaps easily solved. 
When the phone is unlocked the time of day is not entirely visible, so f.e. if the time is 10:00 the first 0 is cut off in the upper right corner already and the second 0 is barely visible at all, only a few pixel from the bottom of the 0 can be seen, the rest is behind the display's corner. Shifting the time a little to the left will probably solve that entirely.

**Comment by Flohack74** [comment] 2022-01-18 14:03
Well thats a generic problem mit modern phone hardware: We need to be able to define "keepout areas" for the important UI parts. Since that is deeply buried in the display code its a superhard thing to do. However progress was made by @mymike00 already, see
* https://github.com/ubports/unity8/pull/403
* https://github.com/ubports/ubuntu-touch/issues/523
* https://github.com/ubports/ubuntu-touch/issues/1820

BTW a more detailed issue search should have yielded you the already existing items, so I close this as duplicate ;)

**Comment by Flohack74** [comment] 2022-01-18 14:04
Duplicate of: https://github.com/ubports/ubuntu-touch/issues/1820

**Closed by Flohack74** 2022-01-18 14:03 UTC

**Comment by Smirftsch** [comment] 2022-01-19 06:45
I did, but always easy if you know what you are looking for- "notch" is nothing I would have seen any relation to this issue...
Thanks nevertheless :)
