### ISSUE TITLE
Integrate OpenStore into system-settings

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-touch#184] opened 2017-07-27 15:40 UTC
Now this only supports ubuntu-click store, but since that's deprecated, we can replace this with OpenStore

**Comment by ChloeWolfieGirl** [comment] 2017-07-27 17:19
This for updating apps via updates in system settings, something else or more?

**Comment by mariogrip** [comment] 2017-07-27 17:27
Jep, via system-settings

**Comment by mariogrip** [comment] 2017-07-27 17:28
or remove it from system-settings and let openstore handle it like google play do on android

**Comment by ChloeWolfieGirl** [comment] 2017-07-27 22:45
I think updating via system settings is a better option, expecially since then if people dont have auto downlaoad on, theyll see which apps have updates that they might want to update.

**Comment by NeoTheThird** [comment] 2017-07-27 23:19
[Why don't we have both](http://gph.is/1G3WGvv)?

**Comment by sverzegnassi** [comment] 2017-09-15 15:50
Since UBports has planned to provide support for pull notifications, OpenStore could gain the ability to check for updates in background, and show a notification when some is available. Also, our current effort for version 2.0 is to make easier to discover available updates, and we are no longer restricted by the capabilities of Unity 8 scopes. That means we will be able to properly manage updates by our own.

Also - in my opinion - Integrating a portion of an app store in a system component seems a bad practise.
If we will ever need to update the OpenStore APIs, we would need to update system-settings accordingly, and push a new OTA since the app is shipped as a Debian package.
Or, if Ubuntu Touch will ever adopt Ubuntu Snappy, system-settings app would need to be rewritten.

In order to keep the transition between Ubuntu Store and OpenStore linear and easy, I would suggest to completely remove the Ubuntu Store features from system-settings. The 'Updates' section should only handled system images from UBports servers.

**Comment by NeoTheThird** [comment] 2017-09-15 16:35
@sverzegnassi You have a point. To help the users change their habit (i've seen Ubuntu Touch users who have never ever opened the openstore to update their apps, because nobody told them to do so), we should add a notice that application updates are handled by the OpenStore, and maybe a link to the OpenStore updates section.

**Comment by sverzegnassi** [comment] 2017-09-15 16:59
After your reply, I just checked on the 'My Apps' page of the Ubuntu Store. Actually, people still use the Ubuntu Store for getting apps that are also available on OpenStore, which means we should make it clear that Ubuntu Store will be dismissed by the end of the year.

We probably need to add a further tile next to the orange 'Ubuntu Store' one, so that people can see there are two different stores installed. Furthermore, I would add a notice directly in the main page of the click-scope, below the two tiles. I really doubt people would miss such information.
I also suspect that the old version of OpenStore (the one with the huge list of apps) - provided by earlier OTAs - makes even harder to update an app, so shipping the latest version of OpenStore would be something important.

After the removal of Ubuntu Store, I think that enabling OpenStore notifications by default (once supported), or only keeping the 'OpenStore' tile in the click-store would be effective enough for making people changing their habit.

From the OpenStore side, we should implement auto-updates of the client app, which is something we currently miss.

**Comment by NeoTheThird** [comment] 2017-09-15 20:37
@sverzegnassi There already is a notice on the click store tile stating it's unsupported, as well as in the separator text above: https://github.com/ubports/unity-scope-click/blob/2b8818cd193b631b1aaaf156db07fe0457cf7abd/scope/clickapps/apps-query.cpp#L271 I added it a while back, but unfortunately the separator does not support line breaks (i did not want to deal with code that will be removed soon, so i didn't look into it), so the message is a little telegraphese...

I think it's not a good idea to also add the OpenStore as a tile, because the tiles don't really fit the whole design of the system anymore, since not even the other scopes use it. If the OpenStore is in fact made into a tile, i'd strongly recommend to revert it back to a normal app after the Ubuntu Store is removed (which will happen before the end of the year), so i'm not really sure if it's worth the time and effort...

I could also imagine that the people who are still installing from the Ubuntu Store are users of the canonical UT version, but i'm not sure... In any case, we need to do some more outreaching.

**Comment by ChloeWolfieGirl** [comment] 2017-09-16 01:42
Open store isnt a scope so it doesnt make sense to be a tile.

I miss app updates being is system settings

**Comment by NeoTheThird** [comment] 2017-09-16 10:35
> I miss app updates being is system settings

But @sverzegnassi makes a compelling case for not doing it that way. Using the API in deb packages would take away a lot of flexibility, so it makes sense to only provide it in the openstore click package. Once the OpenStore has notifications, it's going to be much easier to spot available updates anyways.

**Comment by ChloeWolfieGirl** [comment] 2017-09-17 10:04
@NeoTheThird I do agree with that, I think perhaps now it's best to keep it in the store, but I think in the future it might be a good idea to bring it back to the system settings, especially in a plug-in way.

This would mean that a user could have several stores, and have a single place to update there apps, in android you can have multiple stores, apk pure, f-droid, google play store, etc, etc, In android you'd have to go to every store to update your apps, (unless you have auto update in google play but still) so having a one stop shop would be a nice feature.

I think we have more of a reason to have multiple stores as well, KDE is making a phone, people might prefer there store which might become available on ubuntu, and we might have different stores for different package formats, this might not be a problem, but it's good to be open to the possibility's, and IDK why, but the ad blocker has its own updater in its app, which IDK why, but it seems to not correlate with open store.

It also makes everything seem/feel more integrated, and less all over the place.

So if there's a way to make system settings updates a plug-in feature that any app can plug itself into, then I think its something we should look into.

**Comment by mardy** [comment] 2017-09-18 14:15
I also wouldn't like to see the app updates disappear from the SystemSettings. @sverzegnassi has a valid point but, as @ChloeWolfieGirl writes, even if we had to take the update logic away from the System Settings, that doesn't mean that the UI should also go. If the OpenStore could provide a command-line execution mode, the System Settings could run it, parse its output, and update the UI accordingly.

However, I'm not convinced about the need for this. The OpenStore could provide new APIs on new endpoints, leaving the existing ones working at least for some time. Forever, ideally :-)

**Comment by mardy** [comment] 2017-11-03 21:25
I got the OpenStore working in the system settings :-)
Give me a few days to clean up the code, and I'll submit it.

![screenshot20171103_221928673](https://user-images.githubusercontent.com/59287/32396467-670c828c-c0f6-11e7-8757-d20c0688b7b3.png)

**Comment by Flohack74** [comment] 2017-11-03 22:16
Great!

**Comment by bhdouglass** [comment] 2017-11-05 14:34
I still think Stefano's points are valid. Especially in light of our change from using version's to using revisions. We made the switch in the app, and we were able to easily ship the update and any following patches quickly. Just because this is what Canonical did when their store was a scope doesn't mean UBports/OpenStore has to do the same thing. I believe the proper solution here is to get notifications working for the OpenStore (whether that is push notifications or just a daemon).

**Comment by ChloeWolfieGirl** [comment] 2017-11-05 16:25
I think the centralised updates is very good for a user.
Currently on android, you have multiple stores depending what vender you get your phone from, or what type of person you are.
If you have a samsung phone, you have the play store and the samsung store, then system updates, making 3 seperate places for updates.

If you're like me, you have system updates, f-droid, and apkpure.
These leave you with 3 different places, 3 different apps you have to check to see if you have updates.

I dont think notifications helps this much, of cause it means you dont have to check the app without a prompt, but it does mean that you can have 3 notifications, 1 telling you that theres a new ubuntu update, 1 telling you theres a new version of blender, and 1 telling you theres a new version of Dekko.

The user would then have to open the open store, update all, then have to open another app to update blender, and then open the system settings app to update ubuntu.
Where as if we make it so that stores can intergrete with the system settings app, it means that you can go to system settings, tap update, and get all of your updates, get your Ubuntu, Blender, and Dekko from one place.

Android is a great example for why, if users dont have or use automatic updates, why a centralised location is a good idea in my po.

**Comment by sverzegnassi** [comment] 2017-11-05 17:17
Devil's advocate here. :) Currently, app updates do not occour with such high frequency, so it doesn't justify the risk to miss them. Also, in the exact moment Alberto's PR is merged, we would de-facto deprecated the old Ubuntu Store. The outcome is only one app store available.

For these reasons, I can't see how the Android example could fit here. The result wouldn't be merging 3 into 1, but splitting 1 into thirds.

By moving the OpenStore updates outside the OpenStore client app, we would have the following situation:
- One app for updating apps (SystemSettings)
- One app for installing apps (OpenStore client)
- No system tool for uninstalling apps[1].

This is a concrete UX issue that hasn't been addressed in the discussion yet, and it looks very far from the real goal of the PR.

Snap packages are not a valid argument either, since `snapd` currently forces auto-updates in background - right in order to prevent people from not installing them.

#### OS Updates:
- People on `stable`: they would get an OS update every 6-8 weeks. They wouldn't benefit from having a single "Updates" hub
- People on `devel`: app development is not that active, and - in any case - `devel` channel is designed for active contribution. While we don't put any barrier on using this channel, we might still want to prevent people from passively and unconsciously using unstable updates.
In any case, the "Update All" button does not update both apps and OS, but only downloads the OS update, if available.

OS updates can be efficiently handled by showing a notification, so they wouldn't *really* benefit from the unified hub as well.

[1] - The feature is hidden in the Application scope. OpenStore only supports uninstallation of packages coming from the store. The only app that really allows to install packages is UT Tweak Tool (third party).

**Comment by ChloeWolfieGirl** [comment] 2017-11-05 18:09
Its true that we only have one app for installing apps at the moment, but I don't beleive that will be true forever, I'm not even sure if thats true for the foreseeable future, it depends on what and how KDE and purism decide to do with some of there things.

Theres a posibility that KDEstore or PureOS store might become available for ubuntu phone.

I think having the options to have more stores and have them integreted into one place is very clever, OpenStore started before canonical stopped working on there OS, the Ubuntu store was still heavily supported, and I think having one central place is very forward thinking, of cause OpenStore didnt use it at that point, leaving people having 2 places to go when they wanted to get app updates, this is now down to one for apps by itself, 2 if you include OS updates.

Android has many stores.
Android Tapp, Android Freeware, AppBrain, SlideMe, AppsLib, Soc.io, 1Mobile, Nvidia Shield, AndroidPit, mobiles24, Aptoide, Yandex, Appszoom, Mobogenie, AppBackr, F-Droid, MiKandi, Amazon Appstore, GetJar, Opera Mobile Store, Mobango, etc, etc.

My point isn't that people will use them all, but in android where you only really need is 1 and a browser, for any apps that are rejected or pulled for one reason or another, yet somehow there are still hundereds, and its so easy and common for people to have at least 2 stores.

we're not a closed platform, if we become relevent enough, there's no way that we'd be able to only have one app store as an option.


If we only ever have one store, which seems only possible if we stay incredibly small, then I still think theres an advantage of having it intergrated in the system settings, even if you only get system updates once every 6-8 weeks, then you're getting more usage from it, and users are being trained to go there for updates, meaning that people who dont often go to update there system are propted more to update there OS, how many cassual users do you see the notification which tell people to update there OS then a few weeks later they still have the little icon on there bar?

For me I see it often on my brothers and mothers phone.

I think it healthily promotes updating software and OS to help prevent hacking, something which android, no matter how much it trys to promote updating your OS, isn't working to well.

I do agree that a system installer would be benifical, if you have no store on android, its easy to still install an app from the web browser, so I agree that a system wide installer would be benificial.

There have been discussions for a new way of uninstalling apps, with the new app-draw see bug #142


The idea isn't to have one app rule them all, but to have apps and the system talk to each other, of cause you can still update your apps from open store, but if you have 30 apps to update, and only 14 are from the openstore, it'd be so much easier to just go to one place and update all 30 apps at the same time, and then you can find out, oh, I still havent updated my OS, let me install that while I'm updating my apps.

To me it just makes the users life, so much more convinent, my mother uses 3 maybe even 4 app stores on her phone, why go to 4 apps to update your apps, when you can have just one?

https://www.youtube.com/watch?v=YCeQLeQiRP4

**Comment by sverzegnassi** [comment] 2017-11-05 20:27
You were about to buy me, with that video :D

We're still talking about 4,000+ UBports users vs. 2,000,000,000+ Android users (+49,999,900%, for the records). It's hard to really do a comparison between the OS's cases.

- Sadly, at the moment, I doubt it's possible to easily run PureOS and KDE apps running on UT.
There are too many exceptions in the current UT architecture, and everything has been really designed for click apps only (or snap, but support is not finished yet).

- Also - as I previously said - I can see a huge problem with an hard-coded implementation of app updates in a non-upgradable component of the OS.
If we want to be open, we should allow `system-settings` to be pluginable. All the external app stores should have equal access to the "Updates" tab, without depending on UBports and its OTA updates. Otherwise, it's just not open enough[1].

- If we need to provide a change to the user experience of OpenStore, we can not depend on the timing of UBports OTAs. I was about to change the way downgradable apps are handled in the "My Apps" tab of `openstore-app`; that would potentially cause the two different "update managers" to work differently.
Openness should work on both ways.

- "Unified" update manager exists since a decades in GNU/Linux, but they have never been able to promote a culture of upgrading applications. If someone does not update apps from OpenStore, {she|he} likely won't update {her|his} apps in `system-settings` anyway.

If we had 4 or 5 available stores, I would have said this was the way to go. Given that we still have to finish the transition to the new store, we barely have one.

Also, we haven't even discussed yet how to support snaps; there's a chance we might have to return on this decision again, within 3-4 months (it means the changes in the PR might be live just for OTA-3 and OTA-4, if planned).

Do we want a centralized, agnostic way to handle apps?
That's great, but in order to allow us to support your effort, UBports needs (IMO) to provide the full set of features (as a click hook):
- Install/Uninstall apps (i.e. the system installer you mention)
- Apps management (i.e. bug #142)
- Apps updates

That way, we could safely focus on providing store browsing functionalities only. Otherwise, if it has to lead in partial implementations, fragmentation, or code duplication, it is not worth for us to support the effort.

======

[1] Once upon a time, someone said that he would have supported Torrent downloads, as long as the community had been working on `ubuntu-download-manager` upstream.
Another example is how `filemanager-app` (unconfined app) can not reproduce audio because apps currently need to be explicitly whitelisted in `media-hub` (bug report coming soon, btw).

**Comment by mardy** [comment] 2017-11-05 20:50
And here's the code, please review :-)
https://github.com/ubports/system-settings/pull/24

**Comment by mariogrip** [comment] 2017-11-05 21:25
I give a +1 for system-settings

**Comment by ChloeWolfieGirl** [comment] 2017-11-05 22:27
"If we want to be open, we should allow system-settings to be pluginable. All the external app stores should have equal access to the "Updates" tab, without depending on UBports and its OTA updates."

I completely agree, hardcoding would never solve the multiple store issue as we'd have to keep up to date with stores, and that would end up being a big problem.

If system settings gets a good api for store devs to create stores which would make it independent from OTA updates, and a way to install and uninstall apps inside the system, would that clench most of your worries?

**Comment by bhdouglass** [comment] 2017-11-05 22:57
I think the pluggable system settings option seems better than the currently proposed solution. But honestly it seems like we are trying to solve a problem we don't have yet. We only have one store when the Canonical store shuts down. I believe we should be spending developer resources doing problems we actually need solved.

**Comment by mardy** [comment] 2017-11-06 08:01
Let me jump in to bring some facts (well, at least try to :-) ):

 * Yes, I did remove the support for the Ubuntu Store, but that was only my decision (based on the fact that it won't receive more app updates); I could have left it there, too, if I wanted.
 * The System Settings app is totally plugin based. Most of the plugins are sadly part of the same git repo, but they could easily be moved out; Online Accounts is an example of a plugin coded in an external repo.
 * The Update plugin in the System Settings has been almost completely rewritten in 2016, and is now very flexible; it can support different types of updates (system image, clicks, snaps, and what not), one just have to add an engine to it.
 * At the moment, there's only a click and a system image backend. I've changed the click backend to be compatible with the OpenStore.
 * The OpenStore is open source, there could be more instance of it. Now, the one I'm supporting with ubports/system-settings#24 is only `openstore.ubports.com`, but it could be made configurable to support more, if they appear. It could be made as simple as installing a json config file somewhere, or maybe even editable from the UI.

Now, for the opinion parts: let's have both ways. If you feel like, we could play a bit with the User-Agent string in the SystemSettings plugin and OpenStore app, and then collects statistics on the openstore site to see which one is most used to get updates. Though, TBH, I don't see a good reason to kill one or the other one.
Another option could be to have the System Settings plugin only detect the updates, and then launch the OpenStore app to download and install them; though, again, I the code for downloading and installing the updates is so tiny, that I don't see any benefit from removing it from the System Settings.

**Comment by bhdouglass** [comment] 2017-11-06 15:05
For the pluggable system settings to be really useful it would need to allow us to add the plugin from within the OpenStore's click so we can control the update logic and update it easily as needed.

Please use https://open.uappexplorer.com when referencing the OpenStore as it's the official domain of the OpenStore and could get very confusing if we continue to cross pollinate, especially if we ever acquire a good top level domain for the OpenStore. https://open.uappexplorer.com is guaranteed to always work, but if we ever moved our setup it could easily get forgotten openstore.ubports.com until people start complaining.

Having it both ways quickly becomes a nightmare. Not only does it violate the DRY principle it also (currently) has two vastly different methodologies of performing updates (revisions vs versions). If one method gets updated the other one could easily get forgotten about and lead to major user issues (and you really don't want to have to perform the same code changes twice). Plus the release time for an OTA is much slower than one for the OpenStore, we could easily get into a situation where the OpenStore has the update and it's another month before the System Settings catches up. And on top of the technical issues, just think about the user confusion, where do you update your apps? In the OpenStore or in the System Setting? Do those updates in the System Settings actually come from the OpenStore? etc, etc. Additionally users are already use to getting their app updates from the OpenStore, rather than the System Settings anymore.

I believe our best solutions here are to either continue letting the OpenStore do what it's been doing since it's inception (and add a notification to alert user to updates). Or to make the System Settings pluggable in a way that allows the OpenStore click to ship plugin updates.

**Comment by mardy** [comment] 2017-11-06 17:27
OK, I'll change the plugin to use https://open.uappexplorer.com, thanks (I thought that the ubports one was just a redirect?).

As for the rest, I'm afraid it's a fruitless discussion that will lead to nowhere, as I don't see any of us changing his mind anytime soon. :-)
I don't understand your remark about the OTA release time (it's true that it's completely unrelated to the apps release time, but I don't see how it's relevant here: whenever the user sees an update whether an app update or OTA, he can install it), but the main problem here is that we lack a mechanism to take this time of UX decisions: we should try to find a UX designer (not just me or you, but someone with a proven record and a long term plan for Ubports development), or let the community take a decision (either directly with a poll, or indirectly by looking at their behaviour -- the usage stats I mentioned before).

While we don't have a clear guidance, let's keep them both; we can revisit that once we'll get a bunch of angry users yelling at us because there are two ways to accomplish the same action, which I believe won't happen anytime soon. Or, if either of the mechanisms gets unmaintained, then of course we should drop that. But we have them both, so let's use them (at least we've got three people commenting in this bug who are happy with it being in the System Settings).

**Comment by ChloeWolfieGirl** [comment] 2017-11-06 19:43
I think it wouldn't be a great idea to have a notification from system settings that takes you to the open store.

If you have an openstore notification that takes you to open store, then that makes sense, but then if you get a notification from system settings, and it takes you to different apps depending where the app is coming from, I dont think it solves any problem, other then, the user doesn't have to open 7 apps just to check if they have any updates, app, or OS wise, but they'd still have to go to 7 apps to update what ever app has an update.

If you have a system settings notification which redirects you to an app store then it'd go something like this

"Software update available"
User taps it
User gets taken to Openstore, updates app

"Software update available"
User taps it, expects to go to Openstore
User gets taken to KDEstore.

"Software update available"
User taps it, expects to go to a store of some kind
User gets taken to system settings.

Instead of making thing easier, the user just doesn't know where they're going, and that could lead to loads of update notifications, a user having to tap them, and go to several different apps to get there updates.

The main point of having app updates in system settings is so that when a user wants to update there software, they only have to go to one place.

If I want to update my apps, on Ubuntu I can do apt upgrade, and most of my apps are updated, my snaps are automatic, and if I do apt upgrade, my OS and apps are upgrading at the same time, it doesn't matter what ppa they're coming from, it doesn't matter which store, apt upgrade, and you're mostly upto date.

You could also tap the update software icon, which we used to have on ubuntu phone, but then that got merged with system settings, and thats one universal place.

If you have to go "sudo apt upgrade" then "sudo snap refresh" then "sudo -ssyu" or what ever.
Or if you had to open system updater to update your os, then you had to open the ubuntu software centre, then you have to open that tiled version of the app store people liked for a little while.

And you had to open 3 desktop apps to just make sure that your OS, Libreoffice, and blender where up to date, that'd get tedious for people used to Linux, and something which would make switching to linux so much more complicated.

**Comment by bhdouglass** [comment] 2017-11-07 03:42
If you insist on doing both at least listen to us and make sure you are doing the updates correctly.

"I think it wouldn't be a great idea to have a notification from system settings that takes you to the open store." This is not what anyone is advocating. Any notifications about OpenStore updates should come from the OpenStore and not system settings. And the messaging should be better than "software update available", it should be targeted to what's being updated, apps or the system. This multiple stores thing keeps coming up, we only have one store when the Canonical store goes away. We should focus on that and not solve problems that don't exist yet.

**Comment by NeoTheThird** [comment] 2017-12-15 09:40
https://github.com/ubports/system-settings/pull/25

**Comment by Flohack74** [comment] 2017-12-17 11:35
As something is fishy with Openstore not able to update Apps (401 Unauthorized or similar) this becomes a blocker.

**Comment by mardy** [comment] 2017-12-17 17:02
@Flohack74 Do you have the same problem with updating from the System Settings? It sounds like an issue with the server, so it might affect the System Settings too.

**Comment by Flohack74** [comment] 2017-12-17 20:35
I have no details, just relaying user comments here. Will try to find an App I can update (or downgrade one)... Just still not fully at home.

**Comment by Flohack74** [comment] 2017-12-17 21:34
I updated now clock and telegram via Openstore, seems to work. So WFM, maybe this was smth else ;) - If nothing appears, will remove critical label tomorrow...

**Comment by bhdouglass** [comment] 2017-12-17 22:41
Yeah the OpenStore app is just fine. If anything broken it's the system settings interface, but I'm only hearing this second hand as well.

**Comment by NeoTheThird** [comment] 2017-12-18 00:31
We might want to revert the system settings PR. We're dangerously close to release now and i do not want to have this in there if it's broken.

**Comment by ruedigerkupper** [comment] 2017-12-18 17:23
Jan, where were you downloading the app from, and how? I have encountered a
problem like yours downloading (anything) from my nextcloud instance:
Whatever file I try to download using the browser, I get a "not authorized"
error. This applies to any file (text, binary,...) and in particular to
click packages which should open in the openstore app.
Could you check if your error is really located in the openstore app, or
could it be a general download error of the web browser?

Regards, Rüdiger

Am Montag, 18. Dezember 2017 schrieb Jan Sprinz :
> We might want to revert the system settings PR. We're dangerously close
to release now and i do not want to have this in there if it's broken.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/5-u29HIcbx5w86sma5-HMRj9We5m1Pru9E_icbVighQkjF_EpJiglLIZwJfnuaA5GzQAzWkis6Hyi4AfQnl0n99XeY20v3Q5czaayr0EJdgvQxwT1WyC4MfxE6jm-rKsvb6vCz6tjJAdPK-GzISB3saokqVbTA=s0-d-e1-ft#https://github.com/notifications/beacon/AUMSlsrOsHcNjTo_ZywAkMAKvp9Zs3RVks5tBbJ8gaJpZM4OleHy.gif
>

-- 
Dr. Rüdiger Kupper
Forststr. 3
72250 Freudenstadt

**Comment by NeoTheThird** [comment] 2017-12-18 18:02
Not sure I follow, Rüdiger. What do you mean? You might want to disable your email signature, btw. Otherwise your address shows up in your comment on github.com. I took the liberty to remove it from your comment.

**Comment by ruedigerkupper** [comment] 2017-12-18 18:49
@NeoTheThird, thanks for caring about my privacy, I appreciate that very mouch! Few people really care about privacy these days.

Sorry that I wasn't clear. My post was in response to Flowhack74's, who wrote:
"As something is fishy with Openstore not able to update Apps (401 Unauthorized or similar) this becomes a blocker." I have encountered similar errors. In detail:

1. Flohack74 reports (s)he gets "401/unauthorized" errors downloading apps from within openstore app.
2. I'm getting the same error (since, like, 4-6 weeks ago) trying to download files via the web browser.
3. Considering that the openstore app probably uses the same mechanism for downloading files as does the webbroswer, I supect there might be a common reason for both of them failing (with the same error).
I might by wrong, but I thought it was worth reporting.

**Comment by ruedigerkupper** [comment] 2017-12-18 19:05
More details:
- I run a nextcloud instance for private purposes.
- I can download files from that site using ubuntu desktop with no problems.
- I was able to download files from that site using ubuntu touch since 4-6 weeks ago.
- Since then, I receive "401/unauthorized" errors and download fails.
- When downloading click-files, which are suppoed to open in the openstore app, that app reports "401/unauthorized" just like Fohack74 reports.

You can try reproducing my error:
- I have created a guest account for you:
  - go to https://rkupper.no-ip.org
  - your login is "ubportsguest", password the same.
- There is only one file: "About.odt". Try downloading it.
- Observe that all works well from Ubuntu desktop.
- Observe that download fails with "401/unauthorized" from Ubuntu touch.

This might be the same problem that prevents the openstore app from downloading click files.

**Comment by mardy** [comment] 2017-12-18 19:09
The System Setting interface is not broken. The user who reported the problem could not update apps from the OpenStore app; then I asked him to try with the System Settings, and that was broken as well. So it was most likely a server issue.

**Comment by bhdouglass** [comment] 2017-12-18 19:24
I tested downloading from the OpenStore site and installing an update from the OpenStore app and both work fine, there isn't any server issue.

**Comment by NeoTheThird** [comment] 2017-12-18 19:47
Ok, so maybe that was all just a temporary thing. Just tested it myself on multiple devices and it seems to work just fine. Good job @mardy and @bhdouglass.

**Closed** 2017-12-18 19:50 UTC
Labels: enhancement

**Comment by NeoTheThird** [comment] 2017-12-18 19:58
@ruedigerkupper Interesting, but that sounds like a different issue. Could you report a new bug for that?

**Comment by ruedigerkupper** [comment] 2017-12-20 16:45
I did, see #372.

**Comment by NeoTheThird** [comment] 2017-12-20 20:57
Thanks :+1:
