### ISSUE TITLE
Alarms do not ring

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#869] opened 2018-09-06 20:54 UTC
Alarms and timers do not ring. This is related to #857.

**Comment by mihaelmilea** [comment] 2018-09-07 05:52
I discovered this this morning :)
But it worked the whole week. Except yesterday - yesterday it rang only once and then silence.
Today I checked in uVolMan and the alarm sound was not muted. I tried `restart unity8` and the same - no alarm sound, only the notification on the screen.
After a phone restart the alarm works again.
Device: turbo, 16.04, rc channel.

**Comment by Stefano0101** [comment] 2018-09-08 10:52
it happened to me on mine Pro 5 previously as well. (on 15.04 not on 16.04 yet )
Now I set up 2 alarms, second for 5 min after the first.
Just to be sure, that I'm not late for work. It could have a bad consequences.

**Comment by wayneoutthere** [comment] 2018-09-12 13:51
this affects me on FP2.  My situation is different.  None of my ACTUAL alarms sounded, but at 9:30pm, just before my bedtime, alarms were sounding then.  These alarms were not set in the clock app.  Definitley a critical bug.  Thanks!

**Comment by mardy** [comment] 2018-09-23 08:34
Ah, this could indeed be due to the QtPim update: I didn't update the `debian/changelog` file, so the updated package never went into the image.

Now I've updated it, so we should re-test this with tomorrow daily image.

**Comment by NeoTheThird** [comment] 2018-09-24 17:15
@mardy Ok, so alarms do ring in todays image (gj), but the old alarms saved from before do not show up, and as soon as an alarm or timer rings and one dismisses the notification popup, the app crashes with "invalid item id" in qtorganizer.

**Comment by mardy** [comment] 2018-09-24 20:05
Working on it :-)
I've a branch with some changes to qtorganizer5-eds where the alarms show up, but I'm still debugging a crash when saving the alarm. Hopefully it will be ready soon :-)

**Comment by mardy** [comment] 2018-09-24 21:11
I finally have a fix :-)
Please have a look at https://github.com/ubports/qtorganizer5-eds/pull/4: the code changes are huge, so there's no need to review it line by line (unless you want to :-D); what is most important is if someone could check out the [artifacts](https://ci.ubports.com/blue/organizations/jenkins/qtorganizer5-eds/detail/PR-4/1/artifacts/), installed the `armhf` package on their device and try to test whether this solves the issue.

I obviously did a test myself, and this seems to be fixed. However, the same component is responsible for handling the calendar, so there might be some regressions there; again, I checked myself and didn't notice any, but it might be worth testing it a bit before merging.

(the calendar sync is still broken, but that will be handled separately)

**Closed** 2018-09-25 15:16 UTC
Labels: bug, critical (devel)

**Comment by Stefano0101** [comment] 2018-10-02 06:58
Is that fix in the latest rc? My alarm failed to ring TWICE today and I was late for work.

**Comment by Flohack74** [comment] 2018-10-02 20:07
Try now to update th RC channel, we made a special release just for you ;)

**Comment by padraic7a** [comment] 2018-10-02 22:08
This problem appears to be solved now.
Checked on Frieza, 16.04 build 2018-10-01. 
Checked on Hammerhead, 16.04 build 2018-10-02.
The alarm and timer sounded and vibrated on both.

**Comment by Arc676** [comment] 2018-10-03 06:06
Can confirm that the timer worked yesterday. I didn't try with alarms.

**Comment by Stefano0101** [comment] 2018-10-03 07:50
I installed the latest click package downloaded from cdimage...site, time of release 1.October and the allarm rings :-)
