### ISSUE TITLE
I want to buy UBports compatible phone

### ISSUE THREAD

**Issue by uratom962** [ubports/ubuntu-touch#1741] opened 2021-05-28 19:23 UTC
Hi !

All device phone compatible list don't have hotspot fully worked, and for have usb tethering, I need to have UTTweakTool on my old broken Nexus 5.

https://devices.ubuntu-touch.io/

So what phone I need to buy for have hotspot fully worked ? And easily have usb tethering connection without install UTTweakTool. Like when I want to connect on my computer for share connection.

I see this on the official website : https://ibb.co/1K8m4p3

**Comment by ivoxavier** [comment] 2021-05-28 22:13
@uratom962 please use the [forum](https://forums.ubports.com/) for that type of questions

Thank you for your comprehension :)

**Comment by mateosalta** [comment] 2021-05-29 03:31
> Hi !
> 
> All device phone compatible list don't have hotspot fully worked, and for have usb tethering, I need to have UTTweakTool on my old broken Nexus 5.
> 
> https://devices.ubuntu-touch.io/
> 
> So what phone I need to buy for have hotspot fully worked ? And easily have usb tethering connection without install UTTweakTool. Like when I want to connect on my computer for share connection.
> 
> I see this on the official website : https://ibb.co/1K8m4p3

Hi, I think all the devices are listed for hotspot not fully working because of issues, usually you need to reboot the device or try a few times for it to work.

**Comment by UniversalSuperBox** [comment] 2021-06-01 13:45
Hi @uratom962, thanks for your report.

I hope the answers you've gotten here have answered your question. However, this is a bug and request tracker rather than a support forum. It's better to post problems you have with Ubuntu Touch here, following [our bug reporting guide](https://docs.ubports.com/en/latest/contribute/bugreporting.html). For questions about using Ubuntu Touch or the devices it runs on, please join us at [our community forum](https://forums.ubports.com/).

You can click on many of the features listed as "not working" on devices.ubuntu-touch.io to find out why they've been marked the way they are. In the case of hotspot, the issue is https://github.com/ubports/ubuntu-touch/issues/532.

Since this report is not actionable as a bug or feature request, I'll close it now.

**Closed by UniversalSuperBox** 2021-06-01 13:45 UTC
