### ISSUE TITLE
Auto brightness stopped working

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#1747] opened 2021-06-13 08:08 UTC
- Device: Xperia X
- Channel: dev
- Build: 419

### Steps to reproduce
Enable auto brightness (it doesn't matter whether this is done via system settings or the pulldown menu). Expose the device to light or to darkness.

### Expected behavior
The brightness adapts to the environmental brightness.

### Actual behavior
The brightness does not change at all.

### Logfiles and additional information
After a `sudo stop repowerd && sudo env REPOWERD_LOG=console repowerd`:

On enabling auto brightness:
```
[2021-06-12 01:08:59.277885] DefaultStateMachine[c1]: handle_user_activity_extending_power_state
[2021-06-12 01:08:59.405772] UnityScreenService: dbus_userAutobrightnessEnable(enable)
[2021-06-12 01:08:59.408785] DefaultStateMachine[c1]: enable_autobrightness
```
Then no further log messages.

**Comment by ruedigerkupper** [comment] 2021-06-13 09:01
Confirming the problem and the logs as described above.

**Comment by lduboeuf** [comment] 2021-06-15 21:45
confirmed N5 devel

**Comment by wilfridd** [comment] 2021-06-16 08:33
Hi, same issue on Meizu PRO5 and MX4
Best,
W.

**Comment by MenmuirMark** [comment] 2021-06-16 13:50
Same issue on OPO, rc.

**Comment by Openanonwriter** [comment] 2021-06-17 01:32
Confirmed with pixel 3a, RC 2021-W24

**Comment by MenmuirMark** [comment] 2021-06-17 07:58
> Same issue on OPO, rc.

and on my N5, rc

**Comment by UniversalSuperBox** [comment] 2021-06-22 17:45
I can confirm this issue. This now blocks the release of Ubuntu Touch OTA-18. It must be resolved for the release to continue.

**Comment by Openanonwriter** [comment] 2021-06-23 17:44
RC OTA-18 Did not did not fix this issue for pixel 3a

**Comment by Flohack74** [comment] 2021-06-23 18:53
Yes please do not post "still not working" messages, we will notify here when it can be tested again...

**Comment by Openanonwriter** [comment] 2021-06-24 00:14
> Yes please do not post "still not working" messages, we will notify here when it can be tested again...

I removed my message, I do apologize, about that. .

**Comment by UniversalSuperBox** [comment] 2021-06-30 17:14
Fixed by https://gitlab.com/ubports/core/repowerd/-/merge_requests/31

**Comment by ruedigerkupper** [comment] 2021-06-30 17:28
Yeah! Thank you!

**Comment by terrorzelle77** [comment] 2021-08-02 14:56
Hello,
since some weeks auto brightness on Volla Phone isn't working further. 
Reboot not helps. 

So much months everything was ok. 
I think it's since version 443 on the DEV-Channel. 

Is this problem known? Someone works on a fix?

Best regards

**Comment by stekalb** [comment] 2021-08-03 10:58
I can confirm it's an issue again on current volla dev images

**Comment by stekalb** [comment] 2021-08-03 12:05
It seems to be no issue on mx4, bq e4.5 (both on dev) and opo on halium-dev.
In some tg-chat an other user mentioned he is also affected on a different halium9/64bit device.

**Comment by mattbel10** [comment] 2021-08-04 21:32
It doesn't work either on my Pixel 3a, Halium 9 device, devel channel.

**Comment by stekalb** [comment] 2021-08-10 06:45
According to sensorsstaus app light sensor works on dev

**Comment by Flohack74** [comment] 2021-08-10 06:50
@stekalb a) proximity sensor is different to light sensor and b) Its not sufficient to test if it works with sensorsstatus app, you must do a call and see if the display goes black when you come closer with your face or palm of your hand :) I reopen this.

**Comment by stekalb** [comment] 2021-08-10 07:20
Also got a confirmation on TG for not working in OP 6T either.

**Comment by lduboeuf** [comment] 2021-08-11 22:09
auri brightness works on N5 devel

**Comment by UniversalSuperBox** [comment] 2021-08-12 00:30
Should be fixed by a force-push to https://gitlab.com/ubports/core/repowerd/-/commits/ubports/xenial_-_android9 (old version was https://gitlab.com/ubports/core/repowerd/-/commits/ubports/xenial_-_android9-before-aug-2021-rebase). Will take another day before it lands in images.

**Closed by UniversalSuperBox** 2021-08-12 00:30 UTC
Labels: bug, critical (rc)
