### ISSUE TITLE
Bluetooth file transfer is missing

### ISSUE THREAD

**Issue by lgd821** [ubports/ubuntu-touch#849] opened 2018-09-01 16:51 UTC
### Description of the feature
Before OTA-4 the App "Bluetooth file transfer" could be used. Maybe this feature could be added to Ubuntu Touch or the App could be made available again for OTA-4

**Comment by NeoTheThird** [comment] 2018-09-01 16:57
Duplicate of #369.

**Closed by NeoTheThird** 2018-09-01 16:57 UTC
