### ISSUE TITLE
Launcher is opened over the lock screen when all apps stop

### ISSUE THREAD

**Issue by jld3103** [ubports/ubuntu-touch#1178] opened 2019-07-07 10:21 UTC
- Device: Nexus 5
- Channel: edge
- Build: 2019-07-05

### Steps to reproduce

- Enable password/pin
- Reboot device

### Expected behavior

Drawer should be closed when booting.

### Actual behavior

Drawer is open and overlaps with the keyboard/keypad for password/pin.

**Comment by UniversalSuperBox** [comment] 2019-07-10 03:36
Hmm, browsing through the code of `Shell.qml` I see a few cases where this could be triggered erroneously. Basically, it involves us not knowing that our greeter (the unlock page) is showing. Alternatively, the swipe area that triggers the Drawer could be getting swiped incorrectly. If either of these are the case, we have a bit of a problem.

Are you able to reproduce this issue on multiple reboots? Does it only happen on the first reboot after enabling a PIN unlock? Have you done any other setup on the device, or is it fresh from factory reset?

**Comment by jld3103** [comment] 2019-07-10 05:45
It happens after every reboot, but only the first unlock time.
Is it possible to set a SIM lock in UT? I thought there is no SIM toolkit.
The issue happens regardless of the setup.

**Comment by UniversalSuperBox** [comment] 2019-07-10 15:50
Yes, a SIM PIN can be set from the Security and Privacy settings. Please create new threads for different topics or head over to https://forums.ubports.com/ for support in the future.

I'm not able to reproduce this problem by performing the following actions:

1. Factory resetting the device
1. Running setup as normal, but selecting "No password"
1. Setting a PIN
1. Rebooting

Is there a step I'm missing?

**Comment by jld3103** [comment] 2019-07-10 16:41
Ah sorry. I thought you meant a SIM Pin and not the device PIN. That confused me :)
On my device I have set the PIN from the beginning. Maybe that's the difference.

**Comment by UniversalSuperBox** [comment] 2019-07-10 16:53
Hmm, after a factory reset and setting a PIN in the Wizard, I'm still not able to reproduce this issue. Could you do the following?

1. Delete `~/.cache/upstart/unity8.log`
1. Reboot
1. Send the contents of `~/.cache/upstart/unity8.log` to a service like paste.ubuntu.com

**Comment by jld3103** [comment] 2019-07-10 17:55
There is no file:
```
phablet@ubuntu-phablet:~$ rm ~/.cache/upstart/unity8.log
rm: cannot remove '/home/phablet/.cache/upstart/unity8.log': No such file or directory
```

**Comment by UniversalSuperBox** [comment] 2019-07-10 19:41
Aha! Anbox is installed. I installed Anbox and now the Launcher opens over the keyboard on boot, but not the Drawer. Is that the problem you're seeing?

**Comment by UniversalSuperBox** [comment] 2019-07-10 19:58
It appears that there's an app called "Anbox" which starts, then stops, on boot, leading to the app count dropping to zero. When the app count drops to zero, the Launcher appears. This behavior was created by https://github.com/ubports/unity8/commit/0b7586f46458c60ae8b915d5d17df6b065edde36#diff-1a20607e15f3c5e77eecbd68303523a9

**Comment by jld3103** [comment] 2019-07-13 19:39
Seems to be fixed on latest edge @UniversalSuperBox

**Comment by jld3103** [comment] 2019-07-14 07:10
Okay happened again.

**Comment by UniversalSuperBox** [comment] 2019-07-17 15:39
Fixed by https://github.com/ubports/unity8/pull/166

**Closed by UniversalSuperBox** 2019-07-17 15:39 UTC
Labels: bug, edge
