### ISSUE TITLE
Dialer crashes when inputting nbr that exists in Contacts

### ISSUE THREAD

**Issue by matv1** [ubports/ubuntu-touch#858] opened 2018-09-04 12:02 UTC
### Illustrations

- Device: Meizu PRO 5
- Channel: 16.04/devel
- Build: 20180902-21830

### Steps to reproduce
When inputting a phonenumber that was previously stored in Contacts, the dialer crashes instantly.

### Expected behavior
Dialer shouldnt crash

### Actual behavior
Dialer crashes and app closes.

### Logfiles and additional information

This seems related to: 
https://github.com/ubports/ubuntu-touch/issues/857
which I see happening too. In contacts one can add entries, but after entering them they dont show up.

So this dialer issue is only happening when inputting a number that I previously entered in Contacts. 

This issue is persistent across reboots.

**Comment by UniversalSuperBox** [comment] 2018-09-05 15:59
I can confirm this on all my devices with a dialer. The following log is generated when entering a number (or when pre-entering a number by selecting Dialer from the Contacts app): https://paste.ubuntu.com/p/hDzmbMmSQg/

**Comment by hummlbach** [comment] 2018-09-05 17:06
This did not happen with the devel image 18/8/27.

**Comment by mardy** [comment] 2018-09-06 06:12
This is indeed caused by the QtPim update. I created a merge proposal for the telephony-service (https://github.com/ubports/telephony-service/pull/1), which was merged, but for some reason the rebuilt packages are not part of the image, which still has an older version of them:

    qtdeclarative5-ubuntu-telephony-phonenumber0.1:armhf	0.2+ubports+0~20180107231112.1~1.gbp9efa14
    qtdeclarative5-ubuntu-telephony0.1:armhf	0.2+ubports+0~20180107231112.1~1.gbp9efa14

@mariogrip, are you able to find out why the new packages didn't end up in the rootfs?

**Comment by mariogrip** [comment] 2018-09-07 17:41
@mardy Humm, might be a dependency issue here. Will dig into it.

**Comment by mardy** [comment] 2018-09-07 20:58
@mariogrip found it! The package was built fine, but because of a versioning issue, the newly built version is considered older than the existing one, so it's not getting upgraded. I need to add a `0` before the version name. I'll take care of it right now :-)

**Comment by mardy** [comment] 2018-09-08 07:12
Nice, GitHub decided to close this issue as soon as I merged my branch, but they actual image is being built only now.
So, if you reflash your devices to the latest image in about one hour, you should be able to verify that this has been fixed (please confirm).

**Comment by hummlbach** [comment] 2018-09-08 13:09
@mardy is working for me now. But I'm getting the following warning now everytime I try to add an account using the dialer app:
![screenshot20180908_145813494](https://user-images.githubusercontent.com/10819327/45254482-37992c00-b379-11e8-8de5-1b0887b6f2f8.png)

**Comment by hummlbach** [comment] 2018-09-08 15:55
@mardy I'll do. Thanks!

**Closed by hummlbach** 2018-09-08 15:55 UTC
Labels: bug, critical (devel)
