### ISSUE TITLE
OPO Camera flash

### ISSUE THREAD

**Issue by rocky58** [ubports/ubuntu-touch#401] opened 2017-12-31 18:31 UTC
### Illustrations

- Device: OnePlus One
- Channel:
- Build:

**Comment by Flohack74** [comment] 2017-12-31 19:43
@rocky58 Can you please describe what exactly is the problem?

**Comment by NeoTheThird** [comment] 2018-01-01 12:59
Thanks for reporting, @rocky58. This seems to be a duplicate of #258. Also, please read the [bugreporting guide](https://docs.ubports.com/en/latest/contribute/bugreporting.html)

**Closed by NeoTheThird** 2018-01-01 12:59 UTC
Labels: needs confirmation, question

**Comment by rocky58** [comment] 2018-01-05 20:58
Yes, I saw after this issue opening. Flash don't light during photo shut
