### ISSUE TITLE
[ Xenial ] Missing wifi button to switch on/off - bqm10 frieza

### ISSUE THREAD

**Issue by mebruno** [ubports/ubuntu-touch#518] opened 2018-03-11 09:00 UTC
### Description of the feature

Missing:

systemsettings / Wi-Fi / on/off button - list of accesspoints to choose from

- Device: Frieza
- Channel: 16.04 Devel
- Build: r48 an r49

### Steps to reproduce
Just update or install

### Expected behavior
button to enable wifi
choose accesspoint from list

### Actual behavior
no button
no list

**Comment by tsimonq2** [comment] 2018-03-11 09:07
Duplicate of #422.

**Closed by tsimonq2** 2018-03-11 09:07 UTC
