### ISSUE TITLE
Extensive battery drain on OPO

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#299] opened 2017-10-16 08:33 UTC
- Device: Bacon
- Channel: Devel
- Build: r205

## Steps to reproduce

1. Charge the phone
2. Watch the battery drain really fast

## Expected behavoir
Battery drain of <5% per hour

## Actual behavior
Battery drain of 7-10% per hour, with light use or idle

## Logfiles and additional information
I have wifi, cellular (2G/3G/4G), bluetooth and location on, but the battery lasts shorter than it used to. I get about 11-12 hours until battery reaches critical level of <10%, sometimes shorter.

**Comment by Flohack74** [comment] 2017-10-16 16:11
Can you connect via adb, let "top" command execute, and then lock the device? See the processor load, is smth there using more than a few percent?

**Comment by tomoqv** [comment] 2017-10-17 07:29
Hi @Flohack74 , sorry, I got tired of the battery drain and switched back to devel again after I posted this bug report. It seems battery performance is a lot better now, albeit not excellent - about 5% per hour. I'll let you know if I return to stable again.
Thanks!

**Comment by dark-eye** [comment] 2017-10-18 09:57
Maybe It will be a good idea to add the pidstat tool or sar tool to the next OTA this will allow people to find  rogue processes the  uses too much resources

**Comment by NeoTheThird** [comment] 2017-10-19 14:59
I switched to my Oneplus One as a daily driver, and it usually gets me through the day. Since i didn't use it before OTA-2, i don't have anything to compare it to, though. Do you have apps running in the background?

**Comment by tomoqv** [comment] 2017-10-19 15:04
Not that I am aware of. I thought that normally UT didn't run apps in the background. Here is what top looks like on my device a minute ago:

```
top - 17:02:57 up 10:15,  1 user,  load average: 14.05, 23.56, 17.24
Tasks: 332 total,   3 running, 290 sleeping,  17 stopped,  22 zombie
%Cpu(s): 30.3 us, 31.8 sy,  0.0 ni, 37.8 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem:   2962608 total,  2876584 used,    86024 free,   141872 buffers
KiB Swap:    32764 total,      680 used,    32084 free.   671116 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
 2551 phablet   20   0    7668   2956   1192 R  38.4  0.1   6:44.29 upstart     
 2688 phablet   20   0    5572    740    348 S  16.7  0.0   1:08.29 upstart-db+ 
 2594 phablet   20   0    5900   2468    808 R  12.8  0.1   1:04.70 dbus-daemon 
 2583 phablet   20   0    5380    712    528 S   4.9  0.0   0:50.70 upstart-ud+ 
 2687 phablet   20   0    5432    624    376 S   4.9  0.0   1:44.96 upstart-db+ 
 2694 phablet   20   0    5936    812    420 S   4.9  0.0   0:31.83 upstart-fi+ 
 2618 phablet   20   0    5304    892    744 S   4.6  0.0   0:28.58 upstart-ev+ 
 2959 phablet   20   0 1159488 512212 183476 S   2.0 17.3   6:00.08 unity8      
 5278 phablet   20   0   42976   3288   2592 S   2.0  0.1   0:03.40 zeitgeist-+ 
 5286 phablet   20   0   63252   7248   5632 S   2.0  0.2   0:04.90 zeitgeist-+ 
 3559 phablet   20   0   40276  12728   4992 S   1.6  0.4   0:04.13 python3     
 2725 phablet   20   0   41992   5348   3956 S   1.3  0.2   0:06.37 mission-co+ 
11346 phablet   20   0    6260   1304    808 R   1.3  0.0   0:00.70 top         
    3 root      20   0       0      0      0 S   0.7  0.0   0:36.27 ksoftirqd/0 
 2619 phablet   20   0    2968   1104    932 S   0.7  0.0   0:01.16 mpris-proxy 
 2640 phablet   20   0   29444   2932   2416 S   0.7  0.1   0:02.35 gnome-keyr+ 
  143 root      rt   0       0      0      0 S   0.3  0.0   0:35.07 cfinteract+
```

**Comment by Rom4nB** [comment] 2017-10-20 17:31
I also experience with normal use 15% akku drain with the N5 per hour (OTA2 stable).

The phone gets also quite warm (which is not the case with LineageOS) in the upper part, which indicates strong chip activity.

Example screenshot (30% in 2h):
![photo_2017-10-20_19-29-03](https://user-images.githubusercontent.com/19626851/31834057-f74f5a02-b5cc-11e7-816f-be6a48b4395f.jpg)

With LineageOS on the same device battery life was 24-36h (depending on usage, normal mode in Android, with the "energy safing mode" of Android it would last much longer), but regarding internet reports the LineageOS seems to be one of the most modest  battery-usage ROMs available for the N5, so it seems to be "kind of maximum possible".

**Comment by tomoqv** [comment] 2017-11-06 10:10
Title of this bug could maybe change from "extreme" to "extensive". Battery on my OPO usually does not last me through the day even with light use. I get about 12-14 hours, which averages at about 7% per hour drain.

**Comment by Flohack74** [comment] 2017-11-07 11:58
@tomoqv from your screenshot I see there is too much activity on upstart. Is this on stable 15.04?

**Comment by tomoqv** [comment] 2017-11-07 12:16
Hi @Flohack74 , I am on Devel r205 now and can't even adb into my OPO now. I get the error: device offline, which is probably related to this [https://github.com/ubports/ubuntu-touch/issues/13]. However, running top in terminal on the device itself shows similar data as above, i.e. a lot of upstart* stuff.

My battery now is at 44%, only 6+ hours since fully charged.

**Comment by tomoqv** [comment] 2017-11-07 12:18
Now adb shell worked. Here is top:

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
 2580 phablet   20   0   12072   7348   1192 S  39.9  0.2  12:02.01 upstart     
 2713 phablet   20   0    5568    756    348 R  15.5  0.0   3:11.35 upstart-db+ 
 2628 phablet   20   0    6436   3092    808 R  11.9  0.1   2:42.72 dbus-daemon 
 2717 phablet   20   0    5308    592    372 S   4.9  0.0   3:05.10 upstart-db+ 
 2720 phablet   20   0    5936    816    420 S   4.9  0.0   1:15.79 upstart-fi+ 
 2609 phablet   20   0    5380    708    528 S   4.6  0.0   1:36.82 upstart-ud+ 
 2647 phablet   20   0    5304    892    744 S   4.6  0.0   1:10.74 upstart-ev+ 
 2967 phablet   20   0 1235680 576072 191456 S   2.6 19.4   7:01.02 unity8      
 5843 phablet   20   0  611156 112180  79528 S   2.3  3.8   9:38.28 webapp-con+ 
 3506 phablet   20   0   40276  12716   4988 S   1.6  0.4   0:15.14 python3     
 5868 phablet   20   0   42976   3292   2596 R   1.6  0.1   0:25.80 zeitgeist-+ 
 5880 phablet   20   0   63304   7212   5636 S   1.6  0.2   0:15.86 zeitgeist-+ 
 5993 phablet   20   0  349296  72696  24380 S   1.6  2.5   4:17.07 oxide-rend+ 
10646 phablet   20   0    6260   1288    808 R   1.3  0.0   0:00.27 top         
 2754 phablet   20   0   41728   5100   3972 S   1.0  0.2   0:31.17 mission-co+ 
  865 root      20   0   47700   2492   1580 S   0.7  0.1   1:27.74 Binder_2    
 2669 phablet   20   0   28420   2916   2408 R   0.7  0.1   0:06.44 gnome-keyr+ 

```

**Comment by BlueKenny** [comment] 2017-12-07 13:49
On Stable and Devel I habe no problem like this

**Comment by ChloeWolfieGirl** [comment] 2017-12-09 15:40
RC-proposed if I unplug my phone, and dont use it, by the end of the day its dead, but I dont know if thats my battery getting worse.

**Comment by Dantali0n** [comment] 2018-02-02 21:17
I experience the same heavy upstart & dbus cpu usage, the percentages seem to be much lower when I have the phone disconnect from usb / adb and just execute top from the openstore terminal application.

**Comment by Flohack74** [comment] 2018-02-03 16:21
Guys we need to make sure to separate 15.04 and 16.04 properly. From this report I cannot tell whetever it appears on either of them or both.

**Comment by Dantali0n** [comment] 2018-02-03 16:32
@Flohack74 Maybe its a good idea to add an 15.04 and 16.04 label so we can easily see to which Ubuntu versions the problem applies, Right now we are adding "[xenial]" to issue names I think that adding labels is an improvement over that.

**Comment by tomoqv** [comment] 2018-02-05 08:55
My original bug report was for 15.04 and I must say battery stamina is still an issue on my OPO running OTA3 now. Very rarely will it last me through the day, even if I am not doing much calling or surfing.

**Comment by Flohack74** [comment] 2018-02-10 10:28
I have the OPO now as daily (15.04 r281), and I got still 30% after 24hrs, so it seems to be not easy to pinpoint the source of these issues.

**Comment by tomoqv** [comment] 2018-02-10 15:39
I am still on OTA-3 and have these battery issues more or less every day. Today for instance, my OPO went from 100% to 55% in just 4.5 hours. Not much use, but all the radios on and bluetooth connected to my Pebble watch, but still...

**Comment by Flohack74** [comment] 2018-02-10 18:59
I got BT turmed off all the time, but use wifi and network daily. I am moving approx 1.5 - 2 hrs a day with public transport, the other time I am in wifi...

**Comment by tomoqv** [comment] 2018-02-11 11:24
Battery performance is better today, 88% after 3 hours of very light use. But yesterday was horrible, I charged the phone to almost 100% around 4pm. At midnight battery died. Only a couple of sms in that 8 hour period.
sftp://phablet@192.168.1.202/home/phablet/Pictures/Screenshots/screenshot20180211_004423162.png

**Comment by Flohack74** [comment] 2018-11-15 22:54
@tomoqv How is your battery ;)

**Comment by tomoqv** [comment] 2018-11-16 08:30
@Flohack74 
My OPO with xenial is idling for the moment and I am using my Pro 5 as the daily driver, so I can't really tell. Battery isn't great on the Pro 5 though, but I usually make it through the day with maybe 15-20% battery left.

**Comment by jfrederickson** [comment] 2019-04-27 13:14
I recently started using a OPO with 16.04 and a brand new battery from iFixit. It does generally last me through the day, but battery drain during idle is pretty inconsistent. Sometimes it will drain much faster during which the phone will be warm to the touch.

I've looked at `top` output through ADB while this is happening though and nothing seems particularly off, so I'm not sure what's going on. I did notice at one point that my phone seemed to be disconnecting/reconnecting from wifi while this was happening; I don't know if that's causative though.

**Comment by jfrederickson** [comment] 2019-04-27 17:24
...and I've just had wifi turned off entirely today and so far haven't felt the device heat up. So seems like it may be related.

**Comment by Rom4nB** [comment] 2019-04-27 22:17
I noticed that with my FP2 and UT the battery lasts much longer when the phone is without WIFI (and mobile data) in standby than with WIFI.
I assume that maybe the Dekko app is also a reason. As far as I know it "wakes up" from time to time and checks whether there are new emails to show a notification (even when I have deactivated it for all my email accounts). This theory is confirmed because sometimes the Dekko icon "appears" at the unity launcher bar by itself (I assume when it found a new mail, but I don't open Dekko so often on the phone to really know it for sure).

**Comment by Flaburgan** [comment] 2020-03-19 18:57
There is a big battery drain with data sharing, see https://github.com/ubports/ubuntu-touch/issues/42.
Can everyone here confirm if they switched on data sharing at least briefly before the battery drain?

**Comment by Flohack74** [comment] 2020-03-25 08:29
What is data sharing? My OPO is doing very well on devel now, except of:
- You have Dekko 2 installed and you are connected to either network or wifi, but cannot reach the internet. Dekko will go crazy trying to download mails and drain your battery
- Sometimes on boot a process has a race condition and starts draining battery. This is not device-specific. Just reboot and its fine again.
Except for that 2 cases I have my OPO as daily with an endurance of more than 1 day. Roughly 1.5 days of use.

**Comment by Flohack74** [comment] 2020-03-25 08:30
I also will close this issue now as it is very old, and we never got confirmations on that. Please try latest devel channel and compare your results. With OTA-12 this will come to all users.

**Closed by Flohack74** 2020-03-25 08:30 UTC
Labels: device: bacon, needs confirmation

**Comment by Flaburgan** [comment] 2020-03-25 11:41
>What is data sharing?

Sharing you 4G connection with a computer, turning your phone into a Wi-Fi hotspot. I don't know the english term for it.

**Comment by Flohack74** [comment] 2020-03-26 07:34
Ah well its called... hotspot :P - ok I would rather vote to open a separate item for this. Also, hotspot on OPO has other issues too so its not the best feature there.
