### ISSUE TITLE
Feature Request Bock numbers on calls and messages

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-touch#2035] opened 2022-08-30 20:40 UTC
- Feature Request
It will be great if we could block calls and sms from unwanted numbers.

**Comment by MK1973** [comment] 2022-08-31 09:38
Hi Ruben, there is already somebody offering this feature but it requires payment and also part of the IMEI: 

https://f-call-dev.blogspot.com/

Also Rodney made some time ago some comments about this feature, something realted to privacy problems, maybe the IMEI? Because in the beginning this app needed to send the app developer full IMEI number. 

Best regards. MK

**Comment by Flohack74** [comment] 2022-08-31 16:14
Duplicate of https://github.com/ubports/ubuntu-touch/issues/738

**Closed as completed by Flohack74** 2022-08-31 16:14 UTC
Labels: duplicate
