### ISSUE TITLE
Ubuntu touch doesn t see android files in dual boot opo

### ISSUE THREAD

**Issue by Remix65** [ubports/ubuntu-touch#564] opened 2018-04-21 07:00 UTC
Good afternoon i have ubuntu touch 15.04 stable in dual boot with android 7 on my one plus one and then i open file manager in ubuntu touch it doesn t see android files.may help me ?i have to mount android from terminal command ?thanks

**Comment by Flohack74** [comment] 2018-04-21 12:44
Duplicate of #565 - Please avoid creating duplicates.

**Closed by Flohack74** 2018-04-21 12:44 UTC
Labels: duplicate
